# Generated by Django 3.2.16 on 2023-02-01 18:57

import uuid

import django.db.models.deletion
import django_extensions.db.fields
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, null=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, null=True, verbose_name='modified'
                    ),
                ),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1000)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('link', models.URLField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ('-created', '-modified'),
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, null=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, null=True, verbose_name='modified'
                    ),
                ),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('-created', '-modified'),
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, null=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, null=True, verbose_name='modified'
                    ),
                ),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                (
                    'status',
                    models.CharField(
                        choices=[('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')],
                        default='Confirmed',
                        max_length=15,
                    ),
                ),
                (
                    'event',
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='export_academy.event'
                    ),
                ),
                (
                    'registration',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='export_academy.registration'),
                ),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
