# Generated by Django 3.2.16 on 2023-02-10 14:16

import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
from django.db import migrations, models

import export_academy.cms_panels


class Migration(migrations.Migration):
    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('export_academy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportAcademyHomePage',
            fields=[
                (
                    'page_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='wagtailcore.page',
                    ),
                ),
                ('hero_text', wagtail.core.fields.RichTextField()),
                (
                    'hero_cta',
                    wagtail.core.fields.StreamField(
                        [
                            (
                                'button',
                                wagtail.core.blocks.StructBlock(
                                    [
                                        ('label', wagtail.core.blocks.CharBlock(max_length=255)),
                                        (
                                            'link',
                                            wagtail.core.blocks.StructBlock(
                                                [
                                                    (
                                                        'internal_link',
                                                        wagtail.core.blocks.PageChooserBlock(
                                                            label='Internal link', required=False
                                                        ),
                                                    ),
                                                    (
                                                        'external_link',
                                                        wagtail.core.blocks.CharBlock(
                                                            label='External link', max_length=255, required=False
                                                        ),
                                                    ),
                                                ],
                                                required=False,
                                            ),
                                        ),
                                    ],
                                    icon='cog',
                                ),
                            )
                        ],
                        blank=True,
                        null=True,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
            bases=(export_academy.cms_panels.ExportAcademyPagePanels, 'wagtailcore.page'),
        ),
    ]
