# Generated by Django 3.2.16 on 2023-02-10 11:01

import django.db.models.deletion
import wagtail.core.fields
from django.db import migrations, models

import export_academy.cms_panels


class Migration(migrations.Migration):
    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('export_academy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportAcademyHomePage',
            fields=[
                (
                    'page_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='wagtailcore.page',
                    ),
                ),
                ('hero_text', wagtail.core.fields.RichTextField()),
                ('hero_cta_text', models.CharField(blank=True, max_length=255, null=True)),
                ('hero_cta_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(export_academy.cms_panels.ExportAcademyPagePanels, 'wagtailcore.page'),
        ),
    ]
