# Generated by Django 3.2.18 on 2023-03-08 20:29

import django.db.models.deletion
import wagtail.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('wagtailmedia', '0003_copy_media_permissions_to_collections'),
        ('export_academy', '0002_export_academy_homepage_squashed'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='slide_show',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='wagtaildocs.document',
            ),
        ),
        migrations.AddField(
            model_name='event',
            name='video_recording',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='wagtailmedia.media',
            ),
        ),
        migrations.AddField(
            model_name='event',
            name='video_recording_transcript',
            field=wagtail.core.fields.RichTextField(
                blank=True, help_text='If the video is present, a transcript must be provided.', null=True
            ),
        ),
    ]
