# Generated by Django 3.2.16 on 2023-02-16 12:26

import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0074_populate_country_iso2'),
        ('export_academy', '0002_exportacademyhomepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportacademyhomepage',
            name='hero_image',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='core.alttextimage',
            ),
        ),
        migrations.AddField(
            model_name='exportacademyhomepage',
            name='next_cta',
            field=wagtail.core.fields.StreamField(
                [
                    (
                        'button',
                        wagtail.core.blocks.StructBlock(
                            [
                                ('label', wagtail.core.blocks.CharBlock(max_length=255)),
                                (
                                    'link',
                                    wagtail.core.blocks.StructBlock(
                                        [
                                            (
                                                'internal_link',
                                                wagtail.core.blocks.PageChooserBlock(
                                                    label='Internal link', required=False
                                                ),
                                            ),
                                            (
                                                'external_link',
                                                wagtail.core.blocks.CharBlock(
                                                    label='External link', max_length=255, required=False
                                                ),
                                            ),
                                        ],
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='exportacademyhomepage',
            name='panel_description',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exportacademyhomepage',
            name='panels',
            field=wagtail.core.fields.StreamField(
                [
                    (
                        'panel',
                        wagtail.core.blocks.StructBlock(
                            [
                                ('title', wagtail.core.blocks.CharBlock(label='Title', max_length=255, required=False)),
                                ('image', wagtail.images.blocks.ImageChooserBlock(label='Hero Image', required=False)),
                                (
                                    'description',
                                    wagtail.core.blocks.RichTextBlock(
                                        features=[
                                            'h2',
                                            'h3',
                                            'h4',
                                            'bold',
                                            'italic',
                                            'ol',
                                            'ul',
                                            'hr',
                                            'link',
                                            'document-link',
                                        ],
                                        label='Description',
                                        required=False,
                                    ),
                                ),
                                ('link', wagtail.core.blocks.CharBlock()),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='exportacademyhomepage',
            name='steps',
            field=wagtail.core.fields.StreamField(
                [
                    (
                        'panel',
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    'description',
                                    wagtail.core.blocks.RichTextBlock(
                                        features=[
                                            'h2',
                                            'h3',
                                            'h4',
                                            'bold',
                                            'italic',
                                            'ol',
                                            'ul',
                                            'hr',
                                            'link',
                                            'document-link',
                                        ],
                                        label='Description',
                                        required=False,
                                    ),
                                )
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='exportacademyhomepage',
            name='steps_description',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exportacademyhomepage',
            name='hero_text',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
