# Generated by Django 3.2.18 on 2023-03-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_academy', '0002_export_academy_homepage_squashed'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='format',
            field=models.CharField(choices=[('online', 'Online'), ('in_person', 'In-person')], default='online', max_length=15),
        ),
    ]
