# Generated by Django 3.2.17 on 2023-02-21 15:30

import wagtail.core.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('export_academy', '0002_exportacademyhomepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportacademyhomepage',
            name='hero_text',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
