# Generated by Django 3.2.16 on 2023-02-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('export_academy', '0002_exportacademyhomepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=255)),
                ('data', models.JSONField()),
            ],
        ),
    ]
