# Generated by Django 3.2.18 on 2023-03-08 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0076_merge_20230307_1719'),
        ('export_academy', '0003_events_complete_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='video_recording',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='core.greatmedia',
            ),
        ),
    ]
