# Generated by Django 3.2.18 on 2023-03-09 16:14

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('export_academy', '0003_event_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTypeTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Event type tag',
                'verbose_name_plural': 'Event type tags',
            },
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-start_date', '-end_date')},
        ),
        migrations.CreateModel(
            name='TaggedEventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'content_object',
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE, to='export_academy.event'
                    ),
                ),
                (
                    'tag',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='+', to='export_academy.eventtypetag'
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='event',
            name='types',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                help_text='A comma-separated list of tags.',
                through='export_academy.TaggedEventType',
                to='export_academy.EventTypeTag',
                verbose_name='Tags',
            ),
        ),
    ]
