# Generated by Django 3.2.18 on 2023-03-13 12:35

import django.db.models.deletion
import wagtail.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('core', '0076_merge_20230307_1719'),
        ('export_academy', '0004_event_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='slide_show',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='wagtaildocs.document',
            ),
        ),
        migrations.AddField(
            model_name='event',
            name='video_recording',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='core.greatmedia',
            ),
        ),
        migrations.AddField(
            model_name='event',
            name='video_recording_transcript',
            field=wagtail.core.fields.RichTextField(
                blank=True, help_text='If the video is present, a transcript must be provided.', null=True
            ),
        ),
    ]
