# Generated by Django 3.2.18 on 2023-03-16 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('core', '0077_alter_micrositepage_page_body'),
        ('export_academy', '0004_event_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='document',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='wagtaildocs.document',
            ),
        ),
        migrations.AddField(
            model_name='event',
            name='video_recording',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='core.greatmedia',
            ),
        ),
    ]
