# Generated by Django 3.2.16 on 2023-02-27 12:02

import wagtail.core.blocks
import wagtail.core.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('export_academy', '0004_exportacademyhomepage_inherit_base_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportacademyhomepage',
            name='hero_cta',
            field=wagtail.core.fields.StreamField(
                [
                    (
                        'button',
                        wagtail.core.blocks.StructBlock(
                            [
                                ('label', wagtail.core.blocks.CharBlock(max_length=255)),
                                (
                                    'link',
                                    wagtail.core.blocks.StructBlock(
                                        [
                                            (
                                                'internal_link',
                                                wagtail.core.blocks.PageChooserBlock(
                                                    label='Internal link', required=False
                                                ),
                                            ),
                                            (
                                                'external_link',
                                                wagtail.core.blocks.CharBlock(
                                                    label='External link', max_length=255, required=False
                                                ),
                                            ),
                                        ],
                                        required=False,
                                    ),
                                ),
                                (
                                    'secondary',
                                    wagtail.core.blocks.BooleanBlock(
                                        help_text='Determines the appearance of the button. Default is primary.',
                                        required=False,
                                    ),
                                ),
                            ],
                            icon='cog',
                        ),
                    )
                ],
                blank=True,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='exportacademyhomepage',
            name='next_cta',
            field=wagtail.core.fields.StreamField(
                [
                    (
                        'button',
                        wagtail.core.blocks.StructBlock(
                            [
                                ('label', wagtail.core.blocks.CharBlock(max_length=255)),
                                (
                                    'link',
                                    wagtail.core.blocks.StructBlock(
                                        [
                                            (
                                                'internal_link',
                                                wagtail.core.blocks.PageChooserBlock(
                                                    label='Internal link', required=False
                                                ),
                                            ),
                                            (
                                                'external_link',
                                                wagtail.core.blocks.CharBlock(
                                                    label='External link', max_length=255, required=False
                                                ),
                                            ),
                                        ],
                                        required=False,
                                    ),
                                ),
                                (
                                    'secondary',
                                    wagtail.core.blocks.BooleanBlock(
                                        help_text='Determines the appearance of the button. Default is primary.',
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
            ),
        ),
    ]
