# Generated by Django 3.2.16 on 2023-03-01 16:22

import wagtail.core.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('export_academy', '0005_add_secondary_field_button_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportacademyhomepage',
            name='intro_text',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
