# Generated by Django 3.2.18 on 2023-03-17 14:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('export_academy', '0005_event_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='video_recording_transcript',
        ),
    ]
