# Generated by Django 3.2.18 on 2023-03-13 16:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('export_academy', '0005_event_documents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='slide_show',
            new_name='document',
        ),
    ]
