# Generated by Django 3.2.18 on 2023-03-30 09:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('export_academy', '0006_remove_event_video_recording_transcript'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='completed',
        ),
    ]
