# Generated by Django 3.2.18 on 2023-03-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('export_academy', '0007_remove_event_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='live',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
