# Generated by Django 3.2.18 on 2023-04-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('export_academy', '0008_event_live_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
