# Generated by Django 3.2.18 on 2023-04-20 10:31

import wagtail.core.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('export_academy', '0008_event_live_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportacademyhomepage',
            name='anais_field',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
