# Generated by Django 3.2.18 on 2023-05-09 08:37

from django.db import migrations, models

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ('export_academy', '0009_event_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtypetag',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='exportacademyhomepage',
            name='hero_cta',
            field=wagtail.fields.StreamField(
                [
                    (
                        'button',
                        wagtail.blocks.StructBlock(
                            [
                                ('label', wagtail.blocks.CharBlock(max_length=255)),
                                (
                                    'link',
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                'internal_link',
                                                wagtail.blocks.PageChooserBlock(label='Internal link', required=False),
                                            ),
                                            (
                                                'external_link',
                                                wagtail.blocks.CharBlock(
                                                    label='External link', max_length=255, required=False
                                                ),
                                            ),
                                        ],
                                        required=False,
                                    ),
                                ),
                                (
                                    'secondary',
                                    wagtail.blocks.BooleanBlock(
                                        help_text='Determines the appearance of the button. Default is primary.',
                                        required=False,
                                    ),
                                ),
                            ],
                            icon='cog',
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name='exportacademyhomepage',
            name='next_cta',
            field=wagtail.fields.StreamField(
                [
                    (
                        'button',
                        wagtail.blocks.StructBlock(
                            [
                                ('label', wagtail.blocks.CharBlock(max_length=255)),
                                (
                                    'link',
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                'internal_link',
                                                wagtail.blocks.PageChooserBlock(label='Internal link', required=False),
                                            ),
                                            (
                                                'external_link',
                                                wagtail.blocks.CharBlock(
                                                    label='External link', max_length=255, required=False
                                                ),
                                            ),
                                        ],
                                        required=False,
                                    ),
                                ),
                                (
                                    'secondary',
                                    wagtail.blocks.BooleanBlock(
                                        help_text='Determines the appearance of the button. Default is primary.',
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name='exportacademyhomepage',
            name='panels',
            field=wagtail.fields.StreamField(
                [
                    (
                        'panel',
                        wagtail.blocks.StructBlock(
                            [
                                ('title', wagtail.blocks.CharBlock(label='Title', max_length=255, required=False)),
                                ('image', wagtail.images.blocks.ImageChooserBlock(label='Hero Image', required=False)),
                                (
                                    'description',
                                    wagtail.blocks.RichTextBlock(
                                        features=[
                                            'h2',
                                            'h3',
                                            'h4',
                                            'bold',
                                            'italic',
                                            'ol',
                                            'ul',
                                            'hr',
                                            'link',
                                            'document-link',
                                        ],
                                        label='Description',
                                        required=False,
                                    ),
                                ),
                                ('link', wagtail.blocks.CharBlock()),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name='exportacademyhomepage',
            name='steps',
            field=wagtail.fields.StreamField(
                [
                    (
                        'panel',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'description',
                                    wagtail.blocks.RichTextBlock(
                                        features=[
                                            'h2',
                                            'h3',
                                            'h4',
                                            'bold',
                                            'italic',
                                            'ol',
                                            'ul',
                                            'hr',
                                            'link',
                                            'document-link',
                                        ],
                                        label='Description',
                                        required=False,
                                    ),
                                )
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name='exportacademyhomepage',
            name='struct_org_actions',
            field=wagtail.fields.StreamField(
                [
                    (
                        'actions',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'action_type',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[('OrderAction', 'OrderAction'), ('ReserveAction', 'ReserveAction')],
                                        verbose_name='Action Type',
                                    ),
                                ),
                                ('target', wagtail.blocks.URLBlock(verbose_name='Target URL')),
                                (
                                    'language',
                                    wagtail.blocks.CharBlock(
                                        default='en-US',
                                        help_text='If the action is offered in multiple languages, create separate actions for each language.',
                                        verbose_name='Language',
                                    ),
                                ),
                                (
                                    'result_type',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ('Reservation', 'Reservation'),
                                            ('BusReservation', 'BusReservation'),
                                            ('EventReservation', 'EventReservation'),
                                            ('FlightReservation', 'FlightReservation'),
                                            ('FoodEstablishmentReservation', 'FoodEstablishmentReservation'),
                                            ('LodgingReservation', 'LodgingReservation'),
                                            ('RentalCarReservation', 'RentalCarReservation'),
                                            ('ReservationPackage', 'ReservationPackage'),
                                            ('TaxiReservation', 'TaxiReservation'),
                                            ('TrainReservation', 'TrainReservation'),
                                        ],
                                        help_text='Leave blank for OrderAction',
                                        required=False,
                                        verbose_name='Result Type',
                                    ),
                                ),
                                (
                                    'result_name',
                                    wagtail.blocks.CharBlock(
                                        help_text='Example: "Reserve a table", "Book an appointment", etc.',
                                        required=False,
                                        verbose_name='Result Name',
                                    ),
                                ),
                                (
                                    'extra_json',
                                    wagtail.blocks.RawHTMLBlock(
                                        form_classname='monospace',
                                        help_text='Additional JSON-LD inserted into the Action dictionary. Must be properties of https://schema.org/Action.',
                                        required=False,
                                        verbose_name='Additional action markup',
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                use_json_field=True,
                verbose_name='Actions',
            ),
        ),
        migrations.AlterField(
            model_name='exportacademyhomepage',
            name='struct_org_hours',
            field=wagtail.fields.StreamField(
                [
                    (
                        'hours',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'days',
                                    wagtail.blocks.MultipleChoiceBlock(
                                        choices=[
                                            ('Monday', 'Monday'),
                                            ('Tuesday', 'Tuesday'),
                                            ('Wednesday', 'Wednesday'),
                                            ('Thursday', 'Thursday'),
                                            ('Friday', 'Friday'),
                                            ('Saturday', 'Saturday'),
                                            ('Sunday', 'Sunday'),
                                        ],
                                        help_text='For late night hours past 23:59, define each day in a separate block.',
                                        verbose_name='Days',
                                    ),
                                ),
                                ('start_time', wagtail.blocks.TimeBlock(verbose_name='Opening time')),
                                ('end_time', wagtail.blocks.TimeBlock(verbose_name='Closing time')),
                            ]
                        ),
                    )
                ],
                blank=True,
                use_json_field=True,
                verbose_name='Hours of operation',
            ),
        ),
    ]
