# Generated by Django 3.2.18 on 2023-05-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('export_academy', '0010_auto_20230509_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
