# Generated by Django 4.1.9 on 2023-06-13 07:48

import uuid

from django.db import migrations, models


def create_registration_ids(apps, schema_editor):
    Registration = apps.get_model('export_academy', 'Registration')
    for row in Registration.objects.all():
        row.id = uuid.uuid4()
        row.save(update_fields=['id'])


def copy_registration_ids(apps, schema_editor):
    Registration = apps.get_model('export_academy', 'Registration')
    Booking = apps.get_model('export_academy', 'Booking')

    for row in Booking.objects.all():
        registration = Registration.objects.get(email=row.registration_old)
        row.registration = registration
        row.save(update_fields=['registration'])


class Migration(migrations.Migration):
    dependencies = [
        ('export_academy', '0011_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        migrations.RunPython(create_registration_ids, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='registration',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='registration',
            field=models.EmailField(),
        ),
        migrations.RenameField(model_name='booking', old_name='registration', new_name='registration_old'),
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='registration',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, to='export_academy.registration', null=True),
        ),
        migrations.RunPython(copy_registration_ids, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(model_name='booking', name='registration_old'),
        migrations.AlterField(
            model_name='booking',
            name='registration',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, to='export_academy.registration', null=False),
        ),
    ]
