# Generated by Django 4.1.9 on 2023-06-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('export_academy', '0012_change_registration_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='external_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='external_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
