# Generated by Django 4.1.9 on 2023-06-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('export_academy', '0013_event_external_id_registration_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
