# Generated by Django 4.1.9 on 2023-06-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('export_academy', '0014_alter_event_external_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(
                choices=[('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Joined', 'Joined')],
                default='Confirmed',
                max_length=15,
            ),
        ),
    ]
