# Generated by Django 4.1.9 on 2023-06-27 14:34

from django.db import migrations, models

import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ('export_academy', '0014_alter_event_external_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportacademyhomepage',
            name='hero_cta_logged_in',
            field=wagtail.fields.StreamField(
                [
                    (
                        'button',
                        wagtail.blocks.StructBlock(
                            [
                                ('label', wagtail.blocks.CharBlock(max_length=255)),
                                (
                                    'link',
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                'internal_link',
                                                wagtail.blocks.PageChooserBlock(label='Internal link', required=False),
                                            ),
                                            (
                                                'external_link',
                                                wagtail.blocks.CharBlock(
                                                    label='External link', max_length=255, required=False
                                                ),
                                            ),
                                        ],
                                        required=False,
                                    ),
                                ),
                                (
                                    'secondary',
                                    wagtail.blocks.BooleanBlock(
                                        help_text='Determines the appearance of the button. Default is primary.',
                                        required=False,
                                    ),
                                ),
                            ],
                            icon='cog',
                            verbose_name='CTA button for EA logged in users',
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AddField(
            model_name='exportacademyhomepage',
            name='hero_text_below_cta_logged_out',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(
                choices=[('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Joined', 'Joined')],
                default='Confirmed',
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name='exportacademyhomepage',
            name='hero_cta',
            field=wagtail.fields.StreamField(
                [
                    (
                        'button',
                        wagtail.blocks.StructBlock(
                            [
                                ('label', wagtail.blocks.CharBlock(max_length=255)),
                                (
                                    'link',
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                'internal_link',
                                                wagtail.blocks.PageChooserBlock(label='Internal link', required=False),
                                            ),
                                            (
                                                'external_link',
                                                wagtail.blocks.CharBlock(
                                                    label='External link', max_length=255, required=False
                                                ),
                                            ),
                                        ],
                                        required=False,
                                    ),
                                ),
                                (
                                    'secondary',
                                    wagtail.blocks.BooleanBlock(
                                        help_text='Determines the appearance of the button. Default is primary.',
                                        required=False,
                                    ),
                                ),
                            ],
                            icon='cog',
                            verbose_name='CTA button for EA logged out users',
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
