# Generated by Django 4.1.9 on 2023-06-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('export_academy', '0015_exportacademyhomepage_hero_cta_logged_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='hashed_sso_id',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
