# Generated by Django 4.1.9 on 2023-07-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('export_academy', '0016_registration_hashed_sso_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
