# Generated by Django 4.1.9 on 2023-07-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('export_academy', '0016_registration_hashed_sso_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='link',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
