# Generated by Django 4.1.9 on 2023-07-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('export_academy', '0016_registration_hashed_sso_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='event',
            name='external_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='external_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='registration',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
    ]
