# Generated by Django 4.1.10 on 2023-08-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('export_academy', '0017_alter_external_id_fields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cookies_accepted_on_details_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='details_viewed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
