# Generated by Django 4.1.9 on 2023-07-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('export_academy', '0017_alter_external_id_fields_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=2500, null=True),
        ),
    ]
