# Generated by Django 4.1.9 on 2023-07-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('export_academy', '0019_booking_external_id_alter_event_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={},
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['event_id'], name='event_id_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['registration_id'], name='registration_id_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='status_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['external_id'], name='event_external_id_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['format'], name='format_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['hashed_sso_id'], name='hashed_sso_id_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['external_id'], name='registration_external_id_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['email'], name='email_idx'),
        ),
    ]
