# Generated by Django 4.1.9 on 2023-09-01 10:40

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ('export_academy', '0020_add_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='detail',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
