# Generated by Django 4.1.10 on 2023-09-04 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0103_alter_speaker_options'),
        ('export_academy', '0021_event_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='speakers',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='speaker',
                to='core.speaker',
            ),
        ),
    ]
