# Generated by Django 4.1.10 on 2023-09-05 08:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('export_academy', '0021_alter_exportacademyhomepage_panels_and_more'),
        ('export_academy', '0021_replace_wagtail_font_awesome_icons'),
    ]

    operations = []
