# Generated by Django 4.1.10 on 2023-09-04 14:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('export_academy', '0022_event_speakers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='speakers',
        ),
    ]
