# Generated by Django 4.1.10 on 2023-09-05 14:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('export_academy', '0022_merge_20230905_0958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ('-created',)},
        ),
    ]
