# Generated by Django 4.1.10 on 2023-09-07 12:33

from django.db import migrations

import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ('export_academy', '0023_alter_booking_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description_long',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='outcomes',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
