# Generated by Django 4.1.10 on 2023-09-05 10:50

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('export_academy', '0024_rename_detail_event_description_long_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='outcomes',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exportacademyhomepage',
            name='panels',
            field=wagtail.fields.StreamField(
                [
                    (
                        'panel',
                        wagtail.blocks.StructBlock(
                            [
                                ('title', wagtail.blocks.CharBlock(label='Title', max_length=255, required=False)),
                                ('image', wagtail.images.blocks.ImageChooserBlock(label='Hero Image', required=False)),
                                (
                                    'description',
                                    wagtail.blocks.RichTextBlock(
                                        features=[
                                            'h2',
                                            'h3',
                                            'h4',
                                            'bold',
                                            'italic',
                                            'ol',
                                            'ul',
                                            'hr',
                                            'link',
                                            'document-link',
                                        ],
                                        label='Description',
                                        required=False,
                                    ),
                                ),
                                ('link', wagtail.blocks.CharBlock()),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name='exportacademyhomepage',
            name='steps',
            field=wagtail.fields.StreamField(
                [
                    (
                        'panel',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'description',
                                    wagtail.blocks.RichTextBlock(
                                        features=[
                                            'h2',
                                            'h3',
                                            'h4',
                                            'bold',
                                            'italic',
                                            'ol',
                                            'ul',
                                            'hr',
                                            'link',
                                            'document-link',
                                        ],
                                        label='Description',
                                        required=False,
                                    ),
                                )
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
