# Generated by Django 4.1.10 on 2023-09-25 12:49

import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('export_academy', '0025_event_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportacademyhomepage',
            name='course_cta',
            field=wagtail.fields.StreamField(
                [
                    (
                        'button',
                        wagtail.blocks.StructBlock(
                            [
                                ('label', wagtail.blocks.CharBlock(max_length=255)),
                                (
                                    'link',
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                'internal_link',
                                                wagtail.blocks.PageChooserBlock(label='Internal link', required=False),
                                            ),
                                            (
                                                'external_link',
                                                wagtail.blocks.CharBlock(
                                                    label='External link', max_length=255, required=False
                                                ),
                                            ),
                                        ],
                                        required=False,
                                    ),
                                ),
                                (
                                    'secondary',
                                    wagtail.blocks.BooleanBlock(
                                        help_text='Determines the appearance of the button. Default is primary.',
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AddField(
            model_name='exportacademyhomepage',
            name='course_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Course Description'),
        ),
        migrations.AddField(
            model_name='exportacademyhomepage',
            name='course_feature_one',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Course Feature One'),
        ),
        migrations.AddField(
            model_name='exportacademyhomepage',
            name='course_feature_three',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Course Feature Three'),
        ),
        migrations.AddField(
            model_name='exportacademyhomepage',
            name='course_feature_two',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Course Feature Two'),
        ),
        migrations.AddField(
            model_name='exportacademyhomepage',
            name='course_heading',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Course Heading'),
        ),
        migrations.AddField(
            model_name='exportacademyhomepage',
            name='course_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Course Name'),
        ),
        migrations.AddField(
            model_name='exportacademyhomepage',
            name='course_subheading',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Course Subheading'),
        ),
    ]
