# Generated by Django 4.1.10 on 2023-09-28 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0113_alter_micrositepage_page_body'),
        ('export_academy', '0026_exportacademyhomepage_course_cta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportacademyhomepage',
            name='course_image',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='core.alttextimage',
            ),
        ),
    ]
