# Generated by Django 4.1.10 on 2023-09-25 15:12

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('export_academy', '0026_coursepage_eventorderable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventorderable',
            options={},
        ),
        migrations.RemoveField(
            model_name='eventorderable',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventorderable',
            name='sort_order',
        ),
        migrations.CreateModel(
            name='ModuleEventSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='export_academy.event')),
                (
                    'page',
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='module_events',
                        to='export_academy.eventorderable',
                    ),
                ),
            ],
        ),
    ]
