7  # Generated by Django 4.1.10 on 2023-10-05 04:02

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0116_alter_interstitialpage_button_and_more'),
        ('export_academy', '0026_event_course_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportacademyhomepage',
            name='course_cta_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Course CTA Text'),
        ),
        migrations.AddField(
            model_name='exportacademyhomepage',
            name='course_cta_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Course CTA URL'),
        ),
        migrations.AddField(
            model_name='exportacademyhomepage',
            name='course_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Course Description'),
        ),
        migrations.AddField(
            model_name='exportacademyhomepage',
            name='course_feature_one',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Course Feature One'),
        ),
        migrations.AddField(
            model_name='exportacademyhomepage',
            name='course_feature_three',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Course Feature Three'),
        ),
        migrations.AddField(
            model_name='exportacademyhomepage',
            name='course_feature_two',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Course Feature Two'),
        ),
        migrations.AddField(
            model_name='exportacademyhomepage',
            name='course_image',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='core.alttextimage',
            ),
        ),
        migrations.AddField(
            model_name='exportacademyhomepage',
            name='course_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Course Name'),
        ),
        migrations.AlterField(
            model_name='exportacademyhomepage',
            name='hero_cta',
            field=wagtail.fields.StreamField(
                [
                    (
                        'button',
                        wagtail.blocks.StructBlock(
                            [
                                ('label', wagtail.blocks.CharBlock(max_length=255)),
                                (
                                    'link',
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                'internal_link',
                                                wagtail.blocks.PageChooserBlock(label='Internal link', required=False),
                                            ),
                                            (
                                                'external_link',
                                                wagtail.blocks.CharBlock(
                                                    label='External link', max_length=255, required=False
                                                ),
                                            ),
                                        ],
                                        required=False,
                                    ),
                                ),
                                (
                                    'secondary',
                                    wagtail.blocks.BooleanBlock(
                                        help_text='Determines the appearance of the button. Default is primary.',
                                        required=False,
                                    ),
                                ),
                                (
                                    'chevron',
                                    wagtail.blocks.BooleanBlock(
                                        help_text='Adds a right chevron to the button. Default is None.', required=False
                                    ),
                                ),
                            ],
                            icon='cog',
                            verbose_name='CTA button for EA logged out users',
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name='exportacademyhomepage',
            name='hero_cta_logged_in',
            field=wagtail.fields.StreamField(
                [
                    (
                        'button',
                        wagtail.blocks.StructBlock(
                            [
                                ('label', wagtail.blocks.CharBlock(max_length=255)),
                                (
                                    'link',
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                'internal_link',
                                                wagtail.blocks.PageChooserBlock(label='Internal link', required=False),
                                            ),
                                            (
                                                'external_link',
                                                wagtail.blocks.CharBlock(
                                                    label='External link', max_length=255, required=False
                                                ),
                                            ),
                                        ],
                                        required=False,
                                    ),
                                ),
                                (
                                    'secondary',
                                    wagtail.blocks.BooleanBlock(
                                        help_text='Determines the appearance of the button. Default is primary.',
                                        required=False,
                                    ),
                                ),
                                (
                                    'chevron',
                                    wagtail.blocks.BooleanBlock(
                                        help_text='Adds a right chevron to the button. Default is None.', required=False
                                    ),
                                ),
                            ],
                            icon='cog',
                            verbose_name='CTA button for EA logged in users',
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name='exportacademyhomepage',
            name='next_cta',
            field=wagtail.fields.StreamField(
                [
                    (
                        'button',
                        wagtail.blocks.StructBlock(
                            [
                                ('label', wagtail.blocks.CharBlock(max_length=255)),
                                (
                                    'link',
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                'internal_link',
                                                wagtail.blocks.PageChooserBlock(label='Internal link', required=False),
                                            ),
                                            (
                                                'external_link',
                                                wagtail.blocks.CharBlock(
                                                    label='External link', max_length=255, required=False
                                                ),
                                            ),
                                        ],
                                        required=False,
                                    ),
                                ),
                                (
                                    'secondary',
                                    wagtail.blocks.BooleanBlock(
                                        help_text='Determines the appearance of the button. Default is primary.',
                                        required=False,
                                    ),
                                ),
                                (
                                    'chevron',
                                    wagtail.blocks.BooleanBlock(
                                        help_text='Adds a right chevron to the button. Default is None.', required=False
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
