# Generated by Django 4.1.10 on 2023-09-28 09:40

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('export_academy', '0027_exportacademyhomepage_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportacademyhomepage',
            name='course_cta',
            field=wagtail.fields.StreamField(
                [
                    (
                        'link',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'internal_link',
                                    wagtail.blocks.PageChooserBlock(label='Internal link', required=False),
                                ),
                                (
                                    'external_link',
                                    wagtail.blocks.CharBlock(label='External link', max_length=255, required=False),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
