# Generated by Django 4.1.10 on 2023-10-12 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0116_alter_interstitialpage_button_and_more'),
        ('wagtaildocs', '0012_uploadeddocument'),
        ('export_academy', '0027_exportacademyhomepage_course_cta_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='past_event_presentation_file',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='wagtaildocs.document',
            ),
        ),
        migrations.AddField(
            model_name='event',
            name='past_event_recorded_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='past_event_video_recording',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='core.greatmedia',
            ),
        ),
    ]
