# Generated by Django 4.1.10 on 2023-10-20 10:13

import uuid

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('export_academy', '0027_exportacademyhomepage_course_cta_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoPageTracking',
            fields=[
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, null=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, null=True, verbose_name='modified'
                    ),
                ),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('details_viewed', models.DateTimeField(auto_now_add=True)),
                ('cookies_accepted_on_details_view', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
