# Generated by Django 4.1.10 on 2023-09-25 15:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('export_academy', '0027_alter_eventorderable_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventOrderable',
            new_name='EventsOnCourse',
        ),
    ]
