# Generated by Django 4.1.10 on 2023-10-23 14:06

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('export_academy', '0028_event_past_event_presentation_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepage',
            name='reviews',
            field=wagtail.fields.StreamField(
                [
                    (
                        'review',
                        wagtail.blocks.StructBlock(
                            [
                                ('image', wagtail.images.blocks.ImageChooserBlock()),
                                (
                                    'quote',
                                    wagtail.blocks.TextBlock(help_text='Enter a quote (*required)', required=True),
                                ),
                                ('name', wagtail.blocks.TextBlock(required=False)),
                                ('role', wagtail.blocks.TextBlock(required=False)),
                                ('company_name', wagtail.blocks.TextBlock(required=False)),
                            ]
                        ),
                    )
                ],
                blank=True,
                default=[],
                use_json_field=None,
            ),
        ),
    ]
