# Generated by Django 4.1.10 on 2023-10-25 15:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('export_academy', '0028_event_past_event_presentation_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventsoncourse',
            options={'ordering': ['id']},
        ),
    ]
