# Generated by Django 4.1.10 on 2023-09-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('export_academy', '0028_alter_exportacademyhomepage_course_cta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportacademyhomepage',
            name='course_cta',
        ),
        migrations.AddField(
            model_name='exportacademyhomepage',
            name='course_cta_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Course CTA Text'),
        ),
        migrations.AddField(
            model_name='exportacademyhomepage',
            name='course_cta_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Course CTA URL'),
        ),
    ]
