# Generated by Django 4.1.10 on 2023-09-28 15:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('export_academy', '0029_remove_exportacademyhomepage_course_cta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportacademyhomepage',
            name='course_heading',
        ),
        migrations.RemoveField(
            model_name='exportacademyhomepage',
            name='course_subheading',
        ),
    ]
