# Generated by Django 4.1.10 on 2023-10-26 15:03

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0117_add_embed_video_block_and_alter_link_block'),
        ('export_academy', '0030_alter_eventsoncourse_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursepage',
            options={'verbose_name': 'Series page', 'verbose_name_plural': 'Series pages'},
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='is_course_right_for_you_list',
            field=wagtail.fields.StreamField(
                [
                    (
                        'is_this_series_right_for_you_list',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'description',
                                    wagtail.blocks.RichTextBlock(
                                        features=[
                                            'anchor-identifier',
                                            'h2',
                                            'h3',
                                            'h4',
                                            'bold',
                                            'italic',
                                            'ol',
                                            'ul',
                                            'hr',
                                            'link',
                                            'document-link',
                                        ],
                                        label='Description',
                                        required=False,
                                    ),
                                )
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name='exportacademyhomepage',
            name='course_cta_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Series CTA Text'),
        ),
        migrations.AlterField(
            model_name='exportacademyhomepage',
            name='course_cta_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Series CTA URL'),
        ),
        migrations.AlterField(
            model_name='exportacademyhomepage',
            name='course_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Series Description'),
        ),
        migrations.AlterField(
            model_name='exportacademyhomepage',
            name='course_feature_one',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Series Feature One'),
        ),
        migrations.AlterField(
            model_name='exportacademyhomepage',
            name='course_feature_three',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Series Feature Three'),
        ),
        migrations.AlterField(
            model_name='exportacademyhomepage',
            name='course_feature_two',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Series Feature Two'),
        ),
        migrations.AlterField(
            model_name='exportacademyhomepage',
            name='course_image',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='core.alttextimage',
                verbose_name='Series image',
            ),
        ),
        migrations.AlterField(
            model_name='exportacademyhomepage',
            name='course_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Series Name'),
        ),
    ]
