# Generated by Django 4.1.10 on 2023-11-15 10:50

import uuid

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0118_alter_micrositepage_page_body'),
        ('export_academy', '0031_rename_course_labels_to_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoOnDemandPageTracking',
            fields=[
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, null=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, null=True, verbose_name='modified'
                    ),
                ),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=254)),
                ('hashed_uuid', models.CharField(max_length=200)),
                ('region', models.CharField(blank=True, max_length=10, null=True)),
                ('company_name', models.CharField(blank=True, max_length=50, null=True)),
                ('company_postcode', models.CharField(blank=True, max_length=50, null=True)),
                ('company_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('details_viewed', models.DateTimeField(blank=True, null=True)),
                ('cookies_accepted_on_details_view', models.BooleanField(default=False)),
                (
                    'booking',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='vod_booking',
                        to='export_academy.booking',
                    ),
                ),
                (
                    'event',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='vod_event',
                        to='export_academy.event',
                    ),
                ),
                (
                    'registration',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='vod_registration',
                        to='export_academy.registration',
                    ),
                ),
                (
                    'video',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='vod_video',
                        to='core.greatmedia',
                    ),
                ),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
