# Generated by Django 4.1.10 on 2023-11-07 11:44

import uuid

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0117_add_embed_video_block_and_alter_link_block'),
        ('export_academy', '0031_rename_course_labels_to_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoOnDemandPageTracking',
            fields=[
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, null=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, null=True, verbose_name='modified'
                    ),
                ),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user_id', models.PositiveIntegerField()),
                ('details_viewed', models.DateTimeField(blank=True, null=True)),
                ('cookies_accepted_on_details_view', models.BooleanField(default=False)),
                (
                    'event',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='events',
                        to='export_academy.event',
                    ),
                ),
                (
                    'video',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='video',
                        to='core.greatmedia',
                    ),
                ),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
