# Generated by Django 4.1.10 on 2023-11-03 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0117_add_embed_video_block_and_alter_link_block'),
        ('export_academy', '0032_videoondemandpagetracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoondemandpagetracking',
            name='video',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='video',
                to='core.greatmedia',
            ),
        ),
    ]
