# Generated by Django 4.1.10 on 2023-11-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('export_academy', '0032_videoondemandpagetracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoondemandpagetracking',
            name='user_id',
        ),
        migrations.AddField(
            model_name='videoondemandpagetracking',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
