# Generated by Django 4.1.10 on 2023-11-16 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0118_alter_micrositepage_page_body'),
        ('export_academy', '0032_videoondemandpagetracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoondemandpagetracking',
            name='video',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vod_video', to='core.greatmedia'
            ),
        ),
    ]
