# Generated by Django 4.1.13 on 2023-11-16 16:02

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('export_academy', '0032_videoondemandpagetracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepage',
            name='metadata',
            field=wagtail.fields.StreamField(
                [
                    (
                        'metadata_item',
                        wagtail.blocks.StructBlock(
                            [
                                ('label', wagtail.blocks.CharBlock(required=True)),
                                ('value', wagtail.blocks.CharBlock(required=True)),
                            ]
                        ),
                    )
                ],
                blank=True,
                default=[],
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='reviews',
            field=wagtail.fields.StreamField(
                [
                    (
                        'review',
                        wagtail.blocks.StructBlock(
                            [
                                ('image', wagtail.images.blocks.ImageChooserBlock()),
                                (
                                    'quote',
                                    wagtail.blocks.TextBlock(help_text='Enter a quote (*required)', required=True),
                                ),
                                ('name', wagtail.blocks.TextBlock(required=False)),
                                ('role', wagtail.blocks.TextBlock(required=False)),
                                ('company_name', wagtail.blocks.TextBlock(required=False)),
                            ]
                        ),
                    )
                ],
                blank=True,
                default=[],
                use_json_field=True,
            ),
        ),
    ]
