# Generated by Django 4.1.10 on 2023-11-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('export_academy', '0032_videoondemandpagetracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoondemandpagetracking',
            name='hashed_sso_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
