# Generated by Django 4.1.10 on 2023-11-09 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0117_add_embed_video_block_and_alter_link_block'),
        ('export_academy', '0033_remove_videoondemandpagetracking_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoondemandpagetracking',
            name='booking',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='vod_booking',
                to='export_academy.booking',
            ),
        ),
        migrations.AddField(
            model_name='videoondemandpagetracking',
            name='company_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='videoondemandpagetracking',
            name='company_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='videoondemandpagetracking',
            name='company_postcode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='videoondemandpagetracking',
            name='hashed_uuid',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videoondemandpagetracking',
            name='region',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='videoondemandpagetracking',
            name='registration',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='vod_registration',
                to='export_academy.registration',
            ),
        ),
        migrations.AlterField(
            model_name='videoondemandpagetracking',
            name='event',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='vod_event',
                to='export_academy.event',
            ),
        ),
        migrations.AlterField(
            model_name='videoondemandpagetracking',
            name='user_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='videoondemandpagetracking',
            name='video',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='vod_video',
                to='core.greatmedia',
            ),
        ),
    ]
