# Generated by Django 4.2 on 2024-02-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('export_academy', '0033_alter_coursepage_metadata_alter_coursepage_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
