# Generated by Django 4.2 on 2024-02-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('export_academy', '0033_alter_coursepage_metadata_alter_coursepage_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='event_completed_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
