# Generated by Django 4.2.10 on 2024-03-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_academy', '0034_booking_event_completed_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='telephone_number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
