# Generated by Django 4.2 on 2024-02-15 08:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('export_academy', '0034_event_completed_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='completed_date',
        ),
    ]
