# Generated by Django 4.2 on 2024-03-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('export_academy', '0034_booking_event_completed_email_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='event_completed_email_sent',
        ),
        migrations.AddField(
            model_name='event',
            name='completed_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
