# Generated by Django 4.1.10 on 2023-11-09 16:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('export_academy', '0034_videoondemandpagetracking_booking_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoondemandpagetracking',
            options={'ordering': ('-created',)},
        ),
    ]
