# Generated by Django 4.2.10 on 2024-04-10 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('export_academy', '0035_remove_booking_event_completed_email_sent_and_more'),
        ('export_academy', '0035_typeofexporttagged_sectortagged_countrytagged_and_more'),
    ]

    operations = []
