# Generated by Django 4.2.10 on 2024-04-05 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('export_academy', '0035_registration_telephone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='telephone_number',
            new_name='mobile_phone_number',
        ),
    ]
