# Generated by Django 4.2.11 on 2024-04-11 13:06

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    replaces = [
        ('export_academy', '0036_remove_exportacademyhomepage_course_cta_text_and_more'),
        ('export_academy', '0038_exportacademyhomepage_serieslist_and_more'),
        ('export_academy', '0039_remove_exportacademyhomepage_series_delete_series'),
        ('export_academy', '0040_alter_exportacademyhomepage_serieslist'),
        ('export_academy', '0041_rename_serieslist_exportacademyhomepage_series_list'),
        ('export_academy', '0042_alter_exportacademyhomepage_series_list'),
        ('export_academy', '0043_remove_exportacademyhomepage_series_list_and_more'),
        ('export_academy', '0044_remove_exportacademyhomepage_course_cta_text_and_more'),
        ('export_academy', '0045_alter_exportacademyhomepage_series_list'),
        ('export_academy', '0046_alter_exportacademyhomepage_series_list'),
    ]

    dependencies = [
        ('export_academy', '0035_typeofexporttagged_sectortagged_countrytagged_and_more'),
        ('core', '0140_casestudy_sector_tags_casestudy_type_of_export_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportacademyhomepage',
            name='course_cta_text',
        ),
        migrations.RemoveField(
            model_name='exportacademyhomepage',
            name='course_cta_url',
        ),
        migrations.RemoveField(
            model_name='exportacademyhomepage',
            name='course_description',
        ),
        migrations.RemoveField(
            model_name='exportacademyhomepage',
            name='course_feature_one',
        ),
        migrations.RemoveField(
            model_name='exportacademyhomepage',
            name='course_feature_three',
        ),
        migrations.RemoveField(
            model_name='exportacademyhomepage',
            name='course_feature_two',
        ),
        migrations.RemoveField(
            model_name='exportacademyhomepage',
            name='course_image',
        ),
        migrations.RemoveField(
            model_name='exportacademyhomepage',
            name='course_name',
        ),
        migrations.AddField(
            model_name='exportacademyhomepage',
            name='series_list',
            field=wagtail.fields.StreamField(
                [
                    (
                        'Series',
                        wagtail.blocks.StructBlock(
                            [
                                ('course_name', wagtail.blocks.CharBlock(max_length=255, required=False)),
                                ('course_description', wagtail.blocks.CharBlock(max_length=255, required=False)),
                                ('course_image', wagtail.images.blocks.ImageChooserBlock(required=False)),
                                ('course_feature_one', wagtail.blocks.CharBlock(max_length=255, required=False)),
                                ('course_feature_two', wagtail.blocks.CharBlock(max_length=255, required=False)),
                                ('course_feature_three', wagtail.blocks.CharBlock(max_length=255, required=False)),
                                ('course_cta_text', wagtail.blocks.CharBlock(max_length=255, required=False)),
                                ('course_cta_url', wagtail.blocks.CharBlock(max_length=255, required=False)),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
