# Generated by Django 4.2.11 on 2024-04-10 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0140_casestudy_sector_tags_casestudy_type_of_export_tags_and_more'),
        ('export_academy', '0035_typeofexporttagged_sectortagged_countrytagged_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportacademyhomepage',
            name='course_cta_text',
        ),
        migrations.RemoveField(
            model_name='exportacademyhomepage',
            name='course_cta_url',
        ),
        migrations.RemoveField(
            model_name='exportacademyhomepage',
            name='course_description',
        ),
        migrations.RemoveField(
            model_name='exportacademyhomepage',
            name='course_feature_one',
        ),
        migrations.RemoveField(
            model_name='exportacademyhomepage',
            name='course_feature_three',
        ),
        migrations.RemoveField(
            model_name='exportacademyhomepage',
            name='course_feature_two',
        ),
        migrations.RemoveField(
            model_name='exportacademyhomepage',
            name='course_image',
        ),
        migrations.RemoveField(
            model_name='exportacademyhomepage',
            name='course_name',
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Series Name')),
                (
                    'course_description',
                    models.CharField(blank=True, max_length=255, null=True, verbose_name='Series Description'),
                ),
                (
                    'course_feature_one',
                    models.CharField(blank=True, max_length=255, null=True, verbose_name='Series Feature One'),
                ),
                (
                    'course_feature_two',
                    models.CharField(blank=True, max_length=255, null=True, verbose_name='Series Feature Two'),
                ),
                (
                    'course_feature_three',
                    models.CharField(blank=True, max_length=255, null=True, verbose_name='Series Feature Three'),
                ),
                (
                    'course_cta_text',
                    models.CharField(blank=True, max_length=255, null=True, verbose_name='Series CTA Text'),
                ),
                (
                    'course_cta_url',
                    models.CharField(blank=True, max_length=255, null=True, verbose_name='Series CTA URL'),
                ),
                (
                    'course_image',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='core.alttextimage',
                        verbose_name='Series image',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='exportacademyhomepage',
            name='series',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='export_academy.series'
            ),
        ),
    ]
