# Generated by Django 4.2.11 on 2024-04-09 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('export_academy', '0035_typeofexporttagged_sectortagged_countrytagged_and_more'),
        ('export_academy', '0036_rename_telephone_number_registration_mobile_phone_number'),
    ]

    operations = []
