# Generated by Django 4.2.11 on 2024-04-15 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('export_academy', '0036_merge_20240410_0903'),
        ('export_academy', '0037_merge_20240409_1218'),
    ]

    operations = []
