# Generated by Django 4.2.11 on 2024-04-10 15:29

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('export_academy', '0036_remove_exportacademyhomepage_course_cta_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportacademyhomepage',
            name='seriesList',
            field=wagtail.fields.StreamField(
                [
                    ('heading', wagtail.blocks.CharBlock(help_text='heading', max_length=255)),
                    ('course_name', wagtail.blocks.CharBlock(help_text='heading', max_length=255)),
                    ('course_description', wagtail.blocks.CharBlock(help_text='heading', max_length=255)),
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
