# Generated by Django 4.2.11 on 2024-04-22 08:41

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('export_academy', '0038_merge_20240415_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportacademyhomepage',
            name='course_cta_text',
        ),
        migrations.RemoveField(
            model_name='exportacademyhomepage',
            name='course_cta_url',
        ),
        migrations.RemoveField(
            model_name='exportacademyhomepage',
            name='course_description',
        ),
        migrations.RemoveField(
            model_name='exportacademyhomepage',
            name='course_feature_one',
        ),
        migrations.RemoveField(
            model_name='exportacademyhomepage',
            name='course_feature_three',
        ),
        migrations.RemoveField(
            model_name='exportacademyhomepage',
            name='course_feature_two',
        ),
        migrations.RemoveField(
            model_name='exportacademyhomepage',
            name='course_image',
        ),
        migrations.RemoveField(
            model_name='exportacademyhomepage',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='exportacademyhomepage',
            name='next_cta',
        ),
        migrations.RemoveField(
            model_name='exportacademyhomepage',
            name='panel_description',
        ),
        migrations.RemoveField(
            model_name='exportacademyhomepage',
            name='panels',
        ),
        migrations.AddField(
            model_name='exportacademyhomepage',
            name='events_and_series',
            field=wagtail.fields.StreamField(
                [
                    (
                        'Series_Section',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'series_section_description',
                                    wagtail.blocks.RichTextBlock(max_length=255, required=False),
                                ),
                                (
                                    'series_list',
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                'Series',
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            'course_name',
                                                            wagtail.blocks.CharBlock(max_length=255, required=False),
                                                        ),
                                                        (
                                                            'course_description',
                                                            wagtail.blocks.CharBlock(max_length=255, required=False),
                                                        ),
                                                        (
                                                            'course_image',
                                                            wagtail.images.blocks.ImageChooserBlock(required=False),
                                                        ),
                                                        (
                                                            'course_feature_one',
                                                            wagtail.blocks.CharBlock(max_length=255, required=False),
                                                        ),
                                                        (
                                                            'course_feature_two',
                                                            wagtail.blocks.CharBlock(max_length=255, required=False),
                                                        ),
                                                        (
                                                            'course_feature_three',
                                                            wagtail.blocks.CharBlock(max_length=255, required=False),
                                                        ),
                                                        (
                                                            'course_cta_text',
                                                            wagtail.blocks.CharBlock(max_length=255, required=False),
                                                        ),
                                                        (
                                                            'course_cta_url',
                                                            wagtail.blocks.CharBlock(max_length=255, required=False),
                                                        ),
                                                    ]
                                                ),
                                            )
                                        ],
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        'Panels_Section',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'panel_section_description',
                                    wagtail.blocks.RichTextBlock(max_length=255, required=False),
                                ),
                                (
                                    'panels',
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                'Panel',
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            'title',
                                                            wagtail.blocks.CharBlock(
                                                                label='Title', max_length=255, required=False
                                                            ),
                                                        ),
                                                        (
                                                            'image',
                                                            wagtail.images.blocks.ImageChooserBlock(
                                                                label='Hero Image', required=False
                                                            ),
                                                        ),
                                                        (
                                                            'description',
                                                            wagtail.blocks.RichTextBlock(
                                                                features=[
                                                                    'anchor-identifier',
                                                                    'h2',
                                                                    'h3',
                                                                    'h4',
                                                                    'bold',
                                                                    'italic',
                                                                    'ol',
                                                                    'ul',
                                                                    'hr',
                                                                    'link',
                                                                    'document-link',
                                                                ],
                                                                label='Description',
                                                                required=False,
                                                            ),
                                                        ),
                                                        ('link', wagtail.blocks.CharBlock()),
                                                    ]
                                                ),
                                            )
                                        ],
                                        required=False,
                                    ),
                                ),
                                (
                                    'next_cta',
                                    wagtail.blocks.StructBlock(
                                        [
                                            ('label', wagtail.blocks.CharBlock(max_length=255)),
                                            (
                                                'link',
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            'internal_link',
                                                            wagtail.blocks.PageChooserBlock(
                                                                label='Internal link', required=False
                                                            ),
                                                        ),
                                                        (
                                                            'external_link',
                                                            wagtail.blocks.CharBlock(
                                                                label='External link', max_length=255, required=False
                                                            ),
                                                        ),
                                                    ],
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                'secondary',
                                                wagtail.blocks.BooleanBlock(
                                                    help_text='Determines the appearance of the button. Default is primary.',
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                'chevron',
                                                wagtail.blocks.BooleanBlock(
                                                    help_text='Adds a right chevron to the button. Default is None.',
                                                    required=False,
                                                ),
                                            ),
                                        ],
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
