# Generated by Django 4.2.11 on 2024-04-10 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('export_academy', '0038_exportacademyhomepage_serieslist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportacademyhomepage',
            name='series',
        ),
        migrations.DeleteModel(
            name='Series',
        ),
    ]
