# Generated by Django 4.2.11 on 2024-05-10 07:56

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0145_remove_taggedsector_content_object_and_more'),
        ('export_academy', '0039_remove_exportacademyhomepage_course_cta_text_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CountryTagged',
            new_name='CountryTaggedEvent',
        ),
        migrations.RenameModel(
            old_name='SectorTagged',
            new_name='SectorTaggedEvent',
        ),
        migrations.RenameModel(
            old_name='TypeOfExportTagged',
            new_name='TypeOfExportTaggedEvent',
        ),
        migrations.AddField(
            model_name='coursepage',
            name='country_tags',
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text='A comma-separated list of tags.',
                through='core.CountryTagged',
                to='core.CountryTag',
                verbose_name='Country Tags',
            ),
        ),
        migrations.AddField(
            model_name='coursepage',
            name='sector_tags',
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text='A comma-separated list of tags.',
                through='core.SectorTagged',
                to='core.SectorTag',
                verbose_name='Sector Tags',
            ),
        ),
        migrations.AddField(
            model_name='coursepage',
            name='type_of_export_tags',
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text='A comma-separated list of tags.',
                through='core.TypeOfExportTagged',
                to='core.TypeOfExportTag',
                verbose_name='Type of Export Tags',
            ),
        ),
    ]
