# Generated by Django 4.2.11 on 2024-04-10 15:55

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('export_academy', '0039_remove_exportacademyhomepage_series_delete_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportacademyhomepage',
            name='seriesList',
            field=wagtail.fields.StreamField(
                [
                    (
                        'Series',
                        wagtail.blocks.StructBlock(
                            [
                                ('course_name', wagtail.blocks.CharBlock(max_length=255)),
                                ('course_description', wagtail.blocks.CharBlock(max_length=255)),
                                ('course_image', wagtail.blocks.CharBlock(max_length=255)),
                                ('course_feature_one', wagtail.blocks.CharBlock(max_length=255)),
                                ('course_feature_twp', wagtail.blocks.CharBlock(max_length=255)),
                                ('course_feature_three', wagtail.blocks.CharBlock(max_length=255)),
                                ('course_cta_text', wagtail.blocks.CharBlock(max_length=255)),
                                ('course_cta_url', wagtail.blocks.CharBlock(max_length=255)),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
