# Generated by Django 4.2.11 on 2024-04-10 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('export_academy', '0040_alter_exportacademyhomepage_serieslist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exportacademyhomepage',
            old_name='seriesList',
            new_name='series_list',
        ),
    ]
