# Generated by Django 4.2.11 on 2024-05-13 13:56

import django.contrib.postgres.fields
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('export_academy', '0040_rename_countrytagged_countrytaggedevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsatUserFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, null=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, null=True, verbose_name='modified'
                    ),
                ),
                ('URL', models.CharField(max_length=255)),
                ('user_journey', models.CharField(max_length=255, null=True)),
                (
                    'satisfaction_rating',
                    models.CharField(
                        choices=[
                            ('VERY_SATISFIED', 'Very satisfied'),
                            ('SATISFIED', 'Satisfied'),
                            ('NEITHER', 'Neither satisfied nor dissatisfied'),
                            ('DISSATISFIED', 'Dissatisfied'),
                            ('VERY_DISSATISFIED', 'Very dissatisfied'),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    'experienced_issue',
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ('I_DID_NOT_EXPERIENCE_ANY_ISSUE', 'I did not experience any issue'),
                                ('I_DID_NOT_FIND_WHAT_I_WAS_LOOKING_FOR', 'I did not find what I was looking for'),
                                (
                                    'I_FOUND_IT_DIFFICULT_TO_NAVIGATE_THE_SITE',
                                    'I found it difficult to navigate the site',
                                ),
                                ('THE_SYSTEM_LACKS_THE_FEATURE_I_NEED', 'The system lacks the feature I need'),
                                (
                                    'I_WAS_UNABLE_TO_LOAD_REFRESH_ENTER_A_PAGE',
                                    'I was unable to load/refresh/enter a page',
                                ),
                                ('OTHER', 'Other'),
                            ],
                            max_length=255,
                        ),
                        default=list,
                        null=True,
                        size=6,
                    ),
                ),
                ('other_detail', models.CharField(max_length=255, null=True)),
                ('service_improvements_feedback', models.CharField(max_length=255, null=True)),
                (
                    'likelihood_of_return',
                    models.CharField(
                        choices=[
                            ('EXTREMELY_LIKELY', 'Extremely likely'),
                            ('LIKELY', 'Likely'),
                            ('NEITHER_LIKELY_NOR_UNLIKELY', 'Neither likely nor unlikely'),
                            ('UNLIKELY', 'Unlikely'),
                            ('EXTREMELY_UNLIKELY', 'Extremely unlikely'),
                            ('DONT_KNOW_OR_PREFER_NOT_TO_SAY', "Don't know / prefer not to say"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
