# Generated by Django 4.2.11 on 2024-05-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_academy', '0041_csatuserfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csatuserfeedback',
            name='service_improvements_feedback',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
