# Generated by Django 4.2.11 on 2024-05-30 15:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_academy', '0042_alter_csatuserfeedback_service_improvements_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csatuserfeedback',
            name='experienced_issue',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ('NOT_FIND_LOOKING_FOR', 'I did not find what I was looking for'),
                        ('DIFFICULT_TO_NAVIGATE', 'I found it difficult to navigate the service'),
                        ('SYSTEM_LACKS_FEATURE', 'The service lacks the feature I need'),
                        ('UNABLE_TO_LOAD/REFRESH/ENTER', 'I was unable to load/refresh/enter a page'),
                        ('OTHER', 'Other'),
                        ('NO_ISSUE', 'I did not experience any issues'),
                    ],
                    max_length=255,
                ),
                default=list,
                null=True,
                size=6,
            ),
        ),
        migrations.AlterField(
            model_name='csatuserfeedback',
            name='likelihood_of_return',
            field=models.CharField(
                choices=[
                    ('EXTREMELY_UNLIKELY', 'Extremely unlikely'),
                    ('UNLIKELY', 'Unlikely'),
                    ('NEITHER_LIKELY_NOR_UNLIKELY', 'Neither likely nor unlikely'),
                    ('LIKELY', 'Likely'),
                    ('EXTREMELY_LIKELY', 'Extremely likely'),
                    ('DONT_KNOW_OR_PREFER_NOT_TO_SAY', "Don't know / prefer not to say"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='csatuserfeedback',
            name='satisfaction_rating',
            field=models.CharField(
                choices=[
                    ('VERY_DISSATISFIED', 'Very dissatisfied'),
                    ('DISSATISFIED', 'Dissatisfied'),
                    ('NEITHER', 'Neither satisfied nor dissatisfied'),
                    ('SATISFIED', 'Satisfied'),
                    ('VERY_SATISFIED', 'Very satisfied'),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name='csatuserfeedback',
            name='user_journey',
            field=models.CharField(choices=[('EVENT_BOOKING', 'Event booking')], max_length=255, null=True),
        ),
    ]
