# Generated by Django 4.2.11 on 2024-04-11 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0140_casestudy_sector_tags_casestudy_type_of_export_tags_and_more'),
        ('export_academy', '0042_alter_exportacademyhomepage_series_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportacademyhomepage',
            name='series_list',
        ),
        migrations.AddField(
            model_name='exportacademyhomepage',
            name='course_cta_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Series CTA Text'),
        ),
        migrations.AddField(
            model_name='exportacademyhomepage',
            name='course_cta_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Series CTA URL'),
        ),
        migrations.AddField(
            model_name='exportacademyhomepage',
            name='course_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Series Description'),
        ),
        migrations.AddField(
            model_name='exportacademyhomepage',
            name='course_feature_one',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Series Feature One'),
        ),
        migrations.AddField(
            model_name='exportacademyhomepage',
            name='course_feature_three',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Series Feature Three'),
        ),
        migrations.AddField(
            model_name='exportacademyhomepage',
            name='course_feature_two',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Series Feature Two'),
        ),
        migrations.AddField(
            model_name='exportacademyhomepage',
            name='course_image',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='core.alttextimage',
                verbose_name='Series image',
            ),
        ),
        migrations.AddField(
            model_name='exportacademyhomepage',
            name='course_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Series Name'),
        ),
    ]
