# Generated by Django 4.2.11 on 2024-04-11 09:16

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('export_academy', '0043_remove_exportacademyhomepage_series_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportacademyhomepage',
            name='course_cta_text',
        ),
        migrations.RemoveField(
            model_name='exportacademyhomepage',
            name='course_cta_url',
        ),
        migrations.RemoveField(
            model_name='exportacademyhomepage',
            name='course_description',
        ),
        migrations.RemoveField(
            model_name='exportacademyhomepage',
            name='course_feature_one',
        ),
        migrations.RemoveField(
            model_name='exportacademyhomepage',
            name='course_feature_three',
        ),
        migrations.RemoveField(
            model_name='exportacademyhomepage',
            name='course_feature_two',
        ),
        migrations.RemoveField(
            model_name='exportacademyhomepage',
            name='course_image',
        ),
        migrations.RemoveField(
            model_name='exportacademyhomepage',
            name='course_name',
        ),
        migrations.AddField(
            model_name='exportacademyhomepage',
            name='series_list',
            field=wagtail.fields.StreamField(
                [
                    (
                        'Series',
                        wagtail.blocks.StructBlock(
                            [
                                ('course_name', wagtail.blocks.CharBlock(max_length=255)),
                                ('course_description', wagtail.blocks.CharBlock(max_length=255)),
                                ('course_image', wagtail.images.blocks.ImageChooserBlock()),
                                ('course_feature_one', wagtail.blocks.CharBlock(max_length=255)),
                                ('course_feature_twp', wagtail.blocks.CharBlock(max_length=255)),
                                ('course_feature_three', wagtail.blocks.CharBlock(max_length=255)),
                                ('course_cta_text', wagtail.blocks.CharBlock(max_length=255)),
                                ('course_cta_url', wagtail.blocks.CharBlock(max_length=255)),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
