# Generated by Django 4.2.11 on 2024-05-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_academy', '0043_alter_csatuserfeedback_experienced_issue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csatuserfeedback',
            name='user_journey',
            field=models.CharField(
                choices=[('EVENT_BOOKING', 'Event booking')], default='EVENT_BOOKING', max_length=255, null=True
            ),
        ),
    ]
