# Generated by Django 4.2.11 on 2024-04-11 09:28

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('export_academy', '0044_remove_exportacademyhomepage_course_cta_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportacademyhomepage',
            name='series_list',
            field=wagtail.fields.StreamField(
                [
                    (
                        'Series',
                        wagtail.blocks.StructBlock(
                            [
                                ('course_name', wagtail.blocks.CharBlock(max_length=255, required=False)),
                                ('course_description', wagtail.blocks.CharBlock(max_length=255, required=False)),
                                ('course_image', wagtail.images.blocks.ImageChooserBlock(required=False)),
                                ('course_feature_one', wagtail.blocks.CharBlock(max_length=255, required=False)),
                                ('course_feature_twp', wagtail.blocks.CharBlock(max_length=255, required=False)),
                                ('course_feature_three', wagtail.blocks.CharBlock(max_length=255, required=False)),
                                ('course_cta_text', wagtail.blocks.CharBlock(max_length=255, required=False)),
                                ('course_cta_url', wagtail.blocks.CharBlock(max_length=255, required=False)),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
