# Generated by Django 4.2.11 on 2024-05-30 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('export_academy', '0044_alter_csatuserfeedback_user_journey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csatuserfeedback',
            old_name='experienced_issue',
            new_name='experienced_issues',
        ),
    ]
