# Generated by Django 4.2.11 on 2024-06-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_academy', '0048_alter_exportacademyhomepage_events_and_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csatuserfeedback',
            name='likelihood_of_return',
            field=models.CharField(
                choices=[
                    ('EXTREMELY_UNLIKELY', 'Extremely unlikely'),
                    ('UNLIKELY', 'Unlikely'),
                    ('NEITHER_LIKELY_NOR_UNLIKELY', 'Neither likely nor unlikely'),
                    ('LIKELY', 'Likely'),
                    ('EXTREMELY_LIKELY', 'Extremely likely'),
                    ('DONT_KNOW_OR_PREFER_NOT_TO_SAY', "Don't know/prefer not to say"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
