# Generated by Django 4.2.11 on 2024-07-10 07:50

import django.db.models.deletion
import modelcluster.fields
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0151_regiontagged'),
        ('export_academy', '0049_alter_csatuserfeedback_likelihood_of_return'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='type_of_export_tags',
        ),
        migrations.CreateModel(
            name='RegionTaggedEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'content_object',
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE, to='export_academy.event'
                    ),
                ),
                (
                    'tag',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='+',
                        to='core.personalisationregiontag',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='event',
            name='region_tags',
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text='A comma-separated list of tags.',
                through='export_academy.RegionTaggedEvent',
                to='core.PersonalisationRegionTag',
                verbose_name='Region Tags',
            ),
        ),
    ]
