# Generated by Django 4.2.11 on 2024-04-18 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('export_academy', '0038_merge_20240415_0906'),
        ('export_academy', '0049_alter_exportacademyhomepage_events_and_series'),
    ]

    operations = []
