# Generated by Django 4.2.11 on 2024-07-19 07:30

import django.db.models.deletion
import modelcluster.fields
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0153_taskbasedcategorypage_taskbasedsubcategorypage'),
        ('export_academy', '0050_remove_event_type_of_export_tags_regiontaggedevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingBlocTaggedEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'content_object',
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE, to='export_academy.event'
                    ),
                ),
                (
                    'tag',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='+',
                        to='core.personalisationtradingbloctag',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='event',
            name='trading_bloc_tags',
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text='A comma-separated list of tags.',
                through='export_academy.TradingBlocTaggedEvent',
                to='core.PersonalisationTradingBlocTag',
                verbose_name='Trading Bloc Tags',
            ),
        ),
    ]
