# Generated by Django 4.2.14 on 2024-08-06 12:18

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0153_taskbasedcategorypage_taskbasedsubcategorypage'),
        ('export_academy', '0051_tradingbloctaggedevent_event_trading_bloc_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepage',
            name='region_tags',
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text='A comma-separated list of tags.',
                through='core.RegionTagged',
                to='core.PersonalisationRegionTag',
                verbose_name='Region Tags',
            ),
        ),
    ]
