# Generated by Django 4.2.15 on 2024-09-17 16:02

import modelcluster.contrib.taggit
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0158_alter_countrytagged_tag_alter_regiontagged_tag_and_more'),
        ('export_academy', '0052_coursepage_region_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepage',
            name='country_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text='A comma-separated list of tags.',
                through='core.CountryTagged',
                to='core.CountryTag',
                verbose_name='Tags',
            ),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='region_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text='A comma-separated list of tags.',
                through='core.RegionTagged',
                to='core.PersonalisationRegionTag',
                verbose_name='Tags',
            ),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='sector_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text='A comma-separated list of tags.',
                through='core.SectorTagged',
                to='core.SectorTag',
                verbose_name='Tags',
            ),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='type_of_export_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text='A comma-separated list of tags.',
                through='core.TypeOfExportTagged',
                to='core.TypeOfExportTag',
                verbose_name='Tags',
            ),
        ),
    ]
