# Generated by Django 4.2.20 on 2025-04-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_academy', '0054_remove_coursepage_struct_org_actions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepage',
            name='meta_robots_nofollow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coursepage',
            name='meta_robots_noindex',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exportacademyhomepage',
            name='meta_robots_nofollow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exportacademyhomepage',
            name='meta_robots_noindex',
            field=models.BooleanField(default=False),
        ),
    ]
