# Generated by Django 4.2.20 on 2025-05-08 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_academy', '0055_coursepage_meta_robots_nofollow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleeventset',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='export_academy.event'),
        ),
    ]
