exclude: ^react-components/dist/
repos:
    - repo: https://github.com/psf/black
      rev: 22.6.0
      hooks:
          - id: black
          # Config for black lives in pyproject.toml
    - repo: https://github.com/asottile/blacken-docs
      rev: v1.12.1
      hooks:
          - id: blacken-docs
            additional_dependencies: [black==20.8b1]
    - repo: https://github.com/PyCQA/isort
      rev: 5.10.1
      hooks:
          - id: isort
    - repo: https://github.com/pycqa/flake8
      rev: 3.9.2
      hooks:
          - id: flake8
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
          - id: trailing-whitespace
            args: ["--markdown-linebreak-ext=md,markdown"]
          - id: end-of-file-fixer
          - id: check-yaml
          # - id: check-added-large-files
          # - id: fix-encoding-pragma
          - id: check-ast
          - id: fix-byte-order-marker
          - id: check-merge-conflict
          - id: debug-statements
          - id: detect-private-key
          - id: detect-aws-credentials
            args: ["--allow-missing-credentials"]
    - repo: https://github.com/uktrade/pii-secret-check-hooks
      rev: 0.0.0.34
      hooks:
          - id: pii_secret_filename
            files: ''
            language: python
            args: [exclude]
            pass_filenames: true
            require_serial: true
          - id: pii_secret_file_content
            files: ''
            language: python
            args: [--exclude=pii-secret-exclude.txt]
            pass_filenames: true
            require_serial: true
            exclude: core/static/fonts/
          - id: hooks_version_check
            name: Checking local hooks against latest release
            verbose: true
            require_serial: true
# -   repo: https://github.com/pre-commit/pygrep-hooks
#     rev: v1.7.0
#     hooks:
#     -   id: python-use-type-annotations
#     -   id: python-no-eval
#     -   id: python-no-log-warn
