exclude: ^react-components/dist/
repos:
    - repo: https://github.com/psf/black
      rev: 24.4.2
      hooks:
          - id: black
          # Config for black lives in pyproject.toml
    - repo: https://github.com/asottile/blacken-docs
      rev: 1.18.0
      hooks:
          - id: blacken-docs
            additional_dependencies: [black==24.1.0]
    - repo: https://github.com/PyCQA/isort
      rev: 5.13.2
      hooks:
          - id: isort
    - repo: https://github.com/pycqa/flake8
      rev: 7.1.0
      hooks:
          - id: flake8
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
          - id: trailing-whitespace
            args: ["--markdown-linebreak-ext=md,markdown"]
          - id: end-of-file-fixer
          - id: check-yaml
          # - id: check-added-large-files
          # - id: fix-encoding-pragma
          - id: check-ast
          - id: fix-byte-order-marker
          - id: check-merge-conflict
          - id: debug-statements
          - id: detect-private-key
          - id: detect-aws-credentials
            args: ["--allow-missing-credentials"]
    - repo: https://github.com/uktrade/pii-secret-check-hooks
      rev: 0.0.0.36
      hooks:
          - id: pii_secret_filename
            files: ''
            language: python
            args: [exclude]
            pass_filenames: true
            require_serial: true
          - id: pii_secret_file_content
            files: ''
            language: python
            args: [--exclude=pii-secret-exclude.txt]
            pass_filenames: true
            require_serial: true
            exclude: core/static/fonts/
          - id: hooks_version_check
            name: Checking local hooks against latest release
            verbose: true
            require_serial: true


    - repo: local
      hooks:
        - id: check-django-migrations
          name: Check django migrations
          entry: make checkmigrations
          #if the above doesnt work for you
          # entry: python manage.py makemigrations --dry-run --check
          language: system
          types: [python] # hook only runs if a python file is staged
          pass_filenames: false

    - repo: https://github.com/Riverside-Healthcare/djLint
      rev: v1.34.1
      hooks:
        - id: djlint-reformat-django
        - id: djlint-django

# -   repo: https://github.com/pre-commit/pygrep-hooks
#     rev: v1.7.0
#     hooks:
#     -   id: python-use-type-annotations
#     -   id: python-no-eval
#     -   id: python-no-log-warn
