codecov:
  require_ci_to_pass: yes
  bot: 'magna-bot'

coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 2%
        base: auto
    patch:
      default:
        target: 90%
        threshold: 2%
        base: auto
  precision: 2
  round: down
  range: "90...100"


parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
