# Generated by Django 2.2.10 on 2020-03-12 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tour_tourstep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='page',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tour', to='wagtailcore.Page'),
        ),
    ]
