# Generated by Django 2.2.10 on 2020-03-18 09:24

from django.db import migrations
from django.core.management import call_command


def create_pages(apps, schema_editor):
    # this may fail when new fields are added to Page models.py because
    # call_command('create_pages') interacts with code that expects fields
    # to exist in the databse that have not yet been created in databse schema,
    # because call_command('create_pages') has no knowlege of the historic
    # Model shape that would normally be generatoed via apps.get_model(...)
    call_command('create_pages')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200312_1655'),
    ]

    operations = [
        migrations.RunPython(create_pages)
    ]
