# Generated by Django 2.2.10 on 2020-03-19 17:34

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields
import wagtail_personalisation.blocks
import wagtail_personalisation.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_personalisation', '0025_auto_20190822_0627'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('core', '0004_country_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalisedPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.core.fields.StreamField([('body', wagtail.core.blocks.StructBlock([('segment', wagtail.core.blocks.ChoiceBlock(choices=wagtail_personalisation.blocks.list_segment_choices, help_text='Only show this content block for users in this segment', label='Personalisation segment', required=False)), ('paragraph', wagtail.core.blocks.RichTextBlock())], icon='pilcrow'))])),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail_personalisation.models.PersonalisablePageMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='MatchProductQuerystring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Product')),
                ('segment', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_matchproductquerystrings', to='wagtail_personalisation.Segment')),
            ],
            options={
                'verbose_name': 'Match product rule',
            },
        ),
        migrations.CreateModel(
            name='MatchFirstCountryOfInterestRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Country')),
                ('segment', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_matchfirstcountryofinterestrules', to='wagtail_personalisation.Segment')),
            ],
            options={
                'verbose_name': 'Match first country of interest rule',
            },
        ),
        migrations.CreateModel(
            name='MatchCountryQuerystring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Country')),
                ('segment', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_matchcountryquerystrings', to='wagtail_personalisation.Segment')),
            ],
            options={
                'verbose_name': 'Match country rule',
            },
        ),
    ]
