# Generated by Django 2.2.10 on 2020-03-23 14:13

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail_personalisation.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_matchcountryquerystring_matchfirstcountryofinterestrule_matchproductquerystring_personalisedpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalisedpage',
            name='body',
            field=wagtail.core.fields.StreamField([('body', wagtail.core.blocks.StructBlock([('segment', wagtail.core.blocks.ChoiceBlock(choices=wagtail_personalisation.blocks.list_segment_choices, help_text='Only show this content block for users in this segment', label='Personalisation segment', required=False)), ('paragraph', wagtail.core.blocks.RichTextBlock())], icon='pilcrow', template='core/personalised_page_struct_block.html'))]),
        ),
    ]
