# Generated by Django 2.2.10 on 2020-04-24 22:07

import core.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200408_0851'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('listpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.ListPage')),
            ],
            options={
                'abstract': False,
            },
            bases=(core.mixins.WagtailAdminExclusivePageMixin, 'core.listpage'),
        ),
    ]
