# Generated by Django 2.2.10 on 2020-05-04 16:18

import core.blocks
import core.mixins
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail_personalisation.blocks
import wagtail_personalisation.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtail_personalisation', '0025_auto_20190822_0627'),
        ('core', '0010_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuratedListPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('template', models.CharField(max_length=255)),
                ('heading', models.TextField()),
                ('topics', wagtail.core.fields.StreamField([('title', wagtail.core.blocks.RichTextBlock()), ('page', wagtail.core.blocks.PageChooserBlock(page_type=['core.DetailPage']))])),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail_personalisation.models.PersonalisablePageMixin, core.mixins.EnableTourMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='InterstitialPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('template', models.CharField(max_length=255)),
                ('button', wagtail.core.fields.StreamField([('text', wagtail.core.blocks.CharBlock(max_length=255)), ('link', wagtail.core.blocks.StructBlock([('internal_link', wagtail.core.blocks.PageChooserBlock(label='Internal link', required=False)), ('external_link', wagtail.core.blocks.CharBlock(label='External link', max_length=255, required=False))]))])),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail_personalisation.models.PersonalisablePageMixin, core.mixins.EnableTourMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('template', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('button', wagtail.core.fields.StreamField([('text', wagtail.core.blocks.CharBlock(max_length=255)), ('link', wagtail.core.blocks.StructBlock([('internal_link', wagtail.core.blocks.PageChooserBlock(label='Internal link', required=False)), ('external_link', wagtail.core.blocks.CharBlock(label='External link', max_length=255, required=False))]))])),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail_personalisation.models.PersonalisablePageMixin, core.mixins.EnableTourMixin, 'wagtailcore.page'),
        ),
        migrations.AlterModelOptions(
            name='detailpage',
            options={'verbose_name': 'Personalisable detail page', 'verbose_name_plural': 'Personalisable detail pages'},
        ),
        migrations.AlterModelOptions(
            name='listpage',
            options={'verbose_name': 'Automated list page', 'verbose_name_plural': 'Automated list pages'},
        ),
        migrations.RemoveField(
            model_name='listpage',
            name='body',
        ),
        migrations.AddField(
            model_name='listpage',
            name='button',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.CharBlock(max_length=255)), ('link', wagtail.core.blocks.StructBlock([('internal_link', wagtail.core.blocks.PageChooserBlock(label='Internal link', required=False)), ('external_link', wagtail.core.blocks.CharBlock(label='External link', max_length=255, required=False))]))], default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listpage',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detailpage',
            name='body',
            field=wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.StructBlock([('segment', wagtail.core.blocks.ChoiceBlock(choices=wagtail_personalisation.blocks.list_segment_choices, help_text='Only show this content block for users in this segment', label='Personalisation segment', required=False)), ('paragraph', wagtail.core.blocks.RichTextBlock())], icon='pilcrow', template='core/personalised_page_struct_paragraph_block.html')), ('video', wagtail.core.blocks.StructBlock([('segment', wagtail.core.blocks.ChoiceBlock(choices=wagtail_personalisation.blocks.list_segment_choices, help_text='Only show this content block for users in this segment', label='Personalisation segment', required=False)), ('video', wagtail.core.blocks.StructBlock([('width', wagtail.core.blocks.IntegerBlock()), ('height', wagtail.core.blocks.IntegerBlock()), ('video', core.blocks.MediaChooserBlock())]))], icon='media', template='core/personalised_page_struct_video_block.html'))]),
        ),
        migrations.DeleteModel(
            name='HomePage',
        ),
    ]
