# Generated by Django 2.2.10 on 2020-05-04 14:08

import django.db.models.deletion
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields
import wagtail_personalisation.blocks
from django.db import migrations, models

import core.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_personalisation', '0025_auto_20190822_0627'),
        ('core', '0010_homepage'),
    ]

    operations = [
        migrations.RenameModel('MatchProductQuerystring', 'MatchProductExpertise'),
    ]
