# Generated by Django 2.2.10 on 2020-05-20 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200514_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curatedlistpage',
            name='record_read_progress',
        ),
        migrations.AddField(
            model_name='listpage',
            name='record_read_progress',
            field=models.BooleanField(default=False, help_text='Should we record when a user views a page in this collection?'),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='list_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views_list', to='core.ListPage'),
        ),
    ]
