# Generated by Django 2.2.14 on 2020-08-13 14:51

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtail_personalisation', '0025_auto_20190822_0627'),
        ('core', '0017_extendedlandingpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='body',
            field=wagtail.core.fields.StreamField([('section', wagtail.core.blocks.StreamBlock([('title', core.blocks.TitleBlock()), ('hr', core.blocks.HrBlock()), ('text_block', wagtail.core.blocks.RichTextBlock(helptext='Add a textblock', icon='openquote')), ('side_link', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=255)), ('lede', wagtail.core.blocks.CharBlock(max_length=255, required=False)), ('body', wagtail.core.blocks.TextBlock(max_length=255, required=False)), ('link', wagtail.core.blocks.StructBlock([('internal_link', wagtail.core.blocks.PageChooserBlock(label='Internal link', required=False)), ('external_link', wagtail.core.blocks.CharBlock(label='External link', max_length=255, required=False))], required=False))], icon='pick'))], icon='pick'))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='components',
            field=wagtail.core.fields.StreamField([('route', wagtail.core.blocks.StructBlock([('route_type', wagtail.core.blocks.ChoiceBlock(choices=[('learn', 'Learning'), ('plan', 'Export plan'), ('target', 'Target market')], icon='redirect')), ('title', wagtail.core.blocks.CharBlock(max_length=255)), ('body', wagtail.core.blocks.TextBlock(max_length=4096)), ('image', wagtail.images.blocks.ImageChooserBlock()), ('button', wagtail.core.blocks.StructBlock([('label', wagtail.core.blocks.CharBlock(max_length=255)), ('link', wagtail.core.blocks.StructBlock([('internal_link', wagtail.core.blocks.PageChooserBlock(label='Internal link', required=False)), ('external_link', wagtail.core.blocks.CharBlock(label='External link', max_length=255, required=False))], required=False))], icon='cog', required=False))], icon='pick'))], blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ExtendedLandingPage',
        ),
    ]
