# Generated by Django 2.2.14 on 2020-08-13 07:19

import core.mixins
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail_personalisation.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtail_personalisation', '0025_auto_20190822_0627'),
        ('core', '0017_detailpage_objective'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='body',
            field=wagtail.core.fields.StreamField([('section', wagtail.core.blocks.StreamBlock([('title', core.blocks.TitleBlock()), ('hr', core.blocks.HrBlock()), ('text_block', wagtail.core.blocks.RichTextBlock(helptext='Add a textblock', icon='openquote')), ('side_link', wagtail.core.blocks.StructBlock([('link', wagtail.core.blocks.StructBlock([('internal_link', wagtail.core.blocks.PageChooserBlock(label='Internal link', required=False)), ('external_link', wagtail.core.blocks.CharBlock(label='External link', max_length=255, required=False))], required=True)), ('title_override', wagtail.core.blocks.CharBlock(max_length=255, required=False)), ('lede_override', wagtail.core.blocks.CharBlock(max_length=255, required=False))])), ('image', core.blocks.ImageBlock()), ('target_table', core.blocks.ComponentTargetTable())])), ('hr', core.blocks.HrBlock()), ('image', core.blocks.ImageBlock())], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='components',
            field=wagtail.core.fields.StreamField([('route', wagtail.core.blocks.StructBlock([('route_type', wagtail.core.blocks.ChoiceBlock(choices=[('learn', 'Learning'), ('plan', 'Export plan'), ('target', 'Target market')], icon='redirect')), ('title', wagtail.core.blocks.CharBlock(max_length=255)), ('body', wagtail.core.blocks.TextBlock(max_length=4096)), ('image', wagtail.images.blocks.ImageChooserBlock()), ('button', wagtail.core.blocks.StructBlock([('label', wagtail.core.blocks.CharBlock(max_length=255)), ('link', wagtail.core.blocks.StructBlock([('internal_link', wagtail.core.blocks.PageChooserBlock(label='Internal link', required=False)), ('external_link', wagtail.core.blocks.CharBlock(label='External link', max_length=255, required=False))], required=False))], icon='cog', required=False))]))], blank=True, null=True),
        ),
    ]
