# Generated by Django 2.2.14 on 2020-08-17 13:07

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_detailpage_objective'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailpage',
            name='step_by_step',
            field=wagtail.core.fields.StreamField([('Step', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=255)), ('body', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))], icon='cog'))], blank=True, null=True),
        ),
    ]
