# Generated by Django 2.2.14 on 2020-08-25 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200819_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailpage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.AltTextImage'),
        ),
    ]
