# Generated by Django 2.2.14 on 2020-08-27 15:56

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_detailpage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailpage',
            name='recap',
            field=wagtail.core.fields.StreamField([('title', wagtail.core.blocks.CharBlock(icon='fa-header')), ('item', wagtail.core.blocks.StructBlock([('item', wagtail.core.blocks.CharBlock(max_length=255))], icon='fa-list'))], default=None),
            preserve_default=False,
        ),
    ]
