# Generated by Django 2.2.14 on 2020-08-27 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_detailpage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailpage',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.AltTextImage'),
        ),
    ]
