# Generated by Django 2.2.14 on 2020-08-28 16:13

import wagtail.core.blocks
import wagtail.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20200828_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailpage',
            name='recap',
            field=wagtail.core.fields.StreamField([('recap_item', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(icon='fa-header')), ('item', wagtail.core.blocks.StreamBlock([('item', wagtail.core.blocks.StructBlock([('item', wagtail.core.blocks.CharBlock(max_length=255))]))]))], icon='fa-commenting-o', template='learn/recap.html'))]),
        ),
    ]
