# Generated by Django 2.2.14 on 2020-09-03 15:06

import wagtail.core.blocks
import wagtail.core.fields
from django.db import migrations

import core.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20200902_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailpage',
            name='image',
        ),
        migrations.AddField(
            model_name='detailpage',
            name='hero',
            field=wagtail.core.fields.StreamField([('Image', core.blocks.ImageBlock()), ('Video', wagtail.core.blocks.StructBlock([('video', core.blocks.MediaChooserBlock())]))], null=True),
        ),
    ]
