# Generated by Django 2.2.14 on 2020-09-04 12:33

import wagtail.core.blocks
import wagtail.core.fields
from django.db import migrations

import core.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20200903_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailpage',
            name='hero',
            field=wagtail.core.fields.StreamField([('Image', core.blocks.ImageBlock(block_counts={'video': {'max_num': 1}}, max_num=1, template='core/includes/_hero_image.html')), ('Video', wagtail.core.blocks.StructBlock([('video', core.blocks.MediaChooserBlock())], max_num=1))], null=True),
        ),
    ]
