# Generated by Django 2.2.14 on 2020-09-08 11:51

import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import wagtail_personalisation.blocks
from django.db import migrations, models

import core.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20200907_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailpage',
            name='topic_block_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
