# Generated by Django 2.2.14 on 2020-09-16 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmedia', '0003_copy_media_permissions_to_collections'),
        ('core', '0032_auto_20200908_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='GreatMedia',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailmedia.Media')),
                ('transcript', models.TextField(blank=True, null=True, verbose_name='Transcript')),
            ],
            options={
                'verbose_name': 'media',
                'abstract': False,
            },
            bases=('wagtailmedia.media',),
        ),
    ]
