# Generated by Django 2.2.14 on 2020-10-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_change_content_module_to_case_study_on_detail_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greatmedia',
            name='transcript',
            field=models.TextField(null=True, verbose_name='Transcript'),
        ),
    ]
