# Generated by Django 2.2.14 on 2020-10-14 11:41

from django.db import migrations

import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0038_add_image_and_video_to_lesson_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curatedlistpage',
            name='topics',
            field=wagtail.fields.StreamField(
                [
                    (
                        'topic',
                        wagtail.blocks.StructBlock(
                            [
                                ('title', wagtail.blocks.CharBlock(max_length=255)),
                                (
                                    'pages',
                                    wagtail.blocks.ListBlock(wagtail.blocks.PageChooserBlock(label='Detail page')),
                                ),
                                (
                                    'lessons_and_placeholders',
                                    wagtail.blocks.StreamBlock(
                                        [
                                            ('lesson', wagtail.blocks.PageChooserBlock(page_type=['core.DetailPage'])),
                                            (
                                                'placeholder',
                                                wagtail.blocks.StructBlock(
                                                    [('title', wagtail.blocks.CharBlock(max_length=255))]
                                                ),
                                            ),
                                        ],
                                        required=False,
                                    ),
                                ),
                            ],
                            icon='plus',
                        ),
                    )
                ],
                use_json_field=True,
                blank=True,
                null=True,
            ),
        ),
    ]
