# Generated by Django 2.2.14 on 2020-10-14 11:41

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_add_image_and_video_to_lesson_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curatedlistpage',
            name='topics',
            field=wagtail.core.fields.StreamField([('topic', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=255)), ('pages', wagtail.core.blocks.ListBlock(wagtail.core.blocks.PageChooserBlock(label='Detail page'))), ('lessons_and_placeholders', wagtail.core.blocks.StreamBlock([('lesson', wagtail.core.blocks.PageChooserBlock(page_type=['core.DetailPage'])), ('placeholder', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=255))]))], required=False))], icon='plus'))], blank=True, null=True),
        ),
    ]
