# Generated by Django 2.2.14 on 2020-10-15 16:13

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_migrate_data_to_new_lessons_and_placeholders_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curatedlistpage',
            name='topics',
            field=wagtail.core.fields.StreamField([('topic', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=255)), ('lessons_and_placeholders', wagtail.core.blocks.StreamBlock([('lesson', wagtail.core.blocks.PageChooserBlock(page_type=['core.DetailPage'])), ('placeholder', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=255))]))], required=False))], icon='plus'))], blank=True, null=True),
        ),
    ]
