# Generated by Django 2.2.14 on 2020-11-02 13:52

import django.db.models.deletion
from django.db import migrations, models

import core.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        ('core', '0042_casestudy_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlaceholderPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=(core.mixins.AuthenticatedUserRequired, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='TopicPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=(core.mixins.AuthenticatedUserRequired, 'wagtailcore.page'),
        ),
        migrations.AlterModelOptions(
            name='detailpage',
            options={'verbose_name': 'Detail page', 'verbose_name_plural': 'Detail pages'},
        ),
    ]
