# Generated by Django 2.2.14 on 2020-11-05 13:30

"""This data migration updates the page tree to use the new TopicPage model.

It takes information from CuratedListPage.topics (a CuratedTopicBlock instance)
and uses that to:

1) For EACH `topic` within the CuratedTopicBlock add one new TopicPage (using the
title of the `topic`) as a child of the CuratedListPage instance

2) For EACH `topic` within the CuratedTopicBlock, for EACH item featured
within it:
   a) if it is a lesson, move that lesson (DetailPage) to be a child of the
   relevant TopicPage,
   B) if it is a placeholder, create a LessonPlaceholderPage, using the title
   from the data, to be a child of the relevant TopicPage,
all the while ensuring the order of the children of the TopicPage is the same as the
order they were in when represented by a CuratedTopicBlock

"""

from django.db import migrations

from core.migration_helpers import create_topics_and_reparent_lessons


# NB: there is no backwards procedure for this migration
def forwards(apps, schema_editor):

    # function lives elsewhere, to make it more easily testable
    create_topics_and_reparent_lessons()



class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_new_topics_hierarchy_schema'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop)
    ]
