# Generated by Django 2.2.14 on 2020-11-26 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_data_reparent_topics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curatedlistpage',
            name='topics',
        ),
        migrations.RemoveField(
            model_name='detailpage',
            name='topic_block_id',
        ),
    ]
