# Generated by Django 2.2.14 on 2021-01-11 16:55

from django.db import migrations


def forwards_tags(apps, schema_editor):
    Tag = apps.get_model('core', 'Tag')
    for name in [
        'Legal',
        'Accessing markets',
        'Tariffs',
        'New to exporting',
        'Trade restrictions',
        'Export tips',
        'Regulations',
        'Exporting to EU countries',
        'Importing from EU countries',
        'Free economic zones',
        'Tax',
        'Duty',
    ]:
        Tag.objects.get_or_create(name=name)


def forwards_industry_tags(apps, schema_editor):
    IndustryTag = apps.get_model('core', 'IndustryTag')
    for name in [
        'Advanced manufacturing',
        'Aerospace',
        'Agri-technology',
        'Agriculture',
        'Automotive',
        'Biotechnology',
        'Cleantech',
        'Construction',
        'Consumer products',
        'Cyber security',
        'E-commerce',
        'Education',
        'Energy',
        'Engineering',
        'Financial services',
        'Fintech',
        'Fisheries',
        'Food and drink',
        'Healthcare',
        'Horticulture',
        'Infrastructure',
        'International organisations',
        'Leisure and tourism',
        'Life sciences',
        'Low carbon',
        'Luxury',
        'Mining',
        'Nuclear',
        'Ocean economy',
        'Offshore wind',
        'Oil and gas',
        'Pharmaceuticals',
        'Professional services',
        'Renewables',
        'Retail',
        'Safety',
        'Security',
        'Smart cities',
        'Sport',
        'Technology',
        'Training',
        'Transport',
    ]:
        IndustryTag.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_make_country_slug_non_nullable'),
    ]

    operations = [
        migrations.RunPython(forwards_tags, migrations.RunPython.noop),
        migrations.RunPython(forwards_industry_tags, migrations.RunPython.noop),
    ]
