# Generated by Django 2.2.14 on 2021-01-25 10:04

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        ('core', '0049_data_bootstrap_tag_and_industrytag_snippets'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudyRelatedPages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                (
                    'case_study',
                    modelcluster.fields.ParentalKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='related_pages',
                        to='core.CaseStudy',
                    ),
                ),
                (
                    'page',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='wagtailcore.Page',
                    ),
                ),
            ],
            options={
                'unique_together': {('case_study', 'page')},
            },
        ),
    ]
