# Generated by Django 2.2.14 on 2021-01-28 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_add_region_and_country_data_for_snippets'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('name',), 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='industrytag',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('name',)},
        ),
    ]
