# Generated by Django 2.2.18 on 2021-02-02 12:36

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations

import core.blocks


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0052_update_meta_options_for_snippets'),
    ]

    operations = [
        # DELIBERATELY DISABLED AS PART OF CONTROLLED REMOVAL - NO LONGER CREATED (SEE SQUASHED MIGRATION)
        # migrations.RemoveField(
        #     model_name='matchfirstcountryofinterestrule',
        #     name='country',
        # ),
        # migrations.RemoveField(
        #     model_name='matchfirstcountryofinterestrule',
        #     name='segment',
        # ),
        # migrations.RemoveField(
        #     model_name='matchfirstindustryofinterestrule',
        #     name='segment',
        # ),
        # migrations.RemoveField(
        #     model_name='matchproductexpertise',
        #     name='product',
        # ),
        # migrations.RemoveField(
        #     model_name='matchproductexpertise',
        #     name='segment',
        # ),
        migrations.AlterField(
            model_name='detailpage',
            name='body',
            field=wagtail.fields.StreamField(
                [
                    (
                        'paragraph',
                        wagtail.blocks.StructBlock(
                            [('paragraph', wagtail.blocks.RichTextBlock())],
                            icon='fa-font',
                            template='core/struct_paragraph_block.html',
                        ),
                    ),
                    (
                        'video',
                        wagtail.blocks.StructBlock(
                            [('video', core.blocks.MediaChooserBlock())],
                            help_text='Video displayed within a full-page-width block',
                            template='core/includes/_video_full_width.html',
                        ),
                    ),
                    ('case_study', core.blocks.CaseStudyStaticBlock(icon='fa-book')),
                    (
                        'Step',
                        wagtail.blocks.StructBlock(
                            [
                                ('title', wagtail.blocks.CharBlock(max_length=255)),
                                ('body', wagtail.blocks.RichTextBlock()),
                                ('image', wagtail.images.blocks.ImageChooserBlock(required=False)),
                            ],
                            icon='cog',
                        ),
                    ),
                    (
                        'fictional_example',
                        wagtail.blocks.StructBlock(
                            [('fiction_body', wagtail.blocks.RichTextBlock(icon='openquote'))],
                            icon='fa-commenting-o',
                            template='learn/fictional_company_example.html',
                        ),
                    ),
                    (
                        'ITA_Quote',
                        wagtail.blocks.StructBlock(
                            [
                                ('quote', wagtail.blocks.RichTextBlock()),
                                ('author', wagtail.blocks.CharBlock(max_length=255)),
                            ],
                            icon='fa-quote-left',
                        ),
                    ),
                    (
                        'pros_cons',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'pros',
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                'item',
                                                wagtail.blocks.StructBlock(
                                                    [('item', wagtail.blocks.CharBlock(max_length=255))],
                                                    icon='fa-arrow-right',
                                                ),
                                            )
                                        ]
                                    ),
                                ),
                                (
                                    'cons',
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                'item',
                                                wagtail.blocks.StructBlock(
                                                    [('item', wagtail.blocks.CharBlock(max_length=255))],
                                                    icon='fa-arrow-right',
                                                ),
                                            )
                                        ]
                                    ),
                                ),
                            ],
                            icon='fa-arrow-right',
                            template='learn/pros_and_cons.html',
                        ),
                    ),
                    (
                        'choose_do_not_choose',
                        wagtail.blocks.StructBlock(
                            [
                                ('choose_title', wagtail.blocks.CharBlock(max_length=255)),
                                ('choose_body', wagtail.blocks.RichTextBlock(features=())),
                                ('do_not_choose_title', wagtail.blocks.CharBlock(max_length=255)),
                                ('do_not_choose_body', wagtail.blocks.RichTextBlock(features=())),
                            ]
                        ),
                    ),
                    (
                        'image',
                        core.blocks.ImageBlock(
                            help_text='Image displayed within a full-page-width block',
                            template='core/includes/_image_full_width.html',
                        ),
                    ),
                ],
                use_json_field=True,
            ),
        ),
        # DELIBERATELY DISABLED AS PART OF CONTROLLED REMOVAL - NO LONGER CREATED (SEE SQUASHED MIGRATION)
        # migrations.DeleteModel(
        #     name='MatchCountryQuerystring',
        # ),
        # migrations.DeleteModel(
        #     name='MatchFirstCountryOfInterestRule',
        # ),
        # migrations.DeleteModel(
        #     name='MatchFirstIndustryOfInterestRule',
        # ),
        # migrations.DeleteModel(
        #     name='MatchProductExpertise',
        # ),
    ]
