# Generated by Django 2.2.18 on 2021-02-09 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        ('core', '0053_remove_wagtail_personalisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudyScoringSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'threshold',
                    models.DecimalField(
                        decimal_places=3,
                        default=20,
                        help_text='This is the minimum score which a case study needs to have to be considered before being presented to users. This is calculated as the sum of the positive scores deducted by the dampening scores below.',
                        max_digits=5,
                    ),
                ),
                (
                    'module',
                    models.DecimalField(
                        decimal_places=3,
                        default=2,
                        help_text='This is the score we give a case study should it have an association at this level in our information architecture',
                        max_digits=5,
                    ),
                ),
                (
                    'topic',
                    models.DecimalField(
                        decimal_places=3,
                        default=4,
                        help_text='This is the score we give a case study should it have an association at this level in our information architecture',
                        max_digits=5,
                    ),
                ),
                (
                    'lesson',
                    models.DecimalField(
                        decimal_places=3,
                        default=8,
                        help_text='This is the score we give a case study should it have an association at this level in our information architecture',
                        max_digits=5,
                    ),
                ),
                (
                    'no_product',
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text='This is the score we give if a case study matches the HS code product attribute ',
                        max_digits=5,
                    ),
                ),
                (
                    'product_hs6',
                    models.DecimalField(
                        decimal_places=3,
                        default=8,
                        help_text='This is the score we give if a case study matches the HS code product tag at the HS6 level ',
                        max_digits=5,
                    ),
                ),
                (
                    'product_hs4',
                    models.DecimalField(
                        decimal_places=3,
                        default=4,
                        help_text='This is the score we give if a case study matches the HS code product tag at the HS4 level ',
                        max_digits=5,
                    ),
                ),
                (
                    'product_hs2',
                    models.DecimalField(
                        decimal_places=3,
                        default=2,
                        help_text='This is the score we give if a case study matches the HS code product tag at the HS2 level ',
                        max_digits=5,
                    ),
                ),
                (
                    'no_country',
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text='This is the score we give if a case study matches the country tag',
                        max_digits=5,
                    ),
                ),
                (
                    'country_region',
                    models.DecimalField(
                        decimal_places=3,
                        default=2,
                        help_text='This is the score we give if a case study matches the country tag at a regional level',
                        max_digits=5,
                    ),
                ),
                (
                    'country_exact',
                    models.DecimalField(
                        decimal_places=3,
                        default=4,
                        help_text='This is the score we give if a case study matches the country tag at a country level',
                        max_digits=5,
                    ),
                ),
                (
                    'other_product_hs6',
                    models.DecimalField(
                        decimal_places=3,
                        default=-0.5,
                        help_text='This is the score we deduct if a case study matches for another HS code at the HS6 level',
                        max_digits=5,
                    ),
                ),
                (
                    'other_product_hs4',
                    models.DecimalField(
                        decimal_places=3,
                        default=-0.25,
                        help_text='This is the score we deduct if a case study matches for another HS code at the HS4 level',
                        max_digits=5,
                    ),
                ),
                (
                    'other_product_hs2',
                    models.DecimalField(
                        decimal_places=3,
                        default=-0.125,
                        help_text='This is the score we deduct if a case study matches for another HS code at the HS2 level',
                        max_digits=5,
                    ),
                ),
                (
                    'other_country_region',
                    models.DecimalField(
                        decimal_places=3,
                        default=-0.125,
                        help_text='This is the score we deduct if a case study matches for another country tag at a regional level',
                        max_digits=5,
                    ),
                ),
                (
                    'other_country_exact',
                    models.DecimalField(
                        decimal_places=3,
                        default=-0.25,
                        help_text='This is the score we deduct if a case study matches for another country tag at a country level',
                        max_digits=5,
                    ),
                ),
                (
                    'other_lesson_tags',
                    models.DecimalField(
                        decimal_places=3,
                        default=-0.125,
                        help_text='This is the score we deduct for a case study should it have an association at this level in our information architecture',
                        max_digits=5,
                    ),
                ),
                (
                    'recency_3_months',
                    models.DecimalField(
                        decimal_places=3,
                        default=8,
                        help_text='This is the score we give if a case study has been published or modified in this time range',
                        max_digits=5,
                    ),
                ),
                (
                    'recency_6_months',
                    models.DecimalField(
                        decimal_places=3,
                        default=4,
                        help_text='This is the score we give if a case study has been published or modified in this time range',
                        max_digits=5,
                    ),
                ),
                (
                    'recency_9_months',
                    models.DecimalField(
                        decimal_places=3,
                        default=2,
                        help_text='This is the score we give if a case study has been published or modified in this time range',
                        max_digits=5,
                    ),
                ),
                (
                    'recency_12_months',
                    models.DecimalField(
                        decimal_places=3,
                        default=1,
                        help_text='This is the score we give if a case study has been published or modified in this time range',
                        max_digits=5,
                    ),
                ),
                (
                    'recency_15_months',
                    models.DecimalField(
                        decimal_places=3,
                        default=0.5,
                        help_text='This is the score we give if a case study has been published or modified in this time range',
                        max_digits=5,
                    ),
                ),
                (
                    'recency_18_months',
                    models.DecimalField(
                        decimal_places=3,
                        default=0.25,
                        help_text='This is the score we give if a case study has been published or modified in this time range',
                        max_digits=5,
                    ),
                ),
                (
                    'recency_21_months',
                    models.DecimalField(
                        decimal_places=3,
                        default=0.125,
                        help_text='This is the score we give if a case study has been published or modified in this time range',
                        max_digits=5,
                    ),
                ),
                (
                    'recency_24_months',
                    models.DecimalField(
                        decimal_places=3,
                        default=0.0625,
                        help_text='This is the score we give if a case study has been published or modified in this time range',
                        max_digits=5,
                    ),
                ),
                (
                    'trading_blocs',
                    models.DecimalField(
                        decimal_places=3,
                        default=2,
                        help_text='This is the score we give if a case study matches the country tag at a trading bloc level',
                        max_digits=5,
                    ),
                ),
                (
                    'site',
                    models.OneToOneField(
                        editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Case Study Scoring',
            },
        ),
    ]
