# Generated by Django 2.2.19 on 2021-02-22 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_auto_20210217_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industrytag',
            name='icon',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='core.AltTextImage',
            ),
        ),
    ]
