# Generated by Django 2.2.19 on 2021-02-23 00:16

import wagtail.blocks
import wagtail.fields
from django.db import migrations

import core.blocks
import core.models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0058_auto_20210217_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='body',
            field=wagtail.fields.StreamField(
                [
                    (
                        'media',
                        wagtail.blocks.StreamBlock(
                            [
                                (
                                    'video',
                                    wagtail.blocks.StructBlock(
                                        [('video', core.blocks.MediaChooserBlock())],
                                        template='core/includes/_case_study_video.html',
                                    ),
                                ),
                                ('image', core.blocks.ImageBlock()),
                            ],
                            max_num=2,
                            min_num=1,
                        ),
                    ),
                    ('text', wagtail.blocks.RichTextBlock(features=())),
                    (
                        'quote',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'quotes',
                                    wagtail.blocks.StreamBlock(
                                        [('quote', wagtail.blocks.RichTextBlock(features=()))],
                                        block_counts={'quote': {'max_num': 10}},
                                        required=False,
                                    ),
                                ),
                                (
                                    'attribution',
                                    wagtail.blocks.CharBlock(label='Who said it?', max_length=255, required=False),
                                ),
                                ('role', wagtail.blocks.CharBlock(label='Their role', max_length=255, required=False)),
                            ]
                        ),
                    ),
                ],
                use_json_field=True,
                help_text='This block must contain one Media section (with one or two items in it) and/or Quote sections, then one Text section.',
                validators=[core.models.case_study_body_validation],
            ),
        ),
    ]
