# Generated by Django 2.2.19 on 2021-02-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_add_quote_block_to_case_study_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casestudy',
            old_name='summary',
            new_name='lead_title',
        ),
        migrations.RenameField(
            model_name='casestudy',
            old_name='company_name',
            new_name='summary_context',
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Internal case study title'),
        ),
    ]
