# Generated by Django 2.2.19 on 2021-02-23 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_correct_image_relation_for_industrytag'),
        ('core', '0059_add_quote_block_to_case_study_page'),
    ]

    operations = [
    ]
