# Generated by Django 2.2.19 on 2021-02-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_auto_20210223_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='summary_context',
            field=models.CharField(default='How we did it', max_length=255),
        ),
    ]
