# Generated by Django 2.2.19 on 2021-03-09 12:12

"""This migration was created after squashing core.0001 ... core.0038.

The four fields slightly amended here appear to all be ones which once had
a default value explicitly set (either None or ''), but which isn't currently
reflected in the real model code. (This implies some editing of migrations
might have taken place in the past.) They don't look like problematic changes.
"""

import wagtail.core.blocks
import wagtail.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_add_case_study_context_field_default_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailpage',
            name='objective',
            field=wagtail.core.fields.StreamField(
                [
                    ('paragraph', wagtail.core.blocks.RichTextBlock(options={'class': 'objectives'})),
                    (
                        'ListItem',
                        wagtail.core.blocks.StructBlock([('item', wagtail.core.blocks.CharBlock(max_length=255))]),
                    ),
                ]
            ),
        ),
        migrations.AlterField(
            model_name='detailpage',
            name='template',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='listpage',
            name='button_label',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='listpage',
            name='description',
            field=wagtail.core.fields.RichTextField(),
        ),
    ]
