# Generated by Django 2.2.19 on 2021-03-09 16:12

import logging

from django.db import connection, migrations

logger = logging.getLogger(__name__)


def drop_wagtail_personalisation_migration_history(apps, schema_migration):
    # Drop the records from the django_migrations table that reference
    # wagtail-personalisation, which would cause issues if re-adding W-P
    # to the project in the future

    with connection.cursor() as cursor:
        query = f"delete from django_migrations where app = 'wagtail_personalisation';"
        logger.info(f"Query: {query}")
        cursor.execute(query)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_delete_wagtail_personalisation_tables'),
    ]

    operations = [
        migrations.RunPython(
            drop_wagtail_personalisation_migration_history,
            migrations.RunPython.noop,
        ),
    ]
