# Generated by Django 2.2.22 on 2021-05-12 11:40

import wagtail.core.blocks
import wagtail.core.fields
from django.db import migrations

import core.blocks
import core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_delete_wagtail_personalisation_migration_references'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailpage',
            name='hero',
            field=wagtail.core.fields.StreamField(
                [
                    ('Image', core.blocks.ImageBlock(template='core/includes/_hero_image.html')),
                    (
                        'Video',
                        wagtail.core.blocks.StructBlock(
                            [('video', core.blocks.MediaChooserBlock())], template='core/includes/_hero_video.html'
                        ),
                    ),
                ],
                blank=True,
                null=True,
                validators=[core.models.hero_singular_validation],
            ),
        ),
    ]
