# Generated by Django 2.2.22 on 2021-05-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_allow_blank_detailpage_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='greatmedia',
            name='subtitles_en',
            field=models.TextField(
                blank=True,
                help_text='English-language subtitles for this video, in VTT format',
                null=True,
                verbose_name='English subtitles',
            ),
        ),
    ]
