# Generated by Django 2.2.24 on 2021-08-17 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_greatmedia_subtitles_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudyrelatedpages',
            name='page',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Page'
            ),
        ),
    ]
