# Generated by Django 2.2.24 on 2021-10-14 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_auto_20210817_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casestudyscoringsettings',
            name='other_country_exact',
        ),
        migrations.RemoveField(
            model_name='casestudyscoringsettings',
            name='other_country_region',
        ),
        migrations.RemoveField(
            model_name='casestudyscoringsettings',
            name='other_lesson_tags',
        ),
        migrations.RemoveField(
            model_name='casestudyscoringsettings',
            name='other_module_tags',
        ),
        migrations.RemoveField(
            model_name='casestudyscoringsettings',
            name='other_product_hs2',
        ),
        migrations.RemoveField(
            model_name='casestudyscoringsettings',
            name='other_product_hs4',
        ),
        migrations.RemoveField(
            model_name='casestudyscoringsettings',
            name='other_product_hs6',
        ),
        migrations.RemoveField(
            model_name='casestudyscoringsettings',
            name='other_topic_tags',
        ),
        migrations.RemoveField(
            model_name='casestudyscoringsettings',
            name='recency_12_months',
        ),
        migrations.RemoveField(
            model_name='casestudyscoringsettings',
            name='recency_15_months',
        ),
        migrations.RemoveField(
            model_name='casestudyscoringsettings',
            name='recency_18_months',
        ),
        migrations.RemoveField(
            model_name='casestudyscoringsettings',
            name='recency_21_months',
        ),
        migrations.RemoveField(
            model_name='casestudyscoringsettings',
            name='recency_24_months',
        ),
        migrations.RemoveField(
            model_name='casestudyscoringsettings',
            name='recency_3_months',
        ),
        migrations.RemoveField(
            model_name='casestudyscoringsettings',
            name='recency_6_months',
        ),
        migrations.RemoveField(
            model_name='casestudyscoringsettings',
            name='recency_9_months',
        ),
    ]
