# Generated by Django 2.2.24 on 2021-11-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_auto_20211014_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudyscoringsettings',
            name='country_exact',
            field=models.DecimalField(
                decimal_places=3,
                default=4,
                help_text="Score given when any case study country tag exactly matches one of the user's export markets.",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name='casestudyscoringsettings',
            name='country_region',
            field=models.DecimalField(
                decimal_places=3,
                default=2,
                help_text="Score given when any case study region tag matches the region of any of the user's export markets unless there is an exact country match.",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name='casestudyscoringsettings',
            name='lesson',
            field=models.DecimalField(
                decimal_places=3,
                default=8,
                help_text="Score given when user's lesson is tagged in the case study.",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name='casestudyscoringsettings',
            name='module',
            field=models.DecimalField(
                decimal_places=3,
                default=2,
                help_text="Score given when the user's lesson's module is tagged in the case study unless there is also lesson or topic match.",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name='casestudyscoringsettings',
            name='product_hs2',
            field=models.DecimalField(
                decimal_places=3,
                default=2,
                help_text="Score given when any case study HS2 tag matches the first 2 digits of any of the user's products unless there is an HS6 or HS4 match.",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name='casestudyscoringsettings',
            name='product_hs4',
            field=models.DecimalField(
                decimal_places=3,
                default=4,
                help_text="Score given when any case study HS4 tag matches the first 4 digits of any of the user's products unless there is an HS6 match.",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name='casestudyscoringsettings',
            name='product_hs6',
            field=models.DecimalField(
                decimal_places=3,
                default=8,
                help_text="Score given when any case study HS6 tag matches the complete HS6 code of any of the user's products",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name='casestudyscoringsettings',
            name='threshold',
            field=models.DecimalField(
                decimal_places=3,
                default=10,
                help_text='This is the minimum score which a case study needs to have to be considered before being presented to users. ',
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name='casestudyscoringsettings',
            name='topic',
            field=models.DecimalField(
                decimal_places=3,
                default=4,
                help_text="Score given when user's lesson's topic is tagged in the case study unless there is also lesson match.",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name='casestudyscoringsettings',
            name='trading_blocs',
            field=models.DecimalField(
                decimal_places=3,
                default=2,
                help_text="Score given when any case study trading bloc tag matches the any trading bloc that any of the user's export markets falls into unless there is an exact country or region match.",
                max_digits=5,
            ),
        ),
    ]
