# Generated by Django 2.2.24 on 2021-11-25 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_auto_20211108_0850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alttextimage',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images List'},
        ),
    ]
