# Generated by Django 2.2.27 on 2022-02-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_auto_20211125_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='iso2',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
