# Generated by Django 2.2.27 on 2022-02-24 12:56
import requests
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_country_iso2'),
    ]

    operations = [
        migrations.RunPython(code=migrations.RunPython.noop, reverse_code=migrations.RunPython.noop),
    ]
