# Generated by Django 2.2.27 on 2022-02-24 12:56
import requests
from django.db import migrations


def populate_iso2(apps, schema_editor):
    """
    This attempts to resolve ISO2 codes from the API available at restcountries.com
    """
    Country = apps.get_model('core', 'Country')
    all_countries = requests.get("https://restcountries.com/v3.1/all?fields=name,cca2")
    if all_countries.status_code == 200:
        all_countries_json = all_countries.json()
        for country in Country.objects.all():
            if country.name:
                found = list(filter(lambda x: x['name']['common'] == country.name, all_countries_json))
                if len(found) > 0:
                    country.iso2 = found[0]['cca2']
                    country.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_country_iso2'),
    ]

    operations = [
        migrations.RunPython(populate_iso2),
    ]
