# Generated by Django 3.2.16 on 2023-02-21 15:32

import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('core', '0074_populate_country_iso2'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicrositeRoot',
            fields=[
                (
                    'page_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='wagtailcore.page',
                    ),
                ),
                (
                    'menu_choices',
                    wagtail.core.fields.StreamField(
                        [
                            (
                                'menu_item',
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            'title',
                                            wagtail.core.blocks.CharBlock(
                                                choices=[('test1', 'test1')], default='', form_classname='title'
                                            ),
                                        ),
                                        ('url', wagtail.core.blocks.CharBlock(default='', form_classname='url')),
                                    ]
                                ),
                            ),
                            (
                                'external_link',
                                wagtail.core.blocks.StructBlock(
                                    [
                                        ('title', wagtail.core.blocks.CharBlock(default='', form_classname='title')),
                                        ('url', wagtail.core.blocks.URLBlock(default='', form_classname='url')),
                                    ]
                                ),
                            ),
                        ],
                        blank=True,
                        null=True,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Microsite root page',
                'verbose_name_plural': 'Microsite root pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='MicrositeSubPage',
            fields=[
                (
                    'page_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='wagtailcore.page',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Microsite sub page',
                'verbose_name_plural': 'Microsite sub pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
