# Generated by Django 2.2.28 on 2022-06-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_populate_country_iso2'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='latlng',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
