# Generated by Django 2.2.28 on 2022-09-06 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_populate_country_iso2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourstep',
            name='tour',
        ),
        migrations.DeleteModel(
            name='Tour',
        ),
        migrations.DeleteModel(
            name='TourStep',
        ),
    ]
