# Generated by Django 3.2.16 on 2023-02-10 16:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0075_micrositeroot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='micrositeroot',
            name='canonical_url',
        ),
        migrations.RemoveField(
            model_name='micrositeroot',
            name='og_image',
        ),
        migrations.RemoveField(
            model_name='micrositeroot',
            name='struct_org_actions',
        ),
        migrations.RemoveField(
            model_name='micrositeroot',
            name='struct_org_address_country',
        ),
        migrations.RemoveField(
            model_name='micrositeroot',
            name='struct_org_address_locality',
        ),
        migrations.RemoveField(
            model_name='micrositeroot',
            name='struct_org_address_postal',
        ),
        migrations.RemoveField(
            model_name='micrositeroot',
            name='struct_org_address_region',
        ),
        migrations.RemoveField(
            model_name='micrositeroot',
            name='struct_org_address_street',
        ),
        migrations.RemoveField(
            model_name='micrositeroot',
            name='struct_org_extra_json',
        ),
        migrations.RemoveField(
            model_name='micrositeroot',
            name='struct_org_geo_lat',
        ),
        migrations.RemoveField(
            model_name='micrositeroot',
            name='struct_org_geo_lng',
        ),
        migrations.RemoveField(
            model_name='micrositeroot',
            name='struct_org_hours',
        ),
        migrations.RemoveField(
            model_name='micrositeroot',
            name='struct_org_image',
        ),
        migrations.RemoveField(
            model_name='micrositeroot',
            name='struct_org_logo',
        ),
        migrations.RemoveField(
            model_name='micrositeroot',
            name='struct_org_name',
        ),
        migrations.RemoveField(
            model_name='micrositeroot',
            name='struct_org_phone',
        ),
        migrations.RemoveField(
            model_name='micrositeroot',
            name='struct_org_type',
        ),
        migrations.RemoveField(
            model_name='micrositeroot',
            name='template',
        ),
    ]
