# Generated by Django 3.2.18 on 2023-03-07 17:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0075_add_secondary_field_button_block'),
        ('core', '0075_microsite_model'),
    ]

    operations = []
