# Generated by Django 3.2.16 on 2023-02-10 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('core', '0076_auto_20230210_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicrositeSubPage',
            fields=[
                (
                    'page_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='wagtailcore.page',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Microsite sub page',
                'verbose_name_plural': 'Microsite sub pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
