# Generated by Django 3.2.18 on 2023-03-20 09:40

import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
from django.db import migrations

import core.blocks


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0077_alter_micrositepage_page_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='micrositepage',
            name='page_body',
            field=wagtail.core.fields.StreamField(
                [
                    ('text', wagtail.core.blocks.RichTextBlock(template='microsites/blocks/text.html')),
                    (
                        'image',
                        wagtail.images.blocks.ImageChooserBlock(
                            required=False, template='microsites/blocks/image.html'
                        ),
                    ),
                    (
                        'video',
                        wagtail.core.blocks.StructBlock(
                            [('video', core.blocks.MediaChooserBlock())], template='microsites/blocks/video.html'
                        ),
                    ),
                    (
                        'columns',
                        wagtail.core.blocks.StreamBlock(
                            [
                                (
                                    'column',
                                    wagtail.core.blocks.StructBlock(
                                        [
                                            (
                                                'title',
                                                wagtail.core.blocks.CharBlock(
                                                    label='Title', max_length=255, required=False
                                                ),
                                            ),
                                            (
                                                'image',
                                                wagtail.images.blocks.ImageChooserBlock(
                                                    label='Hero Image', required=False
                                                ),
                                            ),
                                            (
                                                'description',
                                                wagtail.core.blocks.RichTextBlock(
                                                    features=[
                                                        'h2',
                                                        'h3',
                                                        'h4',
                                                        'bold',
                                                        'italic',
                                                        'ol',
                                                        'ul',
                                                        'hr',
                                                        'link',
                                                        'document-link',
                                                    ],
                                                    label='Description',
                                                    required=False,
                                                ),
                                            ),
                                            ('link', wagtail.core.blocks.URLBlock(label='Title link', required=False)),
                                        ]
                                    ),
                                )
                            ],
                            help_text='Add two or three columns text',
                            max_num=3,
                            min_num=2,
                            template='microsites/blocks/columns.html',
                        ),
                    ),
                ],
                blank=True,
                null=True,
            ),
        ),
    ]
