# Generated by Django 3.2.16 on 2023-02-10 17:05

import wagtail.core.blocks
import wagtail.core.fields
from django.db import migrations

import core.blocks


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0077_micrositesubpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='micrositesubpage',
            name='body',
            field=wagtail.core.fields.StreamField(
                [
                    (
                        'section',
                        wagtail.core.blocks.StreamBlock(
                            [
                                ('title', core.blocks.TitleBlock()),
                                (
                                    'text_block',
                                    wagtail.core.blocks.RichTextBlock(helptext='Add a textblock', icon='openquote'),
                                ),
                                ('image', core.blocks.ImageBlock()),
                                ('hr', core.blocks.HrBlock()),
                                (
                                    'side_link',
                                    wagtail.core.blocks.StructBlock(
                                        [
                                            (
                                                'link',
                                                wagtail.core.blocks.StructBlock(
                                                    [
                                                        (
                                                            'internal_link',
                                                            wagtail.core.blocks.PageChooserBlock(
                                                                label='Internal link', required=False
                                                            ),
                                                        ),
                                                        (
                                                            'external_link',
                                                            wagtail.core.blocks.CharBlock(
                                                                label='External link', max_length=255, required=False
                                                            ),
                                                        ),
                                                    ],
                                                    required=True,
                                                ),
                                            ),
                                            (
                                                'title_override',
                                                wagtail.core.blocks.CharBlock(max_length=255, required=False),
                                            ),
                                            (
                                                'lede_override',
                                                wagtail.core.blocks.CharBlock(max_length=255, required=False),
                                            ),
                                        ]
                                    ),
                                ),
                                ('target_table', core.blocks.ComponentTargetTable()),
                            ]
                        ),
                    ),
                    ('title', core.blocks.TitleBlock()),
                    ('text', wagtail.core.blocks.RichTextBlock(helptext='Add a textblock', icon='openquote')),
                    ('image', core.blocks.ImageBlock()),
                ],
                blank=True,
                null=True,
            ),
        ),
    ]
