# Generated by Django 3.2.18 on 2023-03-20 14:19

import core.blocks
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_alter_micrositepage_page_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='micrositepage',
            name='page_body',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.RichTextBlock(template='microsites/blocks/text.html')), ('image', wagtail.images.blocks.ImageChooserBlock(required=False, template='microsites/blocks/image.html')), ('video', wagtail.core.blocks.StructBlock([('video', core.blocks.MediaChooserBlock())], template='microsites/blocks/video.html')), ('columns', wagtail.core.blocks.StreamBlock([('column', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='Title', max_length=255, required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(label='Hero Image', required=False)), ('description', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'hr', 'link', 'document-link'], label='Description', required=False)), ('link', wagtail.core.blocks.URLBlock(label='Title link', required=False))]))], help_text='Add two or three columns text', max_num=3, min_num=2, template='microsites/blocks/columns.html')), ('cta', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='Title', max_length=255, required=True)), ('teaser', wagtail.core.blocks.TextBlock(label='Teaser', max_length=255, required=True)), ('link_label', wagtail.core.blocks.CharBlock(label='Link label', max_length=255, required=True)), ('link', wagtail.core.blocks.CharBlock(label='Link', max_length=255, required=True))], template='microsites/blocks/cta.html')), ('pull_quote', wagtail.core.blocks.StructBlock([('quote', wagtail.core.blocks.TextBlock()), ('attribution', wagtail.core.blocks.CharBlock(label='Who said it?', max_length=255, required=False)), ('role', wagtail.core.blocks.CharBlock(label='Their role', max_length=255, required=False)), ('organisation', wagtail.core.blocks.CharBlock(label='Their organisation', max_length=255, required=False)), ('organisation_link', wagtail.core.blocks.URLBlock(label='Link to organisation site', max_length=255, required=False))], template='domestic/blocks/pull_quote_block.html'))], blank=True, null=True),
        ),
    ]
