# Generated by Django 3.2.16 on 2023-02-13 16:01

import wagtail.core.blocks
import wagtail.core.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0078_micrositesubpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='micrositeroot',
            name='menu_choices',
            field=wagtail.core.fields.StreamField(
                [
                    ('title', wagtail.core.blocks.CharBlock(default='test', form_classname='title')),
                    ('user', wagtail.core.blocks.CharBlock(default='test', form_classname='title')),
                ],
                blank=True,
                null=True,
            ),
        ),
    ]
