# Generated by Django 3.2.18 on 2023-03-15 15:42

import django.db.models.deletion
import wagtail.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0079_add_cta_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'slug',
                    models.CharField(
                        help_text='Select the use-case for this snippet from a fixed list of choices',
                        max_length=255,
                        unique=True,
                        verbose_name='Purpose',
                    ),
                ),
                (
                    'internal_title',
                    models.CharField(
                        editable=False, max_length=255, verbose_name='Title (internal use only - not publicly shown)'
                    ),
                ),
                (
                    'seo_title',
                    models.CharField(
                        blank=True,
                        help_text="Optional. 'Search Engine Friendly' title. This will appear at the top of the browser window.",
                        max_length=255,
                        verbose_name='Page title',
                    ),
                ),
                ('search_description', models.TextField(blank=True, verbose_name='Search description')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('text', wagtail.core.fields.RichTextField(blank=True, null=True)),
                (
                    'image',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='core.alttextimage',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
