# Generated by Django 3.2.16 on 2023-02-13 16:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0079_micrositeroot_menu_choices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='micrositeroot',
            old_name='menu_choices',
            new_name='body',
        ),
    ]
