# Generated by Django 3.2.18 on 2023-04-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0081_alter_micrositepage_page_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='micrositepage',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='micrositepage',
            name='facebook',
            field=models.URLField(blank=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='micrositepage',
            name='linkedin',
            field=models.URLField(blank=True, verbose_name='Linkedin'),
        ),
        migrations.AddField(
            model_name='micrositepage',
            name='twitter',
            field=models.URLField(blank=True, verbose_name='Twitter'),
        ),
    ]
