# Generated by Django 3.2.18 on 2023-04-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0082_add_form_to_microstie'),
    ]

    operations = [
        migrations.AddField(
            model_name='micrositepage',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='micrositepage',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='micrositepage',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='micrositepage',
            name='twitter',
            field=models.URLField(blank=True),
        ),
    ]
