# Generated by Django 3.2.18 on 2023-04-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0082_auto_20230412_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='micrositepage',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='micrositepage',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='micrositepage',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='micrositepage',
            name='twitter',
            field=models.URLField(blank=True),
        ),
    ]
