# Generated by Django 3.2.16 on 2023-02-14 10:55

import wagtail.core.blocks
import wagtail.core.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0083_auto_20230213_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='micrositeroot',
            name='menu_choices',
            field=wagtail.core.fields.StreamField(
                [
                    (
                        'menu_item',
                        wagtail.core.blocks.StructBlock(
                            [
                                ('title', wagtail.core.blocks.CharBlock(default='', form_classname='title')),
                                ('url', wagtail.core.blocks.URLBlock(default='', form_classname='url')),
                            ]
                        ),
                    )
                ],
                default=[{'title': 'hi', 'url': 'hi'}],
            ),
        ),
    ]
