# Generated by Django 3.2.18 on 2023-03-27 14:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0083_auto_20230323_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='micrositepage',
            old_name='page_body_en',
            new_name='page_body_en_gb',
        ),
    ]
