# Generated by Django 3.2.18 on 2023-05-09 08:33

import wagtail.images.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0084_change_microsite_column_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alttextimage',
            name='file',
            field=wagtail.images.models.WagtailImageField(
                height_field='height',
                upload_to=wagtail.images.models.get_upload_to,
                verbose_name='file',
                width_field='width',
            ),
        ),
        migrations.AlterField(
            model_name='alttextimage',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=40),
        ),
        migrations.AlterField(
            model_name='personalisationcountrytag',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='personalisationhscodetag',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='personalisationregiontag',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='personalisationtradingbloctag',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='rendition',
            name='file',
            field=wagtail.images.models.WagtailImageField(
                height_field='height', upload_to=wagtail.images.models.get_rendition_upload_to, width_field='width'
            ),
        ),
    ]
