# Generated by Django 3.2.18 on 2023-03-30 11:04

import wagtail.core.blocks
import wagtail.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0084_rename_page_body_en_micrositepage_page_body_en_gb'),
    ]

    operations = [
        migrations.AddField(
            model_name='micrositepage',
            name='cta_link_label_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CTA link label'),
        ),
        migrations.AddField(
            model_name='micrositepage',
            name='cta_link_label_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CTA link label'),
        ),
        migrations.AddField(
            model_name='micrositepage',
            name='cta_teaser_en_gb',
            field=models.TextField(blank=True, null=True, verbose_name='CTA teaser'),
        ),
        migrations.AddField(
            model_name='micrositepage',
            name='cta_teaser_es',
            field=models.TextField(blank=True, null=True, verbose_name='CTA teaser'),
        ),
        migrations.AddField(
            model_name='micrositepage',
            name='cta_title_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CTA title'),
        ),
        migrations.AddField(
            model_name='micrositepage',
            name='cta_title_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CTA title'),
        ),
        migrations.AddField(
            model_name='micrositepage',
            name='hero_video_transcript_en_gb',
            field=wagtail.core.fields.RichTextField(
                blank=True, help_text='If the video is present, a transcript must be provided.', null=True
            ),
        ),
        migrations.AddField(
            model_name='micrositepage',
            name='hero_video_transcript_es',
            field=wagtail.core.fields.RichTextField(
                blank=True, help_text='If the video is present, a transcript must be provided.', null=True
            ),
        ),
        migrations.AddField(
            model_name='micrositepage',
            name='page_subheading_en_gb',
            field=models.TextField(
                blank=True,
                help_text='This is a subheading that displays below the main title on the microsite page',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='micrositepage',
            name='page_subheading_es',
            field=models.TextField(
                blank=True,
                help_text='This is a subheading that displays below the main title on the microsite page',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='micrositepage',
            name='page_teaser_en_gb',
            field=models.TextField(
                blank=True,
                help_text='This is a subheading that displays when the microsite is featured on another page',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='micrositepage',
            name='page_teaser_es',
            field=models.TextField(
                blank=True,
                help_text='This is a subheading that displays when the microsite is featured on another page',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='micrositepage',
            name='page_title_en_gb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='micrositepage',
            name='page_title_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='micrositepage',
            name='related_links_en_gb',
            field=wagtail.core.fields.StreamField(
                [
                    ('page', wagtail.core.blocks.PageChooserBlock(blank=True, null=True)),
                    (
                        'link',
                        wagtail.core.blocks.StructBlock(
                            [
                                ('title', wagtail.core.blocks.CharBlock(default='', form_classname='title')),
                                ('full_url', wagtail.core.blocks.URLBlock(default='', form_classname='url')),
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='micrositepage',
            name='related_links_es',
            field=wagtail.core.fields.StreamField(
                [
                    ('page', wagtail.core.blocks.PageChooserBlock(blank=True, null=True)),
                    (
                        'link',
                        wagtail.core.blocks.StructBlock(
                            [
                                ('title', wagtail.core.blocks.CharBlock(default='', form_classname='title')),
                                ('full_url', wagtail.core.blocks.URLBlock(default='', form_classname='url')),
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
            ),
        ),
    ]
