# Generated by Django 3.2.18 on 2023-03-30 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wagtailmedia', '0003_copy_media_permissions_to_collections'),
        ('core', '0085_auto_20230330_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='micrositepage',
            name='hero_image_en_gb',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='core.alttextimage',
            ),
        ),
        migrations.AddField(
            model_name='micrositepage',
            name='hero_image_es',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='core.alttextimage',
            ),
        ),
        migrations.AddField(
            model_name='micrositepage',
            name='hero_video_en_gb',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='wagtailmedia.media',
            ),
        ),
        migrations.AddField(
            model_name='micrositepage',
            name='hero_video_es',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='wagtailmedia.media',
            ),
        ),
    ]
