# Generated by Django 3.2.18 on 2023-05-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0085_auto_20230509_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='microsite',
            name='use_domestic_logo',
            field=models.BooleanField(
                default=True,
                help_text='If selected the great logo will be displayed, otherwise the department for business and trade logo will be displayed',
            ),
        ),
    ]
