# Generated by Django 3.2.16 on 2023-02-14 11:48

import wagtail.core.blocks
import wagtail.core.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0085_alter_micrositeroot_menu_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='micrositeroot',
            name='menu_choices',
            field=wagtail.core.fields.StreamField(
                [
                    (
                        'menu_item',
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    'title',
                                    wagtail.core.blocks.CharBlock(choices=[], default='', form_classname='title'),
                                ),
                                ('url', wagtail.core.blocks.CharBlock(choices=[], default='', form_classname='url')),
                            ]
                        ),
                    ),
                    (
                        'external_link',
                        wagtail.core.blocks.StructBlock(
                            [
                                ('title', wagtail.core.blocks.CharBlock(default='', form_classname='title')),
                                ('url', wagtail.core.blocks.URLBlock(default='', form_classname='url')),
                            ]
                        ),
                    ),
                ]
            ),
        ),
    ]
