# Generated by Django 3.2.18 on 2023-05-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0086_alter_contentmoduletag_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='micrositepage',
            name='use_domestic_header_logo',
            field=models.BooleanField(
                default=True,
                help_text='If selected the dbt logo will be displayed in the header. Otherwise the UK Gov logo will be shown. Note this checkbox only works on the root page',
            ),
        ),
    ]
