# Generated by Django 3.2.18 on 2023-06-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0087_add_use_domestic_header_logo_option_to_microsites'),
    ]

    operations = [
        migrations.AddField(
            model_name='greatmedia',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
