# Generated by Django 4.1.9 on 2023-06-08 10:45

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0088_greatmedia_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosnippet',
            name='ea_registered_text',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='herosnippet',
            name='logged_in_text',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='herosnippet',
            name='logged_out_text',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
