# Generated by Django 4.1.9 on 2023-06-15 15:40

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations

import core.blocks


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0090_alter_micrositepage_page_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='micrositepage',
            name='cta_teaser',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='CTA teaser'),
        ),
        migrations.AlterField(
            model_name='micrositepage',
            name='page_body',
            field=wagtail.fields.StreamField(
                [
                    (
                        'form',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'type',
                                    wagtail.blocks.ChoiceBlock(
                                        blank=False, choices=[('Short', 'Short'), ('Long', 'Long')], null=False
                                    ),
                                ),
                                ('email_subject', wagtail.blocks.TextBlock(required=True)),
                                ('email_title', wagtail.blocks.TextBlock(required=True)),
                                ('email_body', wagtail.blocks.TextBlock(required=True)),
                            ]
                        ),
                    ),
                    ('text', wagtail.blocks.RichTextBlock(template='microsites/blocks/text.html')),
                    (
                        'image',
                        wagtail.images.blocks.ImageChooserBlock(
                            required=False, template='microsites/blocks/image.html'
                        ),
                    ),
                    (
                        'video',
                        wagtail.blocks.StructBlock(
                            [('video', core.blocks.MediaChooserBlock())], template='microsites/blocks/video.html'
                        ),
                    ),
                    (
                        'columns',
                        wagtail.blocks.StreamBlock(
                            [
                                (
                                    'column',
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                'image',
                                                wagtail.images.blocks.ImageChooserBlock(
                                                    label='Hero Image', required=False
                                                ),
                                            ),
                                            ('text', wagtail.blocks.RichTextBlock(label='Description', required=False)),
                                            ('button_label', wagtail.blocks.CharBlock(required=False)),
                                            ('button_url', wagtail.blocks.URLBlock(required=False)),
                                        ]
                                    ),
                                )
                            ],
                            help_text='Add two or three columns text',
                            max_num=3,
                            min_num=2,
                            template='microsites/blocks/columns.html',
                        ),
                    ),
                    (
                        'links_block',
                        wagtail.blocks.StreamBlock(
                            [
                                (
                                    'link_block',
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                'title',
                                                wagtail.blocks.CharBlock(label='Title', max_length=255, required=False),
                                            ),
                                            (
                                                'description',
                                                wagtail.blocks.RichTextBlock(
                                                    features=[
                                                        'h2',
                                                        'h3',
                                                        'h4',
                                                        'bold',
                                                        'italic',
                                                        'ol',
                                                        'ul',
                                                        'hr',
                                                        'link',
                                                        'document-link',
                                                    ],
                                                    label='Description',
                                                    required=False,
                                                ),
                                            ),
                                            ('link_text', wagtail.blocks.CharBlock()),
                                            ('link_url', wagtail.blocks.CharBlock()),
                                        ]
                                    ),
                                ),
                                ('text', wagtail.blocks.RichTextBlock()),
                            ],
                            block_counts={'link_block': {'max_num': 6}, 'text': {'max_num': 1}},
                            template='microsites/blocks/link.html',
                        ),
                    ),
                    (
                        'cta',
                        wagtail.blocks.StructBlock(
                            [
                                ('title', wagtail.blocks.CharBlock(label='Title', max_length=255, required=True)),
                                ('teaser', wagtail.blocks.RichTextBlock(template='microsites/blocks/text.html')),
                                (
                                    'link_label',
                                    wagtail.blocks.CharBlock(label='Link label', max_length=255, required=True),
                                ),
                                ('link', wagtail.blocks.CharBlock(label='Link', max_length=255, required=True)),
                            ],
                            template='microsites/blocks/cta.html',
                        ),
                    ),
                    (
                        'pull_quote',
                        wagtail.blocks.StructBlock(
                            [
                                ('quote', wagtail.blocks.TextBlock()),
                                (
                                    'attribution',
                                    wagtail.blocks.CharBlock(label='Who said it?', max_length=255, required=False),
                                ),
                                ('role', wagtail.blocks.CharBlock(label='Their role', max_length=255, required=False)),
                                (
                                    'organisation',
                                    wagtail.blocks.CharBlock(
                                        label='Their organisation', max_length=255, required=False
                                    ),
                                ),
                                (
                                    'organisation_link',
                                    wagtail.blocks.URLBlock(
                                        label='Link to organisation site', max_length=255, required=False
                                    ),
                                ),
                            ],
                            template='domestic/blocks/pull_quote_block.html',
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
