# Generated by Django 3.2.17 on 2023-02-21 12:34

import wagtail.core.blocks
import wagtail.core.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0090_alter_micrositeroot_menu_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='micrositeroot',
            name='menu_choices',
            field=wagtail.core.fields.StreamField(
                [
                    (
                        'menu_item',
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    'title',
                                    wagtail.core.blocks.CharBlock(
                                        choices=[('test1', 'test1')], default='', form_classname='title'
                                    ),
                                ),
                                ('url', wagtail.core.blocks.CharBlock(default='', form_classname='url')),
                            ]
                        ),
                    ),
                    (
                        'external_link',
                        wagtail.core.blocks.StructBlock(
                            [
                                ('title', wagtail.core.blocks.CharBlock(default='', form_classname='title')),
                                ('url', wagtail.core.blocks.URLBlock(default='', form_classname='url')),
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
            ),
        ),
    ]
