# Generated by Django 3.2.17 on 2023-02-21 12:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0091_alter_micrositeroot_menu_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='micrositesubpage',
            name='body',
        ),
    ]
