# Generated by Django 4.1.10 on 2023-07-31 09:19

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models

import core.cms_panels


class Migration(migrations.Migration):
    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('core', '0092_alter_micrositepage_page_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                (
                    'page_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='wagtailcore.page',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Support',
                'verbose_name_plural': 'Support',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SupportPage',
            fields=[
                (
                    'page_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='wagtailcore.page',
                    ),
                ),
                ('page_title', models.TextField(null=True)),
                ('page_teaser', models.TextField(blank=True, null=True)),
                (
                    'page_body',
                    wagtail.fields.StreamField(
                        [
                            (
                                'cards',
                                wagtail.blocks.StreamBlock(
                                    [
                                        (
                                            'card',
                                            wagtail.blocks.StructBlock(
                                                [
                                                    (
                                                        'title',
                                                        wagtail.blocks.CharBlock(
                                                            label='Title', max_length=255, required=False
                                                        ),
                                                    )
                                                ]
                                            ),
                                        )
                                    ],
                                    template='domestic/contact/export-support/card.html',
                                ),
                            )
                        ],
                        blank=True,
                        null=True,
                        use_json_field=True,
                    ),
                ),
                (
                    'hero_image',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='core.alttextimage',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Support page',
                'verbose_name_plural': 'Support pages',
            },
            bases=(core.cms_panels.SupportPanels, 'wagtailcore.page'),
        ),
    ]
