# Generated by Django 4.1.10 on 2023-08-03 14:20

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0094_alter_supportpage_page_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportpage',
            name='page_body',
            field=wagtail.fields.StreamField(
                [
                    (
                        'topic',
                        wagtail.blocks.StreamBlock(
                            [
                                ('title', wagtail.blocks.CharBlock(default='', form_classname='title', required=True)),
                                (
                                    'description',
                                    wagtail.blocks.CharBlock(default='', form_classname='description', required=True),
                                ),
                                ('type', wagtail.blocks.ChoiceBlock(choices=[('topic', 'Topic')], label='Type')),
                                (
                                    'card',
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                'image',
                                                wagtail.images.blocks.ImageChooserBlock(
                                                    label='Card Image', required=False
                                                ),
                                            ),
                                            (
                                                'type',
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[
                                                        ('govuk', 'GOV.UK'),
                                                        ('tools', 'Tools'),
                                                        ('howTo', 'How to'),
                                                    ],
                                                    label='Type',
                                                ),
                                            ),
                                            ('title', wagtail.blocks.CharBlock(label='Title', max_length=255)),
                                            (
                                                'description',
                                                wagtail.blocks.CharBlock(label='Description', max_length=255),
                                            ),
                                            ('link_text', wagtail.blocks.CharBlock(label='Link text')),
                                            ('link_url', wagtail.blocks.CharBlock(label='Link url')),
                                            (
                                                'full_width',
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[('yes', 'Yes'), ('no', 'No')],
                                                    label='Full width?',
                                                    required=False,
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                                (
                                    'sidebar_item',
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                'image',
                                                wagtail.images.blocks.ImageChooserBlock(
                                                    label='Card Image', required=False
                                                ),
                                            ),
                                            (
                                                'type',
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[
                                                        ('govuk', 'GOV.UK'),
                                                        ('tools', 'Tools'),
                                                        ('howTo', 'How to'),
                                                    ],
                                                    label='Type',
                                                ),
                                            ),
                                            ('title', wagtail.blocks.CharBlock(label='Title', max_length=255)),
                                            (
                                                'description',
                                                wagtail.blocks.CharBlock(label='Description', max_length=255),
                                            ),
                                            ('link_text', wagtail.blocks.CharBlock(label='Link text')),
                                            ('link_url', wagtail.blocks.CharBlock(label='Link url')),
                                            (
                                                'full_width',
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[('yes', 'Yes'), ('no', 'No')],
                                                    label='Full width?',
                                                    required=False,
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                                (
                                    'related_item',
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                'image',
                                                wagtail.images.blocks.ImageChooserBlock(
                                                    label='Card Image', required=False
                                                ),
                                            ),
                                            (
                                                'type',
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[
                                                        ('govuk', 'GOV.UK'),
                                                        ('tools', 'Tools'),
                                                        ('howTo', 'How to'),
                                                    ],
                                                    label='Type',
                                                ),
                                            ),
                                            ('title', wagtail.blocks.CharBlock(label='Title', max_length=255)),
                                            (
                                                'description',
                                                wagtail.blocks.CharBlock(label='Description', max_length=255),
                                            ),
                                            ('link_text', wagtail.blocks.CharBlock(label='Link text')),
                                            ('link_url', wagtail.blocks.CharBlock(label='Link url')),
                                            (
                                                'full_width',
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[('yes', 'Yes'), ('no', 'No')],
                                                    label='Full width?',
                                                    required=False,
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                            ],
                            block_counts={
                                'description': {'max_num': 1},
                                'title': {'max_num': 1},
                                'type': {'max_num': 1},
                            },
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name='supportpage',
            name='page_teaser',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
