# Generated by Django 4.1.10 on 2023-08-07 09:04

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models

import core.cms_panels


class Migration(migrations.Migration):
    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('core', '0095_alter_supportpage_page_body_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetInTouchPage',
            fields=[
                (
                    'page_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='wagtailcore.page',
                    ),
                ),
                ('page_title', models.TextField(null=True)),
                ('page_teaser', wagtail.fields.RichTextField(blank=True, null=True)),
                (
                    'page_body',
                    wagtail.fields.StreamField(
                        [
                            (
                                'cards',
                                wagtail.blocks.StreamBlock(
                                    [
                                        (
                                            'card',
                                            wagtail.blocks.StructBlock(
                                                [
                                                    (
                                                        'image',
                                                        wagtail.images.blocks.ImageChooserBlock(
                                                            label='Card Image', required=False
                                                        ),
                                                    ),
                                                    (
                                                        'type',
                                                        wagtail.blocks.ChoiceBlock(
                                                            choices=[
                                                                ('govuk', 'GOV.UK'),
                                                                ('tools', 'Tools'),
                                                                ('howTo', 'How to'),
                                                            ],
                                                            label='Type',
                                                        ),
                                                    ),
                                                    ('title', wagtail.blocks.CharBlock(label='Title', max_length=255)),
                                                    (
                                                        'description',
                                                        wagtail.blocks.CharBlock(label='Description', max_length=255),
                                                    ),
                                                    ('link_text', wagtail.blocks.CharBlock(label='Link text')),
                                                    ('link_url', wagtail.blocks.CharBlock(label='Link url')),
                                                    (
                                                        'full_width',
                                                        wagtail.blocks.ChoiceBlock(
                                                            choices=[('yes', 'Yes'), ('no', 'No')],
                                                            label='Full width?',
                                                            required=False,
                                                        ),
                                                    ),
                                                ]
                                            ),
                                        )
                                    ]
                                ),
                            )
                        ],
                        blank=True,
                        null=True,
                        use_json_field=True,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Get in touch page',
                'verbose_name_plural': 'Get in touch pages',
            },
            bases=(core.cms_panels.GetInTouchPanels, 'wagtailcore.page'),
        ),
    ]
