# Generated by Django 4.1.9 on 2023-08-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0096_getintouchpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='micrositepage',
            name='external_link_label',
            field=models.CharField(
                blank=True,
                default='',
                help_text='The label to be included within the menu items.',
                max_length=256,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='micrositepage',
            name='external_link_url',
            field=models.URLField(blank=True, help_text='The url of the external link', null=True),
        ),
    ]
