# Generated by Django 4.1.10 on 2023-08-24 08:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0098_alter_casestudy_body_alter_detailpage_body_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='microsite',
            options={'verbose_name': 'Campaign site', 'verbose_name_plural': 'Campaign sites'},
        ),
        migrations.AlterModelOptions(
            name='micrositepage',
            options={'verbose_name': 'Campaign site page', 'verbose_name_plural': 'Campaign site pages'},
        ),
    ]
