# Generated by Django 4.1.10 on 2023-08-24 14:37

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models

import core.cms_panels


class Migration(migrations.Migration):
    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('core', '0098_alter_casestudy_body_alter_detailpage_body_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTopicLandingPage',
            fields=[
                (
                    'page_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='wagtailcore.page',
                    ),
                ),
                ('page_title', models.TextField(null=True)),
                ('page_teaser', wagtail.fields.RichTextField(blank=True, null=True)),
                (
                    'page_body',
                    wagtail.fields.StreamField(
                        [
                            (
                                'cards',
                                wagtail.blocks.StreamBlock(
                                    [
                                        (
                                            'card',
                                            wagtail.blocks.StructBlock(
                                                [
                                                    (
                                                        'image',
                                                        wagtail.images.blocks.ImageChooserBlock(
                                                            label='Card Image', required=False
                                                        ),
                                                    ),
                                                    (
                                                        'type',
                                                        wagtail.blocks.ChoiceBlock(
                                                            choices=[
                                                                ('govuk', 'GOV.UK'),
                                                                ('tools', 'Tools'),
                                                                ('howTo', 'How to'),
                                                            ],
                                                            label='Type',
                                                        ),
                                                    ),
                                                    ('title', wagtail.blocks.CharBlock(label='Title', max_length=255)),
                                                    (
                                                        'description',
                                                        wagtail.blocks.CharBlock(label='Description', max_length=255),
                                                    ),
                                                    ('link_text', wagtail.blocks.CharBlock(label='Link text')),
                                                    ('link_url', wagtail.blocks.CharBlock(label='Link url')),
                                                    (
                                                        'full_width',
                                                        wagtail.blocks.ChoiceBlock(
                                                            choices=[('yes', 'Yes'), ('no', 'No')],
                                                            label='Full width?',
                                                            required=False,
                                                        ),
                                                    ),
                                                ]
                                            ),
                                        )
                                    ]
                                ),
                            )
                        ],
                        blank=True,
                        null=True,
                        use_json_field=True,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Topic landing page',
                'verbose_name_plural': 'Topic landing pages',
            },
            bases=(core.cms_panels.GetInTouchPanels, 'wagtailcore.page'),
        ),
        migrations.AlterModelOptions(
            name='microsite',
            options={'verbose_name': 'Campaign site', 'verbose_name_plural': 'Campaign sites'},
        ),
        migrations.AlterModelOptions(
            name='micrositepage',
            options={'verbose_name': 'Campaign site page', 'verbose_name_plural': 'Campaign site pages'},
        ),
        migrations.AlterField(
            model_name='supportpage',
            name='page_body',
            field=wagtail.fields.StreamField(
                [
                    (
                        'topic_cards',
                        wagtail.blocks.StreamBlock(
                            [
                                (
                                    'topic_card',
                                    wagtail.blocks.StructBlock(
                                        [
                                            ('title', wagtail.blocks.CharBlock(label='Title', max_length=255)),
                                            (
                                                'description',
                                                wagtail.blocks.CharBlock(label='Description', max_length=255),
                                            ),
                                            ('link_text', wagtail.blocks.CharBlock(label='Link text')),
                                            ('link_url', wagtail.blocks.CharBlock(label='Link url')),
                                        ]
                                    ),
                                )
                            ],
                            block_counts={'topic_card': {'min_num': 1}},
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
