# Generated by Django 4.1.10 on 2023-08-25 09:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0099_rename_and_reorder_microsite_panels_and_remove_hero_video'),
        ('core', '0100_remove_supporttopiclandingpage_page_teaser_and_more'),
    ]

    operations = []
