# Generated by Django 4.1.10 on 2023-08-29 09:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0100_merge_20230825_1050'),
        ('core', '0101_merge_20230825_1003'),
    ]

    operations = []
