# Generated by Django 4.1.10 on 2023-09-04 16:03

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations

import core.blocks


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0101_merge_20230825_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailpage',
            name='body',
            field=wagtail.fields.StreamField(
                [
                    (
                        'paragraph',
                        wagtail.blocks.StructBlock(
                            [('paragraph', wagtail.blocks.RichTextBlock())],
                            icon='font',
                            template='core/struct_paragraph_block.html',
                        ),
                    ),
                    (
                        'video',
                        wagtail.blocks.StructBlock(
                            [('video', core.blocks.MediaChooserBlock(label='Video'))],
                            help_text='Video displayed within a full-page-width block',
                            template='core/includes/_video_full_width.html',
                        ),
                    ),
                    ('case_study', core.blocks.CaseStudyStaticBlock(icon='fa-book')),
                    (
                        'Step',
                        wagtail.blocks.StructBlock(
                            [
                                ('title', wagtail.blocks.CharBlock(max_length=255)),
                                ('body', wagtail.blocks.RichTextBlock()),
                                ('image', wagtail.images.blocks.ImageChooserBlock(required=False)),
                            ],
                            icon='cog',
                        ),
                    ),
                    (
                        'fictional_example',
                        wagtail.blocks.StructBlock(
                            [('fiction_body', wagtail.blocks.RichTextBlock(icon='openquote'))],
                            icon='comment-dots',
                            template='learn/fictional_company_example.html',
                        ),
                    ),
                    (
                        'ITA_Quote',
                        wagtail.blocks.StructBlock(
                            [
                                ('quote', wagtail.blocks.RichTextBlock()),
                                ('author', wagtail.blocks.CharBlock(max_length=255)),
                            ],
                            icon='quote-left',
                        ),
                    ),
                    (
                        'pros_cons',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'pros',
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                'item',
                                                wagtail.blocks.StructBlock(
                                                    [('item', wagtail.blocks.CharBlock(max_length=255))],
                                                    icon='arrow-right',
                                                ),
                                            )
                                        ]
                                    ),
                                ),
                                (
                                    'cons',
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                'item',
                                                wagtail.blocks.StructBlock(
                                                    [('item', wagtail.blocks.CharBlock(max_length=255))],
                                                    icon='arrow-right',
                                                ),
                                            )
                                        ]
                                    ),
                                ),
                            ],
                            icon='arrow-right',
                            template='learn/pros_and_cons.html',
                        ),
                    ),
                    (
                        'choose_do_not_choose',
                        wagtail.blocks.StructBlock(
                            [
                                ('choose_title', wagtail.blocks.CharBlock(max_length=255)),
                                ('choose_body', wagtail.blocks.RichTextBlock(features=())),
                                ('do_not_choose_title', wagtail.blocks.CharBlock(max_length=255)),
                                ('do_not_choose_body', wagtail.blocks.RichTextBlock(features=())),
                            ]
                        ),
                    ),
                    (
                        'image',
                        core.blocks.ImageBlock(
                            help_text='Image displayed within a full-page-width block',
                            template='core/includes/_image_full_width.html',
                        ),
                    ),
                ],
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name='detailpage',
            name='recap',
            field=wagtail.fields.StreamField(
                [
                    (
                        'recap_item',
                        wagtail.blocks.StructBlock(
                            [
                                ('title', wagtail.blocks.CharBlock(icon='heading')),
                                (
                                    'item',
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                'item',
                                                wagtail.blocks.StructBlock(
                                                    [('item', wagtail.blocks.CharBlock(max_length=255))]
                                                ),
                                            )
                                        ]
                                    ),
                                ),
                            ],
                            icon='comment-dots',
                            template='learn/recap.html',
                        ),
                    )
                ],
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name='micrositepage',
            name='page_body',
            field=wagtail.fields.StreamField(
                [
                    ('text', wagtail.blocks.RichTextBlock(label='Text', template='microsites/blocks/text.html')),
                    (
                        'image',
                        wagtail.images.blocks.ImageChooserBlock(
                            label='Image', required=False, template='microsites/blocks/image.html'
                        ),
                    ),
                    (
                        'image_full_width',
                        wagtail.images.blocks.ImageChooserBlock(
                            label='Image full width', required=False, template='microsites/blocks/image_full_width.html'
                        ),
                    ),
                    (
                        'video',
                        wagtail.blocks.StructBlock(
                            [('video', core.blocks.MediaChooserBlock(label='Video'))],
                            label='Video',
                            template='microsites/blocks/video.html',
                        ),
                    ),
                    (
                        'columns',
                        wagtail.blocks.StreamBlock(
                            [
                                (
                                    'column',
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                'image',
                                                wagtail.images.blocks.ImageChooserBlock(
                                                    label='Hero Image', required=False
                                                ),
                                            ),
                                            ('text', wagtail.blocks.RichTextBlock(label='Description', required=False)),
                                            (
                                                'button_label',
                                                wagtail.blocks.CharBlock(label='Button label', required=False),
                                            ),
                                            ('button_url', wagtail.blocks.URLBlock(label='Button url', required=False)),
                                        ]
                                    ),
                                )
                            ],
                            help_text='Add two or three columns text',
                            icon='grip',
                            label='Columns',
                            max_num=3,
                            min_num=2,
                            template='microsites/blocks/columns.html',
                        ),
                    ),
                    (
                        'links_block',
                        wagtail.blocks.StreamBlock(
                            [
                                (
                                    'link_block',
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                'title',
                                                wagtail.blocks.CharBlock(label='Title', max_length=255, required=False),
                                            ),
                                            (
                                                'description',
                                                wagtail.blocks.RichTextBlock(
                                                    features=[
                                                        'anchor-identifier',
                                                        'h2',
                                                        'h3',
                                                        'h4',
                                                        'bold',
                                                        'italic',
                                                        'ol',
                                                        'ul',
                                                        'hr',
                                                        'link',
                                                        'document-link',
                                                    ],
                                                    label='Description',
                                                    required=False,
                                                ),
                                            ),
                                            ('link_text', wagtail.blocks.CharBlock(label='Link text')),
                                            ('link_url', wagtail.blocks.CharBlock(label='Link url')),
                                        ],
                                        label='Link block',
                                    ),
                                ),
                                ('text', wagtail.blocks.RichTextBlock(label='Text')),
                            ],
                            block_counts={'link_block': {'max_num': 6}, 'text': {'max_num': 1}},
                            icon='link',
                            label='Links block',
                            template='microsites/blocks/link.html',
                        ),
                    ),
                    (
                        'cta',
                        wagtail.blocks.StructBlock(
                            [
                                ('title', wagtail.blocks.CharBlock(label='Title', max_length=255, required=True)),
                                (
                                    'teaser',
                                    wagtail.blocks.RichTextBlock(
                                        label='Teaser', template='microsites/blocks/text.html'
                                    ),
                                ),
                                (
                                    'link_label',
                                    wagtail.blocks.CharBlock(label='Link label', max_length=255, required=True),
                                ),
                                ('link', wagtail.blocks.CharBlock(label='Link', max_length=255, required=True)),
                            ],
                            icon='crosshairs',
                            label='CTA',
                            template='microsites/blocks/cta.html',
                        ),
                    ),
                    (
                        'pull_quote',
                        wagtail.blocks.StructBlock(
                            [
                                ('quote', wagtail.blocks.TextBlock()),
                                (
                                    'attribution',
                                    wagtail.blocks.CharBlock(label='Who said it?', max_length=255, required=False),
                                ),
                                ('role', wagtail.blocks.CharBlock(label='Their role', max_length=255, required=False)),
                                (
                                    'organisation',
                                    wagtail.blocks.CharBlock(
                                        label='Their organisation', max_length=255, required=False
                                    ),
                                ),
                                (
                                    'organisation_link',
                                    wagtail.blocks.URLBlock(
                                        label='Link to organisation site', max_length=255, required=False
                                    ),
                                ),
                            ],
                            label='Pull quote',
                            template='domestic/blocks/pull_quote_block.html',
                        ),
                    ),
                    (
                        'form',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'type',
                                    wagtail.blocks.ChoiceBlock(
                                        blank=False,
                                        choices=[('Short', 'Short'), ('Long', 'Long')],
                                        label='type',
                                        null=False,
                                    ),
                                ),
                                ('email_subject', wagtail.blocks.TextBlock(label='Email subject', required=True)),
                                ('email_title', wagtail.blocks.TextBlock(label='Email title', required=True)),
                                ('email_body', wagtail.blocks.TextBlock(label='Email body', required=True)),
                            ],
                            label='Form',
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=True,
                verbose_name='Page body',
            ),
        ),
    ]
