# Generated by Django 4.1.10 on 2023-09-01 12:43

from django.db import migrations

import core.blocks
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0101_merge_20230825_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getintouchpage',
            name='page_body',
            field=wagtail.fields.StreamField(
                [
                    (
                        'cards',
                        wagtail.blocks.StreamBlock(
                            [
                                (
                                    'card',
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                'image',
                                                wagtail.images.blocks.ImageChooserBlock(
                                                    label='Card Image', required=False
                                                ),
                                            ),
                                            (
                                                'type',
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[
                                                        ('govuk', 'GOV.UK'),
                                                        ('tools', 'Tools'),
                                                        ('howTo', 'How to'),
                                                        ('topic', 'Topic'),
                                                        ('service', 'Service'),
                                                    ],
                                                    label='Type',
                                                ),
                                            ),
                                            ('title', wagtail.blocks.CharBlock(label='Title', max_length=255)),
                                            (
                                                'description',
                                                wagtail.blocks.CharBlock(label='Description', max_length=255),
                                            ),
                                            ('link_text', wagtail.blocks.CharBlock(label='Link text')),
                                            ('link_url', wagtail.blocks.CharBlock(label='Link url')),
                                            (
                                                'full_width',
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[('yes', 'Yes'), ('no', 'No')],
                                                    label='Full width?',
                                                    required=False,
                                                ),
                                            ),
                                        ]
                                    ),
                                )
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name='micrositepage',
            name='page_body',
            field=wagtail.fields.StreamField(
                [
                    ('text', wagtail.blocks.RichTextBlock(label='Text', template='microsites/blocks/text.html')),
                    (
                        'image',
                        wagtail.images.blocks.ImageChooserBlock(
                            label='Image', required=False, template='microsites/blocks/image.html'
                        ),
                    ),
                    (
                        'image_full_width',
                        wagtail.images.blocks.ImageChooserBlock(
                            label='Image full width', required=False, template='microsites/blocks/image_full_width.html'
                        ),
                    ),
                    (
                        'video',
                        wagtail.blocks.StructBlock(
                            [('video', core.blocks.MediaChooserBlock(label='Video'))],
                            label='Video',
                            template='microsites/blocks/video.html',
                        ),
                    ),
                    (
                        'columns',
                        wagtail.blocks.StreamBlock(
                            [
                                (
                                    'column',
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                'image',
                                                wagtail.images.blocks.ImageChooserBlock(
                                                    label='Hero Image', required=False
                                                ),
                                            ),
                                            ('text', wagtail.blocks.RichTextBlock(label='Description', required=False)),
                                            (
                                                'button_label',
                                                wagtail.blocks.CharBlock(label='Button label', required=False),
                                            ),
                                            ('button_url', wagtail.blocks.URLBlock(label='Button url', required=False)),
                                        ]
                                    ),
                                )
                            ],
                            help_text='Add two or three columns text',
                            icon='grip',
                            label='Columns',
                            max_num=3,
                            min_num=2,
                            template='microsites/blocks/columns.html',
                        ),
                    ),
                    (
                        'links_block',
                        wagtail.blocks.StreamBlock(
                            [
                                (
                                    'link_block',
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                'title',
                                                wagtail.blocks.CharBlock(label='Title', max_length=255, required=False),
                                            ),
                                            (
                                                'description',
                                                wagtail.blocks.RichTextBlock(
                                                    features=[
                                                        'anchor-identifier',
                                                        'h2',
                                                        'h3',
                                                        'h4',
                                                        'bold',
                                                        'italic',
                                                        'ol',
                                                        'ul',
                                                        'hr',
                                                        'link',
                                                        'document-link',
                                                    ],
                                                    label='Description',
                                                    required=False,
                                                ),
                                            ),
                                            ('link_text', wagtail.blocks.CharBlock(label='Link text')),
                                            ('link_url', wagtail.blocks.CharBlock(label='Link url')),
                                        ],
                                        label='Link block',
                                    ),
                                ),
                                ('text', wagtail.blocks.RichTextBlock(label='Text')),
                            ],
                            block_counts={'link_block': {'max_num': 6}, 'text': {'max_num': 1}},
                            icon='link',
                            label='Links block',
                            template='microsites/blocks/link.html',
                        ),
                    ),
                    (
                        'cta',
                        wagtail.blocks.StructBlock(
                            [
                                ('title', wagtail.blocks.CharBlock(label='Title', max_length=255, required=True)),
                                (
                                    'teaser',
                                    wagtail.blocks.RichTextBlock(
                                        label='Teaser', template='microsites/blocks/text.html'
                                    ),
                                ),
                                (
                                    'link_label',
                                    wagtail.blocks.CharBlock(label='Link label', max_length=255, required=True),
                                ),
                                ('link', wagtail.blocks.CharBlock(label='Link', max_length=255, required=True)),
                            ],
                            icon='crosshairs',
                            label='CTA',
                            template='microsites/blocks/cta.html',
                        ),
                    ),
                    (
                        'pull_quote',
                        wagtail.blocks.StructBlock(
                            [
                                ('quote', wagtail.blocks.TextBlock()),
                                (
                                    'attribution',
                                    wagtail.blocks.CharBlock(label='Who said it?', max_length=255, required=False),
                                ),
                                ('role', wagtail.blocks.CharBlock(label='Their role', max_length=255, required=False)),
                                (
                                    'organisation',
                                    wagtail.blocks.CharBlock(
                                        label='Their organisation', max_length=255, required=False
                                    ),
                                ),
                                (
                                    'organisation_link',
                                    wagtail.blocks.URLBlock(
                                        label='Link to organisation site', max_length=255, required=False
                                    ),
                                ),
                            ],
                            label='Pull quote',
                            template='domestic/blocks/pull_quote_block.html',
                        ),
                    ),
                    (
                        'form',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'type',
                                    wagtail.blocks.ChoiceBlock(
                                        blank=False,
                                        choices=[('Short', 'Short'), ('Long', 'Long')],
                                        label='type',
                                        null=False,
                                    ),
                                ),
                                ('email_subject', wagtail.blocks.TextBlock(label='Email subject', required=True)),
                                ('email_title', wagtail.blocks.TextBlock(label='Email title', required=True)),
                                ('email_body', wagtail.blocks.TextBlock(label='Email body', required=True)),
                            ],
                            label='Form',
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=True,
                verbose_name='Page body',
            ),
        ),
        migrations.AlterField(
            model_name='supporttopiclandingpage',
            name='page_body',
            field=wagtail.fields.StreamField(
                [
                    (
                        'cards',
                        wagtail.blocks.StreamBlock(
                            [
                                (
                                    'card',
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                'image',
                                                wagtail.images.blocks.ImageChooserBlock(
                                                    label='Card Image', required=False
                                                ),
                                            ),
                                            (
                                                'type',
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[
                                                        ('govuk', 'GOV.UK'),
                                                        ('tools', 'Tools'),
                                                        ('howTo', 'How to'),
                                                        ('topic', 'Topic'),
                                                        ('service', 'Service'),
                                                    ],
                                                    label='Type',
                                                ),
                                            ),
                                            ('title', wagtail.blocks.CharBlock(label='Title', max_length=255)),
                                            (
                                                'description',
                                                wagtail.blocks.CharBlock(label='Description', max_length=255),
                                            ),
                                            ('link_text', wagtail.blocks.CharBlock(label='Link text')),
                                            ('link_url', wagtail.blocks.CharBlock(label='Link url')),
                                            (
                                                'full_width',
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[('yes', 'Yes'), ('no', 'No')],
                                                    label='Full width?',
                                                    required=False,
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                                (
                                    'sidebar_item',
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                'image',
                                                wagtail.images.blocks.ImageChooserBlock(
                                                    label='Card Image', required=False
                                                ),
                                            ),
                                            (
                                                'type',
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[
                                                        ('govuk', 'GOV.UK'),
                                                        ('tools', 'Tools'),
                                                        ('howTo', 'How to'),
                                                        ('topic', 'Topic'),
                                                        ('service', 'Service'),
                                                    ],
                                                    label='Type',
                                                ),
                                            ),
                                            ('title', wagtail.blocks.CharBlock(label='Title', max_length=255)),
                                            (
                                                'description',
                                                wagtail.blocks.CharBlock(label='Description', max_length=255),
                                            ),
                                            ('link_text', wagtail.blocks.CharBlock(label='Link text')),
                                            ('link_url', wagtail.blocks.CharBlock(label='Link url')),
                                            (
                                                'full_width',
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[('yes', 'Yes'), ('no', 'No')],
                                                    label='Full width?',
                                                    required=False,
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                                (
                                    'related_item',
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                'image',
                                                wagtail.images.blocks.ImageChooserBlock(
                                                    label='Card Image', required=False
                                                ),
                                            ),
                                            (
                                                'type',
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[
                                                        ('govuk', 'GOV.UK'),
                                                        ('tools', 'Tools'),
                                                        ('howTo', 'How to'),
                                                        ('topic', 'Topic'),
                                                        ('service', 'Service'),
                                                    ],
                                                    label='Type',
                                                ),
                                            ),
                                            ('title', wagtail.blocks.CharBlock(label='Title', max_length=255)),
                                            (
                                                'description',
                                                wagtail.blocks.CharBlock(label='Description', max_length=255),
                                            ),
                                            ('link_text', wagtail.blocks.CharBlock(label='Link text')),
                                            ('link_url', wagtail.blocks.CharBlock(label='Link url')),
                                            (
                                                'full_width',
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[('yes', 'Yes'), ('no', 'No')],
                                                    label='Full width?',
                                                    required=False,
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
