# Generated by Django 4.1.10 on 2023-09-04 11:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0102_speaker_alter_micrositepage_page_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speaker',
            options={'ordering': ('name',)},
        ),
    ]
