# Generated by Django 4.1.10 on 2023-09-05 08:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0102_alter_getintouchpage_page_body_and_more'),
        ('core', '0102_replace_wagtail_font_awesome_icons'),
    ]

    operations = []
