# Generated by Django 4.1.10 on 2023-09-04 14:32

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('export_academy', '0023_remove_event_speakers'),
        ('core', '0103_alter_speaker_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='event',
            field=modelcluster.fields.ParentalKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='speakers',
                to='export_academy.event',
            ),
        ),
    ]
