# Generated by Django 4.1.10 on 2023-09-05 09:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0102_alter_micrositepage_page_body'),
        ('core', '0103_merge_20230905_0958'),
    ]

    operations = []
