# Generated by Django 4.1.10 on 2023-09-04 15:23

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('export_academy', '0023_remove_event_speakers'),
        ('core', '0104_speaker_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaker',
            name='event',
        ),
        migrations.CreateModel(
            name='SpeakerOrderable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                (
                    'page',
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='event_speakers',
                        to='export_academy.event',
                    ),
                ),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.speaker')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
