# Generated by Django 4.1.10 on 2023-09-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0104_merge_20230905_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getintouchpage',
            name='page_teaser',
            field=models.TextField(null=True),
        ),
    ]
