# Generated by Django 4.1.10 on 2023-09-06 14:30

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0105_alter_getintouchpage_page_teaser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getintouchpage',
            name='page_body',
            field=wagtail.fields.StreamField(
                [
                    (
                        'cards',
                        wagtail.blocks.StreamBlock(
                            [
                                (
                                    'card',
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                'image',
                                                wagtail.images.blocks.ImageChooserBlock(
                                                    label='Card Image', required=False
                                                ),
                                            ),
                                            (
                                                'type',
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[
                                                        ('govuk', 'GOV.UK'),
                                                        ('tool', 'Tool'),
                                                        ('howTo', 'How to'),
                                                        ('service', 'Service'),
                                                    ],
                                                    label='Type',
                                                ),
                                            ),
                                            ('title', wagtail.blocks.CharBlock(label='Title', max_length=255)),
                                            (
                                                'description',
                                                wagtail.blocks.CharBlock(label='Description', max_length=255),
                                            ),
                                            ('link_text', wagtail.blocks.CharBlock(label='Link text')),
                                            ('link_url', wagtail.blocks.CharBlock(label='Link url')),
                                            (
                                                'full_width',
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[('yes', 'Yes'), ('no', 'No')],
                                                    label='Full width?',
                                                    required=False,
                                                ),
                                            ),
                                        ]
                                    ),
                                )
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name='supporttopiclandingpage',
            name='page_body',
            field=wagtail.fields.StreamField(
                [
                    (
                        'cards',
                        wagtail.blocks.StreamBlock(
                            [
                                (
                                    'card',
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                'image',
                                                wagtail.images.blocks.ImageChooserBlock(
                                                    label='Card Image', required=False
                                                ),
                                            ),
                                            (
                                                'type',
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[
                                                        ('govuk', 'GOV.UK'),
                                                        ('tool', 'Tool'),
                                                        ('howTo', 'How to'),
                                                        ('service', 'Service'),
                                                    ],
                                                    label='Type',
                                                ),
                                            ),
                                            ('title', wagtail.blocks.CharBlock(label='Title', max_length=255)),
                                            (
                                                'description',
                                                wagtail.blocks.CharBlock(label='Description', max_length=255),
                                            ),
                                            ('link_text', wagtail.blocks.CharBlock(label='Link text')),
                                            ('link_url', wagtail.blocks.CharBlock(label='Link url')),
                                            (
                                                'full_width',
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[('yes', 'Yes'), ('no', 'No')],
                                                    label='Full width?',
                                                    required=False,
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                                (
                                    'sidebar_item',
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                'image',
                                                wagtail.images.blocks.ImageChooserBlock(
                                                    label='Card Image', required=False
                                                ),
                                            ),
                                            (
                                                'type',
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[
                                                        ('govuk', 'GOV.UK'),
                                                        ('tool', 'Tool'),
                                                        ('howTo', 'How to'),
                                                        ('service', 'Service'),
                                                    ],
                                                    label='Type',
                                                ),
                                            ),
                                            ('title', wagtail.blocks.CharBlock(label='Title', max_length=255)),
                                            (
                                                'description',
                                                wagtail.blocks.CharBlock(label='Description', max_length=255),
                                            ),
                                            ('link_text', wagtail.blocks.CharBlock(label='Link text')),
                                            ('link_url', wagtail.blocks.CharBlock(label='Link url')),
                                            (
                                                'full_width',
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[('yes', 'Yes'), ('no', 'No')],
                                                    label='Full width?',
                                                    required=False,
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                                (
                                    'related_item',
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                'image',
                                                wagtail.images.blocks.ImageChooserBlock(
                                                    label='Card Image', required=False
                                                ),
                                            ),
                                            (
                                                'type',
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[
                                                        ('govuk', 'GOV.UK'),
                                                        ('tool', 'Tool'),
                                                        ('howTo', 'How to'),
                                                        ('service', 'Service'),
                                                    ],
                                                    label='Type',
                                                ),
                                            ),
                                            ('title', wagtail.blocks.CharBlock(label='Title', max_length=255)),
                                            (
                                                'description',
                                                wagtail.blocks.CharBlock(label='Description', max_length=255),
                                            ),
                                            ('link_text', wagtail.blocks.CharBlock(label='Link text')),
                                            ('link_url', wagtail.blocks.CharBlock(label='Link url')),
                                            (
                                                'full_width',
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[('yes', 'Yes'), ('no', 'No')],
                                                    label='Full width?',
                                                    required=False,
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
