# Generated by Django 4.1.10 on 2023-09-05 09:46

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0105_remove_speaker_event_speakerorderable'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='organisation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
