# Generated by Django 4.1.10 on 2023-09-18 08:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0109_allow_4_columns_on_microsites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='micrositepage',
            name='email',
        ),
    ]
