# Generated by Django 4.1.10 on 2023-09-18 10:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0110_alter_micrositepage_link_block'),
        ('core', '0110_remove_micrositepage_email'),
    ]

    operations = []
