# Generated by Django 4.1.10 on 2023-09-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0111_remove_micrositepage_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getintouchpage',
            name='page_teaser',
            field=models.TextField(blank=True, null=True),
        ),
    ]
