# Generated by Django 4.1.10 on 2023-09-18 14:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0110_alter_micrositepage_page_body'),
        ('core', '0111_remove_micrositepage_email'),
    ]

    operations = []
