# Generated by Django 4.1.10 on 2023-11-16 08:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0118_alter_micrositepage_page_body'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LessonPlaceholderPage',
        ),
    ]
