# Generated by Django 4.1.10 on 2023-11-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0118_alter_micrositepage_page_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='microsite',
            name='review_reminder_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
