# Generated by Django 4.1.13 on 2023-12-04 13:32

import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations

import core.blocks


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0118_alter_micrositepage_page_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='micrositepage',
            name='page_body',
            field=wagtail.fields.StreamField(
                [
                    (
                        'text',
                        wagtail.blocks.RichTextBlock(
                            help_text='Note: any indent seen here will not be visible in the live page',
                            label='Text',
                            template='microsites/blocks/text.html',
                        ),
                    ),
                    (
                        'image',
                        wagtail.images.blocks.ImageChooserBlock(
                            label='Image', required=False, template='microsites/blocks/image.html'
                        ),
                    ),
                    (
                        'image_full_width',
                        wagtail.images.blocks.ImageChooserBlock(
                            label='Image full width', required=False, template='microsites/blocks/image_full_width.html'
                        ),
                    ),
                    (
                        'video',
                        wagtail.blocks.StructBlock(
                            [('video', core.blocks.MediaChooserBlock(label='Video'))],
                            label='Upload video',
                            template='microsites/blocks/video.html',
                        ),
                    ),
                    (
                        'embed_video',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'embed_link',
                                    wagtail.embeds.blocks.EmbedBlock(
                                        label='Embed link', max_height=150, max_width=200, required=True
                                    ),
                                ),
                                (
                                    'transcript',
                                    wagtail.blocks.RichTextBlock(
                                        features=['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul'],
                                        label='Transcript',
                                        required=False,
                                    ),
                                ),
                            ],
                            icon='media',
                            template='microsites/blocks/embed_video.html',
                        ),
                    ),
                    (
                        'columns',
                        wagtail.blocks.StreamBlock(
                            [
                                (
                                    'column',
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                'image',
                                                wagtail.images.blocks.ImageChooserBlock(
                                                    label='Hero image', required=False
                                                ),
                                            ),
                                            (
                                                'image_url',
                                                wagtail.blocks.URLBlock(label='Hero image hyperlink', required=False),
                                            ),
                                            (
                                                'text',
                                                wagtail.blocks.RichTextBlock(
                                                    help_text='Note: any indent seen here will not be visible in the live page',
                                                    label='Description',
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                'button_label',
                                                wagtail.blocks.CharBlock(label='Button label', required=False),
                                            ),
                                            ('button_url', wagtail.blocks.URLBlock(label='Button url', required=False)),
                                        ]
                                    ),
                                )
                            ],
                            help_text='Add between 2 and 4 columns of text',
                            icon='grip',
                            label='Columns',
                            max_num=4,
                            min_num=2,
                            template='microsites/blocks/columns.html',
                        ),
                    ),
                    (
                        'links_block',
                        wagtail.blocks.StructBlock(
                            [
                                ('text', wagtail.blocks.RichTextBlock(label='Text (optional)', required=False)),
                                (
                                    'links',
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                'link',
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            'title',
                                                            wagtail.blocks.CharBlock(
                                                                label='Title', max_length=255, required=False
                                                            ),
                                                        ),
                                                        (
                                                            'description',
                                                            wagtail.blocks.RichTextBlock(
                                                                features=[
                                                                    'anchor-identifier',
                                                                    'h2',
                                                                    'h3',
                                                                    'h4',
                                                                    'bold',
                                                                    'italic',
                                                                    'ol',
                                                                    'ul',
                                                                    'hr',
                                                                    'link',
                                                                    'document-link',
                                                                ],
                                                                label='Description',
                                                                required=False,
                                                            ),
                                                        ),
                                                        ('link_text', wagtail.blocks.CharBlock(label='Link text')),
                                                        ('link_url', wagtail.blocks.URLBlock(label='Link url')),
                                                    ],
                                                    label='Link block',
                                                ),
                                            )
                                        ],
                                        max_num=6,
                                        required=True,
                                    ),
                                ),
                            ],
                            label='Links block',
                            template='microsites/blocks/link.html',
                        ),
                    ),
                    (
                        'cta',
                        wagtail.blocks.StructBlock(
                            [
                                ('title', wagtail.blocks.CharBlock(label='Title', max_length=255, required=True)),
                                (
                                    'teaser',
                                    wagtail.blocks.RichTextBlock(
                                        help_text='Note: any indent seen here will not be visible in the live page',
                                        label='Teaser',
                                        template='microsites/blocks/text.html',
                                    ),
                                ),
                                (
                                    'link_label',
                                    wagtail.blocks.CharBlock(label='Link label', max_length=255, required=True),
                                ),
                                ('link', wagtail.blocks.CharBlock(label='Link', max_length=255, required=True)),
                            ],
                            icon='crosshairs',
                            label='CTA',
                            template='microsites/blocks/cta.html',
                        ),
                    ),
                    (
                        'pull_quote',
                        wagtail.blocks.StructBlock(
                            [
                                ('quote', wagtail.blocks.TextBlock()),
                                (
                                    'attribution',
                                    wagtail.blocks.CharBlock(label='Who said it?', max_length=255, required=False),
                                ),
                                ('role', wagtail.blocks.CharBlock(label='Their role', max_length=255, required=False)),
                                (
                                    'organisation',
                                    wagtail.blocks.CharBlock(
                                        label='Their organisation', max_length=255, required=False
                                    ),
                                ),
                                (
                                    'organisation_link',
                                    wagtail.blocks.URLBlock(
                                        label='Link to organisation site', max_length=255, required=False
                                    ),
                                ),
                            ],
                            label='Pull quote',
                            template='domestic/blocks/pull_quote_block.html',
                        ),
                    ),
                    ('data_table', core.blocks.DataTableBlock()),
                ],
                blank=True,
                null=True,
                use_json_field=True,
                verbose_name='Page body',
            ),
        ),
    ]
