# Generated by Django 4.1.13 on 2023-12-07 11:39

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0119_alter_micrositepage_page_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='listpage',
            name='side_links',
            field=wagtail.fields.StreamField(
                [
                    (
                        'heading',
                        wagtail.blocks.CharBlock(
                            default='', form_classname='heading', help_text='Maximum of 1 heading', label='Heading'
                        ),
                    ),
                    (
                        'link',
                        wagtail.blocks.StructBlock(
                            [
                                ('title', wagtail.blocks.CharBlock(default='', form_classname='title', label='Title')),
                                ('url', wagtail.blocks.CharBlock(default='', form_classname='url', label='Url')),
                            ],
                            label='Link',
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AddField(
            model_name='listpage',
            name='ukea_cta',
            field=wagtail.fields.StreamField(
                [
                    ('url', wagtail.blocks.CharBlock(form_classname='url', label='Url')),
                    ('title', wagtail.blocks.CharBlock(form_classname='title', label='Title')),
                    ('description', wagtail.blocks.CharBlock(form_classname='description', label='Description')),
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
