# Generated by Django 4.1.10 on 2023-11-17 14:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0119_microsite_six_month_review_reminder_sent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='microsite',
            old_name='six_month_review_reminder_sent',
            new_name='review_reminder_sent',
        ),
        migrations.RemoveField(
            model_name='microsite',
            name='twelve_month_review_reminder_sent',
        ),
    ]
