# Generated by Django 4.1.10 on 2023-12-19 15:27

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtail.snippets.blocks
from django.db import migrations, models

import core.blocks


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0120_alter_micrositepage_page_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedContentCTA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_text', models.CharField(help_text='Text displayed for the link', max_length=50)),
                (
                    'type',
                    models.CharField(
                        choices=[
                            ('great_service', 'Service'),
                            ('great_guidance', 'Guidance'),
                            ('govuk_service', 'Service on GOV.UK'),
                            ('govuk_guidance', 'Guidance on GOV.UK'),
                        ],
                        help_text='The type of target URL',
                        max_length=20,
                    ),
                ),
                (
                    'link',
                    wagtail.fields.StreamField(
                        [
                            ('page', wagtail.blocks.PageChooserBlock(blank=True, label='Page', null=True)),
                            ('link', wagtail.blocks.URLBlock(default='', form_classname='url', label='External url')),
                        ],
                        use_json_field=None,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Related content call to action',
                'verbose_name_plural': 'Related content call to actions',
            },
        ),
        migrations.AlterField(
            model_name='detailpage',
            name='body',
            field=wagtail.fields.StreamField(
                [
                    (
                        'paragraph',
                        wagtail.blocks.StructBlock(
                            [('paragraph', wagtail.blocks.RichTextBlock())],
                            icon='font',
                            template='core/struct_paragraph_block.html',
                        ),
                    ),
                    (
                        'video',
                        wagtail.blocks.StructBlock(
                            [('video', core.blocks.MediaChooserBlock(label='Video'))],
                            help_text='Video displayed within a full-page-width block',
                            template='core/includes/_video_full_width.html',
                        ),
                    ),
                    ('case_study', core.blocks.CaseStudyStaticBlock(icon='fa-book')),
                    (
                        'Step',
                        wagtail.blocks.StructBlock(
                            [
                                ('title', wagtail.blocks.CharBlock(max_length=255)),
                                ('body', wagtail.blocks.RichTextBlock()),
                                ('image', wagtail.images.blocks.ImageChooserBlock(required=False)),
                            ],
                            icon='cog',
                        ),
                    ),
                    (
                        'fictional_example',
                        wagtail.blocks.StructBlock(
                            [('fiction_body', wagtail.blocks.RichTextBlock(icon='openquote'))],
                            icon='comment-dots',
                            template='learn/fictional_company_example.html',
                        ),
                    ),
                    (
                        'ITA_Quote',
                        wagtail.blocks.StructBlock(
                            [
                                ('quote', wagtail.blocks.RichTextBlock()),
                                ('author', wagtail.blocks.CharBlock(max_length=255)),
                            ],
                            icon='quote-left',
                        ),
                    ),
                    (
                        'pros_cons',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'pros',
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                'item',
                                                wagtail.blocks.StructBlock(
                                                    [('item', wagtail.blocks.CharBlock(max_length=255))],
                                                    icon='arrow-right',
                                                ),
                                            )
                                        ]
                                    ),
                                ),
                                (
                                    'cons',
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                'item',
                                                wagtail.blocks.StructBlock(
                                                    [('item', wagtail.blocks.CharBlock(max_length=255))],
                                                    icon='arrow-right',
                                                ),
                                            )
                                        ]
                                    ),
                                ),
                            ],
                            icon='arrow-right',
                            template='learn/pros_and_cons.html',
                        ),
                    ),
                    (
                        'choose_do_not_choose',
                        wagtail.blocks.StructBlock(
                            [
                                ('choose_title', wagtail.blocks.CharBlock(max_length=255)),
                                ('choose_body', wagtail.blocks.RichTextBlock(features=())),
                                ('do_not_choose_title', wagtail.blocks.CharBlock(max_length=255)),
                                ('do_not_choose_body', wagtail.blocks.RichTextBlock(features=())),
                            ]
                        ),
                    ),
                    (
                        'image',
                        core.blocks.ImageBlock(
                            help_text='Image displayed within a full-page-width block',
                            template='core/includes/_image_full_width.html',
                        ),
                    ),
                    (
                        'related_content_cta',
                        wagtail.blocks.ListBlock(
                            wagtail.snippets.blocks.SnippetChooserBlock('core.RelatedContentCTAOrderable'),
                            label='CTAs',
                            max_num=3,
                        ),
                    ),
                ],
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name='detailpage',
            name='body',
            field=wagtail.fields.StreamField(
                [
                    (
                        'paragraph',
                        wagtail.blocks.StructBlock(
                            [('paragraph', wagtail.blocks.RichTextBlock())],
                            icon='font',
                            template='core/struct_paragraph_block.html',
                        ),
                    ),
                    (
                        'video',
                        wagtail.blocks.StructBlock(
                            [('video', core.blocks.MediaChooserBlock(label='Video'))],
                            help_text='Video displayed within a full-page-width block',
                            template='core/includes/_video_full_width.html',
                        ),
                    ),
                    ('case_study', core.blocks.CaseStudyStaticBlock(icon='fa-book')),
                    (
                        'Step',
                        wagtail.blocks.StructBlock(
                            [
                                ('title', wagtail.blocks.CharBlock(max_length=255)),
                                ('body', wagtail.blocks.RichTextBlock()),
                                ('image', wagtail.images.blocks.ImageChooserBlock(required=False)),
                            ],
                            icon='cog',
                        ),
                    ),
                    (
                        'fictional_example',
                        wagtail.blocks.StructBlock(
                            [('fiction_body', wagtail.blocks.RichTextBlock(icon='openquote'))],
                            icon='comment-dots',
                            template='learn/fictional_company_example.html',
                        ),
                    ),
                    (
                        'ITA_Quote',
                        wagtail.blocks.StructBlock(
                            [
                                ('quote', wagtail.blocks.RichTextBlock()),
                                ('author', wagtail.blocks.CharBlock(max_length=255)),
                            ],
                            icon='quote-left',
                        ),
                    ),
                    (
                        'pros_cons',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'pros',
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                'item',
                                                wagtail.blocks.StructBlock(
                                                    [('item', wagtail.blocks.CharBlock(max_length=255))],
                                                    icon='arrow-right',
                                                ),
                                            )
                                        ]
                                    ),
                                ),
                                (
                                    'cons',
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                'item',
                                                wagtail.blocks.StructBlock(
                                                    [('item', wagtail.blocks.CharBlock(max_length=255))],
                                                    icon='arrow-right',
                                                ),
                                            )
                                        ]
                                    ),
                                ),
                            ],
                            icon='arrow-right',
                            template='learn/pros_and_cons.html',
                        ),
                    ),
                    (
                        'choose_do_not_choose',
                        wagtail.blocks.StructBlock(
                            [
                                ('choose_title', wagtail.blocks.CharBlock(max_length=255)),
                                ('choose_body', wagtail.blocks.RichTextBlock(features=())),
                                ('do_not_choose_title', wagtail.blocks.CharBlock(max_length=255)),
                                ('do_not_choose_body', wagtail.blocks.RichTextBlock(features=())),
                            ]
                        ),
                    ),
                    (
                        'image',
                        core.blocks.ImageBlock(
                            help_text='Image displayed within a full-page-width block',
                            template='core/includes/_image_full_width.html',
                        ),
                    ),
                    (
                        'related_content_cta',
                        wagtail.blocks.ListBlock(
                            wagtail.snippets.blocks.SnippetChooserBlock('core.RelatedContentCTA'),
                            label='CTAs',
                            max_num=3,
                        ),
                    ),
                ],
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name='detailpage',
            name='body',
            field=wagtail.fields.StreamField(
                [
                    (
                        'paragraph',
                        wagtail.blocks.StructBlock(
                            [('paragraph', wagtail.blocks.RichTextBlock())],
                            icon='font',
                            template='core/struct_paragraph_block.html',
                        ),
                    ),
                    (
                        'video',
                        wagtail.blocks.StructBlock(
                            [('video', core.blocks.MediaChooserBlock(label='Video'))],
                            help_text='Video displayed within a full-page-width block',
                            template='core/includes/_video_full_width.html',
                        ),
                    ),
                    ('case_study', core.blocks.CaseStudyStaticBlock(icon='fa-book')),
                    (
                        'Step',
                        wagtail.blocks.StructBlock(
                            [
                                ('title', wagtail.blocks.CharBlock(max_length=255)),
                                ('body', wagtail.blocks.RichTextBlock()),
                                ('image', wagtail.images.blocks.ImageChooserBlock(required=False)),
                            ],
                            icon='cog',
                        ),
                    ),
                    (
                        'fictional_example',
                        wagtail.blocks.StructBlock(
                            [('fiction_body', wagtail.blocks.RichTextBlock(icon='openquote'))],
                            icon='comment-dots',
                            template='learn/fictional_company_example.html',
                        ),
                    ),
                    (
                        'ITA_Quote',
                        wagtail.blocks.StructBlock(
                            [
                                ('quote', wagtail.blocks.RichTextBlock()),
                                ('author', wagtail.blocks.CharBlock(max_length=255)),
                            ],
                            icon='quote-left',
                        ),
                    ),
                    (
                        'pros_cons',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'pros',
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                'item',
                                                wagtail.blocks.StructBlock(
                                                    [('item', wagtail.blocks.CharBlock(max_length=255))],
                                                    icon='arrow-right',
                                                ),
                                            )
                                        ]
                                    ),
                                ),
                                (
                                    'cons',
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                'item',
                                                wagtail.blocks.StructBlock(
                                                    [('item', wagtail.blocks.CharBlock(max_length=255))],
                                                    icon='arrow-right',
                                                ),
                                            )
                                        ]
                                    ),
                                ),
                            ],
                            icon='arrow-right',
                            template='learn/pros_and_cons.html',
                        ),
                    ),
                    (
                        'choose_do_not_choose',
                        wagtail.blocks.StructBlock(
                            [
                                ('choose_title', wagtail.blocks.CharBlock(max_length=255)),
                                ('choose_body', wagtail.blocks.RichTextBlock(features=())),
                                ('do_not_choose_title', wagtail.blocks.CharBlock(max_length=255)),
                                ('do_not_choose_body', wagtail.blocks.RichTextBlock(features=())),
                            ]
                        ),
                    ),
                    (
                        'image',
                        core.blocks.ImageBlock(
                            help_text='Image displayed within a full-page-width block',
                            template='core/includes/_image_full_width.html',
                        ),
                    ),
                    (
                        'related_content_cta',
                        wagtail.blocks.ListBlock(
                            wagtail.snippets.blocks.SnippetChooserBlock('core.RelatedContentCTA'),
                            icon='link',
                            label='Related Content',
                            max_num=3,
                        ),
                    ),
                ],
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name='detailpage',
            name='body',
            field=wagtail.fields.StreamField(
                [
                    (
                        'paragraph',
                        wagtail.blocks.StructBlock(
                            [('paragraph', wagtail.blocks.RichTextBlock())],
                            icon='font',
                            template='core/struct_paragraph_block.html',
                        ),
                    ),
                    (
                        'video',
                        wagtail.blocks.StructBlock(
                            [('video', core.blocks.MediaChooserBlock(label='Video'))],
                            help_text='Video displayed within a full-page-width block',
                            template='core/includes/_video_full_width.html',
                        ),
                    ),
                    ('case_study', core.blocks.CaseStudyStaticBlock(icon='fa-book')),
                    (
                        'Step',
                        wagtail.blocks.StructBlock(
                            [
                                ('title', wagtail.blocks.CharBlock(max_length=255)),
                                ('body', wagtail.blocks.RichTextBlock()),
                                ('image', wagtail.images.blocks.ImageChooserBlock(required=False)),
                            ],
                            icon='cog',
                        ),
                    ),
                    (
                        'fictional_example',
                        wagtail.blocks.StructBlock(
                            [('fiction_body', wagtail.blocks.RichTextBlock(icon='openquote'))],
                            icon='comment-dots',
                            template='learn/fictional_company_example.html',
                        ),
                    ),
                    (
                        'ITA_Quote',
                        wagtail.blocks.StructBlock(
                            [
                                ('quote', wagtail.blocks.RichTextBlock()),
                                ('author', wagtail.blocks.CharBlock(max_length=255)),
                            ],
                            icon='quote-left',
                        ),
                    ),
                    (
                        'pros_cons',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'pros',
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                'item',
                                                wagtail.blocks.StructBlock(
                                                    [('item', wagtail.blocks.CharBlock(max_length=255))],
                                                    icon='arrow-right',
                                                ),
                                            )
                                        ]
                                    ),
                                ),
                                (
                                    'cons',
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                'item',
                                                wagtail.blocks.StructBlock(
                                                    [('item', wagtail.blocks.CharBlock(max_length=255))],
                                                    icon='arrow-right',
                                                ),
                                            )
                                        ]
                                    ),
                                ),
                            ],
                            icon='arrow-right',
                            template='learn/pros_and_cons.html',
                        ),
                    ),
                    (
                        'choose_do_not_choose',
                        wagtail.blocks.StructBlock(
                            [
                                ('choose_title', wagtail.blocks.CharBlock(max_length=255)),
                                ('choose_body', wagtail.blocks.RichTextBlock(features=())),
                                ('do_not_choose_title', wagtail.blocks.CharBlock(max_length=255)),
                                ('do_not_choose_body', wagtail.blocks.RichTextBlock(features=())),
                            ]
                        ),
                    ),
                    (
                        'image',
                        core.blocks.ImageBlock(
                            help_text='Image displayed within a full-page-width block',
                            template='core/includes/_image_full_width.html',
                        ),
                    ),
                    (
                        'related_content_cta',
                        wagtail.blocks.ListBlock(
                            wagtail.snippets.blocks.SnippetChooserBlock('core.RelatedContentCTA'),
                            icon='link',
                            label='Related Content',
                            max_num=3,
                            template='learn/related_pages_cta.html',
                        ),
                    ),
                ],
                use_json_field=True,
            ),
        ),
    ]
