# Generated by Django 4.1.13 on 2023-12-12 09:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0121_listpage_side_links_listpage_ukea_cta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listpage',
            old_name='side_links',
            new_name='popular_links',
        ),
    ]
