# Generated by Django 4.1.10 on 2024-01-03 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('core', '0122_rename_side_links_listpage_popular_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'share_prefix',
                    models.TextField(
                        blank=True,
                        help_text='Prepends draft social media post and email subject when using the share page component',
                        max_length=255,
                        verbose_name='Share prefix',
                    ),
                ),
                (
                    'hashtags',
                    models.TextField(
                        blank=True,
                        help_text='Appends draft social media post when using the share page component. Prefixes each string with a #, removes spaces, and applies Pascal casing',
                        max_length=255,
                        verbose_name='Hashtags',
                    ),
                ),
                (
                    'site',
                    models.OneToOneField(
                        editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Sharing',
            },
        ),
    ]
