# Generated by Django 4.1.13 on 2023-12-20 11:17

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0123_relatedcontentcta_squashed_0126_alter_detailpage_body_alter_relatedcontentcta_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedcontentcta',
            name='link',
            field=wagtail.fields.StreamField(
                [
                    ('page', wagtail.blocks.PageChooserBlock(blank=True, label='Page', null=True)),
                    ('link', wagtail.blocks.URLBlock(default='', form_classname='url', label='External url')),
                ],
                use_json_field=True,
            ),
        ),
    ]
