# Generated by Django 4.1.13 on 2024-01-12 17:57

import core.blocks
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.blocks
import wagtail.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('export_academy', '0033_alter_coursepage_metadata_alter_coursepage_reviews'),
        ('core', '0129_alter_greatmedia_subtitles_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UKEACTA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'image',
                    wagtail.fields.StreamField(
                        [
                            (
                                'media',
                                wagtail.blocks.StreamBlock([('image', core.blocks.ImageBlock())], max_num=1, min_num=1),
                            )
                        ],
                        blank=True,
                        null=True,
                        use_json_field=True,
                    ),
                ),
                ('name', models.CharField(help_text='Snippet name', max_length=50)),
            ],
            options={
                'verbose_name': 'UKEA CTA',
                'verbose_name_plural': "UKEA CTA's",
            },
        ),
        migrations.AddField(
            model_name='detailpage',
            name='call_to_action',
            field=wagtail.fields.StreamField(
                [
                    (
                        'ukea_article_cta',
                        wagtail.blocks.ListBlock(
                            wagtail.snippets.blocks.SnippetChooserBlock('core.UKEACTA'),
                            icon='link',
                            label='UKEA Call to action',
                            max_num=1,
                            template='learn/includes/article_page_cta.html',
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.CreateModel(
            name='EventOrderable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                (
                    'event',
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='export_academy.event'
                    ),
                ),
                (
                    'page',
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='ukea_cta_links', to='core.ukeacta'
                    ),
                ),
                (
                    'series',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='export_academy.coursepage',
                    ),
                ),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
