# Generated by Django 4.2 on 2024-01-29 16:52

import wagtail.images.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0130_ukeacta_detailpage_call_to_action_eventorderable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendition',
            name='file',
            field=wagtail.images.models.WagtailImageField(
                height_field='height',
                storage=wagtail.images.models.get_rendition_storage,
                upload_to=wagtail.images.models.get_rendition_upload_to,
                width_field='width',
            ),
        ),
    ]
