# Generated by Django 4.2.7 on 2024-02-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0131_alter_rendition_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='microsite',
            name='review_reminder_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
