# Generated by Django 4.1.13 on 2024-01-31 09:00

import wagtail.blocks
import wagtail.fields
from django.db import migrations

import core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0131_alter_rendition_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedcontentcta',
            name='link',
            field=wagtail.fields.StreamField(
                [
                    ('page', wagtail.blocks.PageChooserBlock(blank=True, label='Page', null=True)),
                    (
                        'link',
                        wagtail.blocks.CharBlock(
                            form_classname='url',
                            help_text='Enter external URLs in full, for example, https://www.gov.uk/a-page-on-another-website.                          For internal pages, use a relative path, for example, /a-page-on-this-website',
                            label='URL',
                            validators=[core.models.is_valid_url_input],
                        ),
                    ),
                ],
                use_json_field=True,
            ),
        ),
    ]
