# Generated by Django 4.2.7 on 2024-02-02 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0132_microsite_review_reminder_sent'),
        ('core', '0133_alter_detailpage_body'),
    ]

    operations = []
