# Generated by Django 4.2.7 on 2024-02-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0133_alter_detailpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='micrositepage',
            name='review_reminder_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
