# Generated by Django 4.2.7 on 2024-02-14 11:34

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtail.snippets.blocks
from django.db import migrations

import core.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0134_alter_detailpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailpage',
            name='body',
            field=wagtail.fields.StreamField(
                [
                    (
                        'paragraph',
                        wagtail.blocks.StructBlock(
                            [('paragraph', wagtail.blocks.RichTextBlock())],
                            icon='font',
                            template='core/struct_paragraph_block.html',
                        ),
                    ),
                    (
                        'video',
                        wagtail.blocks.StructBlock(
                            [('video', core.blocks.MediaChooserBlock(label='Video'))],
                            help_text='Video displayed within a full-page-width block',
                            template='core/includes/_video_full_width.html',
                        ),
                    ),
                    ('case_study', core.blocks.CaseStudyStaticBlock(icon='fa-book')),
                    (
                        'Step',
                        wagtail.blocks.StructBlock(
                            [
                                ('title', wagtail.blocks.CharBlock(max_length=255)),
                                ('body', wagtail.blocks.RichTextBlock()),
                                ('image', wagtail.images.blocks.ImageChooserBlock(required=False)),
                            ],
                            icon='cog',
                        ),
                    ),
                    (
                        'step_list',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'step_list',
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    'title',
                                                    wagtail.blocks.RichTextBlock(
                                                        features=['h2', 'h3'],
                                                        max_length=255,
                                                        validators=[core.blocks.title_has_heading],
                                                    ),
                                                ),
                                                ('body', wagtail.blocks.RichTextBlock()),
                                            ]
                                        )
                                    ),
                                )
                            ],
                            icon='cog',
                            template='learn/step_list.html',
                        ),
                    ),
                    (
                        'fictional_example',
                        wagtail.blocks.StructBlock(
                            [('fiction_body', wagtail.blocks.RichTextBlock(icon='openquote'))],
                            icon='comment-dots',
                            template='learn/fictional_company_example.html',
                        ),
                    ),
                    (
                        'ITA_Quote',
                        wagtail.blocks.StructBlock(
                            [
                                ('quote', wagtail.blocks.RichTextBlock()),
                                ('author', wagtail.blocks.CharBlock(max_length=255)),
                            ],
                            icon='quote-left',
                        ),
                    ),
                    (
                        'pros_cons',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'pros',
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                'item',
                                                wagtail.blocks.StructBlock(
                                                    [('item', wagtail.blocks.CharBlock(max_length=255))],
                                                    icon='arrow-right',
                                                ),
                                            )
                                        ]
                                    ),
                                ),
                                (
                                    'cons',
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                'item',
                                                wagtail.blocks.StructBlock(
                                                    [('item', wagtail.blocks.CharBlock(max_length=255))],
                                                    icon='arrow-right',
                                                ),
                                            )
                                        ]
                                    ),
                                ),
                            ],
                            icon='arrow-right',
                            template='learn/pros_and_cons.html',
                        ),
                    ),
                    (
                        'choose_do_not_choose',
                        wagtail.blocks.StructBlock(
                            [
                                ('choose_title', wagtail.blocks.CharBlock(max_length=255)),
                                ('choose_body', wagtail.blocks.RichTextBlock(features=['ol', 'ul'])),
                                ('do_not_choose_title', wagtail.blocks.CharBlock(max_length=255)),
                                ('do_not_choose_body', wagtail.blocks.RichTextBlock(features=['ol', 'ul'])),
                            ]
                        ),
                    ),
                    (
                        'image',
                        core.blocks.ImageBlock(
                            help_text='Image displayed within a full-page-width block',
                            template='core/includes/_image_full_width.html',
                        ),
                    ),
                    (
                        'related_content_cta',
                        wagtail.blocks.ListBlock(
                            wagtail.snippets.blocks.SnippetChooserBlock('core.RelatedContentCTA'),
                            icon='link',
                            label='Related Content',
                            max_num=3,
                            template='learn/related_pages_cta.html',
                        ),
                    ),
                ],
                use_json_field=True,
            ),
        ),
    ]
