# Generated by Django 4.2.7 on 2024-03-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0136_alter_detailpage_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Sector tag',
                'verbose_name_plural': 'Sector tags',
            },
        ),
        migrations.CreateModel(
            name='TypeOfExportTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Type of export tag',
                'verbose_name_plural': 'Type of export tags',
            },
        ),
        migrations.RenameModel(
            old_name='PersonalisationCountryTag',
            new_name='CountryTag',
        ),
        migrations.AlterModelOptions(
            name='countrytag',
            options={'verbose_name': 'Country tag', 'verbose_name_plural': 'Country tags'},
        ),
    ]
