# Generated by Django 4.2.7 on 2024-03-18 16:07

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0138_taggedtypeofexport_taggedsector_taggedcountry'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggedCountrySnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaggedSectorSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaggedSnippetBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'country_tags',
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text='A comma-separated list of tags.',
                        through='core.TaggedCountrySnippet',
                        to='core.CountryTag',
                        verbose_name='Country Tags',
                    ),
                ),
                (
                    'sector_tags',
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text='A comma-separated list of tags.',
                        through='core.TaggedSectorSnippet',
                        to='core.SectorTag',
                        verbose_name='Sector Tags',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.CreateModel(
            name='TaggedTypeOfExportSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'content_object',
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='type_of_export_tagged_snippet',
                        to='core.taggedsnippetbase',
                    ),
                ),
                (
                    'tag',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='tagged_type_of_export_snippet',
                        to='core.typeofexporttag',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='taggedsnippetbase',
            name='type_of_export_tags',
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text='A comma-separated list of tags.',
                through='core.TaggedTypeOfExportSnippet',
                to='core.TypeOfExportTag',
                verbose_name='Type of Export Tags',
            ),
        ),
        migrations.AddField(
            model_name='taggedsectorsnippet',
            name='content_object',
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='sector_tags_snippet',
                to='core.taggedsnippetbase',
            ),
        ),
        migrations.AddField(
            model_name='taggedsectorsnippet',
            name='tag',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='tagged_sector_snippet', to='core.sectortag'
            ),
        ),
        migrations.AddField(
            model_name='taggedcountrysnippet',
            name='content_object',
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='country_tags_snippet',
                to='core.taggedsnippetbase',
            ),
        ),
        migrations.AddField(
            model_name='taggedcountrysnippet',
            name='tag',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='tagged_countries_snippet',
                to='core.countrytag',
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='taggedsnippetbase_ptr',
            field=models.OneToOneField(
                auto_created=True,
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to='core.taggedsnippetbase',
            ),
            preserve_default=False,
        ),
    ]
