# Generated by Django 4.2.7 on 2024-03-22 14:06

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0139_typeofexporttagged_sectortagged_countrytagged'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='sector_tags',
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text='A comma-separated list of tags.',
                through='core.SectorTagged',
                to='core.SectorTag',
                verbose_name='Sector tags',
            ),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='type_of_export_tags',
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text='A comma-separated list of tags.',
                through='core.TypeOfExportTagged',
                to='core.TypeOfExportTag',
                verbose_name='Type of Export Tags',
            ),
        ),
        migrations.AlterField(
            model_name='typeofexporttagged',
            name='tag',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='%(app_label)s_%(class)s_items',
                to='core.typeofexporttag',
            ),
        ),
    ]
