# Generated by Django 4.2.7 on 2024-03-19 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0139_taggedcountrysnippet_taggedsectorsnippet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaker',
            name='id',
        ),
        migrations.AddField(
            model_name='speaker',
            name='taggedsnippetbase_ptr',
            field=models.OneToOneField(
                auto_created=True,
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to='core.taggedsnippetbase',
            ),
            preserve_default=False,
        ),
    ]
