# Generated by Django 4.2.11 on 2024-04-08 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0140_casestudy_sector_tags_casestudy_type_of_export_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourstep',
            name='tour',
        ),
        migrations.DeleteModel(
            name='Tour',
        ),
        migrations.DeleteModel(
            name='TourStep',
        ),
    ]
