# Generated by Django 4.2.10 on 2024-05-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0141_remove_tourstep_tour_delete_tour_delete_tourstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentmodule',
            name='hide_title',
            field=models.BooleanField(default=False, verbose_name='Hide the title for this snippet'),
        ),
        migrations.AddField(
            model_name='contentmodule',
            name='title_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
