# Generated by Django 4.2.11 on 2024-05-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0142_contentmodule_hide_title_contentmodule_title_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentmodule',
            name='hide_title',
            field=models.BooleanField(
                default=False,
                help_text='Check this box to prevent the title displaying on the page.',
                verbose_name='Hide title?',
            ),
        ),
        migrations.AlterField(
            model_name='contentmodule',
            name='title_id',
            field=models.CharField(
                blank=True,
                help_text='Your provided ID might change upon saving to ensure its valid. Check this snippet after saving to see the formatted ID.',
                max_length=255,
                null=True,
            ),
        ),
    ]
