# Generated by Django 4.2.11 on 2024-05-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0143_alter_contentmodule_hide_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentmodule',
            name='title_id',
            field=models.CharField(
                blank=True,
                help_text='Your provided ID might change upon saving to ensure its valid. Check this snippet after saving to see the formatted ID.',
                max_length=255,
                null=True,
                verbose_name='Title ID?',
            ),
        ),
    ]
