# Generated by Django 4.2.11 on 2024-05-09 15:03

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtail.search.index
import wagtail.snippets.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0144_alter_contentmodule_title_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField()),
                ('description', models.CharField()),
                ('url', models.CharField()),
            ],
            options={
                'ordering': ('task',),
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.AlterField(
            model_name='supporttopiclandingpage',
            name='page_body',
            field=wagtail.fields.StreamField(
                [
                    (
                        'cards',
                        wagtail.blocks.StreamBlock(
                            [
                                (
                                    'card',
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                'image',
                                                wagtail.images.blocks.ImageChooserBlock(
                                                    label='Card Image', required=False
                                                ),
                                            ),
                                            (
                                                'type',
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[
                                                        ('govuk', 'GOV.UK'),
                                                        ('tool', 'Tool'),
                                                        ('howTo', 'How to'),
                                                        ('service', 'Service'),
                                                    ],
                                                    label='Type',
                                                    required=False,
                                                ),
                                            ),
                                            ('title', wagtail.blocks.CharBlock(label='Title', max_length=255)),
                                            (
                                                'description',
                                                wagtail.blocks.CharBlock(label='Description', max_length=255),
                                            ),
                                            ('link_text', wagtail.blocks.CharBlock(label='Link text')),
                                            ('link_url', wagtail.blocks.CharBlock(label='Link url')),
                                            (
                                                'full_width',
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[('yes', 'Yes'), ('no', 'No')],
                                                    label='Full width?',
                                                    required=False,
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                                (
                                    'sidebar_item',
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                'image',
                                                wagtail.images.blocks.ImageChooserBlock(
                                                    label='Card Image', required=False
                                                ),
                                            ),
                                            (
                                                'type',
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[
                                                        ('govuk', 'GOV.UK'),
                                                        ('tool', 'Tool'),
                                                        ('howTo', 'How to'),
                                                        ('service', 'Service'),
                                                    ],
                                                    label='Type',
                                                    required=False,
                                                ),
                                            ),
                                            ('title', wagtail.blocks.CharBlock(label='Title', max_length=255)),
                                            (
                                                'description',
                                                wagtail.blocks.CharBlock(label='Description', max_length=255),
                                            ),
                                            ('link_text', wagtail.blocks.CharBlock(label='Link text')),
                                            ('link_url', wagtail.blocks.CharBlock(label='Link url')),
                                            (
                                                'full_width',
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[('yes', 'Yes'), ('no', 'No')],
                                                    label='Full width?',
                                                    required=False,
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                                (
                                    'related_item',
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                'image',
                                                wagtail.images.blocks.ImageChooserBlock(
                                                    label='Card Image', required=False
                                                ),
                                            ),
                                            (
                                                'type',
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[
                                                        ('govuk', 'GOV.UK'),
                                                        ('tool', 'Tool'),
                                                        ('howTo', 'How to'),
                                                        ('service', 'Service'),
                                                    ],
                                                    label='Type',
                                                    required=False,
                                                ),
                                            ),
                                            ('title', wagtail.blocks.CharBlock(label='Title', max_length=255)),
                                            (
                                                'description',
                                                wagtail.blocks.CharBlock(label='Description', max_length=255),
                                            ),
                                            ('link_text', wagtail.blocks.CharBlock(label='Link text')),
                                            ('link_url', wagtail.blocks.CharBlock(label='Link url')),
                                            (
                                                'full_width',
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[('yes', 'Yes'), ('no', 'No')],
                                                    label='Full width?',
                                                    required=False,
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                                (
                                    'task_item',
                                    wagtail.blocks.ListBlock(
                                        wagtail.snippets.blocks.SnippetChooserBlock('core.TaskItem'),
                                        label='Choose task item',
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
