# Generated by Django 4.2.11 on 2024-05-10 07:56

import modelcluster.contrib.taggit
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0144_alter_contentmodule_title_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taggedsector',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='taggedsector',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='taggedtypeofexport',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='taggedtypeofexport',
            name='tag',
        ),
        migrations.AddField(
            model_name='curatedlistpage',
            name='country_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text='A comma-separated list of tags.',
                through='core.CountryTagged',
                to='core.CountryTag',
                verbose_name='Country Tags',
            ),
        ),
        migrations.AddField(
            model_name='curatedlistpage',
            name='sector_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text='A comma-separated list of tags.',
                through='core.SectorTagged',
                to='core.SectorTag',
                verbose_name='Sector Tags',
            ),
        ),
        migrations.AddField(
            model_name='curatedlistpage',
            name='type_of_export_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text='A comma-separated list of tags.',
                through='core.TypeOfExportTagged',
                to='core.TypeOfExportTag',
                verbose_name='Type of Export Tags',
            ),
        ),
        migrations.AddField(
            model_name='topicpage',
            name='country_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text='A comma-separated list of tags.',
                through='core.CountryTagged',
                to='core.CountryTag',
                verbose_name='Country Tags',
            ),
        ),
        migrations.AddField(
            model_name='topicpage',
            name='sector_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text='A comma-separated list of tags.',
                through='core.SectorTagged',
                to='core.SectorTag',
                verbose_name='Sector Tags',
            ),
        ),
        migrations.AddField(
            model_name='topicpage',
            name='type_of_export_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text='A comma-separated list of tags.',
                through='core.TypeOfExportTagged',
                to='core.TypeOfExportTag',
                verbose_name='Type of Export Tags',
            ),
        ),
        migrations.DeleteModel(
            name='TaggedCountry',
        ),
        migrations.DeleteModel(
            name='TaggedSector',
        ),
        migrations.DeleteModel(
            name='TaggedTypeOfExport',
        ),
    ]
