# Generated by Django 4.2.11 on 2024-05-02 13:28
# IMPORTANT NOTE
# This is an irreversable migration. If this migration does need to be reversed you will need to remove it manually from the migration history in the database.
# This migration copies all tags for market guide pages into the new tagging system. In the unlikely case that this change needs to be reversed we will preferably need a second
# data migration to perform the same actions but remove entries wherever there is a tag present for IndustryTags.

from django.db import migrations
from django.utils.text import slugify


def migrate_tags(apps, schema_editor):
    industry_tags = apps.get_model('core', 'IndustryTag')
    sector_tags = apps.get_model('core', 'SectorTag')
    sector_tagged = apps.get_model('core', 'SectorTagged')
    for tag in industry_tags.objects.all():
        # if tag exists in sector tags skip else add new tag
        sector_tags.objects.get_or_create(name=tag.name, slug=slugify(tag.name))

    market_guide_pages = apps.get_model('domestic', 'CountryGuidePage')
    for page in market_guide_pages.objects.all():
        # for tags in page.tags add tag to page.sector_tags
        industries = page.tags.all()
        if list(industries):
            for industry in list(industries):
                sector_id = list(sector_tags.objects.filter(name=industry.name))[0].id
                sector_tagged.objects.create(object_id=page.id, content_type_id=85, tag_id=sector_id)
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0145_remove_taggedsector_content_object_and_more'),
        ('domestic', '0061_countryguidepage_country_tags_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_tags),
    ]
