# Generated by Django 4.2.11 on 2024-05-10 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0146_task_taskbasedlandingpage_delete_taskitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskbasedlandingpage',
            options={'verbose_name': 'Task based landing pagex', 'verbose_name_plural': 'Task based landing pagesx'},
        ),
    ]
