# Generated by Django 4.2.11 on 2024-05-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0146_migrate_market_guide_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='supporttopiclandingpage',
            name='back_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supporttopiclandingpage',
            name='page_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supporttopiclandingpage',
            name='task_based_layout',
            field=models.BooleanField(default=False),
        ),
    ]
