# Generated by Django 4.2.11 on 2024-05-14 11:03

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.search.index
import wagtail.snippets.blocks
from django.db import migrations, models

import core.cms_panels


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('core', '0146_migrate_market_guide_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField()),
                ('description', models.CharField()),
                ('url', models.CharField()),
            ],
            options={
                'ordering': ('task',),
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='TaskBasedLandingPage',
            fields=[
                (
                    'page_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='wagtailcore.page',
                    ),
                ),
                ('page_title', models.TextField(null=True)),
                ('page_intro', models.TextField(null=True)),
                (
                    'page_body',
                    wagtail.fields.StreamField(
                        [
                            (
                                'sub_category',
                                wagtail.blocks.StructBlock(
                                    [
                                        ('title', wagtail.blocks.CharBlock()),
                                        ('description', wagtail.blocks.CharBlock()),
                                        (
                                            'task',
                                            wagtail.blocks.ListBlock(
                                                wagtail.snippets.blocks.SnippetChooserBlock('core.Task'),
                                                label='Choose task',
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ],
                        blank=True,
                        null=True,
                        use_json_field=True,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Task based landing page',
                'verbose_name_plural': 'Task based landing pages',
            },
            bases=(core.cms_panels.TaskBasedLandingPagePanels, 'wagtailcore.page'),
        ),
    ]
