# Generated by Django 4.2.11 on 2024-05-10 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0147_alter_taskbasedlandingpage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskbasedlandingpage',
            options={'verbose_name': 'Task based landing page', 'verbose_name_plural': 'Task based landing pages'},
        ),
    ]
