# Generated by Django 4.2.11 on 2024-06-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0147_supporttopiclandingpage_back_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alttextimage',
            name='alt_text',
            field=models.CharField(
                blank=True,
                help_text='Not required for purely decorative images without informational or functional value.',
                max_length=255,
            ),
        ),
    ]
