# Generated by Django 4.2.11 on 2024-05-10 13:30

import wagtail.blocks
import wagtail.fields
import wagtail.snippets.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0148_alter_taskbasedlandingpage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskbasedlandingpage',
            name='page_body',
            field=wagtail.fields.StreamField(
                [
                    (
                        'sub_category',
                        wagtail.blocks.StructBlock(
                            [
                                ('title', wagtail.blocks.CharBlock()),
                                ('description', wagtail.blocks.CharBlock()),
                                (
                                    'task',
                                    wagtail.blocks.ListBlock(
                                        wagtail.snippets.blocks.SnippetChooserBlock('core.Task'), label='Choose task'
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
