# Generated by Django 4.2.11 on 2024-07-01 14:26

import wagtail.blocks
import wagtail.fields
import wagtail.search.index
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0149_csatuserfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('description', models.TextField()),
                ('url', models.CharField()),
                ('services_url', models.CharField(blank=True)),
                ('message', models.TextField(blank=True)),
                (
                    'meta',
                    wagtail.fields.StreamField(
                        [
                            (
                                'tags',
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            'type',
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ('goods', 'Goods'),
                                                    ('services', 'Services'),
                                                    ('both', 'Both'),
                                                ],
                                                required=False,
                                            ),
                                        ),
                                        (
                                            'necessity',
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[('must_have', 'Must have'), ('may_need', 'May need')],
                                                required=False,
                                            ),
                                        ),
                                        (
                                            'complexity',
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[('simple', 'Simple'), ('difficult', 'Difficult')],
                                                required=False,
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ],
                        blank=True,
                        use_json_field=True,
                    ),
                ),
            ],
            options={
                'ordering': ('title',),
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
