# Generated by Django 4.2.11 on 2024-07-02 11:17

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.search.index
import wagtail.snippets.blocks
from django.db import migrations, models

import core.cms_panels


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('core', '0149_csatuserfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True)),
                ('title', models.CharField()),
                ('description', models.TextField()),
                ('goods_url', models.CharField(blank=True)),
                ('services_url', models.CharField(blank=True)),
                ('message', models.TextField(blank=True)),
                (
                    'meta',
                    wagtail.fields.StreamField(
                        [
                            (
                                'tags',
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            'type',
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ('goods', 'Goods'),
                                                    ('services', 'Services'),
                                                    ('both', 'Both'),
                                                ],
                                                required=False,
                                            ),
                                        ),
                                        (
                                            'necessity',
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[('must_have', 'Must have'), ('may_need', 'May need')],
                                                required=False,
                                            ),
                                        ),
                                        (
                                            'complexity',
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[('simple', 'Simple'), ('difficult', 'Difficult')],
                                                required=False,
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ],
                        blank=True,
                        use_json_field=True,
                    ),
                ),
            ],
            options={
                'ordering': ('title',),
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='TaskBasedSubCatPage',
            fields=[
                (
                    'page_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='wagtailcore.page',
                    ),
                ),
                ('page_title', models.TextField(null=True)),
                ('page_intro', models.TextField(null=True)),
                (
                    'page_body',
                    wagtail.fields.StreamField(
                        [
                            ('task', wagtail.snippets.blocks.SnippetChooserBlock('core.Task')),
                            ('sub_task', wagtail.snippets.blocks.SnippetChooserBlock('core.Task')),
                        ],
                        blank=True,
                        null=True,
                        use_json_field=True,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Task based sub category page',
                'verbose_name_plural': 'Task based sub category pages',
            },
            bases=(core.cms_panels.TaskBasedSubCatPagePanels, 'wagtailcore.page'),
        ),
    ]
