# Generated by Django 4.2.11 on 2024-07-17 09:52

import wagtail.search.index
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0151_regiontagged'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True)),
                ('title', models.CharField()),
                ('description_level_1', models.TextField()),
                ('description_level_2', models.TextField(blank=True)),
                ('link_text', models.CharField(blank=True)),
                ('url_goods', models.CharField(blank=True)),
                ('url_services', models.CharField(blank=True)),
                ('message', models.TextField(blank=True)),
                ('is_goods', models.BooleanField(default=False)),
                ('is_services', models.BooleanField(default=False)),
                ('is_essential', models.BooleanField(default=False)),
                ('is_simple', models.BooleanField(default=False)),
                ('is_difficult', models.BooleanField(default=False)),
                ('platform', models.CharField(blank=True)),
            ],
            options={
                'ordering': ('title',),
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
