# Generated by Django 4.2.11 on 2024-07-12 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0152_micrositepage_canonical_url_micrositepage_og_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='micrositepage',
            name='canonical_url',
        ),
        migrations.RemoveField(
            model_name='micrositepage',
            name='og_image',
        ),
        migrations.RemoveField(
            model_name='micrositepage',
            name='struct_org_actions',
        ),
        migrations.RemoveField(
            model_name='micrositepage',
            name='struct_org_address_country',
        ),
        migrations.RemoveField(
            model_name='micrositepage',
            name='struct_org_address_locality',
        ),
        migrations.RemoveField(
            model_name='micrositepage',
            name='struct_org_address_postal',
        ),
        migrations.RemoveField(
            model_name='micrositepage',
            name='struct_org_address_region',
        ),
        migrations.RemoveField(
            model_name='micrositepage',
            name='struct_org_address_street',
        ),
        migrations.RemoveField(
            model_name='micrositepage',
            name='struct_org_extra_json',
        ),
        migrations.RemoveField(
            model_name='micrositepage',
            name='struct_org_geo_lat',
        ),
        migrations.RemoveField(
            model_name='micrositepage',
            name='struct_org_geo_lng',
        ),
        migrations.RemoveField(
            model_name='micrositepage',
            name='struct_org_hours',
        ),
        migrations.RemoveField(
            model_name='micrositepage',
            name='struct_org_image',
        ),
        migrations.RemoveField(
            model_name='micrositepage',
            name='struct_org_logo',
        ),
        migrations.RemoveField(
            model_name='micrositepage',
            name='struct_org_name',
        ),
        migrations.RemoveField(
            model_name='micrositepage',
            name='struct_org_phone',
        ),
        migrations.RemoveField(
            model_name='micrositepage',
            name='struct_org_type',
        ),
    ]
