# Generated by Django 4.2.11 on 2024-07-18 10:01

import django.db.models.deletion
import wagtail.fields
import wagtail.snippets.blocks
from django.db import migrations, models

import core.cms_panels


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('core', '0152_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskBasedCategoryPage',
            fields=[
                (
                    'page_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='wagtailcore.page',
                    ),
                ),
                ('page_title', models.TextField(null=True)),
                ('page_intro', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Task based category page',
                'verbose_name_plural': 'Task based category pages',
            },
            bases=(core.cms_panels.TaskBasedCategoryPage, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='TaskBasedSubCategoryPage',
            fields=[
                (
                    'page_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='wagtailcore.page',
                    ),
                ),
                ('page_title', models.TextField(null=True)),
                ('page_intro', models.TextField(null=True)),
                (
                    'page_body',
                    wagtail.fields.StreamField(
                        [
                            ('task', wagtail.snippets.blocks.SnippetChooserBlock('core.Task')),
                            ('sub_task', wagtail.snippets.blocks.SnippetChooserBlock('core.Task')),
                        ],
                        blank=True,
                        null=True,
                        use_json_field=True,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Task based sub category page',
                'verbose_name_plural': 'Task based sub category pages',
            },
            bases=(core.cms_panels.TaskBasedSubCategoryPage, 'wagtailcore.page'),
        ),
    ]
