# Generated by Django 4.2.14 on 2024-08-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0153_taskbasedcategorypage_taskbasedsubcategorypage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='platform',
            new_name='info_source',
        ),
        migrations.AddField(
            model_name='task',
            name='difficulty_level',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='output_type',
            field=models.CharField(blank=True),
        ),
    ]
