# Generated by Django 4.2.11 on 2024-08-06 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmedia', '0004_duration_optional_floatfield'),
        ('core', '0153_taskbasedcategorypage_taskbasedsubcategorypage'),
    ]

    operations = [
        migrations.AddField(
            model_name='micrositepage',
            name='hero_video',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='wagtailmedia.media',
            ),
        ),
    ]
