# Generated by Django 4.2.15 on 2024-08-20 13:10

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0154_rename_platform_task_info_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportpage',
            name='page_body',
            field=wagtail.fields.StreamField(
                [
                    (
                        'topic_cards',
                        wagtail.blocks.StreamBlock(
                            [
                                (
                                    'topic_card',
                                    wagtail.blocks.StructBlock(
                                        [
                                            ('title', wagtail.blocks.CharBlock(label='Title', max_length=255)),
                                            (
                                                'description',
                                                wagtail.blocks.CharBlock(
                                                    label='Description', max_length=255, required=False
                                                ),
                                            ),
                                            ('link_text', wagtail.blocks.CharBlock(label='Link text', required=False)),
                                            ('link_url', wagtail.blocks.CharBlock(label='Link url')),
                                        ]
                                    ),
                                )
                            ],
                            block_counts={'topic_card': {'min_num': 1}},
                        ),
                    ),
                    (
                        'sidebar_items',
                        wagtail.blocks.StreamBlock(
                            [
                                (
                                    'sidebar_item',
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                'image',
                                                wagtail.images.blocks.ImageChooserBlock(
                                                    label='Card Image', required=False
                                                ),
                                            ),
                                            (
                                                'type',
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[
                                                        ('govuk', 'GOV.UK'),
                                                        ('tool', 'Tool'),
                                                        ('howTo', 'How to'),
                                                        ('service', 'Service'),
                                                    ],
                                                    label='Type',
                                                    required=False,
                                                ),
                                            ),
                                            ('title', wagtail.blocks.CharBlock(label='Title', max_length=255)),
                                            (
                                                'description',
                                                wagtail.blocks.CharBlock(label='Description', max_length=255),
                                            ),
                                            ('link_text', wagtail.blocks.CharBlock(label='Link text')),
                                            ('link_url', wagtail.blocks.CharBlock(label='Link url')),
                                            (
                                                'full_width',
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[('yes', 'Yes'), ('no', 'No')],
                                                    label='Full width?',
                                                    required=False,
                                                ),
                                            ),
                                        ]
                                    ),
                                )
                            ],
                            block_counts={'sidebar_item': {'min_num': 1}},
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
