# Generated by Django 4.2.11 on 2024-08-22 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmedia', '0004_duration_optional_floatfield'),
        ('core', '0155_alter_supportpage_page_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='micrositepage',
            name='hero_video',
            field=models.ForeignKey(
                blank=True,
                help_text='Adding a hero video will replace the hero image',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='wagtailmedia.media',
            ),
        ),
    ]
