# Generated by Django 4.2.15 on 2024-09-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0156_micrositepage_hero_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='micrositepage',
            name='include_link_to_great',
            field=models.BooleanField(
                default=True,
                help_text='If selected a link to great.gov.uk will appear in the header. Otherwise this will not be shown. Note this checkbox only works on the root page.',
                verbose_name='Include link to Great',
            ),
        ),
        migrations.AlterField(
            model_name='micrositepage',
            name='use_domestic_header_logo',
            field=models.BooleanField(
                default=True,
                help_text='If selected the dbt logo will be displayed in the header. Otherwise the UK Gov logo will be shown. Note this checkbox only works on the root page.',
                verbose_name='Use domestic header logo',
            ),
        ),
    ]
