# Generated by Django 4.2.15 on 2024-09-17 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0157_micrositepage_include_link_to_great_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrytagged',
            name='tag',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='generic_country_tagged', to='core.countrytag'
            ),
        ),
        migrations.AlterField(
            model_name='regiontagged',
            name='tag',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='generric_region_tagged',
                to='core.personalisationregiontag',
            ),
        ),
        migrations.AlterField(
            model_name='sectortagged',
            name='tag',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='generic_sector_tagged', to='core.sectortag'
            ),
        ),
        migrations.AlterField(
            model_name='typeofexporttagged',
            name='tag',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='generic_typeofexport_tagged',
                to='core.typeofexporttag',
            ),
        ),
    ]
