# Generated by Django 4.2.15 on 2024-09-20 11:34

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('domestic', '0064_articlepage_country_tags_articlepage_region_tags_and_more'),
        ('core', '0157_micrositepage_include_link_to_great_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCountryTagged',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True, verbose_name='object ID')),
                (
                    'content_object',
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='test_country_tagged_items',
                        to='domestic.articlepage',
                    ),
                ),
                (
                    'content_type',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(app_label)s_%(class)s_tagged_items',
                        to='contenttypes.contenttype',
                        verbose_name='content type',
                    ),
                ),
                (
                    'tag',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(app_label)s_%(class)s_items',
                        to='core.countrytag',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
