# Generated by Django 4.2.14 on 2024-09-30 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0157_micrositepage_include_link_to_great_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curatedlistpage',
            name='country_tags',
        ),
        migrations.RemoveField(
            model_name='curatedlistpage',
            name='sector_tags',
        ),
        migrations.RemoveField(
            model_name='curatedlistpage',
            name='type_of_export_tags',
        ),
        migrations.RemoveField(
            model_name='topicpage',
            name='country_tags',
        ),
        migrations.RemoveField(
            model_name='topicpage',
            name='sector_tags',
        ),
        migrations.RemoveField(
            model_name='topicpage',
            name='type_of_export_tags',
        ),
    ]
