# Generated by Django 4.2.15 on 2024-09-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0158_hcsat_site_intentions_hcsat_site_intentions_other_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hcsat',
            name='session_key',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
