# Generated by Django 4.2.14 on 2024-09-30 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0158_remove_curatedlistpage_country_tags_and_more'),
        ('domestic', '0065_remove_articlepage_type_of_export_tags_and_more'),
        ('export_academy', '0053_remove_coursepage_type_of_export_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regiontagged',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='regiontagged',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='sectortagged',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='sectortagged',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='typeofexporttagged',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='typeofexporttagged',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='sector_tags',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='type_of_export_tags',
        ),
        migrations.DeleteModel(
            name='CountryTagged',
        ),
        migrations.DeleteModel(
            name='RegionTagged',
        ),
        migrations.DeleteModel(
            name='SectorTagged',
        ),
        migrations.DeleteModel(
            name='TypeOfExportTagged',
        ),
    ]
