# Generated by Django 4.2.15 on 2024-09-20 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0158_testcountrytagged'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcountrytagged',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='testcountrytagged',
            name='object_id',
        ),
        migrations.AlterField(
            model_name='testcountrytagged',
            name='tag',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.countrytag'
            ),
        ),
    ]
