# Generated by Django 4.2.15 on 2024-10-02 11:45

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import taggit.managers
import wagtail.search.index


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0159_remove_regiontagged_content_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryTaggedSectorAndMarketPromo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SectorAndMarketPromo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('description', models.TextField()),
                ('link_text', models.CharField(blank=True)),
                ('link_url', models.CharField(blank=True)),
                (
                    'country_tags',
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text='A comma-separated list of tags.',
                        through='core.CountryTaggedSectorAndMarketPromo',
                        to='core.CountryTag',
                        verbose_name='Country tag',
                    ),
                ),
            ],
            options={
                'ordering': ('title',),
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='SectorTaggedTaggedSectorAndMarketPromo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'content_object',
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE, to='core.sectorandmarketpromo'
                    ),
                ),
                (
                    'tag',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.sectortag'
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sectorandmarketpromo',
            name='sector_tags',
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text='A comma-separated list of tags.',
                through='core.SectorTaggedTaggedSectorAndMarketPromo',
                to='core.SectorTag',
                verbose_name='Sector tag',
            ),
        ),
        migrations.AddField(
            model_name='countrytaggedsectorandmarketpromo',
            name='content_object',
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE, to='core.sectorandmarketpromo'
            ),
        ),
        migrations.AddField(
            model_name='countrytaggedsectorandmarketpromo',
            name='tag',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.countrytag'
            ),
        ),
    ]
