# Generated by Django 4.2.15 on 2024-10-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0159_remove_regiontagged_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosnippet',
            name='slug',
            field=models.CharField(
                choices=[
                    ('export-academy-listing-page-hero', 'Hero for the Export Academy listing page'),
                    ('export-academy-registration-page-hero', 'Hero for the Export Academy registration page'),
                ],
                help_text='Select the use-case for this snippet from a fixed list of choices',
                max_length=255,
                unique=True,
                verbose_name='Purpose',
            ),
        ),
    ]
