# Generated by Django 4.2.15 on 2024-10-02 14:20

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import taggit.managers
import wagtail.search.index


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0160_alter_herosnippet_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryTaggedSectorAndMarketCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SectorAndMarketCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('description', models.TextField()),
                ('link_text', models.CharField(blank=True)),
                ('link_url', models.CharField(blank=True)),
                (
                    'meta_label',
                    models.CharField(
                        choices=[
                            ('guidance_great', 'Guidance on great.gov.uk'),
                            ('service_great', 'Service on great.gov.uk'),
                            ('guidance_gov', 'Guidance on GOV.UK'),
                            ('service_gov', 'Service on GOV.UK'),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    'country_tags',
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text='A comma-separated list of tags.',
                        through='core.CountryTaggedSectorAndMarketCard',
                        to='core.CountryTag',
                        verbose_name='Country tag',
                    ),
                ),
            ],
            options={
                'ordering': ('title',),
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='SectorTaggedTaggedSectorAndMarketCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'content_object',
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE, to='core.sectorandmarketcard'
                    ),
                ),
                (
                    'tag',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.sectortag'
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sectorandmarketcard',
            name='sector_tags',
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text='A comma-separated list of tags.',
                through='core.SectorTaggedTaggedSectorAndMarketCard',
                to='core.SectorTag',
                verbose_name='Sector tag',
            ),
        ),
        migrations.AddField(
            model_name='countrytaggedsectorandmarketcard',
            name='content_object',
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE, to='core.sectorandmarketcard'
            ),
        ),
        migrations.AddField(
            model_name='countrytaggedsectorandmarketcard',
            name='tag',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.countrytag'
            ),
        ),
    ]
