# Generated by Django 4.2.15 on 2024-10-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0161_countrytaggedsectorandmarketcard_sectorandmarketcard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectorandmarketcard',
            name='meta_label',
            field=models.CharField(
                blank=True,
                choices=[
                    ('guidance_great', 'Guidance on great.gov.uk'),
                    ('service_great', 'Service on great.gov.uk'),
                    ('guidance_gov', 'Guidance on GOV.UK'),
                    ('service_gov', 'Service on GOV.UK'),
                ],
                max_length=255,
            ),
        ),
    ]
