# Generated by Django 4.2.15 on 2024-10-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0162_alter_sectorandmarketcard_meta_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectorandmarketcard',
            name='exporter_type',
            field=models.CharField(
                blank=True, choices=[('goods', 'Goods'), ('service', 'Service'), ('both', 'Both')], max_length=255
            ),
        ),
    ]
