# Generated by Django 4.2.15 on 2024-10-09 10:02

import django.contrib.postgres.fields
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0162_alter_sectorandmarketcard_meta_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='HCSAT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, null=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, null=True, verbose_name='modified'
                    ),
                ),
                ('session_key', models.CharField(max_length=255, null=True)),
                ('URL', models.CharField(max_length=255)),
                (
                    'user_journey',
                    models.CharField(
                        choices=[
                            ('ADD_PRODUCT', 'Add Product'),
                            ('ARTICLE_PAGE', 'Article Page'),
                            ('EXPORT_PLAN_UPDATE', 'Export Plan Update'),
                            ('EVENT_BOOKING', 'Event booking'),
                            ('COMPANY_VERIFICATION', 'Company verification'),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    'satisfaction_rating',
                    models.CharField(
                        choices=[
                            ('VERY_DISSATISFIED', 'Very dissatisfied'),
                            ('DISSATISFIED', 'Dissatisfied'),
                            ('NEITHER', 'Neither satisfied nor dissatisfied'),
                            ('SATISFIED', 'Satisfied'),
                            ('VERY_SATISFIED', 'Very satisfied'),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    'experienced_issues',
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ('NOT_FIND_LOOKING_FOR', 'I did not find what I was looking for'),
                                ('DIFFICULT_TO_NAVIGATE', 'I found it difficult to navigate the service'),
                                ('SYSTEM_LACKS_FEATURE', 'The service lacks the feature I need'),
                                ('UNABLE_TO_LOAD/REFRESH/ENTER', 'I was unable to load/refresh/enter a page'),
                                ('OTHER', 'Other'),
                                ('NO_ISSUE', 'I did not experience any issues'),
                            ],
                            max_length=255,
                        ),
                        default=list,
                        null=True,
                        size=6,
                    ),
                ),
                ('other_detail', models.CharField(max_length=255, null=True)),
                ('service_improvements_feedback', models.CharField(max_length=3000, null=True)),
                (
                    'likelihood_of_return',
                    models.CharField(
                        choices=[
                            ('EXTREMELY_UNLIKELY', 'Extremely unlikely'),
                            ('UNLIKELY', 'Unlikely'),
                            ('NEITHER_LIKELY_NOR_UNLIKELY', 'Neither likely nor unlikely'),
                            ('LIKELY', 'Likely'),
                            ('EXTREMELY_LIKELY', 'Extremely likely'),
                            ('DONT_KNOW_OR_PREFER_NOT_TO_SAY', "Don't know/prefer not to say"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    'site_intentions',
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ('HELP_US_SET_UP_IN_THE_UK', 'Help us set up in the UK'),
                                (
                                    'UNDERSTAND_THE_UK_LEGAL_SYSTEM',
                                    'Understand the UK legal system such as tax and employment regulations',
                                ),
                                ('PUT_US_IN_TOUCH_WITH_EXPERTS', 'Put us in touch with experts to help us set up'),
                                ('ACCESS_TRUSTED_INFORMATION', 'Access trusted information'),
                                ('LEARN_ABOUT_AVAILABLE_INCENTIVES', 'Learn about available incentives'),
                                ('DONT_KNOW_OR_PREFER_NOT_TO_SAY', "Don't know / prefer not to say"),
                                ('MY_BUSINESS_WILL_NOT_USE_THE_SITE', 'My business will not use the site'),
                                ('OTHER', 'Other'),
                            ],
                            max_length=255,
                        ),
                        default=list,
                        null=True,
                        size=6,
                    ),
                ),
                ('site_intentions_other', models.CharField(max_length=255, null=True)),
                ('stage', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
