# Generated by Django 4.2.15 on 2024-10-11 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0163_hcsat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hcsat',
            name='site_intentions',
        ),
        migrations.RemoveField(
            model_name='hcsat',
            name='site_intentions_other',
        ),
    ]
