# Generated by Django 4.2.16 on 2024-11-19 11:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0164_hcsat'),
    ]

    operations = [
        migrations.AddField(
            model_name='hcsat',
            name='service_specific_feedback',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), blank=True, default=list, null=True, size=10
            ),
        ),
        migrations.AddField(
            model_name='hcsat',
            name='service_specific_feedback_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
