# Generated by Django 4.2.16 on 2024-11-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0165_hcsat_service_specific_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hcsat',
            name='service_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
