# Generated by Django 4.2.16 on 2024-12-04 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import wagtail.models.collections
import wagtail.search.index


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('taggit', '0005_auto_20220424_2025'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0166_hcsat_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hcsat',
            name='user_journey',
            field=models.CharField(
                choices=[
                    ('ADD_PRODUCT', 'Add Product'),
                    ('ARTICLE_PAGE', 'Article Page'),
                    ('EXPORT_PLAN_UPDATE', 'Export Plan Update'),
                    ('EVENT_BOOKING', 'Event booking'),
                    ('COMPANY_VERIFICATION', 'Company verification'),
                    ('COMPANY_CONTACT', 'Company contact'),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name='GreatDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('file', models.FileField(upload_to='documents', verbose_name='file')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('file_size', models.PositiveIntegerField(editable=False, null=True)),
                ('file_hash', models.CharField(blank=True, editable=False, max_length=40)),
                (
                    'collection',
                    models.ForeignKey(
                        default=wagtail.models.collections.get_root_collection_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='+',
                        to='wagtailcore.collection',
                        verbose_name='collection',
                    ),
                ),
                (
                    'tags',
                    taggit.managers.TaggableManager(
                        blank=True, help_text=None, through='taggit.TaggedItem', to='taggit.Tag', verbose_name='tags'
                    ),
                ),
                (
                    'uploaded_by_user',
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='uploaded by user',
                    ),
                ),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
