# Generated by Django 4.2.16 on 2024-12-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0166_hcsat_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hcsat',
            name='user_journey',
            field=models.CharField(
                choices=[
                    ('ADD_PRODUCT', 'Add Product'),
                    ('ARTICLE_PAGE', 'Article Page'),
                    ('EXPORT_PLAN_UPDATE', 'Export Plan Update'),
                    ('EVENT_BOOKING', 'Event booking'),
                    ('COMPANY_VERIFICATION', 'Company verification'),
                    ('COMPANY_CONTACT', 'Company contact'),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
