# Generated by Django 4.2.17 on 2025-02-27 10:58

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0167_alter_hcsat_user_journey'),
    ]

    operations = [
        migrations.AddField(
            model_name='micrositepage',
            name='expiry_date',
            field=models.DateTimeField(default=core.models.MicrositePage.get_datetime_one_year_ahead),
        ),
    ]
