# Generated by Django 4.2.17 on 2025-02-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0167_alter_hcsat_user_journey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='micrositepage',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='micrositepage',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='micrositepage',
            name='twitter',
        ),
        migrations.AddField(
            model_name='micrositepage',
            name='show_social_media',
            field=models.BooleanField(default=False),
        ),
    ]
