# Generated by Django 4.2.17 on 2025-02-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0167_alter_hcsat_user_journey'),
    ]

    operations = [
        migrations.AddField(
            model_name='micrositepage',
            name='show_social_media_share',
            field=models.BooleanField(default=False),
        ),
    ]
