# Generated by Django 4.2.17 on 2025-02-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0168_remove_micrositepage_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='micrositepage',
            name='facebook',
            field=models.URLField(blank=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='micrositepage',
            name='linkedin',
            field=models.URLField(blank=True, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='micrositepage',
            name='twitter',
            field=models.URLField(blank=True, verbose_name='Twitter'),
        ),
    ]
