# Generated by Django 4.2.19 on 2025-03-04 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0168_micrositepage_show_social_media_share'),
        ('core', '0168_remove_curatedlistpage_struct_org_actions_and_more'),
    ]

    operations = []
