# Generated by Django 4.2.19 on 2025-03-24 15:35

from django.db import migrations, models

import core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0169_merge_20250304_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='micrositepage',
            name='expiry_date',
            field=models.DateTimeField(default=core.models.MicrositePage.get_datetime_one_year_ahead),
        ),
    ]
