# Generated by Django 4.2.17 on 2025-02-19 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0169_micrositepage_facebook_micrositepage_linkedin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='micrositepage',
            name='show_social_media',
        ),
    ]
