# Generated by Django 4.2.20 on 2025-05-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0170_micrositepage_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='curatedlistpage',
            name='meta_robots_nofollow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='curatedlistpage',
            name='meta_robots_noindex',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detailpage',
            name='meta_robots_nofollow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detailpage',
            name='meta_robots_noindex',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='getintouchpage',
            name='meta_robots_nofollow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='getintouchpage',
            name='meta_robots_noindex',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interstitialpage',
            name='meta_robots_nofollow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interstitialpage',
            name='meta_robots_noindex',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='meta_robots_nofollow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='meta_robots_noindex',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listpage',
            name='meta_robots_nofollow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listpage',
            name='meta_robots_noindex',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='support',
            name='meta_robots_nofollow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='support',
            name='meta_robots_noindex',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supportpage',
            name='meta_robots_nofollow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supportpage',
            name='meta_robots_noindex',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supporttopiclandingpage',
            name='meta_robots_nofollow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supporttopiclandingpage',
            name='meta_robots_noindex',
            field=models.BooleanField(default=False),
        ),
    ]
