# Generated by Django 4.2.14 on 2024-10-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international_investment', '0004_investmentopportunityarticlepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentopportunityarticlepage',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
