# Generated by Django 4.2.16 on 2024-11-27 14:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international_investment', '0005_alter_investmentopportunityarticlepage_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentopportunityarticlepage',
            name='dbt_sectors',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), blank=True, default=list, size=None
            ),
        ),
    ]
