# Generated by Django 4.2.16 on 2024-11-27 15:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international_investment', '0006_investmentopportunityarticlepage_dbt_sectors'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentopportunityarticlepage',
            name='dbt_locations',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), blank=True, default=list, size=None
            ),
        ),
    ]
