# Generated by Django 4.2.19 on 2025-04-30 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0170_micrositepage_expiry_date'),
        ('international_investment', '0008_remove_investmentarticlepage_struct_org_actions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentarticlepage',
            name='article_thumbnail_image',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='core.alttextimage',
            ),
        ),
    ]
