# Generated by Django 4.2.20 on 2025-05-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international_investment', '0009_investmentarticlepage_article_thumbnail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentarticlepage',
            name='meta_robots_nofollow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investmentarticlepage',
            name='meta_robots_noindex',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investmentindexpage',
            name='meta_robots_nofollow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investmentindexpage',
            name='meta_robots_noindex',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investmentopportunityarticlepage',
            name='meta_robots_nofollow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investmentopportunityarticlepage',
            name='meta_robots_noindex',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investmentregionspage',
            name='meta_robots_nofollow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investmentregionspage',
            name='meta_robots_noindex',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investmentsectorspage',
            name='meta_robots_nofollow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investmentsectorspage',
            name='meta_robots_noindex',
            field=models.BooleanField(default=False),
        ),
    ]
