from django.urls import re_path

from core.views import PermanentQuerystringRedirectView

"""
    A list of redirects required across the international service for the migration from
    great-international-ui to great-cms
"""
international_migration_redirects = [
    re_path(
        r'^international/trade/search/$',
        PermanentQuerystringRedirectView.as_view(url='/international/buy-from-uk/find-a-supplier/'),
    ),
    re_path(
        r'^international/trade/$',
        PermanentQuerystringRedirectView.as_view(url='/international/buy-from-uk/'),
    ),
    re_path(
        r'^international/contact/$',
        PermanentQuerystringRedirectView.as_view(url='/get-help/'),
    ),
    re_path(
        r'^contact/international/$',
        PermanentQuerystringRedirectView.as_view(url='/get-help/'),
    ),
    re_path(
        r'^international/site-help/$',
        PermanentQuerystringRedirectView.as_view(url='/get-help/'),
    ),
    re_path(
        r'^international/site-help/success/$',
        PermanentQuerystringRedirectView.as_view(url='/get-help/success/'),
    ),
    re_path(
        r'^contact/international/success/$',
        PermanentQuerystringRedirectView.as_view(url='/get-help/success/'),
    ),
    re_path(
        r'^international/content/investment/how-we-can-help/global-entrepreneur-program/$',
        PermanentQuerystringRedirectView.as_view(url='/campaign-site/gep/'),
    ),
    re_path(
        r'^international/content/investment/how-we-can-help/the-venture-capital-unit/$',
        PermanentQuerystringRedirectView.as_view(url='/international/expand-business-in-the-uk/'),
    ),
    re_path(
        r'^international/content/investment/how-we-can-help/$',
        PermanentQuerystringRedirectView.as_view(url='/international/expand-business-in-the-uk/'),
    ),
    re_path(
        r'^international/content/investment/why-invest-in-the-uk/$',
        PermanentQuerystringRedirectView.as_view(url='/international/'),
    ),
    re_path(
        r'^international/content/investment/how-we-can-help/research-and-development-rd-support-in-the-uk/$',
        PermanentQuerystringRedirectView.as_view(url='/international/expand-business-in-the-uk/'),
    ),
    re_path(
        r'^international/trade/contact/$',
        PermanentQuerystringRedirectView.as_view(url='/international/'),
    ),
    re_path(
        r'^international/invest/contact/$',
        PermanentQuerystringRedirectView.as_view(url='/international/'),
    ),
    re_path(
        r'^international/content/investment/how-we-can-help/the-office-for-investment/$',
        PermanentQuerystringRedirectView.as_view(url='/international/'),
    ),
    re_path(
        r'^international/content/investment/how-we-can-help/hire-skilled-workers-for-your-uk-operations/$',
        PermanentQuerystringRedirectView.as_view(url='/international/expand-business-in-the-uk/'),
    ),
    re_path(
        r'^international/content/investment/how-we-can-help/access-finance-in-the-uk/$',
        PermanentQuerystringRedirectView.as_view(url='/international/expand-business-in-the-uk/'),
    ),
    re_path(
        r'^international/content/investment/how-we-can-help/establish-a-base-for-business-in-the-uk/$',
        PermanentQuerystringRedirectView.as_view(url='/international/expand-business-in-the-uk/'),
    ),
    re_path(
        r'^international/content/investment/how-we-can-help/register-a-company-in-the-uk/$',
        PermanentQuerystringRedirectView.as_view(url='/international/expand-business-in-the-uk/'),
    ),
    re_path(
        r'^international/content/investment/how-we-can-help/uk-visas-and-migration/$',
        PermanentQuerystringRedirectView.as_view(url='/international/expand-business-in-the-uk/'),
    ),
    re_path(
        r'^international/content/investment/how-we-can-help/open-a-uk-business-bank-account/$',
        PermanentQuerystringRedirectView.as_view(url='/international/expand-business-in-the-uk/'),
    ),
    re_path(
        r'^international/content/invest/how-to-setup-in-the-uk/.*$',
        PermanentQuerystringRedirectView.as_view(url='/international/expand-business-in-the-uk/'),
    ),
]

invest_in_uk_redirects = [
    re_path(
        r'^invest-in-uk/trade/search/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/buy-from-uk/find-a-supplier/'),
    ),
    re_path(
        r'^invest-in-uk/trade/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/buy-from-the-uk/'),
    ),
    re_path(
        r'^invest-in-uk/content/trade/how-we-help-you-buy/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/buy-from-the-uk/'),
    ),
    re_path(
        r'^invest-in-uk/contact/$',
        PermanentQuerystringRedirectView.as_view(url='/get-help/'),
    ),
    re_path(
        r'^contact/invest-in-uk/$',
        PermanentQuerystringRedirectView.as_view(url='/get-help/'),
    ),
    re_path(
        r'^contact/invest-in-uk/success/$',
        PermanentQuerystringRedirectView.as_view(url='/get-help/success/'),
    ),
    re_path(
        r'^invest-in-uk/site-help/$',
        PermanentQuerystringRedirectView.as_view(url='/get-help/'),
    ),
    re_path(
        r'^invest-in-uk/site-help/success/$',
        PermanentQuerystringRedirectView.as_view(url='/get-help/success/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/how-we-can-help/global-entrepreneur-program/$',
        PermanentQuerystringRedirectView.as_view(url='/campaign-site/gep/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/how-we-can-help/the-venture-capital-unit/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/expand-business-in-the-uk/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/how-we-can-help/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/expand-business-in-the-uk/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/why-invest-in-the-uk/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/how-we-can-help/research-and-development-rd-support-in-the-uk/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/expand-business-in-the-uk/'),
    ),
    re_path(
        r'^invest-in-uk/trade/contact/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/'),
    ),
    re_path(
        r'^invest-in-uk/invest/contact/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/how-we-can-help/the-office-for-investment/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/how-we-can-help/hire-skilled-workers-for-your-uk-operations/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/expand-business-in-the-uk/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/how-we-can-help/access-finance-in-the-uk/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/expand-business-in-the-uk/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/how-we-can-help/establish-a-base-for-business-in-the-uk/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/expand-business-in-the-uk/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/how-we-can-help/register-a-company-in-the-uk/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/expand-business-in-the-uk/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/how-we-can-help/uk-visas-and-migration/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/expand-business-in-the-uk/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/how-we-can-help/open-a-uk-business-bank-account/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/expand-business-in-the-uk/'),
    ),
    re_path(
        r'^invest-in-uk/content/invest/how-to-setup-in-the-uk/.*$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/expand-business-in-the-uk/'),
    ),
]
