from django.urls import re_path

from core.views import PermanentQuerystringRedirectView

"""
    A list of redirects required across the international service for the migration from
    great-international-ui to great-cms
"""
international_migration_redirects = [
    re_path(
        r'^international/content/investment/why-invest-in-the-uk/uk-investment-zones/$',
        PermanentQuerystringRedirectView.as_view(url='/international/investment-opportunities/uk-investment-zones/'),
    ),
    re_path(
        r'^international/trade/search/$',
        PermanentQuerystringRedirectView.as_view(url='/international/buy-from-uk/find-a-supplier/'),
    ),
    re_path(
        r'^international/trade/$',
        PermanentQuerystringRedirectView.as_view(url='/international/buy-from-uk/'),
    ),
    re_path(
        r'^international/content/trade/how-we-help-you-buy/$',
        PermanentQuerystringRedirectView.as_view(url='/international/buy-from-uk/'),
    ),
    re_path(
        r'^international/content/investment/why-invest-in-the-uk/uk-investment-zones/$',
        PermanentQuerystringRedirectView.as_view(url='/international/investment-opportunities/uk-investment-zones/'),
    ),
    re_path(
        r'^international/content/investment/how-we-can-help/uk-tax-and-incentives/$',
        PermanentQuerystringRedirectView.as_view(url='/international/investment-opportunities/uk-tax-and-incentives/'),
    ),
    re_path(
        r'^international/content/investment/why-invest-in-the-uk/uk-talent-and-labour/$',
        PermanentQuerystringRedirectView.as_view(url='/international/investment-opportunities/uk-talent-and-labour/'),
    ),
    re_path(
        r'^international/content/investment/why-invest-in-the-uk/uk-innovation/$',
        PermanentQuerystringRedirectView.as_view(url='/international/investment-opportunities/uk-innovation/'),
    ),
    re_path(
        r'^international/content/investment/why-invest-in-the-uk/uk-infrastructure/$',
        PermanentQuerystringRedirectView.as_view(url='/international/investment-opportunities/uk-infrastructure/'),
    ),
    re_path(
        r'^international/content/investment/why-invest-in-the-uk/clean-growth-in-the-uk/$',
        PermanentQuerystringRedirectView.as_view(url='/international/investment-opportunities/clean-growth-in-the-uk/'),
    ),
    re_path(
        r'^international/content/investment/how-we-can-help/freeports-in-the-uk/$',
        PermanentQuerystringRedirectView.as_view(url='/international/investment-opportunities/freeports-in-the-uk/'),
    ),
    re_path(
        r'^international/content/investment/regions/$',
        PermanentQuerystringRedirectView.as_view(url='/international/investment-opportunities/regions/'),
    ),
    re_path(
        r'^international/content/investment/regions/wales/$',
        PermanentQuerystringRedirectView.as_view(url='/international/investment-opportunities/regions/wales/'),
    ),
    re_path(
        r'^international/content/investment/regions/south-england/$',
        PermanentQuerystringRedirectView.as_view(url='/international/investment-opportunities/regions/south-england/'),
    ),
    re_path(
        r'^international/content/investment/regions/northern-ireland/$',
        PermanentQuerystringRedirectView.as_view(
            url='/international/investment-opportunities/regions/northern-ireland/'
        ),
    ),
    re_path(
        r'^international/content/investment/regions/north-england/$',
        PermanentQuerystringRedirectView.as_view(url='/international/investment-opportunities/regions/north-england/'),
    ),
    re_path(
        r'^international/content/investment/regions/midlands/$',
        PermanentQuerystringRedirectView.as_view(url='/international/investment-opportunities/regions/midlands/'),
    ),
    re_path(
        r'^international/content/investment/regions/scotland/$',
        PermanentQuerystringRedirectView.as_view(url='/international/investment-opportunities/regions/scotland/'),
    ),
    re_path(
        r'^international/content/investment/sectors/$',
        PermanentQuerystringRedirectView.as_view(url='/international/investment-opportunities/sectors/'),
    ),
    re_path(
        r'^international/content/investment/sectors/aerospace-and-jet-zero/$',
        PermanentQuerystringRedirectView.as_view(
            url='/international/investment-opportunities/sectors/aerospace-and-jet-zero/'
        ),
    ),
    re_path(
        r'^international/content/investment/sectors/biopharmaceuticals/$',
        PermanentQuerystringRedirectView.as_view(
            url='/international/investment-opportunities/sectors/biopharmaceuticals/'
        ),
    ),
    re_path(
        r'^international/content/investment/sectors/carbon-capture-usage-and-storage/$',
        PermanentQuerystringRedirectView.as_view(
            url='/international/investment-opportunities/sectors/carbon-capture-usage-and-storage/'
        ),
    ),
    re_path(
        r'^international/content/investment/sectors/chemicals/$',
        PermanentQuerystringRedirectView.as_view(url='/international/investment-opportunities/sectors/chemicals/'),
    ),
    re_path(
        r'^international/content/investment/sectors/civil-nuclear/$',
        PermanentQuerystringRedirectView.as_view(url='/international/investment-opportunities/sectors/civil-nuclear/'),
    ),
    re_path(
        r'^international/content/investment/sectors/agri-tech/$',
        PermanentQuerystringRedirectView.as_view(url='/international/investment-opportunities/sectors/agri-tech/'),
    ),
    re_path(
        r'^international/content/investment/sectors/creative-industries/$',
        PermanentQuerystringRedirectView.as_view(
            url='/international/investment-opportunities/sectors/creative-industries/'
        ),
    ),
    re_path(
        r'^international/content/investment/sectors/cyber-security/$',
        PermanentQuerystringRedirectView.as_view(url='/international/investment-opportunities/sectors/cyber-security/'),
    ),
    re_path(
        r'^international/content/investment/sectors/edtech/$',
        PermanentQuerystringRedirectView.as_view(url='/international/investment-opportunities/sectors/edtech/'),
    ),
    re_path(
        r'^international/content/investment/sectors/financial-services/$',
        PermanentQuerystringRedirectView.as_view(
            url='/international/investment-opportunities/sectors/financial-services/'
        ),
    ),
    re_path(
        r'^international/content/investment/sectors/fintech/$',
        PermanentQuerystringRedirectView.as_view(url='/international/investment-opportunities/sectors/fintech/'),
    ),
    re_path(
        r'^international/content/investment/sectors/food-and-drink/$',
        PermanentQuerystringRedirectView.as_view(url='/international/investment-opportunities/sectors/food-and-drink/'),
    ),
    re_path(
        r'^international/content/investment/sectors/precision-medicine/$',
        PermanentQuerystringRedirectView.as_view(
            url='/international/investment-opportunities/sectors/precision-medicine/'
        ),
    ),
    re_path(
        r'^international/content/investment/sectors/green-shipping/$',
        PermanentQuerystringRedirectView.as_view(url='/international/investment-opportunities/sectors/green-shipping/'),
    ),
    re_path(
        r'^international/content/investment/sectors/green-finance/$',
        PermanentQuerystringRedirectView.as_view(url='/international/investment-opportunities/sectors/green-finance/'),
    ),
    re_path(
        r'^international/content/investment/sectors/greener-buildings/$',
        PermanentQuerystringRedirectView.as_view(
            url='/international/investment-opportunities/sectors/greener-buildings/'
        ),
    ),
    re_path(
        r'^international/content/investment/sectors/healthcare-and-life-sciences/$',
        PermanentQuerystringRedirectView.as_view(
            url='/international/investment-opportunities/sectors/healthcare-and-life-sciences/'
        ),
    ),
    re_path(
        r'^international/content/investment/sectors/hydrogen/$',
        PermanentQuerystringRedirectView.as_view(url='/international/investment-opportunities/sectors/hydrogen/'),
    ),
    re_path(
        r'^international/content/investment/sectors/medtech/$',
        PermanentQuerystringRedirectView.as_view(url='/international/investment-opportunities/sectors/medtech/'),
    ),
    re_path(
        r'^international/content/investment/sectors/mineral-extraction-and-refining/$',
        PermanentQuerystringRedirectView.as_view(
            url='/international/investment-opportunities/sectors/mineral-extraction-and-refining/'
        ),
    ),
    re_path(
        r'^international/content/investment/sectors/offshore-wind/$',
        PermanentQuerystringRedirectView.as_view(url='/international/investment-opportunities/sectors/offshore-wind/'),
    ),
    re_path(
        r'^international/content/investment/sectors/professional-and-business-services/$',
        PermanentQuerystringRedirectView.as_view(
            url='/international/investment-opportunities/sectors/professional-and-business-services/'
        ),
    ),
    re_path(
        r'^international/content/investment/sectors/real-estate/$',
        PermanentQuerystringRedirectView.as_view(url='/international/investment-opportunities/sectors/real-estate/'),
    ),
    re_path(
        r'^international/content/investment/sectors/retail/$',
        PermanentQuerystringRedirectView.as_view(url='/international/investment-opportunities/sectors/retail/'),
    ),
    re_path(
        r'^international/content/investment/sectors/space/$',
        PermanentQuerystringRedirectView.as_view(url='/international/investment-opportunities/sectors/space/'),
    ),
    re_path(
        r'^international/content/investment/sectors/sports-economy/$',
        PermanentQuerystringRedirectView.as_view(url='/international/investment-opportunities/sectors/sports-economy/'),
    ),
    re_path(
        r'^international/content/investment/sectors/sustainable-infrastructure/$',
        PermanentQuerystringRedirectView.as_view(
            url='/international/investment-opportunities/sectors/sustainable-infrastructure/'
        ),
    ),
    re_path(
        r'^international/content/investment/sectors/technology/$',
        PermanentQuerystringRedirectView.as_view(url='/international/investment-opportunities/sectors/technology/'),
    ),
    re_path(
        r'^international/content/investment/sectors/oil-and-gas/$',
        PermanentQuerystringRedirectView.as_view(url='/international/investment-opportunities/sectors/oil-and-gas/'),
    ),
    re_path(
        r'^international/content/investment/sectors/zero-emission-vehicles/$',
        PermanentQuerystringRedirectView.as_view(
            url='/international/investment-opportunities/sectors/zero-emission-vehicles/'
        ),
    ),
    re_path(
        r'^international/content/investment/opportunities/accelerated-electrification-transition-in-the-north-east-of-england/$',  # noqa:E501
        PermanentQuerystringRedirectView.as_view(
            url='/international/investment-opportunities/accelerated-electrification-transition-in-the-north-east-of-england/'  # noqa:E501
        ),
    ),
    re_path(
        r'^international/content/investment/opportunities/5g-and-digitisation-in-norfolk-and-suffolk-east-of-england/$',
        PermanentQuerystringRedirectView.as_view(
            url='/international/investment-opportunities/5g-and-digitisation-in-norfolk-and-suffolk-east-of-england/'
        ),
    ),
    re_path(
        r'^international/content/investment/opportunities/biomanufacturing-in-tees-valley/$',
        PermanentQuerystringRedirectView.as_view(
            url='/international/investment-opportunities/biomanufacturing-in-tees-valley/'
        ),
    ),
    re_path(
        r'^international/content/investment/opportunities/cam-modelling-and-simulation-in-oxfordshire/$',
        PermanentQuerystringRedirectView.as_view(
            url='/international/investment-opportunities/cam-modelling-and-simulation-in-oxfordshire/'
        ),
    ),
    re_path(
        r'^international/content/investment/opportunities/cell-and-gene-therapy-in-hertfordshire/$',
        PermanentQuerystringRedirectView.as_view(
            url='/international/investment-opportunities/cell-and-gene-therapy-in-hertfordshire/'
        ),
    ),
    re_path(
        r'^international/content/investment/opportunities/circular-economy-in-telford/$',
        PermanentQuerystringRedirectView.as_view(
            url='/international/investment-opportunities/circular-economy-in-telford/'
        ),
    ),
    re_path(
        r'^international/content/investment/opportunities/compound-semiconductors-and-applications-in-south-wales/$',
        PermanentQuerystringRedirectView.as_view(
            url='/international/investment-opportunities/compound-semiconductors-and-applications-in-south-wales/'
        ),
    ),
    re_path(
        r'^international/content/investment/opportunities/connected-and-immersive-technologies-for-future-mobility-in-coventry-and-warwickshire/$',  # noqa:E501
        PermanentQuerystringRedirectView.as_view(
            url='/international/investment-opportunities/connected-and-immersive-technologies-for-future-mobility-in-coventry-and-warwickshire/'  # noqa:E501
        ),
    ),
    re_path(
        r'^international/content/investment/opportunities/cyber-security-in-gloucestershire/$',
        PermanentQuerystringRedirectView.as_view(
            url='/international/investment-opportunities/cyber-security-in-gloucestershire/'
        ),
    ),
    re_path(
        r'^international/content/investment/opportunities/data-analytics-and-artificial-intelligence-applications-in-leeds-city-region/$',  # noqa:E501
        PermanentQuerystringRedirectView.as_view(
            url='/international/investment-opportunities/data-analytics-and-artificial-intelligence-applications-in-leeds-city-region/'  # noqa:E501
        ),
    ),
    re_path(
        r'^international/content/investment/opportunities/food-processing-automation-in-greater-lincolnshire/$',
        PermanentQuerystringRedirectView.as_view(
            url='/international/investment-opportunities/food-processing-automation-in-greater-lincolnshire/'
        ),
    ),
    re_path(
        r'^international/content/investment/opportunities/fusion-energy-in-oxfordshire/$',
        PermanentQuerystringRedirectView.as_view(
            url='/international/investment-opportunities/fusion-energy-in-oxfordshire/'
        ),
    ),
    re_path(
        r'^international/content/investment/opportunities/future-of-aerospace-northern-ireland/$',
        PermanentQuerystringRedirectView.as_view(
            url='/international/investment-opportunities/future-of-aerospace-northern-ireland/'
        ),
    ),
    re_path(
        r'^international/content/investment/opportunities/hydrogen-applications-in-thames-estuary/$',
        PermanentQuerystringRedirectView.as_view(
            url='/international/investment-opportunities/hydrogen-applications-in-thames-estuary/'
        ),
    ),
    re_path(
        r'^international/content/investment/opportunities/mining-in-cornwall/$',
        PermanentQuerystringRedirectView.as_view(url='/international/investment-opportunities/mining-in-cornwall/'),
    ),
    re_path(
        r'^international/content/investment/opportunities/net-zero-transport-in-coventry-and-warwickshire/$',
        PermanentQuerystringRedirectView.as_view(
            url='/international/investment-opportunities/net-zero-transport-in-coventry-and-warwickshire/'
        ),
    ),
    re_path(
        r'^international/content/investment/opportunities/nucleic-acid-therapies-in-oxfordshire/$',
        PermanentQuerystringRedirectView.as_view(
            url='/international/investment-opportunities/nucleic-acid-therapies-in-oxfordshire/'
        ),
    ),
    re_path(
        r'^international/content/investment/opportunities/offshore-wind-floating-substructures-in-scotland/$',
        PermanentQuerystringRedirectView.as_view(
            url='/international/investment-opportunities/offshore-wind-floating-substructures-in-scotland/'
        ),
    ),
    re_path(
        r'^international/content/investment/opportunities/plant-science-for-nutrition-in-norfolk-and-suffolk/$',
        PermanentQuerystringRedirectView.as_view(
            url='/international/investment-opportunities/plant-science-for-nutrition-in-norfolk-and-suffolk/'
        ),
    ),
    re_path(
        r'^international/content/investment/opportunities/precision-farming-in-telford/$',
        PermanentQuerystringRedirectView.as_view(
            url='/international/investment-opportunities/precision-farming-in-telford/'
        ),
    ),
    re_path(
        r'^international/content/investment/opportunities/rail-in-doncaster/$',
        PermanentQuerystringRedirectView.as_view(url='/international/investment-opportunities/rail-in-doncaster/'),
    ),
    re_path(
        r'^international/content/investment/opportunities/regtech-in-northern-ireland/$',
        PermanentQuerystringRedirectView.as_view(
            url='/international/investment-opportunities/regtech-in-northern-ireland/'
        ),
    ),
    re_path(
        r'^international/content/investment/opportunities/smart-and-sustainable-aviation-in-south-west-england/$',
        PermanentQuerystringRedirectView.as_view(
            url='/international/investment-opportunities/smart-and-sustainable-aviation-in-south-west-england/'
        ),
    ),
    re_path(
        r'^international/content/investment/opportunities/vaccine-development-and-manufacture-in-liverpool-city-region/$',  # noqa:E501
        PermanentQuerystringRedirectView.as_view(
            url='/international/investment-opportunities/vaccine-development-and-manufacture-in-liverpool-city-region/'
        ),
    ),
    re_path(
        r'^international/content/investment/opportunities/anglesey-freeport/$',
        PermanentQuerystringRedirectView.as_view(url='/international/investment-opportunities/anglesey-freeport/'),
    ),
    re_path(
        r'^international/content/investment/opportunities/celtic-freeport/$',
        PermanentQuerystringRedirectView.as_view(url='/international/investment-opportunities/celtic-freeport/'),
    ),
    re_path(
        r'^international/content/investment/opportunities/east-midlands-freeport/$',
        PermanentQuerystringRedirectView.as_view(url='/international/investment-opportunities/east-midlands-freeport/'),
    ),
    re_path(
        r'^international/content/investment/opportunities/forth-green-freeport/$',
        PermanentQuerystringRedirectView.as_view(url='/international/investment-opportunities/forth-green-freeport/'),
    ),
    re_path(
        r'^international/content/investment/opportunities/felixstowe-and-harwich-freeport/$',
        PermanentQuerystringRedirectView.as_view(
            url='/international/investment-opportunities/felixstowe-and-harwich-freeport/'
        ),
    ),
    re_path(
        r'^international/content/investment/opportunities/humber-freeport/$',
        PermanentQuerystringRedirectView.as_view(url='/international/investment-opportunities/humber-freeport/'),
    ),
    re_path(
        r'^international/content/investment/opportunities/inverness-and-cromarty-firth-green-freeport/$',
        PermanentQuerystringRedirectView.as_view(
            url='/international/investment-opportunities/inverness-and-cromarty-firth-green-freeport/'
        ),
    ),
    re_path(
        r'^international/content/investment/opportunities/liverpool-city-region-freeport/$',
        PermanentQuerystringRedirectView.as_view(
            url='/international/investment-opportunities/liverpool-city-region-freeport/'
        ),
    ),
    re_path(
        r'^international/content/investment/opportunities/plymouth-and-south-devon-freeport/$',
        PermanentQuerystringRedirectView.as_view(
            url='/international/investment-opportunities/plymouth-and-south-devon-freeport/'
        ),
    ),
    re_path(
        r'^international/content/investment/opportunities/solent/$',
        PermanentQuerystringRedirectView.as_view(url='/international/investment-opportunities/solent/'),
    ),
    re_path(
        r'^international/content/investment/opportunities/teesside-freeport/$',
        PermanentQuerystringRedirectView.as_view(url='/international/investment-opportunities/teesside-freeport/'),
    ),
    re_path(
        r'^international/content/investment/opportunities/thames-freeport/$',
        PermanentQuerystringRedirectView.as_view(url='/international/investment-opportunities/thames-freeport/'),
    ),
    re_path(
        r'^international/contact/$',
        PermanentQuerystringRedirectView.as_view(url='/international/site-help/'),
    ),
    re_path(
        r'^international/content/investment/how-we-can-help/global-entrepreneur-program/$',
        PermanentQuerystringRedirectView.as_view(url='/campaign-site/gep/'),
    ),
    re_path(
        r'^international/content/investment/how-we-can-help/the-venture-capital-unit/$',
        PermanentQuerystringRedirectView.as_view(url='/international/expand-business-in-the-uk/'),
    ),
    re_path(
        r'^international/content/investment/how-we-can-help/$',
        PermanentQuerystringRedirectView.as_view(url='/international/expand-business-in-the-uk/'),
    ),
    re_path(
        r'^international/content/investment/why-invest-in-the-uk/$',
        PermanentQuerystringRedirectView.as_view(url='/international/'),
    ),
    re_path(
        r'^international/content/investment/how-we-can-help/research-and-development-rd-support-in-the-uk/$',
        PermanentQuerystringRedirectView.as_view(url='/international/expand-business-in-the-uk/'),
    ),
    re_path(
        r'^international/trade/contact/$',
        PermanentQuerystringRedirectView.as_view(url='/international/'),
    ),
    re_path(
        r'^international/invest/contact/$',
        PermanentQuerystringRedirectView.as_view(url='/international/'),
    ),
    re_path(
        r'^international/content/investment/how-we-can-help/the-office-for-investment/$',
        PermanentQuerystringRedirectView.as_view(url='/international/'),
    ),
    re_path(
        r'^international/content/investment/how-we-can-help/hire-skilled-workers-for-your-uk-operations/$',
        PermanentQuerystringRedirectView.as_view(url='/international/expand-business-in-the-uk/'),
    ),
    re_path(
        r'^international/content/investment/how-we-can-help/access-finance-in-the-uk/$',
        PermanentQuerystringRedirectView.as_view(url='/international/expand-business-in-the-uk/'),
    ),
    re_path(
        r'^international/content/investment/how-we-can-help/establish-a-base-for-business-in-the-uk/$',
        PermanentQuerystringRedirectView.as_view(url='/international/expand-business-in-the-uk/'),
    ),
    re_path(
        r'^international/content/investment/how-we-can-help/register-a-company-in-the-uk/$',
        PermanentQuerystringRedirectView.as_view(url='/international/expand-business-in-the-uk/'),
    ),
    re_path(
        r'^international/content/investment/how-we-can-help/uk-visas-and-migration/$',
        PermanentQuerystringRedirectView.as_view(url='/international/expand-business-in-the-uk/'),
    ),
    re_path(
        r'^international/content/investment/how-we-can-help/open-a-uk-business-bank-account/$',
        PermanentQuerystringRedirectView.as_view(url='/international/expand-business-in-the-uk/'),
    ),
    re_path(
        r'^international/content/invest/how-to-setup-in-the-uk/.*$',
        PermanentQuerystringRedirectView.as_view(url='/international/expand-business-in-the-uk/'),
    ),
]

invest_in_uk_redirects = [
    re_path(
        r'^invest-in-uk/content/investment/why-invest-in-the-uk/uk-investment-zones/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/investment-opportunities/uk-investment-zones/'),
    ),
    re_path(
        r'^invest-in-uk/trade/search/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/buy-from-uk/find-a-supplier/'),
    ),
    re_path(
        r'^invest-in-uk/trade/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/buy-from-uk/'),
    ),
    re_path(
        r'^invest-in-uk/content/trade/how-we-help-you-buy/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/buy-from-uk/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/why-invest-in-the-uk/uk-investment-zones/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/investment-opportunities/uk-investment-zones/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/how-we-can-help/uk-tax-and-incentives/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/investment-opportunities/uk-tax-and-incentives/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/why-invest-in-the-uk/uk-talent-and-labour/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/investment-opportunities/uk-talent-and-labour/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/why-invest-in-the-uk/uk-innovation/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/investment-opportunities/uk-innovation/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/why-invest-in-the-uk/uk-infrastructure/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/investment-opportunities/uk-infrastructure/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/why-invest-in-the-uk/clean-growth-in-the-uk/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/investment-opportunities/clean-growth-in-the-uk/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/how-we-can-help/freeports-in-the-uk/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/investment-opportunities/freeports-in-the-uk/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/regions/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/investment-opportunities/regions/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/regions/wales/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/investment-opportunities/regions/wales/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/regions/south-england/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/investment-opportunities/regions/south-england/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/regions/northern-ireland/$',
        PermanentQuerystringRedirectView.as_view(
            url='/invest-in-uk/investment-opportunities/regions/northern-ireland/'
        ),
    ),
    re_path(
        r'^invest-in-uk/content/investment/regions/north-england/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/investment-opportunities/regions/north-england/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/regions/midlands/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/investment-opportunities/regions/midlands/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/regions/scotland/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/investment-opportunities/regions/scotland/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/sectors/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/investment-opportunities/sectors/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/sectors/aerospace-and-jet-zero/$',
        PermanentQuerystringRedirectView.as_view(
            url='/invest-in-uk/investment-opportunities/sectors/aerospace-and-jet-zero/'
        ),
    ),
    re_path(
        r'^invest-in-uk/content/investment/sectors/biopharmaceuticals/$',
        PermanentQuerystringRedirectView.as_view(
            url='/invest-in-uk/investment-opportunities/sectors/biopharmaceuticals/'
        ),
    ),
    re_path(
        r'^invest-in-uk/content/investment/sectors/carbon-capture-usage-and-storage/$',
        PermanentQuerystringRedirectView.as_view(
            url='/invest-in-uk/investment-opportunities/sectors/carbon-capture-usage-and-storage/'
        ),
    ),
    re_path(
        r'^invest-in-uk/content/investment/sectors/chemicals/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/investment-opportunities/sectors/chemicals/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/sectors/civil-nuclear/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/investment-opportunities/sectors/civil-nuclear/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/sectors/agri-tech/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/investment-opportunities/sectors/agri-tech/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/sectors/creative-industries/$',
        PermanentQuerystringRedirectView.as_view(
            url='/invest-in-uk/investment-opportunities/sectors/creative-industries/'
        ),
    ),
    re_path(
        r'^invest-in-uk/content/investment/sectors/cyber-security/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/investment-opportunities/sectors/cyber-security/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/sectors/edtech/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/investment-opportunities/sectors/edtech/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/sectors/financial-services/$',
        PermanentQuerystringRedirectView.as_view(
            url='/invest-in-uk/investment-opportunities/sectors/financial-services/'
        ),
    ),
    re_path(
        r'^invest-in-uk/content/investment/sectors/fintech/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/investment-opportunities/sectors/fintech/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/sectors/food-and-drink/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/investment-opportunities/sectors/food-and-drink/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/sectors/precision-medicine/$',
        PermanentQuerystringRedirectView.as_view(
            url='/invest-in-uk/investment-opportunities/sectors/precision-medicine/'
        ),
    ),
    re_path(
        r'^invest-in-uk/content/investment/sectors/green-shipping/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/investment-opportunities/sectors/green-shipping/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/sectors/green-finance/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/investment-opportunities/sectors/green-finance/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/sectors/greener-buildings/$',
        PermanentQuerystringRedirectView.as_view(
            url='/invest-in-uk/investment-opportunities/sectors/greener-buildings/'
        ),
    ),
    re_path(
        r'^invest-in-uk/content/investment/sectors/healthcare-and-life-sciences/$',
        PermanentQuerystringRedirectView.as_view(
            url='/invest-in-uk/investment-opportunities/sectors/healthcare-and-life-sciences/'
        ),
    ),
    re_path(
        r'^invest-in-uk/content/investment/sectors/hydrogen/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/investment-opportunities/sectors/hydrogen/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/sectors/medtech/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/investment-opportunities/sectors/medtech/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/sectors/mineral-extraction-and-refining/$',
        PermanentQuerystringRedirectView.as_view(
            url='/invest-in-uk/investment-opportunities/sectors/mineral-extraction-and-refining/'
        ),
    ),
    re_path(
        r'^invest-in-uk/content/investment/sectors/offshore-wind/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/investment-opportunities/sectors/offshore-wind/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/sectors/professional-and-business-services/$',
        PermanentQuerystringRedirectView.as_view(
            url='/invest-in-uk/investment-opportunities/sectors/professional-and-business-services/'
        ),
    ),
    re_path(
        r'^invest-in-uk/content/investment/sectors/real-estate/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/investment-opportunities/sectors/real-estate/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/sectors/retail/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/investment-opportunities/sectors/retail/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/sectors/space/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/investment-opportunities/sectors/space/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/sectors/sports-economy/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/investment-opportunities/sectors/sports-economy/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/sectors/sustainable-infrastructure/$',
        PermanentQuerystringRedirectView.as_view(
            url='/invest-in-uk/investment-opportunities/sectors/sustainable-infrastructure/'
        ),
    ),
    re_path(
        r'^invest-in-uk/content/investment/sectors/technology/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/investment-opportunities/sectors/technology/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/sectors/oil-and-gas/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/investment-opportunities/sectors/oil-and-gas/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/sectors/zero-emission-vehicles/$',
        PermanentQuerystringRedirectView.as_view(
            url='/invest-in-uk/investment-opportunities/sectors/zero-emission-vehicles/'
        ),
    ),
    re_path(
        r'^invest-in-uk/content/investment/opportunities/accelerated-electrification-transition-in-the-north-east-of-england/$',  # noqa:E501
        PermanentQuerystringRedirectView.as_view(
            url='/invest-in-uk/investment-opportunities/accelerated-electrification-transition-in-the-north-east-of-england/'  # noqa:E501
        ),
    ),
    re_path(
        r'^invest-in-uk/content/investment/opportunities/5g-and-digitisation-in-norfolk-and-suffolk-east-of-england/$',
        PermanentQuerystringRedirectView.as_view(
            url='/invest-in-uk/investment-opportunities/5g-and-digitisation-in-norfolk-and-suffolk-east-of-england/'
        ),
    ),
    re_path(
        r'^invest-in-uk/content/investment/opportunities/biomanufacturing-in-tees-valley/$',
        PermanentQuerystringRedirectView.as_view(
            url='/invest-in-uk/investment-opportunities/biomanufacturing-in-tees-valley/'
        ),
    ),
    re_path(
        r'^invest-in-uk/content/investment/opportunities/cam-modelling-and-simulation-in-oxfordshire/$',
        PermanentQuerystringRedirectView.as_view(
            url='/invest-in-uk/investment-opportunities/cam-modelling-and-simulation-in-oxfordshire/'
        ),
    ),
    re_path(
        r'^invest-in-uk/content/investment/opportunities/cell-and-gene-therapy-in-hertfordshire/$',
        PermanentQuerystringRedirectView.as_view(
            url='/invest-in-uk/investment-opportunities/cell-and-gene-therapy-in-hertfordshire/'
        ),
    ),
    re_path(
        r'^invest-in-uk/content/investment/opportunities/circular-economy-in-telford/$',
        PermanentQuerystringRedirectView.as_view(
            url='/invest-in-uk/investment-opportunities/circular-economy-in-telford/'
        ),
    ),
    re_path(
        r'^invest-in-uk/content/investment/opportunities/compound-semiconductors-and-applications-in-south-wales/$',
        PermanentQuerystringRedirectView.as_view(
            url='/invest-in-uk/investment-opportunities/compound-semiconductors-and-applications-in-south-wales/'
        ),
    ),
    re_path(
        r'^invest-in-uk/content/investment/opportunities/connected-and-immersive-technologies-for-future-mobility-in-coventry-and-warwickshire/$',  # noqa:E501
        PermanentQuerystringRedirectView.as_view(
            url='/invest-in-uk/investment-opportunities/connected-and-immersive-technologies-for-future-mobility-in-coventry-and-warwickshire/'  # noqa:E501
        ),
    ),
    re_path(
        r'^invest-in-uk/content/investment/opportunities/cyber-security-in-gloucestershire/$',
        PermanentQuerystringRedirectView.as_view(
            url='/invest-in-uk/investment-opportunities/cyber-security-in-gloucestershire/'
        ),
    ),
    re_path(
        r'^invest-in-uk/content/investment/opportunities/data-analytics-and-artificial-intelligence-applications-in-leeds-city-region/$',  # noqa:E501
        PermanentQuerystringRedirectView.as_view(
            url='/invest-in-uk/investment-opportunities/data-analytics-and-artificial-intelligence-applications-in-leeds-city-region/'  # noqa:E501
        ),
    ),
    re_path(
        r'^invest-in-uk/content/investment/opportunities/food-processing-automation-in-greater-lincolnshire/$',
        PermanentQuerystringRedirectView.as_view(
            url='/invest-in-uk/investment-opportunities/food-processing-automation-in-greater-lincolnshire/'
        ),
    ),
    re_path(
        r'^invest-in-uk/content/investment/opportunities/fusion-energy-in-oxfordshire/$',
        PermanentQuerystringRedirectView.as_view(
            url='/invest-in-uk/investment-opportunities/fusion-energy-in-oxfordshire/'
        ),
    ),
    re_path(
        r'^invest-in-uk/content/investment/opportunities/future-of-aerospace-northern-ireland/$',
        PermanentQuerystringRedirectView.as_view(
            url='/invest-in-uk/investment-opportunities/future-of-aerospace-northern-ireland/'
        ),
    ),
    re_path(
        r'^invest-in-uk/content/investment/opportunities/hydrogen-applications-in-thames-estuary/$',
        PermanentQuerystringRedirectView.as_view(
            url='/invest-in-uk/investment-opportunities/hydrogen-applications-in-thames-estuary/'
        ),
    ),
    re_path(
        r'^invest-in-uk/content/investment/opportunities/mining-in-cornwall/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/investment-opportunities/mining-in-cornwall/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/opportunities/net-zero-transport-in-coventry-and-warwickshire/$',
        PermanentQuerystringRedirectView.as_view(
            url='/invest-in-uk/investment-opportunities/net-zero-transport-in-coventry-and-warwickshire/'
        ),
    ),
    re_path(
        r'^invest-in-uk/content/investment/opportunities/nucleic-acid-therapies-in-oxfordshire/$',
        PermanentQuerystringRedirectView.as_view(
            url='/invest-in-uk/investment-opportunities/nucleic-acid-therapies-in-oxfordshire/'
        ),
    ),
    re_path(
        r'^invest-in-uk/content/investment/opportunities/offshore-wind-floating-substructures-in-scotland/$',
        PermanentQuerystringRedirectView.as_view(
            url='/invest-in-uk/investment-opportunities/offshore-wind-floating-substructures-in-scotland/'
        ),
    ),
    re_path(
        r'^invest-in-uk/content/investment/opportunities/plant-science-for-nutrition-in-norfolk-and-suffolk/$',
        PermanentQuerystringRedirectView.as_view(
            url='/invest-in-uk/investment-opportunities/plant-science-for-nutrition-in-norfolk-and-suffolk/'
        ),
    ),
    re_path(
        r'^invest-in-uk/content/investment/opportunities/precision-farming-in-telford/$',
        PermanentQuerystringRedirectView.as_view(
            url='/invest-in-uk/investment-opportunities/precision-farming-in-telford/'
        ),
    ),
    re_path(
        r'^invest-in-uk/content/investment/opportunities/rail-in-doncaster/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/investment-opportunities/rail-in-doncaster/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/opportunities/regtech-in-northern-ireland/$',
        PermanentQuerystringRedirectView.as_view(
            url='/invest-in-uk/investment-opportunities/regtech-in-northern-ireland/'
        ),
    ),
    re_path(
        r'^invest-in-uk/content/investment/opportunities/smart-and-sustainable-aviation-in-south-west-england/$',
        PermanentQuerystringRedirectView.as_view(
            url='/invest-in-uk/investment-opportunities/smart-and-sustainable-aviation-in-south-west-england/'
        ),
    ),
    re_path(
        r'^invest-in-uk/content/investment/opportunities/vaccine-development-and-manufacture-in-liverpool-city-region/$',  # noqa:E501
        PermanentQuerystringRedirectView.as_view(
            url='/invest-in-uk/investment-opportunities/vaccine-development-and-manufacture-in-liverpool-city-region/'
        ),
    ),
    re_path(
        r'^invest-in-uk/content/investment/opportunities/anglesey-freeport/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/investment-opportunities/anglesey-freeport/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/opportunities/celtic-freeport/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/investment-opportunities/celtic-freeport/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/opportunities/east-midlands-freeport/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/investment-opportunities/east-midlands-freeport/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/opportunities/forth-green-freeport/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/investment-opportunities/forth-green-freeport/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/opportunities/felixstowe-and-harwich-freeport/$',
        PermanentQuerystringRedirectView.as_view(
            url='/invest-in-uk/investment-opportunities/felixstowe-and-harwich-freeport/'
        ),
    ),
    re_path(
        r'^invest-in-uk/content/investment/opportunities/humber-freeport/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/investment-opportunities/humber-freeport/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/opportunities/inverness-and-cromarty-firth-green-freeport/$',
        PermanentQuerystringRedirectView.as_view(
            url='/invest-in-uk/investment-opportunities/inverness-and-cromarty-firth-green-freeport/'
        ),
    ),
    re_path(
        r'^invest-in-uk/content/investment/opportunities/liverpool-city-region-freeport/$',
        PermanentQuerystringRedirectView.as_view(
            url='/invest-in-uk/investment-opportunities/liverpool-city-region-freeport/'
        ),
    ),
    re_path(
        r'^invest-in-uk/content/investment/opportunities/plymouth-and-south-devon-freeport/$',
        PermanentQuerystringRedirectView.as_view(
            url='/invest-in-uk/investment-opportunities/plymouth-and-south-devon-freeport/'
        ),
    ),
    re_path(
        r'^invest-in-uk/content/investment/opportunities/solent/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/investment-opportunities/solent/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/opportunities/teesside-freeport/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/investment-opportunities/teesside-freeport/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/opportunities/thames-freeport/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/investment-opportunities/thames-freeport/'),
    ),
    re_path(
        r'^invest-in-uk/contact/$',
        PermanentQuerystringRedirectView.as_view(url='/get-help/'),
    ),
    re_path(
        r'^invest-in-uk/site-help/$',
        PermanentQuerystringRedirectView.as_view(url='/get-help/'),
    ),
    re_path(
        r'^invest-in-uk/site-help/success/$',
        PermanentQuerystringRedirectView.as_view(url='/get-help/sent/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/how-we-can-help/global-entrepreneur-program/$',
        PermanentQuerystringRedirectView.as_view(url='/campaign-site/gep/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/how-we-can-help/the-venture-capital-unit/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/expand-business-in-the-uk/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/how-we-can-help/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/expand-business-in-the-uk/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/why-invest-in-the-uk/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/how-we-can-help/research-and-development-rd-support-in-the-uk/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/expand-business-in-the-uk/'),
    ),
    re_path(
        r'^invest-in-uk/trade/contact/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/'),
    ),
    re_path(
        r'^invest-in-uk/invest/contact/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/how-we-can-help/the-office-for-investment/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/how-we-can-help/hire-skilled-workers-for-your-uk-operations/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/expand-business-in-the-uk/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/how-we-can-help/access-finance-in-the-uk/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/expand-business-in-the-uk/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/how-we-can-help/establish-a-base-for-business-in-the-uk/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/expand-business-in-the-uk/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/how-we-can-help/register-a-company-in-the-uk/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/expand-business-in-the-uk/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/how-we-can-help/uk-visas-and-migration/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/expand-business-in-the-uk/'),
    ),
    re_path(
        r'^invest-in-uk/content/investment/how-we-can-help/open-a-uk-business-bank-account/$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/expand-business-in-the-uk/'),
    ),
    re_path(
        r'^invest-in-uk/content/invest/how-to-setup-in-the-uk/.*$',
        PermanentQuerystringRedirectView.as_view(url='/invest-in-uk/expand-business-in-the-uk/'),
    ),
]
