# Generated by Django 4.2.20 on 2025-05-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international_buy_from_the_uk', '0002_remove_buyfromtheukindexpage_struct_org_actions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyfromtheukindexpage',
            name='meta_robots_nofollow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buyfromtheukindexpage',
            name='meta_robots_noindex',
            field=models.BooleanField(default=False),
        ),
    ]
