# Generated by Django 2.2.9 on 2020-01-27 14:55

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models

import core.mixins


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomesticHomePage',
            fields=[
                (
                    'page_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='wagtailcore.Page',
                    ),
                ),
                (
                    'hero',
                    wagtail.fields.StreamField(
                        [
                            (
                                'hero',
                                wagtail.blocks.StructBlock(
                                    [
                                        ('text', wagtail.blocks.RichTextBlock()),
                                        ('url', wagtail.blocks.CharBlock(max_length=255, required=False)),
                                        ('image', wagtail.images.blocks.ImageChooserBlock()),
                                    ]
                                ),
                            )
                        ],
                        use_json_field=True,
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    'market_access_db',
                    wagtail.fields.StreamField(
                        [
                            (
                                'market_access_db',
                                wagtail.blocks.StructBlock(
                                    [
                                        ('text', wagtail.blocks.CharBlock(max_length=255, required=False)),
                                        ('url', wagtail.blocks.CharBlock(max_length=255, required=False)),
                                        (
                                            'source',
                                            wagtail.blocks.CharBlock(
                                                help_text='The source or the type of the link, e.g. GOV.UK/Advice'
                                            ),
                                        ),
                                        ('content', wagtail.blocks.RichTextBlock()),
                                        ('image', wagtail.images.blocks.ImageChooserBlock()),
                                        ('title', wagtail.blocks.CharBlock()),
                                    ]
                                ),
                            )
                        ],
                        use_json_field=True,
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    'campaign',
                    wagtail.fields.StreamField(
                        [
                            (
                                'campaign',
                                wagtail.blocks.StructBlock(
                                    [
                                        ('text', wagtail.blocks.CharBlock(max_length=255, required=False)),
                                        ('url', wagtail.blocks.CharBlock(max_length=255, required=False)),
                                        ('heading', wagtail.blocks.CharBlock()),
                                        ('subheading', wagtail.blocks.CharBlock()),
                                        ('image', wagtail.images.blocks.ImageChooserBlock()),
                                    ]
                                ),
                            )
                        ],
                        use_json_field=True,
                        blank=True,
                        null=True,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
            bases=(core.mixins.WagtailAdminExclusivePageMixin, 'wagtailcore.page'),
        ),
    ]
