# Generated by Django 2.2.10 on 2020-05-04 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domestic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domestichomepage',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='domestichomepage',
            name='hero',
        ),
        migrations.RemoveField(
            model_name='domestichomepage',
            name='market_access_db',
        ),
    ]
