# Generated by Django 2.2.14 on 2020-07-24 08:31

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0016_detailpage_estimated_read_duration'),
        ('domestic', '0002_auto_20200504_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='domestichomepage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domestichomepage',
            name='button',
            field=wagtail.fields.StreamField(
                [
                    (
                        'button',
                        wagtail.blocks.StructBlock(
                            [
                                ('label', wagtail.blocks.CharBlock(max_length=255)),
                                (
                                    'link',
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                'internal_link',
                                                wagtail.blocks.PageChooserBlock(label='Internal link', required=False),
                                            ),
                                            (
                                                'external_link',
                                                wagtail.blocks.CharBlock(
                                                    label='External link', max_length=255, required=False
                                                ),
                                            ),
                                        ],
                                        required=False,
                                    ),
                                ),
                            ],
                            icon='cog',
                        ),
                    )
                ],
                use_json_field=True,
                blank=True,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='domestichomepage',
            name='image',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='core.AltTextImage',
            ),
        ),
    ]
