# Generated by Django 2.2.14 on 2020-07-24 13:47

import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
from django.db import migrations, models

import core.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('core', '0016_detailpage_estimated_read_duration'),
        ('domestic', '0003_auto_20200724_0831'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomesticDashboard',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('routes', wagtail.core.fields.StreamField([('route', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=255)), ('body', wagtail.core.blocks.TextBlock(max_length=4096)), ('image', wagtail.images.blocks.ImageChooserBlock()), ('button', wagtail.core.blocks.StructBlock([('label', wagtail.core.blocks.CharBlock(max_length=255)), ('link', wagtail.core.blocks.StructBlock([('internal_link', wagtail.core.blocks.PageChooserBlock(label='Internal link', required=False)), ('external_link', wagtail.core.blocks.CharBlock(label='External link', max_length=255, required=False))], required=False))], icon='cog'))], icon='cog'))], blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(core.mixins.WagtailAdminExclusivePageMixin, core.mixins.EnableTourMixin, core.mixins.AnonymousUserRequired, 'wagtailcore.page'),
        ),
    ]
