# Generated by Django 2.2.14 on 2020-08-07 10:19

from django.db import migrations

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ('domestic', '0004_domesticdashboard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domesticdashboard',
            name='routes',
        ),
        migrations.AddField(
            model_name='domesticdashboard',
            name='components',
            field=wagtail.fields.StreamField(
                [
                    (
                        'route',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'route_type',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ('learn', 'Learning'),
                                            ('plan', 'Export plan'),
                                            ('target', 'Target market'),
                                        ],
                                        icon='redirect',
                                    ),
                                ),
                                ('title', wagtail.blocks.CharBlock(max_length=255)),
                                ('body', wagtail.blocks.TextBlock(max_length=4096)),
                                ('image', wagtail.images.blocks.ImageChooserBlock()),
                                (
                                    'button',
                                    wagtail.blocks.StructBlock(
                                        [
                                            ('label', wagtail.blocks.CharBlock(max_length=255)),
                                            (
                                                'link',
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            'internal_link',
                                                            wagtail.blocks.PageChooserBlock(
                                                                label='Internal link', required=False
                                                            ),
                                                        ),
                                                        (
                                                            'external_link',
                                                            wagtail.blocks.CharBlock(
                                                                label='External link', max_length=255, required=False
                                                            ),
                                                        ),
                                                    ],
                                                    required=False,
                                                ),
                                            ),
                                        ],
                                        icon='cog',
                                        required=False,
                                    ),
                                ),
                            ],
                            icon='pick',
                        ),
                    )
                ],
                use_json_field=True,
                blank=True,
                null=True,
            ),
        ),
    ]
