# Generated by Django 2.2.14 on 2021-01-11 12:14

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models

import core.fields
import domestic.cms_panels


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        ('core', '0046_add_v1_snippet_models'),
        ('wagtailmedia', '0003_copy_media_permissions_to_collections'),
        ('domestic', '0005_auto_20200807_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlePage',
            fields=[
                (
                    'page_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='wagtailcore.Page',
                    ),
                ),
                (
                    'type_of_article',
                    models.TextField(
                        choices=[
                            ('Blog', 'Blog'),
                            ('Advice', 'Advice'),
                            ('Case study', 'Case study'),
                            ('Campaign', 'Campaign'),
                        ],
                        null=True,
                        blank=True,
                    ),
                ),
                ('article_title', models.TextField()),
                (
                    'article_subheading',
                    models.TextField(
                        blank=True,
                        help_text='This is a subheading that displays below the main title on the article page',
                    ),
                ),
                (
                    'article_teaser',
                    models.TextField(
                        blank=True,
                        help_text='This is a subheading that displays when the article is featured on another page',
                        null=True,
                    ),
                ),
                (
                    'article_video_transcript',
                    core.fields.MarkdownField(
                        blank=True, help_text='If the video is present, a transcript must be provided.', null=True
                    ),
                ),
                ('article_body_text', core.fields.MarkdownField()),
                ('cta_title', models.CharField(blank=True, max_length=255, verbose_name='CTA title')),
                ('cta_teaser', models.TextField(blank=True, verbose_name='CTA teaser')),
                ('cta_link_label', models.CharField(blank=True, max_length=255, verbose_name='CTA link label')),
                ('cta_link', models.CharField(blank=True, max_length=255, verbose_name='CTA link')),
                (
                    'article_image',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='core.AltTextImage',
                    ),
                ),
                (
                    'article_video',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='wagtailmedia.Media',
                    ),
                ),
                (
                    'related_page_one',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='domestic.ArticlePage',
                    ),
                ),
                (
                    'related_page_three',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='domestic.ArticlePage',
                    ),
                ),
                (
                    'related_page_two',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='domestic.ArticlePage',
                    ),
                ),
                ('tags', modelcluster.fields.ParentalManyToManyField(blank=True, to='core.Tag')),
            ],
            options={
                'abstract': False,
            },
            bases=(domestic.cms_panels.ArticlePagePanels, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='CountryGuidePage',
            fields=[
                (
                    'page_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='wagtailcore.Page',
                    ),
                ),
                (
                    'heading',
                    models.CharField(
                        help_text='Only enter the country name', max_length=255, verbose_name='Country name'
                    ),
                ),
                ('sub_heading', models.CharField(blank=True, max_length=255)),
                ('heading_teaser', models.TextField(blank=True, verbose_name='Introduction')),
                ('intro_cta_one_title', models.CharField(blank=True, max_length=500, verbose_name='CTA 1 title')),
                ('intro_cta_one_link', models.CharField(blank=True, max_length=500, verbose_name='CTA 1 link')),
                ('intro_cta_two_title', models.CharField(blank=True, max_length=500, verbose_name='CTA 2 title')),
                ('intro_cta_two_link', models.CharField(blank=True, max_length=500, verbose_name='CTA 2 link')),
                ('intro_cta_three_title', models.CharField(blank=True, max_length=500, verbose_name='CTA 3 title')),
                ('intro_cta_three_link', models.CharField(blank=True, max_length=500, verbose_name='CTA 3 link')),
                (
                    'section_one_body',
                    core.fields.MarkdownField(
                        help_text='Use H3 (###) markdown for the 3 subheadings',
                        null=True,
                        verbose_name='3 unique selling points markdown',
                    ),
                ),
                (
                    'section_one_image_caption',
                    models.CharField(blank=True, max_length=255, verbose_name='Bullets image caption'),
                ),
                (
                    'section_one_image_caption_company',
                    models.CharField(blank=True, max_length=255, verbose_name='Bullets image caption — company name'),
                ),
                ('statistic_1_number', models.CharField(max_length=255)),
                ('statistic_1_heading', models.CharField(max_length=255)),
                ('statistic_1_smallprint', models.CharField(blank=True, max_length=255)),
                ('statistic_2_number', models.CharField(max_length=255)),
                ('statistic_2_heading', models.CharField(max_length=255)),
                ('statistic_2_smallprint', models.CharField(blank=True, max_length=255)),
                ('statistic_3_number', models.CharField(blank=True, max_length=255)),
                ('statistic_3_heading', models.CharField(blank=True, max_length=255)),
                ('statistic_3_smallprint', models.CharField(blank=True, max_length=255)),
                ('statistic_4_number', models.CharField(blank=True, max_length=255)),
                ('statistic_4_heading', models.CharField(blank=True, max_length=255)),
                ('statistic_4_smallprint', models.CharField(blank=True, max_length=255)),
                ('statistic_5_number', models.CharField(blank=True, max_length=255)),
                ('statistic_5_heading', models.CharField(blank=True, max_length=255)),
                ('statistic_5_smallprint', models.CharField(blank=True, max_length=255)),
                ('statistic_6_number', models.CharField(blank=True, max_length=255)),
                ('statistic_6_heading', models.CharField(blank=True, max_length=255)),
                ('statistic_6_smallprint', models.CharField(blank=True, max_length=255)),
                (
                    'section_two_heading',
                    models.CharField(
                        blank=True, max_length=255, verbose_name='High potential industries for UK businesses'
                    ),
                ),
                (
                    'section_two_teaser',
                    models.TextField(blank=True, verbose_name='Summary of the industry opportunities'),
                ),
                ('accordion_1_title', models.CharField(blank=True, max_length=255, verbose_name='Industry title')),
                ('accordion_1_teaser', models.TextField(blank=True, verbose_name='Industry teaser')),
                (
                    'accordion_1_subsection_1_heading',
                    models.CharField(blank=True, max_length=255, verbose_name='Subsection 1 heading'),
                ),
                ('accordion_1_subsection_1_body', models.TextField(blank=True, verbose_name='Subsection 1 body')),
                (
                    'accordion_1_subsection_2_heading',
                    models.CharField(blank=True, max_length=255, verbose_name='Subsection 2 heading'),
                ),
                ('accordion_1_subsection_2_body', models.TextField(blank=True, verbose_name='Subsection 2 body')),
                (
                    'accordion_1_subsection_3_heading',
                    models.CharField(blank=True, max_length=255, verbose_name='Subsection 2 heading'),
                ),
                ('accordion_1_subsection_3_body', models.TextField(blank=True, verbose_name='Subsection 2 body')),
                (
                    'accordion_1_case_study_button_text',
                    models.CharField(blank=True, max_length=255, verbose_name='Case study button text'),
                ),
                (
                    'accordion_1_case_study_button_link',
                    models.CharField(blank=True, max_length=255, verbose_name='Case study button link'),
                ),
                (
                    'accordion_1_case_study_title',
                    models.CharField(blank=True, max_length=255, verbose_name='Case study title'),
                ),
                (
                    'accordion_1_case_study_description',
                    models.CharField(blank=True, max_length=255, verbose_name='Case study description'),
                ),
                (
                    'accordion_1_statistic_1_number',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 1 number'),
                ),
                (
                    'accordion_1_statistic_1_heading',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 1 heading'),
                ),
                (
                    'accordion_1_statistic_1_smallprint',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 1 smallprint'),
                ),
                (
                    'accordion_1_statistic_2_number',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 2 number'),
                ),
                (
                    'accordion_1_statistic_2_heading',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 2 heading'),
                ),
                (
                    'accordion_1_statistic_2_smallprint',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 2 smallprint'),
                ),
                (
                    'accordion_1_statistic_3_number',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 3 number'),
                ),
                (
                    'accordion_1_statistic_3_heading',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 3 heading'),
                ),
                (
                    'accordion_1_statistic_3_smallprint',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 3 smallprint'),
                ),
                (
                    'accordion_1_statistic_4_number',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 4 number'),
                ),
                (
                    'accordion_1_statistic_4_heading',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 4 heading'),
                ),
                (
                    'accordion_1_statistic_4_smallprint',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 4 smallprint'),
                ),
                (
                    'accordion_1_statistic_5_number',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 5 number'),
                ),
                (
                    'accordion_1_statistic_5_heading',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 5 heading'),
                ),
                (
                    'accordion_1_statistic_5_smallprint',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 5 smallprint'),
                ),
                (
                    'accordion_1_statistic_6_number',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 6 number'),
                ),
                (
                    'accordion_1_statistic_6_heading',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 6 heading'),
                ),
                (
                    'accordion_1_statistic_6_smallprint',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 6 smallprint'),
                ),
                ('accordion_2_title', models.CharField(blank=True, max_length=255, verbose_name='Industry title')),
                ('accordion_2_teaser', models.TextField(blank=True, verbose_name='Industry teaser')),
                (
                    'accordion_2_subsection_1_heading',
                    models.CharField(blank=True, max_length=255, verbose_name='Subsection 1 heading'),
                ),
                ('accordion_2_subsection_1_body', models.TextField(blank=True, verbose_name='Subsection 1 body')),
                (
                    'accordion_2_subsection_2_heading',
                    models.CharField(blank=True, max_length=255, verbose_name='Subsection 2 heading'),
                ),
                ('accordion_2_subsection_2_body', models.TextField(blank=True, verbose_name='Subsection 2 body')),
                (
                    'accordion_2_subsection_3_heading',
                    models.CharField(blank=True, max_length=255, verbose_name='Subsection 2 heading'),
                ),
                ('accordion_2_subsection_3_body', models.TextField(blank=True, verbose_name='Subsection 2 body')),
                (
                    'accordion_2_case_study_button_text',
                    models.CharField(blank=True, max_length=255, verbose_name='Case study button text'),
                ),
                (
                    'accordion_2_case_study_button_link',
                    models.CharField(blank=True, max_length=255, verbose_name='Case study button link'),
                ),
                (
                    'accordion_2_case_study_title',
                    models.CharField(blank=True, max_length=255, verbose_name='Case study title'),
                ),
                (
                    'accordion_2_case_study_description',
                    models.CharField(blank=True, max_length=255, verbose_name='Case study description'),
                ),
                (
                    'accordion_2_statistic_1_number',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 1 number'),
                ),
                (
                    'accordion_2_statistic_1_heading',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 1 heading'),
                ),
                (
                    'accordion_2_statistic_1_smallprint',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 1 smallprint'),
                ),
                (
                    'accordion_2_statistic_2_number',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 2 number'),
                ),
                (
                    'accordion_2_statistic_2_heading',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 2 heading'),
                ),
                (
                    'accordion_2_statistic_2_smallprint',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 2 smallprint'),
                ),
                (
                    'accordion_2_statistic_3_number',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 3 number'),
                ),
                (
                    'accordion_2_statistic_3_heading',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 3 heading'),
                ),
                (
                    'accordion_2_statistic_3_smallprint',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 3 smallprint'),
                ),
                (
                    'accordion_2_statistic_4_number',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 4 number'),
                ),
                (
                    'accordion_2_statistic_4_heading',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 4 heading'),
                ),
                (
                    'accordion_2_statistic_4_smallprint',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 4 smallprint'),
                ),
                (
                    'accordion_2_statistic_5_number',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 5 number'),
                ),
                (
                    'accordion_2_statistic_5_heading',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 5 heading'),
                ),
                (
                    'accordion_2_statistic_5_smallprint',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 5 smallprint'),
                ),
                (
                    'accordion_2_statistic_6_number',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 6 number'),
                ),
                (
                    'accordion_2_statistic_6_heading',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 6 heading'),
                ),
                (
                    'accordion_2_statistic_6_smallprint',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 6 smallprint'),
                ),
                ('accordion_3_title', models.CharField(blank=True, max_length=255, verbose_name='Industry title')),
                ('accordion_3_teaser', models.TextField(blank=True, verbose_name='Industry teaser')),
                (
                    'accordion_3_subsection_1_heading',
                    models.CharField(blank=True, max_length=255, verbose_name='Subsection 1 heading'),
                ),
                ('accordion_3_subsection_1_body', models.TextField(blank=True, verbose_name='Subsection 1 body')),
                (
                    'accordion_3_subsection_2_heading',
                    models.CharField(blank=True, max_length=255, verbose_name='Subsection 2 heading'),
                ),
                ('accordion_3_subsection_2_body', models.TextField(blank=True, verbose_name='Subsection 2 body')),
                (
                    'accordion_3_subsection_3_heading',
                    models.CharField(blank=True, max_length=255, verbose_name='Subsection 2 heading'),
                ),
                ('accordion_3_subsection_3_body', models.TextField(blank=True, verbose_name='Subsection 2 body')),
                (
                    'accordion_3_case_study_button_text',
                    models.CharField(blank=True, max_length=255, verbose_name='Case study button text'),
                ),
                (
                    'accordion_3_case_study_button_link',
                    models.CharField(blank=True, max_length=255, verbose_name='Case study button link'),
                ),
                (
                    'accordion_3_case_study_title',
                    models.CharField(blank=True, max_length=255, verbose_name='Case study title'),
                ),
                (
                    'accordion_3_case_study_description',
                    models.CharField(blank=True, max_length=255, verbose_name='Case study description'),
                ),
                (
                    'accordion_3_statistic_1_number',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 1 number'),
                ),
                (
                    'accordion_3_statistic_1_heading',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 1 heading'),
                ),
                (
                    'accordion_3_statistic_1_smallprint',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 1 smallprint'),
                ),
                (
                    'accordion_3_statistic_2_number',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 2 number'),
                ),
                (
                    'accordion_3_statistic_2_heading',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 2 heading'),
                ),
                (
                    'accordion_3_statistic_2_smallprint',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 2 smallprint'),
                ),
                (
                    'accordion_3_statistic_3_number',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 3 number'),
                ),
                (
                    'accordion_3_statistic_3_heading',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 3 heading'),
                ),
                (
                    'accordion_3_statistic_3_smallprint',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 3 smallprint'),
                ),
                (
                    'accordion_3_statistic_4_number',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 4 number'),
                ),
                (
                    'accordion_3_statistic_4_heading',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 4 heading'),
                ),
                (
                    'accordion_3_statistic_4_smallprint',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 4 smallprint'),
                ),
                (
                    'accordion_3_statistic_5_number',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 5 number'),
                ),
                (
                    'accordion_3_statistic_5_heading',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 5 heading'),
                ),
                (
                    'accordion_3_statistic_5_smallprint',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 5 smallprint'),
                ),
                (
                    'accordion_3_statistic_6_number',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 6 number'),
                ),
                (
                    'accordion_3_statistic_6_heading',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 6 heading'),
                ),
                (
                    'accordion_3_statistic_6_smallprint',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 6 smallprint'),
                ),
                ('accordion_4_title', models.CharField(blank=True, max_length=255, verbose_name='Industry title')),
                ('accordion_4_teaser', models.TextField(blank=True, verbose_name='Industry teaser')),
                (
                    'accordion_4_subsection_1_heading',
                    models.CharField(blank=True, max_length=255, verbose_name='Subsection 1 heading'),
                ),
                ('accordion_4_subsection_1_body', models.TextField(blank=True, verbose_name='Subsection 1 body')),
                (
                    'accordion_4_subsection_2_heading',
                    models.CharField(blank=True, max_length=255, verbose_name='Subsection 2 heading'),
                ),
                ('accordion_4_subsection_2_body', models.TextField(blank=True, verbose_name='Subsection 2 body')),
                (
                    'accordion_4_subsection_3_heading',
                    models.CharField(blank=True, max_length=255, verbose_name='Subsection 2 heading'),
                ),
                ('accordion_4_subsection_3_body', models.TextField(blank=True, verbose_name='Subsection 2 body')),
                (
                    'accordion_4_case_study_button_text',
                    models.CharField(blank=True, max_length=255, verbose_name='Case study button text'),
                ),
                (
                    'accordion_4_case_study_button_link',
                    models.CharField(blank=True, max_length=255, verbose_name='Case study button link'),
                ),
                (
                    'accordion_4_case_study_title',
                    models.CharField(blank=True, max_length=255, verbose_name='Case study title'),
                ),
                (
                    'accordion_4_case_study_description',
                    models.CharField(blank=True, max_length=255, verbose_name='Case study description'),
                ),
                (
                    'accordion_4_statistic_1_number',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 1 number'),
                ),
                (
                    'accordion_4_statistic_1_heading',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 1 heading'),
                ),
                (
                    'accordion_4_statistic_1_smallprint',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 1 smallprint'),
                ),
                (
                    'accordion_4_statistic_2_number',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 2 number'),
                ),
                (
                    'accordion_4_statistic_2_heading',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 2 heading'),
                ),
                (
                    'accordion_4_statistic_2_smallprint',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 2 smallprint'),
                ),
                (
                    'accordion_4_statistic_3_number',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 3 number'),
                ),
                (
                    'accordion_4_statistic_3_heading',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 3 heading'),
                ),
                (
                    'accordion_4_statistic_3_smallprint',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 3 smallprint'),
                ),
                (
                    'accordion_4_statistic_4_number',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 4 number'),
                ),
                (
                    'accordion_4_statistic_4_heading',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 4 heading'),
                ),
                (
                    'accordion_4_statistic_4_smallprint',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 4 smallprint'),
                ),
                (
                    'accordion_4_statistic_5_number',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 5 number'),
                ),
                (
                    'accordion_4_statistic_5_heading',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 5 heading'),
                ),
                (
                    'accordion_4_statistic_5_smallprint',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 5 smallprint'),
                ),
                (
                    'accordion_4_statistic_6_number',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 6 number'),
                ),
                (
                    'accordion_4_statistic_6_heading',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 6 heading'),
                ),
                (
                    'accordion_4_statistic_6_smallprint',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 6 smallprint'),
                ),
                ('accordion_5_title', models.CharField(blank=True, max_length=255, verbose_name='Industry title')),
                ('accordion_5_teaser', models.TextField(blank=True, verbose_name='Industry teaser')),
                (
                    'accordion_5_subsection_1_heading',
                    models.CharField(blank=True, max_length=255, verbose_name='Subsection 1 heading'),
                ),
                ('accordion_5_subsection_1_body', models.TextField(blank=True, verbose_name='Subsection 1 body')),
                (
                    'accordion_5_subsection_2_heading',
                    models.CharField(blank=True, max_length=255, verbose_name='Subsection 2 heading'),
                ),
                ('accordion_5_subsection_2_body', models.TextField(blank=True, verbose_name='Subsection 2 body')),
                (
                    'accordion_5_subsection_3_heading',
                    models.CharField(blank=True, max_length=255, verbose_name='Subsection 2 heading'),
                ),
                ('accordion_5_subsection_3_body', models.TextField(blank=True, verbose_name='Subsection 2 body')),
                (
                    'accordion_5_case_study_button_text',
                    models.CharField(blank=True, max_length=255, verbose_name='Case study button text'),
                ),
                (
                    'accordion_5_case_study_button_link',
                    models.CharField(blank=True, max_length=255, verbose_name='Case study button link'),
                ),
                (
                    'accordion_5_case_study_title',
                    models.CharField(blank=True, max_length=255, verbose_name='Case study title'),
                ),
                (
                    'accordion_5_case_study_description',
                    models.CharField(blank=True, max_length=255, verbose_name='Case study description'),
                ),
                (
                    'accordion_5_statistic_1_number',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 1 number'),
                ),
                (
                    'accordion_5_statistic_1_heading',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 1 heading'),
                ),
                (
                    'accordion_5_statistic_1_smallprint',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 1 smallprint'),
                ),
                (
                    'accordion_5_statistic_2_number',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 2 number'),
                ),
                (
                    'accordion_5_statistic_2_heading',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 2 heading'),
                ),
                (
                    'accordion_5_statistic_2_smallprint',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 2 smallprint'),
                ),
                (
                    'accordion_5_statistic_3_number',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 3 number'),
                ),
                (
                    'accordion_5_statistic_3_heading',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 3 heading'),
                ),
                (
                    'accordion_5_statistic_3_smallprint',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 3 smallprint'),
                ),
                (
                    'accordion_5_statistic_4_number',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 4 number'),
                ),
                (
                    'accordion_5_statistic_4_heading',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 4 heading'),
                ),
                (
                    'accordion_5_statistic_4_smallprint',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 4 smallprint'),
                ),
                (
                    'accordion_5_statistic_5_number',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 5 number'),
                ),
                (
                    'accordion_5_statistic_5_heading',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 5 heading'),
                ),
                (
                    'accordion_5_statistic_5_smallprint',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 5 smallprint'),
                ),
                (
                    'accordion_5_statistic_6_number',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 6 number'),
                ),
                (
                    'accordion_5_statistic_6_heading',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 6 heading'),
                ),
                (
                    'accordion_5_statistic_6_smallprint',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 6 smallprint'),
                ),
                ('accordion_6_title', models.CharField(blank=True, max_length=255, verbose_name='Industry title')),
                ('accordion_6_teaser', models.TextField(blank=True, verbose_name='Industry teaser')),
                (
                    'accordion_6_subsection_1_heading',
                    models.CharField(blank=True, max_length=255, verbose_name='Subsection 1 heading'),
                ),
                ('accordion_6_subsection_1_body', models.TextField(blank=True, verbose_name='Subsection 1 body')),
                (
                    'accordion_6_subsection_2_heading',
                    models.CharField(blank=True, max_length=255, verbose_name='Subsection 2 heading'),
                ),
                ('accordion_6_subsection_2_body', models.TextField(blank=True, verbose_name='Subsection 2 body')),
                (
                    'accordion_6_subsection_3_heading',
                    models.CharField(blank=True, max_length=255, verbose_name='Subsection 2 heading'),
                ),
                ('accordion_6_subsection_3_body', models.TextField(blank=True, verbose_name='Subsection 2 body')),
                (
                    'accordion_6_case_study_button_text',
                    models.CharField(blank=True, max_length=255, verbose_name='Case study button text'),
                ),
                (
                    'accordion_6_case_study_button_link',
                    models.CharField(blank=True, max_length=255, verbose_name='Case study button link'),
                ),
                (
                    'accordion_6_case_study_title',
                    models.CharField(blank=True, max_length=255, verbose_name='Case study title'),
                ),
                (
                    'accordion_6_case_study_description',
                    models.CharField(blank=True, max_length=255, verbose_name='Case study description'),
                ),
                (
                    'accordion_6_statistic_1_number',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 1 number'),
                ),
                (
                    'accordion_6_statistic_1_heading',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 1 heading'),
                ),
                (
                    'accordion_6_statistic_1_smallprint',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 1 smallprint'),
                ),
                (
                    'accordion_6_statistic_2_number',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 2 number'),
                ),
                (
                    'accordion_6_statistic_2_heading',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 2 heading'),
                ),
                (
                    'accordion_6_statistic_2_smallprint',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 2 smallprint'),
                ),
                (
                    'accordion_6_statistic_3_number',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 3 number'),
                ),
                (
                    'accordion_6_statistic_3_heading',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 3 heading'),
                ),
                (
                    'accordion_6_statistic_3_smallprint',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 3 smallprint'),
                ),
                (
                    'accordion_6_statistic_4_number',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 4 number'),
                ),
                (
                    'accordion_6_statistic_4_heading',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 4 heading'),
                ),
                (
                    'accordion_6_statistic_4_smallprint',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 4 smallprint'),
                ),
                (
                    'accordion_6_statistic_5_number',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 5 number'),
                ),
                (
                    'accordion_6_statistic_5_heading',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 5 heading'),
                ),
                (
                    'accordion_6_statistic_5_smallprint',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 5 smallprint'),
                ),
                (
                    'accordion_6_statistic_6_number',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 6 number'),
                ),
                (
                    'accordion_6_statistic_6_heading',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 6 heading'),
                ),
                (
                    'accordion_6_statistic_6_smallprint',
                    models.CharField(blank=True, max_length=255, verbose_name='Stat 6 smallprint'),
                ),
                (
                    'fact_sheet_title',
                    models.CharField(blank=True, max_length=255, verbose_name="Title for 'Doing business in' section"),
                ),
                (
                    'fact_sheet_teaser',
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Summary for 'Doing business in' section"
                    ),
                ),
                (
                    'fact_sheet_column_1_title',
                    models.CharField(blank=True, max_length=255, verbose_name="Title for 'Tax and customs'"),
                ),
                (
                    'fact_sheet_column_1_teaser',
                    models.CharField(blank=True, max_length=255, verbose_name="Summary for 'Tax and customs'"),
                ),
                (
                    'fact_sheet_column_1_body',
                    core.fields.MarkdownField(
                        blank=True,
                        help_text='Use H4 (####) for each sub category heading. Maximum five sub categories. Aim for 50 words each.',
                        verbose_name="Detailed text for 'Tax and customs'",
                    ),
                ),
                (
                    'fact_sheet_column_2_title',
                    models.CharField(blank=True, max_length=255, verbose_name="Title for 'Protecting your business'"),
                ),
                (
                    'fact_sheet_column_2_teaser',
                    models.CharField(blank=True, max_length=255, verbose_name="Summary for 'Protecting your business'"),
                ),
                (
                    'fact_sheet_column_2_body',
                    core.fields.MarkdownField(
                        blank=True,
                        help_text='Use H4 (####) for each sub category heading. Maximum five sub categories. Aim for 50 words each.',
                        verbose_name="Detailed text for 'Protecting your business'",
                    ),
                ),
                (
                    'duties_and_custom_procedures_cta_link',
                    models.URLField(
                        blank=True, null=True, verbose_name='Check duties and customs procedures for exporting goods'
                    ),
                ),
                (
                    'accordion_1_case_study_hero_image',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='core.AltTextImage',
                        verbose_name='Case study hero',
                    ),
                ),
                (
                    'accordion_1_icon',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='core.AltTextImage',
                        verbose_name='Industry Icon',
                    ),
                ),
                (
                    'accordion_1_subsection_1_icon',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='core.AltTextImage',
                        verbose_name='Subsection 1 icon',
                    ),
                ),
                (
                    'accordion_1_subsection_2_icon',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='core.AltTextImage',
                        verbose_name='Subsection 2 icon',
                    ),
                ),
                (
                    'accordion_1_subsection_3_icon',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='core.AltTextImage',
                        verbose_name='Subsection 2 icon',
                    ),
                ),
                (
                    'accordion_2_case_study_hero_image',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='core.AltTextImage',
                        verbose_name='Case study hero',
                    ),
                ),
                (
                    'accordion_2_icon',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='core.AltTextImage',
                        verbose_name='Industry Icon',
                    ),
                ),
                (
                    'accordion_2_subsection_1_icon',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='core.AltTextImage',
                        verbose_name='Subsection 1 icon',
                    ),
                ),
                (
                    'accordion_2_subsection_2_icon',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='core.AltTextImage',
                        verbose_name='Subsection 2 icon',
                    ),
                ),
                (
                    'accordion_2_subsection_3_icon',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='core.AltTextImage',
                        verbose_name='Subsection 2 icon',
                    ),
                ),
                (
                    'accordion_3_case_study_hero_image',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='core.AltTextImage',
                        verbose_name='Case study hero',
                    ),
                ),
                (
                    'accordion_3_icon',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='core.AltTextImage',
                        verbose_name='Industry Icon',
                    ),
                ),
                (
                    'accordion_3_subsection_1_icon',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='core.AltTextImage',
                        verbose_name='Subsection 1 icon',
                    ),
                ),
                (
                    'accordion_3_subsection_2_icon',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='core.AltTextImage',
                        verbose_name='Subsection 2 icon',
                    ),
                ),
                (
                    'accordion_3_subsection_3_icon',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='core.AltTextImage',
                        verbose_name='Subsection 2 icon',
                    ),
                ),
                (
                    'accordion_4_case_study_hero_image',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='core.AltTextImage',
                        verbose_name='Case study hero',
                    ),
                ),
                (
                    'accordion_4_icon',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='core.AltTextImage',
                        verbose_name='Industry Icon',
                    ),
                ),
                (
                    'accordion_4_subsection_1_icon',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='core.AltTextImage',
                        verbose_name='Subsection 1 icon',
                    ),
                ),
                (
                    'accordion_4_subsection_2_icon',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='core.AltTextImage',
                        verbose_name='Subsection 2 icon',
                    ),
                ),
                (
                    'accordion_4_subsection_3_icon',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='core.AltTextImage',
                        verbose_name='Subsection 2 icon',
                    ),
                ),
                (
                    'accordion_5_case_study_hero_image',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='core.AltTextImage',
                        verbose_name='Case study hero',
                    ),
                ),
                (
                    'accordion_5_icon',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='core.AltTextImage',
                        verbose_name='Industry Icon',
                    ),
                ),
                (
                    'accordion_5_subsection_1_icon',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='core.AltTextImage',
                        verbose_name='Subsection 1 icon',
                    ),
                ),
                (
                    'accordion_5_subsection_2_icon',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='core.AltTextImage',
                        verbose_name='Subsection 2 icon',
                    ),
                ),
                (
                    'accordion_5_subsection_3_icon',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='core.AltTextImage',
                        verbose_name='Subsection 2 icon',
                    ),
                ),
                (
                    'accordion_6_case_study_hero_image',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='core.AltTextImage',
                        verbose_name='Case study hero',
                    ),
                ),
                (
                    'accordion_6_icon',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='core.AltTextImage',
                        verbose_name='Industry Icon',
                    ),
                ),
                (
                    'accordion_6_subsection_1_icon',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='core.AltTextImage',
                        verbose_name='Subsection 1 icon',
                    ),
                ),
                (
                    'accordion_6_subsection_2_icon',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='core.AltTextImage',
                        verbose_name='Subsection 2 icon',
                    ),
                ),
                (
                    'accordion_6_subsection_3_icon',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='core.AltTextImage',
                        verbose_name='Subsection 2 icon',
                    ),
                ),
                (
                    'country',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='core.Country',
                    ),
                ),
                (
                    'hero_image',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='core.AltTextImage',
                    ),
                ),
                (
                    'related_page_one',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='wagtailcore.Page',
                    ),
                ),
                (
                    'related_page_three',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='wagtailcore.Page',
                    ),
                ),
                (
                    'related_page_two',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='wagtailcore.Page',
                    ),
                ),
                (
                    'section_one_image',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='core.AltTextImage',
                        verbose_name='Image for unique selling points',
                    ),
                ),
                ('tags', modelcluster.fields.ParentalManyToManyField(blank=True, to='core.IndustryTag')),
            ],
            options={
                'ordering': ['-heading'],
            },
            bases=(domestic.cms_panels.CountryGuidePagePanels, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='CampaignPage',
            fields=[
                (
                    'page_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='wagtailcore.Page',
                    ),
                ),
                ('campaign_heading', models.CharField(max_length=255)),
                ('section_one_heading', models.CharField(max_length=255)),
                ('section_one_intro', core.fields.MarkdownField()),
                ('selling_point_one_heading', models.CharField(max_length=255)),
                ('selling_point_one_content', core.fields.MarkdownField()),
                ('selling_point_two_heading', models.CharField(blank=True, max_length=255, null=True)),
                ('selling_point_two_content', core.fields.MarkdownField(blank=True, null=True)),
                ('selling_point_three_heading', models.CharField(blank=True, max_length=255, null=True)),
                ('selling_point_three_content', core.fields.MarkdownField(blank=True, null=True)),
                ('section_one_contact_button_url', models.CharField(blank=True, max_length=255, null=True)),
                ('section_one_contact_button_text', models.CharField(blank=True, max_length=255, null=True)),
                ('section_two_heading', models.CharField(max_length=255)),
                ('section_two_intro', core.fields.MarkdownField()),
                ('section_two_contact_button_url', models.CharField(blank=True, max_length=255, null=True)),
                ('section_two_contact_button_text', models.CharField(blank=True, max_length=255, null=True)),
                ('related_content_heading', models.CharField(max_length=255)),
                ('related_content_intro', core.fields.MarkdownField()),
                ('cta_box_message', models.CharField(max_length=255)),
                ('cta_box_button_url', models.CharField(max_length=255)),
                ('cta_box_button_text', models.CharField(max_length=255)),
                (
                    'campaign_hero_image',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='core.AltTextImage',
                    ),
                ),
                (
                    'related_page_one',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='domestic.ArticlePage',
                    ),
                ),
                (
                    'related_page_three',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='domestic.ArticlePage',
                    ),
                ),
                (
                    'related_page_two',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='domestic.ArticlePage',
                    ),
                ),
                (
                    'section_one_image',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='core.AltTextImage',
                    ),
                ),
                (
                    'section_two_image',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='core.AltTextImage',
                    ),
                ),
                (
                    'selling_point_one_icon',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='core.AltTextImage',
                    ),
                ),
                (
                    'selling_point_three_icon',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='core.AltTextImage',
                    ),
                ),
                (
                    'selling_point_two_icon',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='core.AltTextImage',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
            bases=(domestic.cms_panels.CampaignPagePanels, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='ArticleListingPage',
            fields=[
                (
                    'page_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='wagtailcore.Page',
                    ),
                ),
                ('landing_page_title', models.CharField(max_length=255)),
                ('hero_teaser', models.CharField(blank=True, max_length=255, null=True)),
                ('list_teaser', core.fields.MarkdownField(blank=True, null=True)),
                (
                    'hero_image',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='core.AltTextImage',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
            bases=(domestic.cms_panels.ArticleListingPagePanels, 'wagtailcore.page'),
        ),
    ]
