# Generated by Django 2.2.14 on 2021-01-11 15:52

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domestic', '0006_articlelistingpage_articlepage_campaignpage_countryguidepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryguidepage',
            name='tags',
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, to='core.IndustryTag', verbose_name='Industry tag'
            ),
        ),
    ]
