# Generated by Django 2.2.14 on 2021-01-12 15:37

import wagtail.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domestic', '0007_relabel_countryguidepage_tag_as_industrytag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlelistingpage',
            name='list_teaser',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='article_body_text',
            field=wagtail.core.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='article_video_transcript',
            field=wagtail.core.fields.RichTextField(
                blank=True, help_text='If the video is present, a transcript must be provided.', null=True
            ),
        ),
        migrations.AlterField(
            model_name='campaignpage',
            name='related_content_intro',
            field=wagtail.core.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='campaignpage',
            name='section_one_intro',
            field=wagtail.core.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='campaignpage',
            name='section_two_intro',
            field=wagtail.core.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='campaignpage',
            name='selling_point_one_content',
            field=wagtail.core.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='campaignpage',
            name='selling_point_three_content',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaignpage',
            name='selling_point_two_content',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='countryguidepage',
            name='fact_sheet_column_1_body',
            field=wagtail.core.fields.RichTextField(
                blank=True,
                help_text='Use H3 for each subcategory heading. Maximum five sub categories. Aim for 50 words each.',
                verbose_name="Detailed text for 'Tax and customs'",
            ),
        ),
        migrations.AlterField(
            model_name='countryguidepage',
            name='fact_sheet_column_2_body',
            field=wagtail.core.fields.RichTextField(
                blank=True,
                help_text='Use H3 for each sub category heading. Maximum five sub categories. Aim for 50 words each.',
                verbose_name="Detailed text for 'Protecting your business'",
            ),
        ),
        migrations.AlterField(
            model_name='countryguidepage',
            name='section_one_body',
            field=wagtail.core.fields.RichTextField(
                help_text='Use H2s for the 3 subheadings', null=True, verbose_name='3 unique selling points markdown'
            ),
        ),
    ]
