# Generated by Django 2.2.14 on 2021-01-12 20:37

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('domestic', '0008_drop_markdownfield_usage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countryguidepage',
            name='statistic_1_heading',
        ),
        migrations.RemoveField(
            model_name='countryguidepage',
            name='statistic_1_number',
        ),
        migrations.RemoveField(
            model_name='countryguidepage',
            name='statistic_1_smallprint',
        ),
        migrations.RemoveField(
            model_name='countryguidepage',
            name='statistic_2_heading',
        ),
        migrations.RemoveField(
            model_name='countryguidepage',
            name='statistic_2_number',
        ),
        migrations.RemoveField(
            model_name='countryguidepage',
            name='statistic_2_smallprint',
        ),
        migrations.RemoveField(
            model_name='countryguidepage',
            name='statistic_3_heading',
        ),
        migrations.RemoveField(
            model_name='countryguidepage',
            name='statistic_3_number',
        ),
        migrations.RemoveField(
            model_name='countryguidepage',
            name='statistic_3_smallprint',
        ),
        migrations.RemoveField(
            model_name='countryguidepage',
            name='statistic_4_heading',
        ),
        migrations.RemoveField(
            model_name='countryguidepage',
            name='statistic_4_number',
        ),
        migrations.RemoveField(
            model_name='countryguidepage',
            name='statistic_4_smallprint',
        ),
        migrations.RemoveField(
            model_name='countryguidepage',
            name='statistic_5_heading',
        ),
        migrations.RemoveField(
            model_name='countryguidepage',
            name='statistic_5_number',
        ),
        migrations.RemoveField(
            model_name='countryguidepage',
            name='statistic_5_smallprint',
        ),
        migrations.RemoveField(
            model_name='countryguidepage',
            name='statistic_6_heading',
        ),
        migrations.RemoveField(
            model_name='countryguidepage',
            name='statistic_6_number',
        ),
        migrations.RemoveField(
            model_name='countryguidepage',
            name='statistic_6_smallprint',
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='main_statistics',
            field=wagtail.fields.StreamField(
                [
                    (
                        'statistic',
                        wagtail.blocks.StructBlock(
                            [
                                ('number', wagtail.blocks.CharBlock(max_length=255)),
                                ('heading', wagtail.blocks.CharBlock(max_length=255)),
                                ('smallprint', wagtail.blocks.CharBlock(max_length=255, required=False)),
                            ],
                            icon='fa-calculator',
                            max_num=6,
                            min_num=2,
                        ),
                    )
                ],
                use_json_field=True,
                blank=True,
                null=True,
            ),
        ),
    ]
