# Generated by Django 2.2.14 on 2021-01-20 15:49

import django.db.models.deletion
import wagtail.core.fields
from django.db import migrations, models

import domestic.cms_panels


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('wagtailcore', '0052_pagelogentry'),
        ('domestic', '0011_gcp_move_accordions_to_streamfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicLandingPage',
            fields=[
                (
                    'page_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='wagtailcore.Page',
                    ),
                ),
                ('template', models.CharField(max_length=255)),
                ('hero_teaser', models.CharField(blank=True, max_length=255, null=True)),
                ('banner_text', wagtail.core.fields.RichTextField(blank=True)),
                ('teaser', models.TextField(blank=True)),
                (
                    'hero_image',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='wagtailimages.Image',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
            bases=(
                #  Commented out because refactored away and has no impact on schema
                # domestic.cms_panels.TopicLandingPagePanels,
                'wagtailcore.page',
            ),
        ),
    ]
