# Generated by Django 2.2.14 on 2021-01-21 17:11

import django.db.models.deletion
import wagtail.core.fields
from django.db import migrations, models

import domestic.cms_panels


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('core', '0049_data_bootstrap_tag_and_industrytag_snippets'),
        ('wagtail_personalisation', '0025_auto_20190822_0627'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0052_pagelogentry'),
        ('domestic', '0012_topiclandingpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdviceTopicLandingPage',
            fields=[
                (
                    'page_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='wagtailcore.Page',
                    ),
                ),
                ('hero_teaser', models.CharField(blank=True, max_length=255, null=True)),
                ('banner_text', wagtail.core.fields.RichTextField(blank=True)),
                ('teaser', models.TextField(blank=True)),
                (
                    'hero_image',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='wagtailimages.Image',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
            bases=(domestic.cms_panels.AdviceTopicLandingPagePanels, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='MarketsTopicLandingPage',
            fields=[
                (
                    'page_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='wagtailcore.Page',
                    ),
                ),
                ('hero_teaser', models.CharField(blank=True, max_length=255, null=True)),
                ('banner_text', wagtail.core.fields.RichTextField(blank=True)),
                ('teaser', models.TextField(blank=True)),
                (
                    'hero_image',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='wagtailimages.Image',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
            bases=(domestic.cms_panels.MarketsTopicLandingPagePanels, 'wagtailcore.page'),
        ),
        migrations.DeleteModel(
            name='TopicLandingPage',
        ),
    ]
