# Generated by Django 2.2.14 on 2021-01-22 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic', '0013_refactor_topic_landing_page_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advicetopiclandingpage',
            name='hero_image',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='core.AltTextImage',
            ),
        ),
        migrations.AlterField(
            model_name='marketstopiclandingpage',
            name='hero_image',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='core.AltTextImage',
            ),
        ),
    ]
