# Generated by Django 2.2.14 on 2021-01-28 13:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailcore', '0052_pagelogentry'),
        ('wagtail_personalisation', '0025_auto_20190822_0627'),
        ('core', '0050_casestudyrelatedpages'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('domestic', '0014_correct_wagtailimages_image_to_core_alttextimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdviceTopicLandingPage',
            new_name='TopicLandingPage',
        ),
        # This is a stray alteration from a previous changeset, but a no-op at the database level
        migrations.AlterModelOptions(
            name='countryguidepage',
            options={'ordering': ['-heading', '-title']},
        ),
    ]
