# Generated by Django 2.2.14 on 2021-02-01 14:01

import wagtail.core.blocks
import wagtail.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domestic', '0015_rename_articletopiclandingpage_to_topiclandingpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepage',
            name='article_body_text',
        ),
        migrations.AddField(
            model_name='articlepage',
            name='article_body',
            field=wagtail.core.fields.StreamField(
                [
                    (
                        'text',
                        wagtail.core.blocks.RichTextBlock(
                            features=('h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'hr', 'link')
                        ),
                    ),
                    (
                        'pull_quote',
                        wagtail.core.blocks.StructBlock(
                            [
                                ('quote', wagtail.core.blocks.TextBlock()),
                                (
                                    'attribution',
                                    wagtail.core.blocks.CharBlock(label='Who said it?', max_length=255, required=False),
                                ),
                                (
                                    'role',
                                    wagtail.core.blocks.CharBlock(label='Their role', max_length=255, required=False),
                                ),
                                (
                                    'organisation',
                                    wagtail.core.blocks.CharBlock(
                                        label='Their organisation', max_length=255, required=False
                                    ),
                                ),
                                (
                                    'organisation_link',
                                    wagtail.core.blocks.URLBlock(
                                        label='Link to organisation site', max_length=255, required=False
                                    ),
                                ),
                            ],
                            template='domestic/blocks/pull_quote_block.html',
                        ),
                    ),
                ],
                blank=True,
                null=True,
            ),
        ),
    ]
