# Generated by Django 2.2.18 on 2021-02-03 17:11

import django.db.models.deletion
from django.db import migrations, models

import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        ('domestic', '0016_switch_article_body_text_to_streamfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidancePage',
            fields=[
                (
                    'page_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='wagtailcore.Page',
                    ),
                ),
                (
                    'body',
                    wagtail.fields.StreamField(
                        [
                            (
                                'text',
                                wagtail.blocks.RichTextBlock(
                                    features=[
                                        'h1',
                                        'h2',
                                        'h3',
                                        'h4',
                                        'bold',
                                        'italic',
                                        'ol',
                                        'ul',
                                        'hr',
                                        'link',
                                        'document-link',
                                    ]
                                ),
                            ),
                            (
                                'table',
                                wagtail.contrib.table_block.blocks.TableBlock(
                                    table_options={
                                        'autoColumnSize': False,
                                        'colHeaders': True,
                                        'editor': 'text',
                                        'height': 108,
                                        'minSpareRows': 0,
                                        'renderer': 'text',
                                        'rowHeaders': False,
                                        'startCols': 2,
                                        'startRows': 3,
                                        'stretchH': 'all',
                                    }
                                ),
                            ),
                        ],
                        use_json_field=True,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='article_body',
            field=wagtail.fields.StreamField(
                [
                    (
                        'text',
                        wagtail.blocks.RichTextBlock(
                            features=['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'hr', 'link', 'document-link']
                        ),
                    ),
                    (
                        'pull_quote',
                        wagtail.blocks.StructBlock(
                            [
                                ('quote', wagtail.blocks.TextBlock()),
                                (
                                    'attribution',
                                    wagtail.blocks.CharBlock(label='Who said it?', max_length=255, required=False),
                                ),
                                (
                                    'role',
                                    wagtail.blocks.CharBlock(label='Their role', max_length=255, required=False),
                                ),
                                (
                                    'organisation',
                                    wagtail.blocks.CharBlock(
                                        label='Their organisation', max_length=255, required=False
                                    ),
                                ),
                                (
                                    'organisation_link',
                                    wagtail.blocks.URLBlock(
                                        label='Link to organisation site', max_length=255, required=False
                                    ),
                                ),
                            ],
                            template='domestic/blocks/pull_quote_block.html',
                        ),
                    ),
                ],
                use_json_field=True,
                blank=True,
                null=True,
            ),
        ),
    ]
