# Generated by Django 2.2.18 on 2021-02-03 17:11

import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        ('domestic', '0016_switch_article_body_text_to_streamfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidancePage',
            fields=[
                (
                    'page_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='wagtailcore.Page',
                    ),
                ),
                (
                    'body',
                    wagtail.core.fields.StreamField(
                        [
                            (
                                'text',
                                wagtail.core.blocks.RichTextBlock(
                                    features=['h1', 'h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'hr', 'link']
                                ),
                            )
                        ]
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='article_body',
            field=wagtail.core.fields.StreamField(
                [
                    (
                        'text',
                        wagtail.core.blocks.RichTextBlock(
                            features=['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'hr', 'link']
                        ),
                    ),
                    (
                        'pull_quote',
                        wagtail.core.blocks.StructBlock(
                            [
                                ('quote', wagtail.core.blocks.TextBlock()),
                                (
                                    'attribution',
                                    wagtail.core.blocks.CharBlock(label='Who said it?', max_length=255, required=False),
                                ),
                                (
                                    'role',
                                    wagtail.core.blocks.CharBlock(label='Their role', max_length=255, required=False),
                                ),
                                (
                                    'organisation',
                                    wagtail.core.blocks.CharBlock(
                                        label='Their organisation', max_length=255, required=False
                                    ),
                                ),
                                (
                                    'organisation_link',
                                    wagtail.core.blocks.URLBlock(
                                        label='Link to organisation site', max_length=255, required=False
                                    ),
                                ),
                            ],
                            template='domestic/blocks/pull_quote_block.html',
                        ),
                    ),
                ],
                blank=True,
                null=True,
            ),
        ),
    ]
