# Generated by Django 2.2.18 on 2021-02-08 16:02

import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
from django.db import migrations, models

import domestic.cms_panels


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        ('domestic', '0017_add_guidance_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceDashboardPage',
            fields=[
                (
                    'page_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='wagtailcore.Page',
                    ),
                ),
                ('heading', models.CharField(max_length=255)),
                ('description', wagtail.core.fields.RichTextField()),
                (
                    'body',
                    wagtail.core.fields.StreamField(
                        [
                            (
                                'data_block',
                                wagtail.core.blocks.StructBlock(
                                    [
                                        ('data_title', wagtail.core.blocks.CharBlock(max_length=100)),
                                        ('data_value', wagtail.core.blocks.CharBlock(max_length=100)),
                                        ('data_period', wagtail.core.blocks.CharBlock(max_length=100)),
                                        (
                                            'data_description',
                                            wagtail.core.blocks.RichTextBlock(
                                                features=[
                                                    'h2',
                                                    'h3',
                                                    'h4',
                                                    'bold',
                                                    'italic',
                                                    'ol',
                                                    'ul',
                                                    'hr',
                                                    'link',
                                                    'document-link',
                                                ]
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ]
                    ),
                ),
                ('guidance_notes', wagtail.core.fields.RichTextField(blank=True, null=True)),
                (
                    'landing_dashboard',
                    models.BooleanField(
                        default=False, help_text='Will this page act as landing page for other dashboards?'
                    ),
                ),
                (
                    'product_link',
                    models.CharField(
                        choices=[
                            ('https://www.great.gov.uk', 'Great.gov.uk'),
                            ('https://selling-online-overseas.export.great.gov.uk', 'Selling Online Overseas'),
                            ('https://www.great.gov.uk/export-opportunities', 'Export Opportunities'),
                            ('https://www.great.gov.uk/find-a-buyer', 'Business Profiles'),
                            ('https://invest.great.gov.uk', 'Invest in Great Britain'),
                        ],
                        help_text=(
                            'The slug and page heading are inferred from the product link. '
                            'The first option should be the first performance dashboard page and '
                            'the rest should be used for CHILDREN of that main dashboard.'
                        ),
                        max_length=255,
                        unique=True,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
            bases=(domestic.cms_panels.PerformanceDashboardPagePanels, 'wagtailcore.page'),
        ),
    ]
