# Generated by Django 2.2.18 on 2021-02-11 16:55

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models

import core.blocks
import domestic.cms_panels


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0055_auto_20210209_1102'),
        ('wagtailcore', '0052_pagelogentry'),
        ('domestic', '0018_performancedashboardpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GreatDomesticHomePage',
            fields=[
                (
                    'page_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='wagtailcore.Page',
                    ),
                ),
                ('hero_text', models.TextField(blank=True, null=True)),
                ('hero_cta_text', models.CharField(blank=True, max_length=255, null=True)),
                ('hero_cta_url', models.CharField(blank=True, max_length=255, null=True)),
                ('how_dit_helps_title', models.TextField(blank=True, null=True)),
                (
                    'how_dit_helps_columns',
                    wagtail.fields.StreamField(
                        [
                            (
                                'columns',
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            'internal_link',
                                            wagtail.blocks.PageChooserBlock(label='Internal link', required=False),
                                        ),
                                        (
                                            'external_link',
                                            wagtail.blocks.CharBlock(
                                                label='External link', max_length=255, required=False
                                            ),
                                        ),
                                        ('image', wagtail.images.blocks.ImageChooserBlock(required=False)),
                                        ('content', wagtail.blocks.RichTextBlock()),
                                    ]
                                ),
                            )
                        ],
                        use_json_field=True,
                        blank=True,
                        null=True,
                    ),
                ),
                ('madb_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('madb_content', wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Content')),
                ('madb_cta_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='CTA text')),
                ('madb_cta_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='CTA URL')),
                ('what_is_new_title', models.CharField(blank=True, max_length=255, null=True)),
                (
                    'what_is_new_pages',
                    wagtail.fields.StreamField(
                        [
                            (
                                'pages',
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            'internal_link',
                                            wagtail.blocks.PageChooserBlock(label='Internal link', required=False),
                                        ),
                                        (
                                            'external_link',
                                            wagtail.blocks.CharBlock(
                                                label='External link', max_length=255, required=False
                                            ),
                                        ),
                                        ('image', wagtail.images.blocks.ImageChooserBlock(required=False)),
                                        ('content', wagtail.blocks.RichTextBlock()),
                                    ]
                                ),
                            )
                        ],
                        use_json_field=True,
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    'campaign',
                    wagtail.fields.StreamField(
                        [
                            (
                                'campaign',
                                wagtail.blocks.StructBlock(
                                    [
                                        ('heading', wagtail.blocks.CharBlock()),
                                        ('subheading', wagtail.blocks.CharBlock()),
                                        ('related_link_text', wagtail.blocks.CharBlock()),
                                        ('related_link_url', wagtail.blocks.CharBlock()),
                                        ('image', wagtail.images.blocks.ImageChooserBlock()),
                                        ('video', core.blocks.VideoChooserBlock()),
                                    ]
                                ),
                            )
                        ],
                        use_json_field=True,
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    'hero_image',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='core.AltTextImage',
                    ),
                ),
                (
                    'madb_image',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='core.AltTextImage',
                        verbose_name='Image',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
            bases=(domestic.cms_panels.GreatDomesticHomePagePanels, 'wagtailcore.page'),
        ),
    ]
