# Generated by Django 2.2.18 on 2021-02-12 13:27

from django.db import migrations

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ('domestic', '0020_update_domestic_homepage_streamfields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greatdomestichomepage',
            name='how_dit_helps_columns',
            field=wagtail.fields.StreamField(
                [
                    (
                        'columns',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'source',
                                    wagtail.blocks.CharBlock(
                                        help_text='The source or the type of the link, e.g. GOV.UK/Advice'
                                    ),
                                ),
                                ('text', wagtail.blocks.CharBlock()),
                                ('url', wagtail.blocks.CharBlock()),
                                ('image', wagtail.images.blocks.ImageChooserBlock(required=False)),
                                ('content', wagtail.blocks.RichTextBlock()),
                            ]
                        ),
                    )
                ],
                use_json_field=True,
                blank=True,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='greatdomestichomepage',
            name='what_is_new_pages',
            field=wagtail.fields.StreamField(
                [
                    (
                        'pages',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'source',
                                    wagtail.blocks.CharBlock(
                                        help_text='The source or the type of the link, e.g. GOV.UK/Advice'
                                    ),
                                ),
                                ('text', wagtail.blocks.CharBlock()),
                                ('url', wagtail.blocks.CharBlock()),
                                ('image', wagtail.images.blocks.ImageChooserBlock(required=False)),
                                ('content', wagtail.blocks.RichTextBlock()),
                            ]
                        ),
                    )
                ],
                use_json_field=True,
                blank=True,
                null=True,
            ),
        ),
    ]
