# Generated by Django 2.2.19 on 2021-02-25 09:32

from django.db import migrations
import wagtail.contrib.table_block.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('domestic', '0021_further_update_domestic_homepage_streamfields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='article_body',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'hr', 'link', 'document-link'])), ('pull_quote', wagtail.core.blocks.StructBlock([('quote', wagtail.core.blocks.TextBlock()), ('attribution', wagtail.core.blocks.CharBlock(label='Who said it?', max_length=255, required=False)), ('role', wagtail.core.blocks.CharBlock(label='Their role', max_length=255, required=False)), ('organisation', wagtail.core.blocks.CharBlock(label='Their organisation', max_length=255, required=False)), ('organisation_link', wagtail.core.blocks.URLBlock(label='Link to organisation site', max_length=255, required=False))], template='domestic/blocks/pull_quote_block.html'))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guidancepage',
            name='body',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'hr', 'link', 'document-link'])), ('table', wagtail.contrib.table_block.blocks.TableBlock(table_options={'autoColumnSize': False, 'colHeaders': True, 'editor': 'text', 'height': 108, 'minSpareRows': 0, 'renderer': 'text', 'rowHeaders': False, 'startCols': 2, 'startRows': 3, 'stretchH': 'all'}))]),
        ),
        migrations.AlterField(
            model_name='performancedashboardpage',
            name='body',
            field=wagtail.core.fields.StreamField([('data_block', wagtail.core.blocks.StructBlock([('data_title', wagtail.core.blocks.CharBlock(max_length=100)), ('data_value', wagtail.core.blocks.CharBlock(max_length=100)), ('data_period', wagtail.core.blocks.CharBlock(max_length=100)), ('data_description', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'hr', 'link', 'document-link']))]))]),
        ),
    ]
