# Generated by Django 2.2.19 on 2021-02-25 18:13

import django.db.models.deletion
import great_components.mixins
from django.db import migrations, models

import core.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        ('domestic', '0021_further_update_domestic_homepage_streamfields'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructuralPage',
            fields=[
                (
                    'page_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='wagtailcore.Page',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', core.mixins.WagtailGA360Mixin, great_components.mixins.GA360Mixin),
        ),
    ]
