# Generated by Django 2.2.19 on 2021-03-04 10:43

import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic', '0022_structuralpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='greatdomestichomepage',
            name='magna_ctas_columns',
            field=wagtail.core.fields.StreamField(
                [
                    (
                        'columns',
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    'source',
                                    wagtail.core.blocks.CharBlock(
                                        help_text='The source or the type of the link, e.g. GOV.UK/Advice'
                                    ),
                                ),
                                ('text', wagtail.core.blocks.CharBlock()),
                                ('url', wagtail.core.blocks.CharBlock()),
                                ('image', wagtail.images.blocks.ImageChooserBlock(required=False)),
                                ('content', wagtail.core.blocks.RichTextBlock()),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='greatdomestichomepage',
            name='magna_ctas_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
