# Generated by Django 2.2.19 on 2021-03-04 10:58

import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domestic', '0023_auto_20210304_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greatdomestichomepage',
            name='magna_ctas_columns',
            field=wagtail.core.fields.StreamField(
                [
                    (
                        'columns',
                        wagtail.core.blocks.StructBlock(
                            [
                                ('text', wagtail.core.blocks.CharBlock()),
                                ('url', wagtail.core.blocks.CharBlock()),
                                ('image', wagtail.images.blocks.ImageChooserBlock(required=False)),
                                ('content', wagtail.core.blocks.RichTextBlock()),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
            ),
        ),
    ]
