# Generated by Django 2.2.19 on 2021-03-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic', '0023_auto_20210304_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='greatdomestichomepage',
            name='hero_cta_text_signedin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='greatdomestichomepage',
            name='hero_text_signedin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='greatdomestichomepage',
            name='hero_cta_url_signedin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
