# Generated by Django 2.2.19 on 2021-03-18 11:56

import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
from django.db import migrations, models

import domestic.cms_panels


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_delete_wagtail_personalisation_migration_references'),
        ('domestic', '0024_auto_20210315_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeFinanceSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'internal_title',
                    models.CharField(
                        editable=False, max_length=255, verbose_name='Title (internal use only - not publicly shown)'
                    ),
                ),
                (
                    'seo_title',
                    models.CharField(
                        blank=True,
                        help_text="Optional. 'Search Engine Friendly' title. This will appear at the top of the browser window.",
                        max_length=255,
                        verbose_name='Page title',
                    ),
                ),
                ('search_description', models.TextField(blank=True, verbose_name='Search description')),
                (
                    'slug',
                    models.CharField(
                        choices=[('trade-finance', 'Trade Finance')],
                        help_text='Select the use-case for this snippet from a fixed list of choices',
                        max_length=255,
                        unique=True,
                        verbose_name='Purpose',
                    ),
                ),
                ('breadcrumbs_label', models.CharField(max_length=50)),
                ('hero_text', wagtail.core.fields.RichTextField()),
                ('contact_proposition', wagtail.core.fields.RichTextField()),
                ('contact_button', models.CharField(max_length=500)),
                ('advantages_title', models.CharField(max_length=500)),
                (
                    'advantages',
                    wagtail.core.fields.StreamField(
                        [
                            (
                                'advantage',
                                wagtail.core.blocks.StructBlock(
                                    [
                                        ('icon', wagtail.images.blocks.ImageChooserBlock()),
                                        (
                                            'content',
                                            wagtail.core.blocks.RichTextBlock(
                                                features=[
                                                    'h2',
                                                    'h3',
                                                    'h4',
                                                    'bold',
                                                    'italic',
                                                    'ol',
                                                    'ul',
                                                    'hr',
                                                    'link',
                                                    'document-link',
                                                ]
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ]
                    ),
                ),
                ('evidence', wagtail.core.fields.RichTextField()),
                (
                    'evidence_video',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='core.GreatMedia',
                    ),
                ),
                (
                    'hero_image',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='core.AltTextImage',
                    ),
                ),
                (
                    'ukef_logo',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='core.AltTextImage',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
            bases=(
                models.Model,
                # disabled because class later renamed/repurposed, so can't be imported
                # domestic.cms_panels.TradeFinanceSnippetPanels
            ),
        ),
    ]
