# Generated by Django 2.2.19 on 2021-03-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic', '0025_tradefinancesnippet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='greatdomestichomepage',
            old_name='hero_cta_text_si',
            new_name='hero_cta_text_signedin',
        ),
        migrations.RenameField(
            model_name='greatdomestichomepage',
            old_name='hero_text_si',
            new_name='hero_text_signedin',
        ),
        migrations.AddField(
            model_name='greatdomestichomepage',
            name='hero_cta_url_signedin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
