# Generated by Django 2.2.19 on 2021-03-25 20:46

import django.db.models.deletion
import great_components.mixins
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
from django.db import migrations, models

import core.mixins
import domestic.cms_panels


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('core', '0065_delete_wagtail_personalisation_migration_references'),
        ('domestic', '0026_auto_20210324_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeFinancePage',
            fields=[
                (
                    'page_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='wagtailcore.Page',
                    ),
                ),
                ('breadcrumbs_label', models.CharField(max_length=50)),
                ('hero_text', wagtail.core.fields.RichTextField()),
                ('contact_proposition', wagtail.core.fields.RichTextField()),
                ('contact_button', models.CharField(max_length=500)),
                ('advantages_title', models.CharField(max_length=500)),
                (
                    'advantages',
                    wagtail.core.fields.StreamField(
                        [
                            (
                                'advantage',
                                wagtail.core.blocks.StructBlock(
                                    [
                                        ('icon', wagtail.images.blocks.ImageChooserBlock()),
                                        (
                                            'content',
                                            wagtail.core.blocks.RichTextBlock(
                                                features=[
                                                    'h2',
                                                    'h3',
                                                    'h4',
                                                    'bold',
                                                    'italic',
                                                    'ol',
                                                    'ul',
                                                    'hr',
                                                    'link',
                                                    'document-link',
                                                ]
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ]
                    ),
                ),
                ('evidence', wagtail.core.fields.RichTextField()),
                (
                    'evidence_video',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='core.GreatMedia',
                    ),
                ),
                (
                    'hero_image',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='core.AltTextImage',
                    ),
                ),
                (
                    'ukef_logo',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='core.AltTextImage',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
            bases=(
                domestic.cms_panels.TradeFinancePagePanels,
                'wagtailcore.page',
                core.mixins.WagtailGA360Mixin,
                great_components.mixins.GA360Mixin,
            ),
        ),
        migrations.DeleteModel(
            name='TradeFinanceSnippet',
        ),
    ]
