# Generated by Django 2.2.24 on 2021-11-03 10:55

from django.db import migrations

import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ('domestic', '0028_manuallyconfigurabletopiclandingpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='article_body',
            field=wagtail.fields.StreamField(
                [
                    ('text', wagtail.blocks.RichTextBlock()),
                    (
                        'pull_quote',
                        wagtail.blocks.StructBlock(
                            [
                                ('quote', wagtail.blocks.TextBlock()),
                                (
                                    'attribution',
                                    wagtail.blocks.CharBlock(label='Who said it?', max_length=255, required=False),
                                ),
                                (
                                    'role',
                                    wagtail.blocks.CharBlock(label='Their role', max_length=255, required=False),
                                ),
                                (
                                    'organisation',
                                    wagtail.blocks.CharBlock(
                                        label='Their organisation', max_length=255, required=False
                                    ),
                                ),
                                (
                                    'organisation_link',
                                    wagtail.blocks.URLBlock(
                                        label='Link to organisation site', max_length=255, required=False
                                    ),
                                ),
                            ],
                            template='domestic/blocks/pull_quote_block.html',
                        ),
                    ),
                ],
                use_json_field=True,
                blank=True,
                null=True,
            ),
        ),
    ]
