# Generated by Django 2.2.27 on 2022-02-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic', '0030_auto_20211104_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='greatdomestichomepage',
            name='hero_subtitle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='greatdomestichomepage',
            name='hero_subtitle_signedin',
            field=models.TextField(blank=True, null=True),
        ),
    ]
