# Generated by Django 2.2.27 on 2022-03-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic', '0031_auto_20220214_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countryguidepage',
            name='duties_and_custom_procedures_cta_link',
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='intro_cta_four_link',
            field=models.CharField(blank=True, max_length=500, verbose_name='CTA 4 link'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='intro_cta_four_title',
            field=models.CharField(blank=True, max_length=500, verbose_name='CTA 4 title'),
        ),
    ]
