# Generated by Django 2.2.27 on 2022-03-30 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('core', '0074_populate_country_iso2'),
        ('domestic', '0032_auto_20220301_1010'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CampaignPage',
        ),
    ]
