# Generated by Django 2.2.27 on 2022-02-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic', '0032_auto_20220223_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryguidepage',
            name='intro_cta_five_link',
            field=models.CharField(blank=True, max_length=500, verbose_name='CTA 5 link'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='intro_cta_five_title',
            field=models.CharField(blank=True, max_length=500, verbose_name='CTA 5 title'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='intro_cta_six_link',
            field=models.CharField(blank=True, max_length=500, verbose_name='CTA 6 link'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='intro_cta_six_title',
            field=models.CharField(blank=True, max_length=500, verbose_name='CTA 6 title'),
        ),
    ]
