# Generated by Django 2.2.28 on 2022-09-08 11:25

import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
from django.db import migrations

import core.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('domestic', '0033_delete_campaignpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='article_body',
            field=wagtail.core.fields.StreamField(
                [
                    ('text', wagtail.core.blocks.RichTextBlock()),
                    (
                        'image',
                        wagtail.images.blocks.ImageChooserBlock(
                            required=False, template='core/includes/_article_image.html'
                        ),
                    ),
                    (
                        'Video',
                        wagtail.core.blocks.StructBlock(
                            [
                                ('width', wagtail.core.blocks.IntegerBlock()),
                                ('height', wagtail.core.blocks.IntegerBlock()),
                                ('video', core.blocks.MediaChooserBlock()),
                            ],
                            template='core/includes/_article_video.html',
                        ),
                    ),
                    (
                        'pull_quote',
                        wagtail.core.blocks.StructBlock(
                            [
                                ('quote', wagtail.core.blocks.TextBlock()),
                                (
                                    'attribution',
                                    wagtail.core.blocks.CharBlock(label='Who said it?', max_length=255, required=False),
                                ),
                                (
                                    'role',
                                    wagtail.core.blocks.CharBlock(label='Their role', max_length=255, required=False),
                                ),
                                (
                                    'organisation',
                                    wagtail.core.blocks.CharBlock(
                                        label='Their organisation', max_length=255, required=False
                                    ),
                                ),
                                (
                                    'organisation_link',
                                    wagtail.core.blocks.URLBlock(
                                        label='Link to organisation site', max_length=255, required=False
                                    ),
                                ),
                            ],
                            template='domestic/blocks/pull_quote_block.html',
                        ),
                    ),
                ],
                blank=True,
                null=True,
            ),
        ),
    ]
