# Generated by Django 2.2.27 on 2022-02-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic', '0033_auto_20220228_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countryguidepage',
            name='intro_cta_five_link',
        ),
        migrations.RemoveField(
            model_name='countryguidepage',
            name='intro_cta_five_title',
        ),
        migrations.RemoveField(
            model_name='countryguidepage',
            name='intro_cta_six_link',
        ),
        migrations.RemoveField(
            model_name='countryguidepage',
            name='intro_cta_six_title',
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='trade_barriers_cta_link',
            field=models.URLField(blank=True, null=True, verbose_name='Trade barriers link'),
        ),
    ]
