# Generated by Django 2.2.28 on 2022-09-12 10:22

import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
from django.db import migrations, models

import core.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_populate_country_iso2'),
        ('domestic', '0034_auto_20220908_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='greatdomestichomepage',
            name='hero_ipad_image',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='core.AltTextImage',
            ),
        ),
        migrations.AddField(
            model_name='greatdomestichomepage',
            name='hero_mobile_image',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='core.AltTextImage',
            ),
        ),
        migrations.AddField(
            model_name='greatdomestichomepage',
            name='hero_smalldesktop_image',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='core.AltTextImage',
            ),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='article_body',
            field=wagtail.core.fields.StreamField(
                [
                    ('text', wagtail.core.blocks.RichTextBlock()),
                    (
                        'image',
                        wagtail.images.blocks.ImageChooserBlock(
                            required=False, template='core/includes/_article_image.html'
                        ),
                    ),
                    (
                        'Video',
                        wagtail.core.blocks.StructBlock(
                            [('video', core.blocks.MediaChooserBlock())], template='core/includes/_article_video.html'
                        ),
                    ),
                    (
                        'pull_quote',
                        wagtail.core.blocks.StructBlock(
                            [
                                ('quote', wagtail.core.blocks.TextBlock()),
                                (
                                    'attribution',
                                    wagtail.core.blocks.CharBlock(label='Who said it?', max_length=255, required=False),
                                ),
                                (
                                    'role',
                                    wagtail.core.blocks.CharBlock(label='Their role', max_length=255, required=False),
                                ),
                                (
                                    'organisation',
                                    wagtail.core.blocks.CharBlock(
                                        label='Their organisation', max_length=255, required=False
                                    ),
                                ),
                                (
                                    'organisation_link',
                                    wagtail.core.blocks.URLBlock(
                                        label='Link to organisation site', max_length=255, required=False
                                    ),
                                ),
                            ],
                            template='domestic/blocks/pull_quote_block.html',
                        ),
                    ),
                ],
                blank=True,
                null=True,
            ),
        ),
    ]
