# Generated by Django 2.2.28 on 2023-01-30 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic', '0036_add_3_column_stream_field_in_article_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='related_page_one',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='wagtailcore.Page',
            ),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='related_page_three',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='wagtailcore.Page',
            ),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='related_page_two',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='wagtailcore.Page',
            ),
        ),
    ]
