# Generated by Django 3.2.16 on 2023-02-09 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ('domestic', '0037_articlepage_related_page_type'),
        ('domestic', '0038_articlepage_additional_related_pages'),
        ('domestic', '0039_articlepage_flexible_related_page_fields'),
        ('domestic', '0040_remove_countryguide_related_pages'),
    ]

    dependencies = [
        ('domestic', '0036_add_3_column_stream_field_in_article_page'),
        ('wagtailcore', '0059_apply_collection_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='related_page_one',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='wagtailcore.page',
            ),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='related_page_three',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='wagtailcore.page',
            ),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='related_page_two',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='wagtailcore.page',
            ),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='related_page_five',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='wagtailcore.page',
            ),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='related_page_four',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='wagtailcore.page',
            ),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='related_page_five_link',
            field=models.CharField(blank=True, max_length=255, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='related_page_five_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='related_page_four_link',
            field=models.CharField(blank=True, max_length=255, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='related_page_four_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='related_page_one_link',
            field=models.CharField(blank=True, max_length=255, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='related_page_one_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='related_page_three_link',
            field=models.CharField(blank=True, max_length=255, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='related_page_three_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='related_page_two_link',
            field=models.CharField(blank=True, max_length=255, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='related_page_two_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title'),
        ),
    ]
