# Generated by Django 2.2.28 on 2023-01-30 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('domestic', '0037_articlepage_related_page_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='related_page_five',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='wagtailcore.Page',
            ),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='related_page_four',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='wagtailcore.Page',
            ),
        ),
    ]
