# Generated by Django 3.2.16 on 2023-02-27 12:02

import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('domestic', '0037_articlepage_flexible_related_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domesticdashboard',
            name='components',
            field=wagtail.core.fields.StreamField(
                [
                    (
                        'route',
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    'route_type',
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ('learn', 'Learning'),
                                            ('plan', 'Export plan'),
                                            ('target', 'Target market'),
                                        ],
                                        icon='redirect',
                                    ),
                                ),
                                ('title', wagtail.core.blocks.CharBlock(max_length=255)),
                                ('body', wagtail.core.blocks.TextBlock(max_length=4096)),
                                ('image', wagtail.images.blocks.ImageChooserBlock()),
                                (
                                    'button',
                                    wagtail.core.blocks.StructBlock(
                                        [
                                            ('label', wagtail.core.blocks.CharBlock(max_length=255)),
                                            (
                                                'link',
                                                wagtail.core.blocks.StructBlock(
                                                    [
                                                        (
                                                            'internal_link',
                                                            wagtail.core.blocks.PageChooserBlock(
                                                                label='Internal link', required=False
                                                            ),
                                                        ),
                                                        (
                                                            'external_link',
                                                            wagtail.core.blocks.CharBlock(
                                                                label='External link', max_length=255, required=False
                                                            ),
                                                        ),
                                                    ],
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                'secondary',
                                                wagtail.core.blocks.BooleanBlock(
                                                    help_text='Determines the appearance of the button. Default is primary.',
                                                    required=False,
                                                ),
                                            ),
                                        ],
                                        icon='cog',
                                        required=False,
                                    ),
                                ),
                            ],
                            icon='pick',
                        ),
                    )
                ],
                blank=True,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='domestichomepage',
            name='button',
            field=wagtail.core.fields.StreamField(
                [
                    (
                        'button',
                        wagtail.core.blocks.StructBlock(
                            [
                                ('label', wagtail.core.blocks.CharBlock(max_length=255)),
                                (
                                    'link',
                                    wagtail.core.blocks.StructBlock(
                                        [
                                            (
                                                'internal_link',
                                                wagtail.core.blocks.PageChooserBlock(
                                                    label='Internal link', required=False
                                                ),
                                            ),
                                            (
                                                'external_link',
                                                wagtail.core.blocks.CharBlock(
                                                    label='External link', max_length=255, required=False
                                                ),
                                            ),
                                        ],
                                        required=False,
                                    ),
                                ),
                                (
                                    'secondary',
                                    wagtail.core.blocks.BooleanBlock(
                                        help_text='Determines the appearance of the button. Default is primary.',
                                        required=False,
                                    ),
                                ),
                            ],
                            icon='cog',
                        ),
                    )
                ],
                blank=True,
                null=True,
            ),
        ),
    ]
