# Generated by Django 2.2.28 on 2023-01-30 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('domestic', '0038_articlepage_additional_related_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='related_page_five_link',
            field=models.CharField(blank=True, max_length=255, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='related_page_five_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='related_page_four_link',
            field=models.CharField(blank=True, max_length=255, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='related_page_four_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='related_page_one_link',
            field=models.CharField(blank=True, max_length=255, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='related_page_one_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='related_page_three_link',
            field=models.CharField(blank=True, max_length=255, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='related_page_three_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='related_page_two_link',
            field=models.CharField(blank=True, max_length=255, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='related_page_two_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='related_page_five',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='wagtailcore.Page',
            ),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='related_page_four',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='wagtailcore.Page',
            ),
        ),
    ]
