# Generated by Django 3.2.18 on 2023-03-16 16:16

import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('domestic', '0038_add_secondary_field_button_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='greatdomestichomepage',
            name='slice_columns',
            field=wagtail.core.fields.StreamField(
                [
                    (
                        'columns',
                        wagtail.core.blocks.StructBlock(
                            [
                                ('title', wagtail.core.blocks.CharBlock()),
                                ('url', wagtail.core.blocks.CharBlock()),
                                ('category', wagtail.core.blocks.CharBlock(required=False)),
                                ('image', wagtail.images.blocks.ImageChooserBlock()),
                                (
                                    'summary',
                                    wagtail.core.blocks.RichTextBlock(
                                        features=[
                                            'h2',
                                            'h3',
                                            'h4',
                                            'bold',
                                            'italic',
                                            'ol',
                                            'ul',
                                            'hr',
                                            'link',
                                            'document-link',
                                        ],
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='greatdomestichomepage',
            name='slice_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
