# Generated by Django 3.2.18 on 2023-03-23 10:55

import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('domestic', '0039_auto_20230316_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greatdomestichomepage',
            name='slice_columns',
            field=wagtail.core.fields.StreamField(
                [
                    (
                        'columns',
                        wagtail.core.blocks.StructBlock(
                            [
                                ('title', wagtail.core.blocks.CharBlock()),
                                ('url', wagtail.core.blocks.CharBlock()),
                                (
                                    'source',
                                    wagtail.core.blocks.CharBlock(
                                        help_text='The source or the type of the link, e.g. GOV.UK/Advice',
                                        required=False,
                                    ),
                                ),
                                ('image', wagtail.images.blocks.ImageChooserBlock()),
                                (
                                    'summary',
                                    wagtail.core.blocks.RichTextBlock(
                                        features=[
                                            'h2',
                                            'h3',
                                            'h4',
                                            'bold',
                                            'italic',
                                            'ol',
                                            'ul',
                                            'hr',
                                            'link',
                                            'document-link',
                                        ],
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
            ),
        ),
    ]
