# Generated by Django 3.2.16 on 2023-02-07 16:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('domestic', '0039_articlepage_flexible_related_page_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countryguidepage',
            name='related_page_five',
        ),
        migrations.RemoveField(
            model_name='countryguidepage',
            name='related_page_four',
        ),
    ]
