# Generated by Django 3.2.18 on 2023-04-12 09:56

import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
from django.db import migrations

import core.blocks


class Migration(migrations.Migration):
    dependencies = [
        ('domestic', '0040_added_form_to_article_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='article_body',
            field=wagtail.core.fields.StreamField(
                [
                    ('text', wagtail.core.blocks.RichTextBlock()),
                    (
                        'form',
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    'type',
                                    wagtail.core.blocks.ChoiceBlock(
                                        blank=False, choices=[('Short', 'Short'), ('Long', 'Long')], null=False
                                    ),
                                ),
                                ('email_subject', wagtail.core.blocks.TextBlock(required=True)),
                                ('email_title', wagtail.core.blocks.TextBlock(required=True)),
                                ('email_body', wagtail.core.blocks.TextBlock(required=True)),
                            ]
                        ),
                    ),
                    (
                        'image',
                        wagtail.images.blocks.ImageChooserBlock(
                            required=False, template='core/includes/_article_image.html'
                        ),
                    ),
                    (
                        'Video',
                        wagtail.core.blocks.StructBlock(
                            [('video', core.blocks.MediaChooserBlock())], template='core/includes/_article_video.html'
                        ),
                    ),
                    (
                        'Columns',
                        wagtail.core.blocks.StreamBlock(
                            [
                                (
                                    'column',
                                    wagtail.core.blocks.StructBlock(
                                        [
                                            (
                                                'title',
                                                wagtail.core.blocks.CharBlock(
                                                    label='Title', max_length=255, required=False
                                                ),
                                            ),
                                            (
                                                'image',
                                                wagtail.images.blocks.ImageChooserBlock(
                                                    label='Hero Image', required=False
                                                ),
                                            ),
                                            (
                                                'description',
                                                wagtail.core.blocks.RichTextBlock(
                                                    features=[
                                                        'h2',
                                                        'h3',
                                                        'h4',
                                                        'bold',
                                                        'italic',
                                                        'ol',
                                                        'ul',
                                                        'hr',
                                                        'link',
                                                        'document-link',
                                                    ],
                                                    label='Description',
                                                    required=False,
                                                ),
                                            ),
                                            ('link', wagtail.core.blocks.URLBlock(label='Title link', required=False)),
                                        ]
                                    ),
                                )
                            ],
                            help_text='Add two or three columns text',
                            max_num=3,
                            min_num=3,
                            template='core/includes/_columns.html',
                        ),
                    ),
                    (
                        'cta',
                        wagtail.core.blocks.StructBlock(
                            [
                                ('title', wagtail.core.blocks.CharBlock(label='Title', max_length=255, required=True)),
                                (
                                    'teaser',
                                    wagtail.core.blocks.TextBlock(label='Teaser', max_length=255, required=True),
                                ),
                                (
                                    'link_label',
                                    wagtail.core.blocks.CharBlock(label='Link label', max_length=255, required=True),
                                ),
                                ('link', wagtail.core.blocks.CharBlock(label='Link', max_length=255, required=True)),
                            ],
                            template='domestic/blocks/cta.html',
                        ),
                    ),
                    (
                        'pull_quote',
                        wagtail.core.blocks.StructBlock(
                            [
                                ('quote', wagtail.core.blocks.TextBlock()),
                                (
                                    'attribution',
                                    wagtail.core.blocks.CharBlock(label='Who said it?', max_length=255, required=False),
                                ),
                                (
                                    'role',
                                    wagtail.core.blocks.CharBlock(label='Their role', max_length=255, required=False),
                                ),
                                (
                                    'organisation',
                                    wagtail.core.blocks.CharBlock(
                                        label='Their organisation', max_length=255, required=False
                                    ),
                                ),
                                (
                                    'organisation_link',
                                    wagtail.core.blocks.URLBlock(
                                        label='Link to organisation site', max_length=255, required=False
                                    ),
                                ),
                            ],
                            template='domestic/blocks/pull_quote_block.html',
                        ),
                    ),
                ],
                blank=True,
                null=True,
            ),
        ),
    ]
