# Generated by Django 3.2.18 on 2023-04-14 13:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('domestic', '0040_alter_greatdomestichomepage_slice_columns'),
        ('domestic', '0041_alter_articlepage_article_body'),
    ]

    operations = []
