# Generated by Django 3.2.18 on 2023-05-05 13:41

from django.db import migrations

import core.blocks
import domestic.models
import wagtail.blocks
import wagtail.contrib.table_block.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ('domestic', '0043_auto_20230503_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='article_body',
            field=wagtail.fields.StreamField(
                [
                    ('text', wagtail.blocks.RichTextBlock()),
                    (
                        'form',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'type',
                                    wagtail.blocks.ChoiceBlock(
                                        blank=False, choices=[('Short', 'Short'), ('Long', 'Long')], null=False
                                    ),
                                ),
                                ('email_subject', wagtail.blocks.TextBlock(required=True)),
                                ('email_title', wagtail.blocks.TextBlock(required=True)),
                                ('email_body', wagtail.blocks.TextBlock(required=True)),
                            ]
                        ),
                    ),
                    (
                        'image',
                        wagtail.images.blocks.ImageChooserBlock(
                            required=False, template='core/includes/_article_image.html'
                        ),
                    ),
                    (
                        'Video',
                        wagtail.blocks.StructBlock(
                            [('video', core.blocks.MediaChooserBlock())], template='core/includes/_article_video.html'
                        ),
                    ),
                    (
                        'Columns',
                        wagtail.blocks.StreamBlock(
                            [
                                (
                                    'column',
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                'title',
                                                wagtail.blocks.CharBlock(label='Title', max_length=255, required=False),
                                            ),
                                            (
                                                'image',
                                                wagtail.images.blocks.ImageChooserBlock(
                                                    label='Hero Image', required=False
                                                ),
                                            ),
                                            (
                                                'description',
                                                wagtail.blocks.RichTextBlock(
                                                    features=[
                                                        'h2',
                                                        'h3',
                                                        'h4',
                                                        'bold',
                                                        'italic',
                                                        'ol',
                                                        'ul',
                                                        'hr',
                                                        'link',
                                                        'document-link',
                                                    ],
                                                    label='Description',
                                                    required=False,
                                                ),
                                            ),
                                            ('link', wagtail.blocks.URLBlock(label='Title link', required=False)),
                                        ]
                                    ),
                                )
                            ],
                            help_text='Add two or three columns text',
                            max_num=3,
                            min_num=3,
                            template='core/includes/_columns.html',
                        ),
                    ),
                    (
                        'cta',
                        wagtail.blocks.StructBlock(
                            [
                                ('title', wagtail.blocks.CharBlock(label='Title', max_length=255, required=True)),
                                ('teaser', wagtail.blocks.TextBlock(label='Teaser', max_length=255, required=True)),
                                (
                                    'link_label',
                                    wagtail.blocks.CharBlock(label='Link label', max_length=255, required=True),
                                ),
                                ('link', wagtail.blocks.CharBlock(label='Link', max_length=255, required=True)),
                            ],
                            template='domestic/blocks/cta.html',
                        ),
                    ),
                    (
                        'pull_quote',
                        wagtail.blocks.StructBlock(
                            [
                                ('quote', wagtail.blocks.TextBlock()),
                                (
                                    'attribution',
                                    wagtail.blocks.CharBlock(label='Who said it?', max_length=255, required=False),
                                ),
                                ('role', wagtail.blocks.CharBlock(label='Their role', max_length=255, required=False)),
                                (
                                    'organisation',
                                    wagtail.blocks.CharBlock(
                                        label='Their organisation', max_length=255, required=False
                                    ),
                                ),
                                (
                                    'organisation_link',
                                    wagtail.blocks.URLBlock(
                                        label='Link to organisation site', max_length=255, required=False
                                    ),
                                ),
                            ],
                            template='domestic/blocks/pull_quote_block.html',
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name='countryguidepage',
            name='accordions',
            field=wagtail.fields.StreamField(
                [
                    (
                        'industries',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'icon',
                                    wagtail.images.blocks.ImageChooserBlock(label='Industry icon', required=False),
                                ),
                                ('title', wagtail.blocks.CharBlock(label='Industry title', max_length=255)),
                                ('teaser', wagtail.blocks.TextBlock(label='Industry teaser', required=False)),
                                (
                                    'subsections',
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                'subsection',
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            'icon',
                                                            wagtail.images.blocks.ImageChooserBlock(
                                                                label='Subsection icon', required=False
                                                            ),
                                                        ),
                                                        (
                                                            'heading',
                                                            wagtail.blocks.CharBlock(
                                                                label='Subsection heading', max_length=255
                                                            ),
                                                        ),
                                                        (
                                                            'body',
                                                            wagtail.blocks.TextBlock(
                                                                label='Subsection body', required=False
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            )
                                        ],
                                        block_counts={'subsection': {'max_num': 3}},
                                        required=False,
                                    ),
                                ),
                                (
                                    'statistics',
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                'statistic',
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        ('number', wagtail.blocks.CharBlock(max_length=255)),
                                                        ('heading', wagtail.blocks.CharBlock(max_length=255)),
                                                        (
                                                            'smallprint',
                                                            wagtail.blocks.CharBlock(max_length=255, required=False),
                                                        ),
                                                    ],
                                                    icon='fa-calculator',
                                                    required=False,
                                                ),
                                            )
                                        ],
                                        blank=True,
                                        null=True,
                                        required=False,
                                        validators=[core.blocks.general_statistics_streamfield_validation],
                                    ),
                                ),
                                (
                                    'case_study',
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                'title',
                                                wagtail.blocks.CharBlock(
                                                    label='Case study title', max_length=255, required=False
                                                ),
                                            ),
                                            (
                                                'hero_image',
                                                wagtail.images.blocks.ImageChooserBlock(
                                                    label='Case study hero image', required=False
                                                ),
                                            ),
                                            (
                                                'description',
                                                wagtail.blocks.TextBlock(
                                                    label='Case study description', required=False
                                                ),
                                            ),
                                            (
                                                'button_text',
                                                wagtail.blocks.CharBlock(
                                                    label='Case study button text', max_length=255, required=False
                                                ),
                                            ),
                                            (
                                                'button_link',
                                                wagtail.blocks.URLBlock(label='Case study button link', required=False),
                                            ),
                                        ],
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
                validators=[domestic.models.industry_accordions_validation],
            ),
        ),
        migrations.AlterField(
            model_name='countryguidepage',
            name='main_statistics',
            field=wagtail.fields.StreamField(
                [
                    (
                        'statistic',
                        wagtail.blocks.StructBlock(
                            [
                                ('number', wagtail.blocks.CharBlock(max_length=255)),
                                ('heading', wagtail.blocks.CharBlock(max_length=255)),
                                ('smallprint', wagtail.blocks.CharBlock(max_length=255, required=False)),
                            ],
                            icon='fa-calculator',
                            max_num=6,
                            min_num=2,
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
                validators=[domestic.models.main_statistics_validation],
            ),
        ),
        migrations.AlterField(
            model_name='domesticdashboard',
            name='components',
            field=wagtail.fields.StreamField(
                [
                    (
                        'route',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'route_type',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ('learn', 'Learning'),
                                            ('plan', 'Export plan'),
                                            ('target', 'Target market'),
                                        ],
                                        icon='redirect',
                                    ),
                                ),
                                ('title', wagtail.blocks.CharBlock(max_length=255)),
                                ('body', wagtail.blocks.TextBlock(max_length=4096)),
                                ('image', wagtail.images.blocks.ImageChooserBlock()),
                                (
                                    'button',
                                    wagtail.blocks.StructBlock(
                                        [
                                            ('label', wagtail.blocks.CharBlock(max_length=255)),
                                            (
                                                'link',
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            'internal_link',
                                                            wagtail.blocks.PageChooserBlock(
                                                                label='Internal link', required=False
                                                            ),
                                                        ),
                                                        (
                                                            'external_link',
                                                            wagtail.blocks.CharBlock(
                                                                label='External link', max_length=255, required=False
                                                            ),
                                                        ),
                                                    ],
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                'secondary',
                                                wagtail.blocks.BooleanBlock(
                                                    help_text='Determines the appearance of the button. Default is primary.',
                                                    required=False,
                                                ),
                                            ),
                                        ],
                                        icon='cog',
                                        required=False,
                                    ),
                                ),
                            ],
                            icon='pick',
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name='domestichomepage',
            name='button',
            field=wagtail.fields.StreamField(
                [
                    (
                        'button',
                        wagtail.blocks.StructBlock(
                            [
                                ('label', wagtail.blocks.CharBlock(max_length=255)),
                                (
                                    'link',
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                'internal_link',
                                                wagtail.blocks.PageChooserBlock(label='Internal link', required=False),
                                            ),
                                            (
                                                'external_link',
                                                wagtail.blocks.CharBlock(
                                                    label='External link', max_length=255, required=False
                                                ),
                                            ),
                                        ],
                                        required=False,
                                    ),
                                ),
                                (
                                    'secondary',
                                    wagtail.blocks.BooleanBlock(
                                        help_text='Determines the appearance of the button. Default is primary.',
                                        required=False,
                                    ),
                                ),
                            ],
                            icon='cog',
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name='greatdomestichomepage',
            name='campaign',
            field=wagtail.fields.StreamField(
                [
                    (
                        'campaign',
                        wagtail.blocks.StructBlock(
                            [
                                ('heading', wagtail.blocks.CharBlock()),
                                ('subheading', wagtail.blocks.CharBlock()),
                                ('related_link_text', wagtail.blocks.CharBlock()),
                                ('related_link_url', wagtail.blocks.CharBlock()),
                                ('image', wagtail.images.blocks.ImageChooserBlock()),
                                ('video', core.blocks.VideoChooserBlock()),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name='greatdomestichomepage',
            name='how_dit_helps_columns',
            field=wagtail.fields.StreamField(
                [
                    (
                        'columns',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'source',
                                    wagtail.blocks.CharBlock(
                                        help_text='The source or the type of the link, e.g. GOV.UK/Advice'
                                    ),
                                ),
                                ('text', wagtail.blocks.CharBlock()),
                                ('url', wagtail.blocks.CharBlock()),
                                ('image', wagtail.images.blocks.ImageChooserBlock(required=False)),
                                ('content', wagtail.blocks.RichTextBlock()),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name='greatdomestichomepage',
            name='magna_ctas_columns',
            field=wagtail.fields.StreamField(
                [
                    (
                        'columns',
                        wagtail.blocks.StructBlock(
                            [
                                ('text', wagtail.blocks.CharBlock()),
                                ('url', wagtail.blocks.CharBlock()),
                                ('image', wagtail.images.blocks.ImageChooserBlock(required=False)),
                                (
                                    'content',
                                    wagtail.blocks.RichTextBlock(
                                        features=[
                                            'h2',
                                            'h3',
                                            'h4',
                                            'bold',
                                            'italic',
                                            'ol',
                                            'ul',
                                            'hr',
                                            'link',
                                            'document-link',
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name='greatdomestichomepage',
            name='slice_columns',
            field=wagtail.fields.StreamField(
                [
                    (
                        'columns',
                        wagtail.blocks.StructBlock(
                            [
                                ('title', wagtail.blocks.CharBlock()),
                                ('url', wagtail.blocks.CharBlock()),
                                (
                                    'source',
                                    wagtail.blocks.CharBlock(
                                        help_text='The source or the type of the link, e.g. GOV.UK/Advice',
                                        required=False,
                                    ),
                                ),
                                ('image', wagtail.images.blocks.ImageChooserBlock()),
                                (
                                    'summary',
                                    wagtail.blocks.RichTextBlock(
                                        features=[
                                            'h2',
                                            'h3',
                                            'h4',
                                            'bold',
                                            'italic',
                                            'ol',
                                            'ul',
                                            'hr',
                                            'link',
                                            'document-link',
                                        ],
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name='greatdomestichomepage',
            name='what_is_new_pages',
            field=wagtail.fields.StreamField(
                [
                    (
                        'pages',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'source',
                                    wagtail.blocks.CharBlock(
                                        help_text='The source or the type of the link, e.g. GOV.UK/Advice'
                                    ),
                                ),
                                ('text', wagtail.blocks.CharBlock()),
                                ('url', wagtail.blocks.CharBlock()),
                                ('image', wagtail.images.blocks.ImageChooserBlock(required=False)),
                                ('content', wagtail.blocks.RichTextBlock()),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name='guidancepage',
            name='body',
            field=wagtail.fields.StreamField(
                [
                    (
                        'text',
                        wagtail.blocks.RichTextBlock(
                            features=[
                                'h1',
                                'h2',
                                'h3',
                                'h4',
                                'bold',
                                'italic',
                                'ol',
                                'ul',
                                'hr',
                                'link',
                                'document-link',
                            ]
                        ),
                    ),
                    (
                        'table',
                        wagtail.contrib.table_block.blocks.TableBlock(
                            table_options={
                                'autoColumnSize': False,
                                'colHeaders': True,
                                'editor': 'text',
                                'height': 108,
                                'minSpareRows': 0,
                                'renderer': 'text',
                                'rowHeaders': False,
                                'startCols': 2,
                                'startRows': 3,
                                'stretchH': 'all',
                            }
                        ),
                    ),
                ],
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name='manuallyconfigurabletopiclandingpage',
            name='panels',
            field=wagtail.fields.StreamField(
                [
                    (
                        'panel',
                        wagtail.blocks.StructBlock(
                            [
                                ('link_text', wagtail.blocks.CharBlock()),
                                ('link_url', wagtail.blocks.CharBlock()),
                                ('image', wagtail.images.blocks.ImageChooserBlock(required=False)),
                                ('description', wagtail.blocks.TextBlock()),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name='performancedashboardpage',
            name='body',
            field=wagtail.fields.StreamField(
                [
                    (
                        'data_block',
                        wagtail.blocks.StructBlock(
                            [
                                ('data_title', wagtail.blocks.CharBlock(max_length=100)),
                                ('data_value', wagtail.blocks.CharBlock(max_length=100)),
                                ('data_period', wagtail.blocks.CharBlock(max_length=100)),
                                (
                                    'data_description',
                                    wagtail.blocks.RichTextBlock(
                                        features=[
                                            'h2',
                                            'h3',
                                            'h4',
                                            'bold',
                                            'italic',
                                            'ol',
                                            'ul',
                                            'hr',
                                            'link',
                                            'document-link',
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name='tradefinancepage',
            name='advantages',
            field=wagtail.fields.StreamField(
                [
                    (
                        'advantage',
                        wagtail.blocks.StructBlock(
                            [
                                ('icon', wagtail.images.blocks.ImageChooserBlock()),
                                (
                                    'content',
                                    wagtail.blocks.RichTextBlock(
                                        features=[
                                            'h2',
                                            'h3',
                                            'h4',
                                            'bold',
                                            'italic',
                                            'ol',
                                            'ul',
                                            'hr',
                                            'link',
                                            'document-link',
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                use_json_field=True,
            ),
        ),
    ]
