# Generated by Django 4.1.10 on 2023-09-05 08:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('domestic', '0046_alter_articlepage_article_body_and_more'),
        ('domestic', '0046_replace_wagtail_font_awesome_icons'),
    ]

    operations = []
