# Generated by Django 4.1.10 on 2023-09-14 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0109_allow_4_columns_on_microsites'),
        ('domestic', '0047_merge_20230905_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='greatdomestichomepage',
            name='dep_primary_cta_image',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='core.alttextimage',
            ),
        ),
        migrations.AddField(
            model_name='greatdomestichomepage',
            name='dep_primary_cta_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='greatdomestichomepage',
            name='dep_primary_cta_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='greatdomestichomepage',
            name='dep_primary_cta_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='greatdomestichomepage',
            name='dep_secondary_cta_image',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='core.alttextimage',
            ),
        ),
        migrations.AddField(
            model_name='greatdomestichomepage',
            name='dep_secondary_cta_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='greatdomestichomepage',
            name='dep_secondary_cta_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='greatdomestichomepage',
            name='dep_secondary_cta_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='greatdomestichomepage',
            name='dep_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
