# Generated by Django 4.1.10 on 2023-09-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('domestic', '0047_merge_20230905_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='greatdomestichomepage',
            name='dep_primary_cta_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='greatdomestichomepage',
            name='dep_primary_cta_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='greatdomestichomepage',
            name='dep_primary_cta_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='greatdomestichomepage',
            name='dep_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
