# Generated by Django 4.1.10 on 2023-09-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('domestic', '0048_greatdomestichomepage_dep_primary_cta_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='greatdomestichomepage',
            name='dep_secondary_cta_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='greatdomestichomepage',
            name='dep_secondary_cta_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='greatdomestichomepage',
            name='dep_secondary_cta_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
