# Generated by Django 4.1.10 on 2023-10-04 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('domestic', '0049_alter_articlepage_article_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyTask',
            fields=[
                (
                    'task_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='wagtailcore.task',
                    ),
                ),
            ],
            options={
                'managed': False,
            },
            bases=('wagtailcore.task',),
        ),
    ]
