# Generated by Django 4.1.10 on 2023-10-04 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0115_alter_micrositepage_page_body'),
        ('domestic', '0049_alter_articlepage_article_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='greatdomestichomepage',
            name='hero_bigdesktop_image',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='core.alttextimage',
            ),
        ),
    ]
