# Generated by Django 4.1.10 on 2023-12-06 09:56

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('domestic', '0051_alter_domesticdashboard_components_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='greatdomestichomepage',
            name='dep_cards',
            field=wagtail.fields.StreamField(
                [
                    (
                        'cards',
                        wagtail.blocks.StreamBlock(
                            [
                                (
                                    'card',
                                    wagtail.blocks.StructBlock(
                                        [
                                            ('link_text', wagtail.blocks.CharBlock(label='Link text')),
                                            ('link_url', wagtail.blocks.CharBlock(label='Link url')),
                                        ]
                                    ),
                                )
                            ],
                            block_counts={'card': {'min_num': 6}},
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
