# Generated by Django 4.2.7 on 2024-02-14 14:55

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0133_alter_detailpage_body'),
        ('domestic', '0054_findabuyerhomepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='findabuyerhomepage',
            name='body_image',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='core.alttextimage',
            ),
        ),
        migrations.AddField(
            model_name='findabuyerhomepage',
            name='body_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Body title'),
        ),
        migrations.AlterField(
            model_name='findabuyerhomepage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
