# Generated by Django 4.2.7 on 2024-02-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic', '0056_alter_articlepage_article_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='greatdomestichomepage',
            name='dep_sub_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
