# Generated by Django 4.2.11 on 2024-06-25 14:22

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations

import domestic.models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic', '0061_countryguidepage_country_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryguidepage',
            name='sector_links',
            field=wagtail.fields.StreamField(
                [
                    (
                        'sector_link',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'icon',
                                    wagtail.images.blocks.ImageChooserBlock(label='Industry icon', required=False),
                                ),
                                ('title', wagtail.blocks.CharBlock(label='Industry title', max_length=255)),
                                ('page', wagtail.blocks.PageChooserBlock(label='Page')),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
                validators=[domestic.models.industry_accordions_validation],
            ),
        ),
    ]
