# Generated by Django 4.2.14 on 2024-08-06 12:18

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0153_taskbasedcategorypage_taskbasedsubcategorypage'),
        ('domestic', '0063_domesticdashboard_canonical_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='country_tags',
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text='A comma-separated list of tags.',
                through='core.CountryTagged',
                to='core.CountryTag',
                verbose_name='Country Tags',
            ),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='region_tags',
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text='A comma-separated list of tags.',
                through='core.RegionTagged',
                to='core.PersonalisationRegionTag',
                verbose_name='Region Tags',
            ),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='sector_tags',
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text='A comma-separated list of tags.',
                through='core.SectorTagged',
                to='core.SectorTag',
                verbose_name='Sector Tags',
            ),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='type_of_export_tags',
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text='A comma-separated list of tags.',
                through='core.TypeOfExportTagged',
                to='core.TypeOfExportTag',
                verbose_name='Type of Export Tags',
            ),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='region_tags',
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text='A comma-separated list of tags.',
                through='core.RegionTagged',
                to='core.PersonalisationRegionTag',
                verbose_name='Region Tags',
            ),
        ),
    ]
