# Generated by Django 4.2.15 on 2024-09-20 11:34

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0158_testcountrytagged'),
        ('domestic', '0064_articlepage_country_tags_articlepage_region_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepage',
            name='region_tags',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='sector_tags',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='type_of_export_tags',
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='country_tags',
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text='A comma-separated list of tags.',
                through='core.TestCountryTagged',
                to='core.CountryTag',
                verbose_name='Country Tags',
            ),
        ),
    ]
