# Generated by Django 4.2.14 on 2024-09-30 08:24

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0158_remove_curatedlistpage_country_tags_and_more'),
        ('domestic', '0064_articlepage_country_tags_articlepage_region_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepage',
            name='type_of_export_tags',
        ),
        migrations.RemoveField(
            model_name='countryguidepage',
            name='type_of_export_tags',
        ),
        migrations.CreateModel(
            name='TradingBlocTaggedCountryGuidePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'content_object',
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='trading_bloc_tagged_items',
                        to='domestic.countryguidepage',
                    ),
                ),
                (
                    'tag',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='trading_bloc_tagged_market_guide',
                        to='core.personalisationtradingbloctag',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TradingBlocTaggedArticlePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'content_object',
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='trading_bloc_tagged_items',
                        to='domestic.articlepage',
                    ),
                ),
                (
                    'tag',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='trading_bloc_tagged_article',
                        to='core.personalisationtradingbloctag',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SectorTaggedCountryGuidePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'content_object',
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='sector_tagged_items',
                        to='domestic.countryguidepage',
                    ),
                ),
                (
                    'tag',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='sector_tagged_market_guide',
                        to='core.sectortag',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SectorTaggedArticlePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'content_object',
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='sector_tagged_items',
                        to='domestic.articlepage',
                    ),
                ),
                (
                    'tag',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='sector_tagged_article',
                        to='core.sectortag',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegionTaggedCountryGuidePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'content_object',
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='region_tagged_items',
                        to='domestic.countryguidepage',
                    ),
                ),
                (
                    'tag',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='region_tagged_market_guide',
                        to='core.personalisationregiontag',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegionTaggedArticlePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'content_object',
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='region_tagged_items',
                        to='domestic.articlepage',
                    ),
                ),
                (
                    'tag',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='region_tagged_article',
                        to='core.personalisationregiontag',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CountryTaggedCountryGuidePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'content_object',
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='country_tagged_items',
                        to='domestic.countryguidepage',
                    ),
                ),
                (
                    'tag',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='country_tagged_market_guide',
                        to='core.countrytag',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CountryTaggedArticlePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'content_object',
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='country_tagged_items',
                        to='domestic.articlepage',
                    ),
                ),
                (
                    'tag',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='country_tagged_article',
                        to='core.countrytag',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='articlepage',
            name='trading_bloc_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text='A comma-separated list of tags.',
                through='domestic.TradingBlocTaggedArticlePage',
                to='core.PersonalisationTradingBlocTag',
                verbose_name='Trading bloc tags',
            ),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='trading_bloc_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text='A comma-separated list of tags.',
                through='domestic.TradingBlocTaggedCountryGuidePage',
                to='core.PersonalisationTradingBlocTag',
                verbose_name='Trading bloc tags',
            ),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='country_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text='A comma-separated list of tags.',
                through='domestic.CountryTaggedArticlePage',
                to='core.CountryTag',
                verbose_name='Country tags',
            ),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='region_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text='A comma-separated list of tags.',
                through='domestic.RegionTaggedArticlePage',
                to='core.PersonalisationRegionTag',
                verbose_name='Region tags',
            ),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='sector_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text='A comma-separated list of tags.',
                through='domestic.SectorTaggedArticlePage',
                to='core.SectorTag',
                verbose_name='Sector tags',
            ),
        ),
        migrations.AlterField(
            model_name='countryguidepage',
            name='country_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text='A comma-separated list of tags.',
                through='domestic.CountryTaggedCountryGuidePage',
                to='core.CountryTag',
                verbose_name='Country tags',
            ),
        ),
        migrations.AlterField(
            model_name='countryguidepage',
            name='region_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text='A comma-separated list of tags.',
                through='domestic.RegionTaggedCountryGuidePage',
                to='core.PersonalisationRegionTag',
                verbose_name='Region tags',
            ),
        ),
        migrations.AlterField(
            model_name='countryguidepage',
            name='sector_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text='A comma-separated list of tags.',
                through='domestic.SectorTaggedCountryGuidePage',
                to='core.SectorTag',
                verbose_name='Sector tags',
            ),
        ),
    ]
