# Generated by Django 4.2.15 on 2024-09-20 11:40

import modelcluster.contrib.taggit
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0158_testcountrytagged'),
        ('domestic', '0065_remove_articlepage_region_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='country_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text='A comma-separated list of tags.',
                through='core.TestCountryTagged',
                to='core.CountryTag',
                verbose_name='Country Tags',
            ),
        ),
    ]
