# Generated by Django 4.2.16 on 2024-12-09 14:30

import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic', '0065_remove_articlepage_type_of_export_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlelistingpage',
            name='hero_image',
        ),
        migrations.AddField(
            model_name='articlelistingpage',
            name='article_pages',
            field=wagtail.fields.StreamField(
                [
                    (
                        'article_link',
                        wagtail.blocks.StructBlock(
                            [
                                ('link_text', wagtail.blocks.CharBlock(label='Link text', max_length=255)),
                                (
                                    'link_page',
                                    wagtail.blocks.PageChooserBlock(
                                        label='Choose article page', page_type=['domestic.ArticlePage']
                                    ),
                                ),
                            ]
                        ),
                    ),
                    ('text_block', wagtail.blocks.RichTextBlock()),
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AddField(
            model_name='articlelistingpage',
            name='use_updated_link_format',
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text='Show the updated listing page with custom text and links instead of auto-generated button links',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='articlelistingpage',
            name='hero_teaser',
            field=models.CharField(
                default='',
                help_text='Listing page heading. This is the large heading at the top of the page.',
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
