# Generated by Django 4.2.16 on 2024-12-13 10:00

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic', '0066_remove_articlelistingpage_hero_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='greatdomestichomepage',
            name='notification_body',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='greatdomestichomepage',
            name='notification_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
