# Generated by Django 4.2.15 on 2024-09-20 13:10

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0159_remove_testcountrytagged_content_type_and_more'),
        ('domestic', '0066_alter_articlepage_country_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='country_tags',
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text='A comma-separated list of tags.',
                through='core.TestCountryTagged',
                to='core.CountryTag',
                verbose_name='Country Tags',
            ),
        ),
    ]
