# Generated by Django 4.2.19 on 2025-04-02 10:28

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic', '0068_remove_articlelistingpage_struct_org_actions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryguidepage',
            name='notification_body',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='notification_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
