# Generated by Django 4.2.19 on 2025-04-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic', '0069_countryguidepage_notification_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlelistingpage',
            name='hero_teaser',
            field=models.CharField(
                blank=True,
                help_text='Listing page heading. This is the large heading at the top of the page.',
                max_length=255,
                null=True,
            ),
        ),
    ]
