# Generated by Django 2.2.19 on 2021-02-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='ContactSuccessSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'seo_title',
                    models.CharField(
                        blank=True,
                        help_text="Optional. 'Search Engine Friendly' title. This will appear at the top of the browser window.",
                        max_length=255,
                        verbose_name='Page title',
                    ),
                ),
                ('search_description', models.TextField(blank=True, verbose_name='Search description')),
                (
                    'slug',
                    models.CharField(
                        choices=[
                            ('contact-success-form', 'Contact domestic form success'),
                            ('contact-events-success-form', 'Contact Events form success'),
                            ('contact-dso-success-form', 'Contact Defence and Security Organisation form success'),
                            ('contact-export-advice-success-form', 'Contact exporting from the UK form success'),
                            ('contact-feedback-success-form', 'Contact feedback form success'),
                            ('contact-find-companies-success-form', 'Contact find UK companies form success'),
                            ('contact-international-success-form', 'Contact international form success'),
                            ('contact-soo-success-form', 'Contact Selling Online Overseas form success'),
                            ('contact-beis-success', 'Contact BEIS form success'),
                            ('contact-defra-success', 'Contact DEFRA form success'),
                        ],
                        help_text='Select the use-case for this snippet from a fixed list of choices',
                        max_length=255,
                        unique=True,
                        verbose_name='Purpose',
                    ),
                ),
                (
                    'internal_title',
                    models.CharField(
                        editable=False, max_length=255, verbose_name='Title (internal use only - not publicly shown)'
                    ),
                ),
                ('heading', models.CharField(max_length=255, verbose_name='Title')),
                ('body_text', models.CharField(max_length=255, verbose_name='Body text')),
                ('next_title', models.CharField(max_length=255, verbose_name='Next title')),
                ('next_body_text', models.CharField(max_length=255, verbose_name='Next body text')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
