# Generated by Django 2.2.23 on 2021-06-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contactpagecontentsnippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsuccesssnippet',
            name='breadcrumbs_label',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
