# Generated by Django 2.2.24 on 2021-06-15 17:05

import wagtail.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_bootstrap_transition_period_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsGuidanceSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'slug',
                    models.CharField(
                        help_text='Select the use-case for this snippet from a fixed list of choices',
                        max_length=255,
                        unique=True,
                        verbose_name='Purpose',
                    ),
                ),
                (
                    'internal_title',
                    models.CharField(
                        editable=False, max_length=255, verbose_name='Title (internal use only - not publicly shown)'
                    ),
                ),
                (
                    'seo_title',
                    models.CharField(
                        blank=True,
                        help_text="Optional. 'Search Engine Friendly' title. This will appear at the top of the browser window.",
                        max_length=255,
                        verbose_name='Page title',
                    ),
                ),
                ('search_description', models.TextField(blank=True, verbose_name='Search description')),
                ('title', models.CharField(max_length=255, verbose_name='heading')),
                ('body', wagtail.core.fields.RichTextField(verbose_name='Body content')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
