# Generated by Django 2.2.24 on 2021-06-16 16:53

from django.db import migrations

from core import snippet_slugs


def forwards(apps, schema_editor):
    ContactSuccessSnippet = apps.get_model(
        'contact',
        'ContactSuccessSnippet',
    )

    try:
        ContactSuccessSnippet.objects.get(
            slug=snippet_slugs.HELP_FORM_SUCCESS,
        )
    except ContactSuccessSnippet.DoesNotExist:
        snippet = ContactSuccessSnippet(
            slug=snippet_slugs.HELP_FORM_SUCCESS,
            internal_title='Contact domestic form success page content',
            breadcrumbs_label='Contact',
            heading='We have received your enquiry. Thank you',
            body_text="We've also sent an email with the information you've provided.",
            next_title='What happens next',
            next_body_text='Our team will have a look at what you need and will come back to you soon',
        )
        snippet.save()


def backwards(apps, schema_editor):
    ContactSuccessSnippet = apps.get_model(
        'contact',
        'ContactSuccessSnippet',
    )

    ContactSuccessSnippet.objects.filter(slug=snippet_slugs.HELP_FORM_SUCCESS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_data_populate_guidance_snippet_great_account'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
