# Generated by Django 2.2.24 on 2021-06-29 09:38

from django.db import migrations

from core import snippet_slugs

snippet_specs = [
    {
        'slug': snippet_slugs.HELP_EXOPP_ALERTS_IRRELEVANT,
        'internal_title': 'Guidance - Daily alerts are not relevant',
        'title': 'My daily email alerts are not relevant to me.',
        'body': (
            '<p>We would suggest you tailor your email alerts to make them more specific.</p>'
            '<ol>'
            "<li>Click on 'manage your alerts' at the bottom of your email alert</li>"
            "<li>Unsubscribe from alerts for 'all opportunities' and other generic terms</li>"
            '<li>Go to the export opportunities site at <a href="https://great.gov.uk/export-opportunities/">https://great.gov.uk/export-opportunities/</a> '
            'and search for the specific product or service (and country/region if relevant) you want to get subscriptions for</li>'
            "<li>You'll be prompted to sign up for an email alert for that term</li>"
            '</ol>'
        ),
    },
    {
        'slug': snippet_slugs.HELP_EXOPPS_NO_RESPONSE,
        'internal_title': 'Guidance - Export Opportunity application no response',
        'title': "I haven't had a response from the opportunity I applied for.",
        'body': (
            '<p><a href="/contact/domestic/">Submit an enquiry</a>. You should include the name of the export opportunity you applied for.</p>'
        ),
    },
    # NB snippet_slugs.HELP_EXPORTING_TO_UK is NOT bootstrapped via data migration
]


def forwards(apps, schema_editor):
    ContactUsGuidanceSnippet = apps.get_model(
        'contact',
        'ContactUsGuidanceSnippet',
    )

    for spec in snippet_specs:
        _slug = spec['slug']

        try:
            ContactUsGuidanceSnippet.objects.get(slug=_slug)
        except ContactUsGuidanceSnippet.DoesNotExist:
            snippet = ContactUsGuidanceSnippet(**spec)
            snippet.save()


def backwards(apps, schema_editor):
    ContactUsGuidanceSnippet = apps.get_model(
        'contact',
        'ContactUsGuidanceSnippet',
    )

    for spec in snippet_specs:
        ContactUsGuidanceSnippet.objects.filter(slug=spec['slug']).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('contact', '0009_data__bootstrap_more_success_snippets'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
