# Generated by Django 2.2.27 on 2022-03-31 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_data_bootstrap_remaining_guidance_snippets'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactPageContentSnippet',
        ),
    ]
