# Generated by Django 4.2.20 on 2025-05-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'international_investment_support_directory',
            '0002_remove_investmentsupportdirectoryindexpage_struct_org_actions_and_more',
        ),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentsupportdirectoryindexpage',
            name='meta_robots_nofollow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investmentsupportdirectoryindexpage',
            name='meta_robots_noindex',
            field=models.BooleanField(default=False),
        ),
    ]
