# Generated by Django 4.2.11 on 2024-07-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_buyer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csatuserfeedback',
            name='user_journey',
            field=models.CharField(
                choices=[('COMPANY_VERIFICATION', 'Company verification')],
                default='COMPANY_VERIFICATION',
                max_length=255,
                null=True,
            ),
        ),
    ]
