from international_online_offer.core import (
    hirings,
    intents,
    landing_timeframes,
    regions,
    spends,
)

INTENT_CHOICES = (
    (intents.SET_UP_NEW_PREMISES, 'Set up new premises'),
    (intents.SET_UP_A_NEW_DISTRIBUTION_CENTRE, 'Set up a new distribution centre'),
    (intents.ONWARD_SALES_AND_EXPORTS_FROM_THE_UK, 'Onward sales and exports from the UK'),
    (intents.RESEARCH_DEVELOP_AND_COLLABORATE, 'Research, develop and collaborate'),
    (intents.FIND_PEOPLE_WITH_SPECIALIST_SKILLS, 'Find people with specialist skills'),
    (intents.OTHER, 'Other'),
)

# Copy of EXPERTISE_REGION_CHOICES in directory constants but using non const keys needed for scorecard service
REGION_CHOICES = (
    (regions.EAST_OF_ENGLAND, 'East of England'),
    (regions.EAST_MIDLANDS, 'East Midlands'),
    (regions.LONDON, 'London'),
    (regions.NORTH_EAST, 'North East'),
    (regions.NORTH_WEST, 'North West'),
    (regions.NORTHERN_IRELAND, 'Northern Ireland'),
    (regions.SCOTLAND, 'Scotland'),
    (regions.SOUTH_EAST, 'South East'),
    (regions.SOUTH_WEST, 'South West'),
    (regions.WALES, 'Wales'),
    (regions.WEST_MIDLANDS, 'West Midlands'),
    (regions.YORKSHIRE_AND_THE_HUMBER, 'Yorkshire and the Humber'),
)


HIRING_CHOICES = (
    (hirings.ONE_TO_FIVE, '1 to 5'),
    (hirings.SIX_TO_FIFTY, '6 to 50'),
    (hirings.FIFTY_ONE_TO_ONE_HUNDRED, '51 to 100'),
    (hirings.ONE_HUNDRED_ONE_PLUS, 'More than 100'),
    (hirings.NO_PLANS_TO_HIRE_YET, 'No plans to hire'),
)

SPEND_CHOICES = (
    (spends.LESS_THAN_TEN_THOUSAND, 'Less than £10,000'),
    (spends.TEN_THOUSAND_TO_FIVE_HUNDRED_THOUSAND, '£10,000 to £500,000'),
    (spends.FIVE_HUNDRED_THOUSAND_TO_ONE_MILLION, '£500,000 to £1 million'),
    (spends.ONE_MILLION_TO_TWO_MILLION, '£1 million to £2 million'),
    (spends.TWO_MILLION_TO_FIVE_MILLION, '£2 million to £5 million'),
    (spends.FIVE_MILLION_TO_TEN_MILLION, '£5 million to £10 million'),
    (spends.MORE_THAN_TEN_MILLION, 'More than £10 million'),
)

SPEND_CHOICES_EURO = (
    (spends.LESS_THAN_TEN_THOUSAND, 'Less than €11.000'),
    (spends.TEN_THOUSAND_TO_FIVE_HUNDRED_THOUSAND, '€11.000 to €570.000'),
    (spends.FIVE_HUNDRED_THOUSAND_TO_ONE_MILLION, '€570.000 to €1,1 million'),
    (spends.ONE_MILLION_TO_TWO_MILLION, '€1,1 million to €2,2 million'),
    (spends.TWO_MILLION_TO_FIVE_MILLION, '€2,2 million to €5,7 million'),
    (spends.FIVE_MILLION_TO_TEN_MILLION, '€5,7 million to €11 million'),
    (spends.MORE_THAN_TEN_MILLION, 'More than €11 million'),
)

SPEND_CHOICES_USD = (
    (spends.LESS_THAN_TEN_THOUSAND, 'Less than $12,000'),
    (spends.TEN_THOUSAND_TO_FIVE_HUNDRED_THOUSAND, '$12,000 to $600,000'),
    (spends.FIVE_HUNDRED_THOUSAND_TO_ONE_MILLION, '$600,000 to $1.2 million'),
    (spends.ONE_MILLION_TO_TWO_MILLION, '$1.2 million to $2.4 million'),
    (spends.TWO_MILLION_TO_FIVE_MILLION, '$2.4 million to $6 million'),
    (spends.FIVE_MILLION_TO_TEN_MILLION, '$6 million to $12 million'),
    (spends.MORE_THAN_TEN_MILLION, 'More than $12 million'),
)

SPEND_CURRENCY_CHOICES = (
    ('GBP', 'Pound sterling (GBP)'),
    ('EUR', 'Euro (EUR)'),
    ('USD', 'United States Dollar (USD)'),
)

LANDING_TIMEFRAME_CHOICES = (
    (landing_timeframes.UNDER_SIX_MONTHS, 'In the next 6 months'),
    (landing_timeframes.SIX_TO_TWELVE_MONTHS, '6 to 12 months'),
    (landing_timeframes.ONE_TO_TWO_YEARS, '1 to 2 years'),
    (landing_timeframes.OVER_TWO_YEARS, "In more than 2 years' time"),
)

SATISFACTION_CHOICES = (
    ('VERY_DISSATISFIED', 'Very dissatisfied'),
    ('DISSATISFIED', 'Dissatisfied'),
    ('NEITHER', 'Neither satisfied nor dissatisfied'),
    ('SATISFIED', 'Satisfied'),
    ('VERY_SATISFIED', 'Very satisfied'),
)

EXPERIENCE_CHOICES = (
    ('I_DID_NOT_FIND_WHAT_I_WAS_LOOKING_FOR', 'I did not find what I was looking for'),
    ('I_FOUND_IT_DIFFICULT_TO_NAVIGATE_THE_SITE', 'I found it difficult to navigate the service'),
    ('THE_SYSTEM_LACKS_THE_FEATURE_I_NEED', 'The service lacks the feature I need'),
    ('I_WAS_UNABLE_TO_LOAD_REFRESH_ENTER_A_PAGE', 'I was unable to load/refresh/enter a page'),
    ('OTHER', 'Other'),
    ('I_DID_NOT_EXPERIENCE_ANY_ISSUES', 'I did not experience any issues'),
)

LIKELIHOOD_CHOICES = (
    ('EXTREMELY_UNLIKELY', 'Extremely unlikely'),
    ('UNLIKELY', 'Unlikely'),
    ('NEITHER_LIKELY_NOR_UNLIKELY', 'Neither likely nor unlikely'),
    ('LIKELY', 'Likely'),
    ('EXTREMELY_LIKELY', 'Extremely likely'),
    ('DONT_KNOW_OR_PREFER_NOT_TO_SAY', "Don't know / prefer not to say"),
)

INTENSION_CHOICES = (
    ('HELP_US_SET_UP_IN_THE_UK', 'Help us set up in the UK'),
    ('UNDERSTAND_THE_UK_LEGAL_SYSTEM', 'Understand the UK legal system such as tax and employment regulations'),
    ('PUT_US_IN_TOUCH_WITH_EXPERTS', 'Put us in touch with experts to help us set up'),
    ('ACCESS_TRUSTED_INFORMATION', 'Access trusted information'),
    ('LEARN_ABOUT_AVAILABLE_INCENTIVES', 'Learn about available incentives'),
    ('DONT_KNOW_OR_PREFER_NOT_TO_SAY', "Don't know / prefer not to say"),
    ('MY_BUSINESS_WILL_NOT_USE_THE_SITE', 'My business will not use the site'),
    ('OTHER', 'Other'),
)

COMPANY_LOCATION_CHOICES = (
    ('AE-AZ', 'Abu Dhabi'),
    ('AF', 'Afghanistan'),
    ('AE-AJ', 'Ajman'),
    ('XQZ', 'Akrotiri'),
    ('AX', 'Åland Islands'),
    ('AL', 'Albania'),
    ('DZ', 'Algeria'),
    ('AS', 'American Samoa'),
    ('AD', 'Andorra'),
    ('AO', 'Angola'),
    ('AI', 'Anguilla'),
    ('AG', 'Antigua and Barbuda'),
    ('AR', 'Argentina'),
    ('AM', 'Armenia'),
    ('AW', 'Aruba'),
    ('SH-AC', 'Ascension'),
    ('AU', 'Australia'),
    ('AT', 'Austria'),
    ('AZ', 'Azerbaijan'),
    ('BH', 'Bahrain'),
    ('UM-81', 'Baker Island'),
    ('BD', 'Bangladesh'),
    ('BB', 'Barbados'),
    ('BY', 'Belarus'),
    ('BE', 'Belgium'),
    ('BZ', 'Belize'),
    ('BJ', 'Benin'),
    ('BM', 'Bermuda'),
    ('BT', 'Bhutan'),
    ('BO', 'Bolivia'),
    ('BQ-BO', 'Bonaire'),
    ('BA', 'Bosnia and Herzegovina'),
    ('BW', 'Botswana'),
    ('BR', 'Brazil'),
    ('IO', 'British Indian Ocean Territory'),
    ('VG', 'British Virgin Islands'),
    ('BN', 'Brunei'),
    ('BG', 'Bulgaria'),
    ('BF', 'Burkina Faso'),
    ('BI', 'Burundi'),
    ('KH', 'Cambodia'),
    ('CM', 'Cameroon'),
    ('CA', 'Canada'),
    ('CV', 'Cape Verde'),
    ('KY', 'Cayman Islands'),
    ('CF', 'Central African Republic'),
    ('ES-CE', 'Ceuta'),
    ('TD', 'Chad'),
    ('CL', 'Chile'),
    ('CN', 'China'),
    ('CX', 'Christmas Island'),
    ('CC', 'Cocos (Keeling) Islands'),
    ('CO', 'Colombia'),
    ('KM', 'Comoros'),
    ('CG', 'Congo'),
    ('CD', 'Congo (Democratic Republic)'),
    ('CK', 'Cook Islands'),
    ('CR', 'Costa Rica'),
    ('HR', 'Croatia'),
    ('CU', 'Cuba'),
    ('CW', 'Curaçao'),
    ('CY', 'Cyprus'),
    ('CZ', 'Czechia'),
    ('DK', 'Denmark'),
    ('XXD', 'Dhekelia'),
    ('DJ', 'Djibouti'),
    ('DM', 'Dominica'),
    ('DO', 'Dominican Republic'),
    ('AE-DU', 'Dubai'),
    ('TL', 'East Timor'),
    ('EC', 'Ecuador'),
    ('EG', 'Egypt'),
    ('SV', 'El Salvador'),
    ('GQ', 'Equatorial Guinea'),
    ('ER', 'Eritrea'),
    ('EE', 'Estonia'),
    ('SZ', 'Eswatini'),
    ('ET', 'Ethiopia'),
    ('FK', 'Falkland Islands'),
    ('FO', 'Faroe Islands'),
    ('FJ', 'Fiji'),
    ('FI', 'Finland'),
    ('FR', 'France'),
    ('GF', 'French Guiana'),
    ('PF', 'French Polynesia'),
    ('AE-FU', 'Fujairah'),
    ('GA', 'Gabon'),
    ('GE', 'Georgia'),
    ('DE', 'Germany'),
    ('GH', 'Ghana'),
    ('GI', 'Gibraltar'),
    ('GR', 'Greece'),
    ('GL', 'Greenland'),
    ('GD', 'Grenada'),
    ('GP', 'Guadeloupe'),
    ('GU', 'Guam'),
    ('GT', 'Guatemala'),
    ('GG', 'Guernsey'),
    ('GN', 'Guinea'),
    ('GW', 'Guinea-Bissau'),
    ('GY', 'Guyana'),
    ('HT', 'Haiti'),
    ('HN', 'Honduras'),
    ('HK', 'Hong Kong'),
    ('UM-84', 'Howland Island'),
    ('HU', 'Hungary'),
    ('IS', 'Iceland'),
    ('IN', 'India'),
    ('ID', 'Indonesia'),
    ('IR', 'Iran'),
    ('IQ', 'Iraq'),
    ('IE', 'Ireland'),
    ('IM', 'Isle of Man'),
    ('IL', 'Israel'),
    ('IT', 'Italy'),
    ('CI', 'Ivory Coast'),
    ('JM', 'Jamaica'),
    ('JP', 'Japan'),
    ('UM-86', 'Jarvis Island'),
    ('JE', 'Jersey'),
    ('UM-67', 'Johnston Atoll'),
    ('JO', 'Jordan'),
    ('KZ', 'Kazakhstan'),
    ('KE', 'Kenya'),
    ('UM-89', 'Kingman Reef'),
    ('KI', 'Kiribati'),
    ('XK', 'Kosovo'),
    ('KW', 'Kuwait'),
    ('KG', 'Kyrgyzstan'),
    ('LA', 'Laos'),
    ('LV', 'Latvia'),
    ('LB', 'Lebanon'),
    ('LS', 'Lesotho'),
    ('LR', 'Liberia'),
    ('LY', 'Libya'),
    ('LI', 'Liechtenstein'),
    ('LT', 'Lithuania'),
    ('LU', 'Luxembourg'),
    ('MO', 'Macao'),
    ('MG', 'Madagascar'),
    ('MW', 'Malawi'),
    ('MY', 'Malaysia'),
    ('MV', 'Maldives'),
    ('ML', 'Mali'),
    ('MT', 'Malta'),
    ('MH', 'Marshall Islands'),
    ('MQ', 'Martinique'),
    ('MR', 'Mauritania'),
    ('MU', 'Mauritius'),
    ('YT', 'Mayotte'),
    ('ES-ML', 'Melilla'),
    ('MX', 'Mexico'),
    ('FM', 'Micronesia'),
    ('UM-71', 'Midway Islands'),
    ('MD', 'Moldova'),
    ('MC', 'Monaco'),
    ('MN', 'Mongolia'),
    ('ME', 'Montenegro'),
    ('MS', 'Montserrat'),
    ('MA', 'Morocco'),
    ('MZ', 'Mozambique'),
    ('MM', 'Myanmar (Burma)'),
    ('NA', 'Namibia'),
    ('NR', 'Nauru'),
    ('UM-76', 'Navassa Island'),
    ('NP', 'Nepal'),
    ('NL', 'Netherlands'),
    ('NC', 'New Caledonia'),
    ('NZ', 'New Zealand'),
    ('NI', 'Nicaragua'),
    ('NE', 'Niger'),
    ('NG', 'Nigeria'),
    ('NU', 'Niue'),
    ('NF', 'Norfolk Island'),
    ('MP', 'Northern Mariana Islands'),
    ('KP', 'North Korea'),
    ('MK', 'North Macedonia'),
    ('NO', 'Norway'),
    ('PS', 'Occupied Palestinian Territories'),
    ('OM', 'Oman'),
    ('PK', 'Pakistan'),
    ('PW', 'Palau'),
    ('UM-95', 'Palmyra Atoll'),
    ('PA', 'Panama'),
    ('PG', 'Papua New Guinea'),
    ('PY', 'Paraguay'),
    ('PE', 'Peru'),
    ('PH', 'Philippines'),
    ('PN', 'Pitcairn, Henderson, Ducie and Oeno Islands'),
    ('PL', 'Poland'),
    ('PT', 'Portugal'),
    ('PR', 'Puerto Rico'),
    ('QA', 'Qatar'),
    ('AE-RK', 'Ras al-Khaimah'),
    ('RE', 'Réunion'),
    ('RO', 'Romania'),
    ('RU', 'Russia'),
    ('RW', 'Rwanda'),
    ('BQ-SA', 'Saba'),
    ('BL', 'Saint Barthélemy'),
    ('SH-HL', 'Saint Helena'),
    ('MF', 'Saint-Martin (French part)'),
    ('PM', 'Saint Pierre and Miquelon'),
    ('WS', 'Samoa'),
    ('SM', 'San Marino'),
    ('ST', 'Sao Tome and Principe'),
    ('SA', 'Saudi Arabia'),
    ('SN', 'Senegal'),
    ('RS', 'Serbia'),
    ('SC', 'Seychelles'),
    ('AE-SH', 'Sharjah'),
    ('SL', 'Sierra Leone'),
    ('SG', 'Singapore'),
    ('BQ-SE', 'Sint Eustatius'),
    ('SX', 'Sint Maarten (Dutch part)'),
    ('SK', 'Slovakia'),
    ('SI', 'Slovenia'),
    ('SB', 'Solomon Islands'),
    ('SO', 'Somalia'),
    ('ZA', 'South Africa'),
    ('GS', 'South Georgia and South Sandwich Islands'),
    ('KR', 'South Korea'),
    ('SS', 'South Sudan'),
    ('ES', 'Spain'),
    ('LK', 'Sri Lanka'),
    ('KN', 'St Kitts and Nevis'),
    ('LC', 'St Lucia'),
    ('VC', 'St Vincent'),
    ('SD', 'Sudan'),
    ('SR', 'Suriname'),
    ('SJ', 'Svalbard and Jan Mayen'),
    ('SE', 'Sweden'),
    ('CH', 'Switzerland'),
    ('SY', 'Syria'),
    ('TW', 'Taiwan'),
    ('TJ', 'Tajikistan'),
    ('TZ', 'Tanzania'),
    ('TH', 'Thailand'),
    ('BS', 'The Bahamas'),
    ('GM', 'The Gambia'),
    ('TG', 'Togo'),
    ('TK', 'Tokelau'),
    ('TO', 'Tonga'),
    ('TT', 'Trinidad and Tobago'),
    ('SH-TA', 'Tristan da Cunha'),
    ('TN', 'Tunisia'),
    ('TR', 'Turkey'),
    ('TM', 'Turkmenistan'),
    ('TC', 'Turks and Caicos Islands'),
    ('TV', 'Tuvalu'),
    ('UG', 'Uganda'),
    ('UA', 'Ukraine'),
    ('AE-UQ', 'Umm al-Quwain'),
    ('AE', 'United Arab Emirates'),
    ('GB', 'United Kingdom'),
    ('US', 'United States'),
    ('VI', 'United States Virgin Islands'),
    ('UY', 'Uruguay'),
    ('UZ', 'Uzbekistan'),
    ('VU', 'Vanuatu'),
    ('VA', 'Vatican City'),
    ('VE', 'Venezuela'),
    ('VN', 'Vietnam'),
    ('UM-79', 'Wake Island'),
    ('WF', 'Wallis and Futuna'),
    ('EH', 'Western Sahara'),
    ('YE', 'Yemen'),
    ('ZM', 'Zambia'),
    ('ZW', 'Zimbabwe'),
)
