# Generated by Django 3.2.18 on 2023-03-21 09:35

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('international_online_offer', '0002_auto_20230316_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iooarticlepagetag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='ioo_tagged_items',
                to='international_online_offer.iooarticlepage',
            ),
        ),
    ]
