# Generated by Django 3.2.18 on 2023-03-14 12:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('international_online_offer', '0002_auto_20230313_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iooguidepage',
            name='description',
        ),
    ]
