# Generated by Django 3.2.18 on 2023-03-21 12:12

import django.db.models.deletion
import modelcluster.fields
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('international_online_offer', '0003_alter_iooarticlepagetag_content_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='IOOArticleTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'IOO article tag for link to triage answer',
                'verbose_name_plural': 'IOO article tags for links to triage answers',
            },
        ),
        migrations.AlterField(
            model_name='iooarticlepagetag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='ioo_article_tagged_items',
                to='international_online_offer.iooarticlepage',
            ),
        ),
        migrations.AlterField(
            model_name='iooarticlepage',
            name='tags',
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text='A comma-separated list of tags.',
                through='international_online_offer.IOOArticlePageTag',
                to='international_online_offer.IOOArticleTag',
                verbose_name='Tags',
            ),
        ),
        migrations.AlterField(
            model_name='iooarticlepagetag',
            name='tag',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='ioo_tagged_articles',
                to='international_online_offer.iooarticletag',
            ),
        ),
    ]
