# Generated by Django 3.2.18 on 2023-03-15 11:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('core', '0077_alter_micrositepage_page_body'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0066_collection_management_permissions'),
        ('international_online_offer', '0003_remove_iooguidepage_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IOOLandingPage',
        ),
    ]
