# Generated by Django 3.2.18 on 2023-03-24 14:27

import modelcluster.contrib.taggit
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('international_online_offer', '0004_auto_20230321_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iooarticlepage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text='A comma-separated list of tags.',
                through='international_online_offer.IOOArticlePageTag',
                to='international_online_offer.IOOArticleTag',
                verbose_name='Article Tags',
            ),
        ),
    ]
