# Generated by Django 3.2.18 on 2023-03-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('international_online_offer', '0006_triagedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashed_uuid', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=255)),
                (
                    'company_location',
                    models.CharField(
                        choices=[
                            ('France', 'France'),
                            ('Germany', 'Germany'),
                            ('India', 'India'),
                            ('Italy', 'Italy'),
                            ('Spain', 'Spain'),
                            ('United States', 'United States'),
                        ],
                        max_length=255,
                    ),
                ),
                ('full_name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('telephone_number', models.CharField(max_length=255)),
                ('agree_terms', models.BooleanField(default=False)),
                ('agree_info_email', models.BooleanField(default=False)),
                ('agree_info_telephone', models.BooleanField(default=False)),
            ],
        ),
    ]
