# Generated by Django 3.2.18 on 2023-04-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('international_online_offer', '0007_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='triagedata',
            name='is_high_value',
            field=models.BooleanField(default=False),
        ),
    ]
