# Generated by Django 3.2.18 on 2023-04-21 15:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('international_online_offer', '0008_triagedata_is_high_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagedata',
            name='intent',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(
                        choices=[
                            ('Set up new premises', 'Set up new premises'),
                            ('Set up a new distribution centre', 'Set up a new distribution centre'),
                            ('Onward sales and exports from the UK', 'Onward sales and exports from the UK'),
                            ('Research develop and collaborate', 'Research, develop and collaborate'),
                            ('Find people with specialist skills', 'Find people with specialist skills'),
                            ('Other', 'Other'),
                        ],
                        max_length=255,
                    ),
                    size=6,
                ),
                default=list,
                size=1,
            ),
        ),
    ]
