# Generated by Django 3.2.18 on 2023-04-26 13:07

import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('international_online_offer', '0010_auto_20230422_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iooarticlepage',
            name='article_body',
            field=wagtail.core.fields.StreamField(
                [
                    ('text', wagtail.core.blocks.RichTextBlock()),
                    (
                        'image',
                        wagtail.images.blocks.ImageChooserBlock(
                            required=False, template='core/includes/_article_image.html'
                        ),
                    ),
                    (
                        'Columns',
                        wagtail.core.blocks.StreamBlock(
                            [
                                (
                                    'column',
                                    wagtail.core.blocks.StructBlock(
                                        [
                                            (
                                                'title',
                                                wagtail.core.blocks.CharBlock(
                                                    label='Title', max_length=255, required=False
                                                ),
                                            ),
                                            (
                                                'image',
                                                wagtail.images.blocks.ImageChooserBlock(
                                                    label='Hero Image', required=False
                                                ),
                                            ),
                                            (
                                                'description',
                                                wagtail.core.blocks.RichTextBlock(
                                                    features=[
                                                        'h2',
                                                        'h3',
                                                        'h4',
                                                        'bold',
                                                        'italic',
                                                        'ol',
                                                        'ul',
                                                        'hr',
                                                        'link',
                                                        'document-link',
                                                    ],
                                                    label='Description',
                                                    required=False,
                                                ),
                                            ),
                                            ('link', wagtail.core.blocks.URLBlock(label='Title link', required=False)),
                                        ]
                                    ),
                                )
                            ],
                            help_text='Add two or three columns text',
                            max_num=3,
                            min_num=2,
                            template='core/includes/_columns.html',
                        ),
                    ),
                ],
                blank=True,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='iooarticlepage',
            name='article_subheading',
            field=wagtail.core.fields.StreamField(
                [('text', wagtail.core.blocks.RichTextBlock())], blank=True, null=True
            ),
        ),
    ]
