# Generated by Django 3.2.19 on 2023-06-15 12:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('international_online_offer', '0013_auto_20230505_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagedata',
            name='intent',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ('SET_UP_NEW_PREMISES', 'Set up new premises'),
                        ('SET_UP_A_NEW_DISTRIBUTION_CENTRE', 'Set up a new distribution centre'),
                        ('ONWARD_SALES_AND_EXPORTS_FROM_THE_UK', 'Onward sales and exports from the UK'),
                        ('RESEARCH_DEVELOP_AND_COLLABORATE', 'Research, develop and collaborate'),
                        ('FIND_PEOPLE_WITH_SPECIALIST_SKILLS', 'Find people with specialist skills'),
                        ('OTHER', 'Other'),
                    ],
                    max_length=255,
                ),
                default=list,
                size=6,
            ),
        ),
    ]
