# Generated by Django 4.1.9 on 2023-06-20 10:36

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('international_online_offer', '0015_iootradeshowpage_iootradepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='IOOTradeShowPageTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'content_object',
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='ioo_tradeshow_tagged_items',
                        to='international_online_offer.iootradeshowpage',
                    ),
                ),
                (
                    'tag',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='ioo_tagged_tradeshows',
                        to='international_online_offer.iooarticletag',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='iootradeshowpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text='A comma-separated list of tags.',
                through='international_online_offer.IOOTradeShowPageTag',
                to='international_online_offer.IOOArticleTag',
                verbose_name='Trade Show Tags',
            ),
        ),
    ]
