# Generated by Django 4.1.9 on 2023-06-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('international_online_offer', '0016_iootradeshowpagetag_alter_iootradeshowpage_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_association_id', models.CharField(max_length=255)),
                ('sector_grouping', models.CharField(max_length=255)),
                ('association_name', models.CharField(max_length=255)),
                ('website_link', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=255)),
                ('brief_description', models.CharField(max_length=255)),
            ],
        ),
    ]
