# Generated by Django 4.1.9 on 2023-06-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('international_online_offer', '0017_tradeassociation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
                ('vertical', models.CharField(max_length=255)),
                ('professional_level', models.CharField(max_length=255)),
                ('occupation', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('number_of_jobs_thousands', models.IntegerField()),
                ('median_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('median_annual_percentage_change', models.IntegerField()),
                ('mean_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mean_annual_percentage_change', models.IntegerField()),
            ],
        ),
    ]
