# Generated by Django 4.1.9 on 2023-06-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('international_online_offer', '0018_salarydata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarydata',
            name='code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salarydata',
            name='mean_annual_percentage_change',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='salarydata',
            name='mean_salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='salarydata',
            name='median_annual_percentage_change',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='salarydata',
            name='median_salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='salarydata',
            name='number_of_jobs_thousands',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='salarydata',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
