# Generated by Django 4.1.9 on 2023-07-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('international_online_offer', '0019_alter_salarydata_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('city_or_region', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('vertical', models.CharField(max_length=255)),
                ('sub_vertical', models.CharField(max_length=255)),
                ('year', models.IntegerField(null=True)),
                ('metric_converted', models.CharField(max_length=255, null=True)),
                ('value_converted', models.CharField(max_length=255, null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('metric_original', models.CharField(max_length=255, null=True)),
                ('time_period', models.CharField(max_length=255, null=True)),
                ('value_original', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
