# Generated by Django 4.1.9 on 2023-07-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('international_online_offer', '0020_rentdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentdata',
            name='value_converted',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rentdata',
            name='value_original',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
