# Generated by Django 4.1.9 on 2023-07-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('international_online_offer', '0021_alter_rentdata_value_converted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='landing_timeframe',
            field=models.CharField(
                choices=[
                    ('UNDER_SIX_MONTHS', 'Under 6 months'),
                    ('SIX_TO_TWELVE_MONTHS', '6 - 12 months'),
                    ('ONE_TO_TWO_YEARS', '1 - 2 years'),
                    ('OVER_TWO_YEARS', 'Over 2 years'),
                ],
                default=None,
                max_length=255,
                null=True,
            ),
        ),
    ]
