# Generated by Django 4.1.9 on 2023-07-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('international_online_offer', '0022_userdata_landing_timeframe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentdata',
            name='category',
        ),
        migrations.RemoveField(
            model_name='rentdata',
            name='city_or_region',
        ),
        migrations.RemoveField(
            model_name='rentdata',
            name='country',
        ),
        migrations.RemoveField(
            model_name='rentdata',
            name='metric_converted',
        ),
        migrations.RemoveField(
            model_name='rentdata',
            name='metric_original',
        ),
        migrations.RemoveField(
            model_name='rentdata',
            name='time_period',
        ),
        migrations.RemoveField(
            model_name='rentdata',
            name='title',
        ),
        migrations.RemoveField(
            model_name='rentdata',
            name='value_converted',
        ),
        migrations.RemoveField(
            model_name='rentdata',
            name='value_original',
        ),
        migrations.RemoveField(
            model_name='rentdata',
            name='vertical',
        ),
        migrations.RemoveField(
            model_name='rentdata',
            name='year',
        ),
        migrations.AddField(
            model_name='rentdata',
            name='gbp_per_month',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rentdata',
            name='gbp_per_square_foot_per_month',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rentdata',
            name='square_feet',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
