# Generated by Django 4.1.9 on 2023-07-24 13:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('international_online_offer', '0023_remove_rentdata_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarydata',
            name='code',
        ),
        migrations.RemoveField(
            model_name='salarydata',
            name='mean_annual_percentage_change',
        ),
        migrations.RemoveField(
            model_name='salarydata',
            name='median_annual_percentage_change',
        ),
        migrations.RemoveField(
            model_name='salarydata',
            name='number_of_jobs_thousands',
        ),
        migrations.RemoveField(
            model_name='salarydata',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='salarydata',
            name='year',
        ),
    ]
