# Generated by Django 4.1.10 on 2023-08-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('international_online_offer', '0024_remove_salarydata_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='agree_info_telephone',
        ),
        migrations.AlterField(
            model_name='triagedata',
            name='location',
            field=models.CharField(
                choices=[
                    ('EAST_OF_ENGLAND', 'East'),
                    ('EAST_MIDLANDS', 'East Midlands'),
                    ('LONDON', 'London'),
                    ('NORTH_EAST', 'North East'),
                    ('NORTH_WEST', 'North West'),
                    ('NORTHERN_IRELAND', 'Northern Ireland'),
                    ('SCOTLAND', 'Scotland'),
                    ('SOUTH_EAST', 'South East'),
                    ('SOUTH_WEST', 'South West'),
                    ('WALES', 'Wales'),
                    ('WEST_MIDLANDS', 'West Midlands'),
                    ('YORKSHIRE_AND_HUMBER', 'Yorkshire and the Humber'),
                ],
                max_length=255,
            ),
        ),
    ]
