# Generated by Django 4.1.10 on 2023-08-17 14:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('core', '0098_alter_casestudy_body_alter_detailpage_body_and_more'),
        ('international_online_offer', '0025_remove_userdata_agree_info_telephone_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IOOTradePage',
            new_name='IOOTradeShowsPage',
        ),
    ]
