# Generated by Django 4.1.10 on 2023-08-18 09:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('core', '0098_alter_casestudy_body_alter_detailpage_body_and_more'),
        ('international_online_offer', '0026_rename_iootradepage_iootradeshowspage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IOOIndexPage',
            new_name='EYBIndexPage',
        ),
    ]
