# Generated by Django 4.1.10 on 2023-08-18 09:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('international_online_offer', '0028_eybtradeshowpage_eybtradeshowpagetag_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IOOArticlePageTag',
            new_name='EYBArticlePageTag',
        ),
        migrations.RenameModel(
            old_name='IOOArticleTag',
            new_name='EYBArticleTag',
        ),
    ]
