# Generated by Django 4.1.10 on 2023-08-23 08:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('core', '0098_alter_casestudy_body_alter_detailpage_body_and_more'),
        ('international_online_offer', '0029_rename_iooarticlepagetag_eybarticlepagetag_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EYBTradeShowPage',
            new_name='IOOTradeShowPage',
        ),
    ]
