# Generated by Django 4.1.10 on 2023-08-24 10:47

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('international_online_offer', '0030_rename_eybtradeshowpage_iootradeshowpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='triagedata',
            options={'get_latest_by': 'modified', 'ordering': ('-modified', '-created')},
        ),
        migrations.AlterModelOptions(
            name='userdata',
            options={'get_latest_by': 'modified', 'ordering': ('-modified', '-created')},
        ),
        migrations.AddField(
            model_name='triagedata',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, null=True, verbose_name='created'
            ),
        ),
        migrations.AddField(
            model_name='triagedata',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, null=True, verbose_name='modified'
            ),
        ),
        migrations.AddField(
            model_name='userdata',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, null=True, verbose_name='created'
            ),
        ),
        migrations.AddField(
            model_name='userdata',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, null=True, verbose_name='modified'
            ),
        ),
    ]
