# Generated by Django 4.1.10 on 2023-09-01 12:43

from django.db import migrations

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ('international_online_offer', '0032_eybarticlespage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eybarticlepage',
            name='article_body',
            field=wagtail.fields.StreamField(
                [
                    ('text', wagtail.blocks.RichTextBlock()),
                    (
                        'image',
                        wagtail.images.blocks.ImageChooserBlock(
                            required=False, template='core/includes/_article_image.html'
                        ),
                    ),
                    (
                        'Columns',
                        wagtail.blocks.StreamBlock(
                            [
                                (
                                    'column',
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                'title',
                                                wagtail.blocks.CharBlock(label='Title', max_length=255, required=False),
                                            ),
                                            (
                                                'image',
                                                wagtail.images.blocks.ImageChooserBlock(
                                                    label='Hero Image', required=False
                                                ),
                                            ),
                                            (
                                                'description',
                                                wagtail.blocks.RichTextBlock(
                                                    features=[
                                                        'anchor-identifier',
                                                        'h2',
                                                        'h3',
                                                        'h4',
                                                        'bold',
                                                        'italic',
                                                        'ol',
                                                        'ul',
                                                        'hr',
                                                        'link',
                                                        'document-link',
                                                    ],
                                                    label='Description',
                                                    required=False,
                                                ),
                                            ),
                                            ('link', wagtail.blocks.URLBlock(label='Title link', required=False)),
                                        ]
                                    ),
                                )
                            ],
                            help_text='Add two or three columns text',
                            max_num=3,
                            min_num=2,
                            template='core/includes/_columns.html',
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
