# Generated by Django 4.1.10 on 2023-09-05 08:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('international_online_offer', '0033_alter_eybarticlepage_article_body'),
        ('international_online_offer', '0033_replace_wagtail_font_awesome_icons'),
    ]

    operations = []
