# Generated by Django 4.1.10 on 2023-10-10 15:40

import django.contrib.postgres.fields
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('international_online_offer', '0034_merge_20230905_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsatFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, null=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, null=True, verbose_name='modified'
                    ),
                ),
                ('URL', models.CharField(max_length=255)),
                ('user_journey', models.CharField(max_length=255, null=True)),
                (
                    'satisfaction_rating',
                    models.CharField(
                        choices=[
                            ('VERY_SATISFIED', 'Very satisfied'),
                            ('SATISFIED', 'Satisfied'),
                            ('NEITHER', 'Neither satisfied nor dissatisfied'),
                            ('DISSATISFIED', 'Dissatisfied'),
                            ('VERY_DISSATISFIED', 'Very dissatisfied'),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    'experienced_issue',
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ('I_DID_NOT_EXPERIENCE_ANY_ISSUE', 'I did not experience any issue'),
                                ('I_DID_NOT_FIND_WHAT_I_WAS_LOOKING_FOR', 'I did not find what I was looking for'),
                                (
                                    'I_FOUND_IT_DIFFICULT_TO_NAVIGATE_THE_SITE',
                                    'I found it difficult to navigate the site',
                                ),
                                ('THE_SYSTEM_LACKS_THE_FEATURE_I_NEED', 'The system lacks the feature I need'),
                                (
                                    'I_WAS_UNABLE_TO_LOAD_REFRESH_ENTER_A_PAGE',
                                    'I was unable to load/refresh/enter a page',
                                ),
                                ('OTHER', 'Other'),
                            ],
                            max_length=255,
                        ),
                        default=list,
                        null=True,
                        size=6,
                    ),
                ),
                ('other_detail', models.CharField(max_length=255, null=True)),
                ('service_improvements_feedback', models.CharField(max_length=255, null=True)),
                (
                    'likelihood_of_return',
                    models.CharField(
                        choices=[
                            ('EXTREMELY_LIKELY', 'Extremely likely'),
                            ('LIKELY', 'Likely'),
                            ('NEITHER_LIKELY_NOR_UNLIKELY', 'Neither likely nor unlikely'),
                            ('UNLIKELY', 'Unlikely'),
                            ('EXTREMELY_UNLIKELY', 'Extremely unlikely'),
                            ('DONT_KNOW_OR_PREFER_NOT_TO_SAY', "Don't know / prefer not to say"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    'site_intentions',
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ('DECIDE_IF_WE_SHOULD_SET_UP_IN_THE_UK', 'Decide if we should set up in the UK'),
                                ('HELP_US_SET_UP_IN_THE_UK', 'Help us set up in the UK'),
                                (
                                    'UNDERSTAND_THE_UK_LEGAL_SYSTEM',
                                    'Understand the UK legal system such as tax and employment regulations',
                                ),
                                ('PUT_US_IN_TOUCH_WITH_EXPERTS', 'Put us in touch with experts to help us set up'),
                                ('ACCESS_TRUSTED_INFORMATION', 'Access trusted information'),
                                ('LEARN_ABOUT_AVAILABLE_INCENTIVES', 'Learn about available incentives'),
                                ('OTHER', 'Other'),
                                ('DONT_KNOW_OR_PREFER_NOT_TO_SAY', "Don't know / prefer not to say"),
                                ('MY_BUSINESS_WILL_NOT_USE_THE_SITE', 'My business will not use the site'),
                            ],
                            max_length=255,
                        ),
                        default=list,
                        null=True,
                        size=6,
                    ),
                ),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
