# Generated by Django 4.1.10 on 2023-10-11 14:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('international_online_offer', '0035_csatfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='csatfeedback',
            name='site_intentions_other',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='csatfeedback',
            name='site_intentions',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ('HELP_US_SET_UP_IN_THE_UK', 'Help us set up in the UK'),
                        (
                            'UNDERSTAND_THE_UK_LEGAL_SYSTEM',
                            'Understand the UK legal system such as tax and employment regulations',
                        ),
                        ('PUT_US_IN_TOUCH_WITH_EXPERTS', 'Put us in touch with experts to help us set up'),
                        ('ACCESS_TRUSTED_INFORMATION', 'Access trusted information'),
                        ('LEARN_ABOUT_AVAILABLE_INCENTIVES', 'Learn about available incentives'),
                        ('DONT_KNOW_OR_PREFER_NOT_TO_SAY', "Don't know / prefer not to say"),
                        ('MY_BUSINESS_WILL_NOT_USE_THE_SITE', 'My business will not use the site'),
                        ('OTHER', 'Other'),
                    ],
                    max_length=255,
                ),
                default=list,
                null=True,
                size=6,
            ),
        ),
    ]
