# Generated by Django 4.1.10 on 2023-11-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('international_online_offer', '0036_csatfeedback_site_intentions_other_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='triagedata',
            name='location_city',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
