# Generated by Django 4.1.10 on 2023-11-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('international_online_offer', '0037_triagedata_location_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagedata',
            name='location_city',
            field=models.CharField(
                choices=[
                    ('WEST_HAM', 'West Ham'),
                    ('CHELSEA', 'Chelsea'),
                    ('CARRICKFERGUS', 'Carrickfergus'),
                    ('NEWRY', 'Newry'),
                    ('NEWTOWNARDS', 'Newtownards'),
                    ('BALLYMENA', 'Ballymena'),
                    ('LISBURN', 'Lisburn'),
                    ('BANGOR', 'Bangor'),
                    ('NEWTOWNABBEY', 'Newtownabbey'),
                    ('CRAIGAVON', 'Craigavon'),
                    ('DERRY', 'Derry'),
                    ('BELFAST', 'Belfast'),
                    ('MERTHYR_TYDFIL', 'Merthyr Tydfil'),
                    ('POWYS', 'Powys'),
                    ('NEWPORT', 'Newport'),
                    ('MONMOUTHSHIRE', 'Monmouthshire'),
                    ('TORFAEN', 'Torfaen'),
                    ('BLAENAU_GWENT', 'Blaenau Gwent'),
                    ('CAERPHILLY', 'Caerphilly'),
                    ('RHONDDA_CYNON_TAF', 'Rhondda Cynon Taf'),
                    ('CARDIFF', 'Cardiff'),
                    ('VALE_OF_GLAMORGAN', 'Vale of Glamorgan'),
                    ('BRIDGEND', 'Bridgend'),
                    ('NEATH_PORT_TALBOT', 'Neath Port Talbot'),
                    ('SWANSEA', 'Swansea'),
                    ('CARMARTHENSHIRE', 'Carmarthenshire'),
                    ('PEMBROKESHIRE', 'Pembrokeshire'),
                    ('CEREDIGION', 'Ceredigion'),
                    ('WREXHAM', 'Wrexham'),
                    ('FLINTSHIRE', 'Flintshire'),
                    ('DENBIGHSHIRE', 'Denbighshire'),
                    ('CONWY', 'Conwy'),
                    ('GWYNEDD', 'Gwynedd'),
                    ('ISLE_OF_ANGLESEY', 'Isle of Anglesey'),
                ],
                default=None,
                max_length=255,
                null=True,
            ),
        ),
    ]
