# Generated by Django 4.1.10 on 2023-11-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('international_online_offer', '0040_triagedata_sector_sub_alter_triagedata_location_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagedata',
            name='sector',
            field=models.CharField(
                choices=[
                    ('WATER', 'Water'),
                    ('TECHNOLOGY_AND_SMART_CITIES', 'Technology and smart cities'),
                    ('SPACE', 'Space'),
                    ('SECURITY', 'Security'),
                    ('RAILWAYS', 'Railways'),
                    ('PHARMACEUTICALS_AND_BIOTECHNOLOGY', 'Pharmaceuticals and biotechnology'),
                    ('MINING', 'Mining'),
                    ('MEDICAL_DEVICES_AND_EQUIPMENT', 'Medical devices and equipment'),
                    ('MARITIME', 'Maritime'),
                    ('HEALTHCARE_SERVICES', 'Healthcare services'),
                    ('FOOD_AND_DRINK', 'Food and drink'),
                    ('FINANCIAL_AND_PROFESSIONAL_SERVICES', 'Financial and professional services'),
                    ('ENVIRONMENT', 'Environment'),
                    ('ENERGY', 'Energy'),
                    ('EDUCATION_AND_TRAINING', 'Education and training'),
                    ('DEFENCE', 'Defence'),
                    ('CREATIVE_INDUSTRIES', 'Creative industries'),
                    ('CONSUMER_AND_RETAIL', 'Consumer and retail'),
                    ('CONSTRUCTION', 'Construction'),
                    ('CHEMICALS', 'Chemicals'),
                    ('AUTOMOTIVE', 'Automotive'),
                    ('AIRPORTS', 'Airports'),
                    ('AGRICULTURE_HORTICULTURE_FISHERIES_AND_PETS', 'Agriculture, horticulture, fisheries and pets'),
                    ('AEROSPACE', 'Aerospace'),
                    ('ADVANCED_ENGINEERING', 'Advanced engineering'),
                ],
                max_length=255,
            ),
        ),
    ]
