# Generated by Django 4.1.10 on 2023-12-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('international_online_offer', '0044_alter_triagedata_location_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='company_website',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
