# Generated by Django 4.1.13 on 2024-02-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('international_online_offer', '0045_userdata_company_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='triagedata',
            name='spend_currency',
            field=models.CharField(
                choices=[('GBP', 'Pound sterling (GBP)'), ('EUR', 'Euro (EUR)'), ('USD', 'United States Dollar (USD)')],
                default='GBP',
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name='triagedata',
            name='spend',
            field=models.CharField(
                choices=[
                    ('0-9999', 'Less than £10,000'),
                    ('10000-500000', '£10,000 to £500,000'),
                    ('500000-1000000', '£500,000 to £1 million'),
                    ('1000000-2000000', '£1 million to £2 million'),
                    ('2000000-5000000', '£2 million to £5 million'),
                    ('5000000-10000000', '£5 million to £10 million'),
                    ('10000000+', 'More than £10 million'),
                ],
                max_length=255,
            ),
        ),
    ]
