# Generated by Django 4.1.13 on 2024-03-01 13:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('international_online_offer', '0046_triagedata_spend_currency_alter_triagedata_spend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triagedata',
            name='spend_currency',
        ),
    ]
