# Generated by Django 4.1.13 on 2024-04-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('international_online_offer', '0047_remove_triagedata_spend_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagedata',
            name='hiring',
            field=models.CharField(
                choices=[
                    ('1-10', 'Fewer than 10'),
                    ('11-50', '10 to 50'),
                    ('51-100', '50 to 100'),
                    ('101+', 'More than 100'),
                    ('NO_PLANS_TO_HIRE_YET', 'No plans to hire'),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='landing_timeframe',
            field=models.CharField(
                choices=[
                    ('UNDER_SIX_MONTHS', 'In the next 6 months'),
                    ('SIX_TO_TWELVE_MONTHS', '6 to 12 months'),
                    ('ONE_TO_TWO_YEARS', '1 to 2 years'),
                    ('OVER_TWO_YEARS', "In more than 2 years' time"),
                ],
                default=None,
                max_length=255,
                null=True,
            ),
        ),
    ]
