# Generated by Django 4.2.11 on 2024-05-15 08:05

from django.db import migrations, models

import international_online_offer.models


class Migration(migrations.Migration):

    dependencies = [
        ('international_online_offer', '0048_alter_userdata_company_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScorecardCriterion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=255)),
                ('capex_spend', models.IntegerField(blank=True, null=True)),
                ('labour_workforce_hire', models.IntegerField(blank=True, null=True)),
                (
                    'high_potential_opportunity_locations',
                    international_online_offer.models.ChoiceArrayField(
                        base_field=models.CharField(
                            choices=[
                                ('EAST_OF_ENGLAND', 'East of England'),
                                ('EAST_MIDLANDS', 'East Midlands'),
                                ('LONDON', 'London'),
                                ('NORTH_EAST', 'North East'),
                                ('NORTH_WEST', 'North West'),
                                ('NORTHERN_IRELAND', 'Northern Ireland'),
                                ('SCOTLAND', 'Scotland'),
                                ('SOUTH_EAST', 'South East'),
                                ('SOUTH_WEST', 'South West'),
                                ('WALES', 'Wales'),
                                ('WEST_MIDLANDS', 'West Midlands'),
                                ('YORKSHIRE_AND_THE_HUMBER', 'Yorkshire and the Humber'),
                            ],
                            max_length=255,
                        ),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
            ],
        ),
    ]
