# Generated by Django 4.2.11 on 2024-05-30 15:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international_online_offer', '0049_scorecardcriterion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csatfeedback',
            name='experienced_issue',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ('I_DID_NOT_FIND_WHAT_I_WAS_LOOKING_FOR', 'I did not find what I was looking for'),
                        ('I_FOUND_IT_DIFFICULT_TO_NAVIGATE_THE_SITE', 'I found it difficult to navigate the service'),
                        ('THE_SYSTEM_LACKS_THE_FEATURE_I_NEED', 'The service lacks the feature I need'),
                        ('I_WAS_UNABLE_TO_LOAD_REFRESH_ENTER_A_PAGE', 'I was unable to load/refresh/enter a page'),
                        ('OTHER', 'Other'),
                        ('I_DID_NOT_EXPERIENCE_ANY_ISSUES', 'I did not experience any issues'),
                    ],
                    max_length=255,
                ),
                default=list,
                null=True,
                size=6,
            ),
        ),
        migrations.AlterField(
            model_name='csatfeedback',
            name='likelihood_of_return',
            field=models.CharField(
                choices=[
                    ('EXTREMELY_UNLIKELY', 'Extremely unlikely'),
                    ('UNLIKELY', 'Unlikely'),
                    ('NEITHER_LIKELY_NOR_UNLIKELY', 'Neither likely nor unlikely'),
                    ('LIKELY', 'Likely'),
                    ('EXTREMELY_LIKELY', 'Extremely likely'),
                    ('DONT_KNOW_OR_PREFER_NOT_TO_SAY', "Don't know / prefer not to say"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='csatfeedback',
            name='satisfaction_rating',
            field=models.CharField(
                choices=[
                    ('VERY_DISSATISFIED', 'Very dissatisfied'),
                    ('DISSATISFIED', 'Dissatisfied'),
                    ('NEITHER', 'Neither satisfied nor dissatisfied'),
                    ('SATISFIED', 'Satisfied'),
                    ('VERY_SATISFIED', 'Very satisfied'),
                ],
                max_length=255,
            ),
        ),
    ]
