# Generated by Django 4.2.11 on 2024-07-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international_online_offer', '0050_alter_csatfeedback_experienced_issue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagedata',
            name='hiring',
            field=models.CharField(
                choices=[
                    ('1-5', '1 to 5'),
                    ('6-50', '6 to 50'),
                    ('51-100', '51 to 100'),
                    ('101+', 'More than 100'),
                    ('NO_PLANS_TO_HIRE_YET', 'No plans to hire'),
                ],
                max_length=255,
            ),
        ),
    ]
