# Generated by Django 4.2.11 on 2024-07-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international_online_offer', '0051_alter_triagedata_hiring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagedata',
            name='location_none',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
