# Generated by Django 4.2.11 on 2024-07-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international_online_offer', '0053_alter_userdata_landing_timeframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='triagedata',
            name='sector_sub_sub',
            field=models.CharField(choices=[('Cyber', 'Cyber')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='triagedata',
            name='sector',
            field=models.CharField(
                choices=[
                    ('Technology and smart cities', 'Technology and smart cities'),
                    ('Food and drink', 'Food and drink'),
                    ('Defence', 'Defence'),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name='triagedata',
            name='sector_sub',
            field=models.CharField(
                choices=[
                    ('Land', 'Land'),
                    ('Communications', 'Communications'),
                    ('Alcoholic drinks', 'Alcoholic drinks'),
                ],
                default=None,
                max_length=255,
                null=True,
            ),
        ),
    ]
