# Generated by Django 4.2.11 on 2024-07-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international_online_offer', '0053_alter_userdata_landing_timeframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='triagedata',
            name='sector_id',
            field=models.CharField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='triagedata',
            name='sector_sub_sub',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='triagedata',
            name='sector',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='triagedata',
            name='sector_sub',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
