# Generated by Django 4.2.11 on 2024-07-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international_online_offer', '0054_triagedata_sector_sub_sub_alter_triagedata_sector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='triagedata',
            name='sector_id',
            field=models.CharField(default=None, null=True),
        ),
    ]
