# Generated by Django 4.2.16 on 2024-10-29 11:57

import modelcluster.contrib.taggit
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('international_online_offer', '0057_alter_userdata_address_line_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eybarticlepage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="A comma-separated list of tags. Each article needs at least two tags to display a) a sector, b) an intent. Do not include commas in the sector name, e.g. 'Agriculture, horticulture, fisheries and pets' is tagged as 'Agriculture horticulture fisheries and pets'",
                through='international_online_offer.EYBArticlePageTag',
                to='international_online_offer.EYBArticleTag',
                verbose_name='Article Tags',
            ),
        ),
        migrations.AlterField(
            model_name='iootradeshowpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="A comma-separated list of tags. Do not include commas in the sector name, e.g. 'Agriculture, horticulture, fisheries and pets' is tagged as 'Agriculture horticulture fisheries and pets'",
                through='international_online_offer.EYBTradeShowPageTag',
                to='international_online_offer.EYBArticleTag',
                verbose_name='Trade Show Tags',
            ),
        ),
    ]
