# Generated by Django 4.2.16 on 2024-11-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international_online_offer', '0058_alter_eybarticlepage_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='company_location',
            field=models.CharField(max_length=255),
        ),
    ]
