# Generated by Django 4.2.16 on 2024-11-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international_online_offer', '0059_alter_userdata_company_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagedata',
            name='hiring',
            field=models.CharField(
                choices=[
                    ('1-5', '1 to 5'),
                    ('6-10', '6 to 10'),
                    ('11-20', '11 to 20'),
                    ('21+', 'More than 20'),
                    ('NO_PLANS_TO_HIRE_YET', 'No plans to hire'),
                ],
                max_length=255,
            ),
        ),
    ]
