# Generated by Django 4.2.16 on 2024-11-25 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('international_online_offer', '0060_alter_triagedata_hiring'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CsatFeedback',
        ),
    ]
