# Generated by Django 4.2.16 on 2024-11-28 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('international_online_offer', '0061_delete_csatfeedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScorecardCriterion',
        ),
    ]
