# Generated by Django 4.2.16 on 2024-12-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international_online_offer', '0062_delete_scorecardcriterion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagedata',
            name='spend',
            field=models.CharField(
                choices=[
                    ('0-499999', 'Less than £500,000'),
                    ('500000-1000000', '£500,000 to £1 million'),
                    ('1000000-2500000', '£1 million to £2.5 million'),
                    ('2500000-5000000', '£2.5 million to £5 million'),
                    ('5000000+', 'More than £5 million'),
                ],
                max_length=255,
            ),
        ),
    ]
