# Generated by Django 4.2.17 on 2024-12-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international_online_offer', '0064_tradeassociation_link_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeassociation',
            name='link_valid',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
