# Generated by Django 4.2.17 on 2025-02-10 15:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international_online_offer', '0065_alter_tradeassociation_link_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='eybarticlepage',
            name='dbt_sectors',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(),
                blank=True,
                default=list,
                help_text='Select multiple sectors by holding the Ctrl key (Windows) or the Command key (Mac).',
                size=None,
            ),
        ),
    ]
