# Generated by Django 4.2.17 on 2025-02-12 15:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international_online_offer', '0066_eybarticlepage_dbt_sectors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eybarticlepage',
            name='dbt_sectors',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(),
                blank=True,
                default=list,
                help_text='Select multiple sectors by holding the Ctrl key (Windows) or the Command key (Mac). Currently the parent sector only is used for mapping.',
                size=None,
            ),
        ),
    ]
