# Generated by Django 4.2.17 on 2025-02-17 12:03

import django.contrib.postgres.fields
import modelcluster.contrib.taggit
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international_online_offer', '0067_alter_eybarticlepage_dbt_sectors'),
    ]

    operations = [
        migrations.AddField(
            model_name='iootradeshowpage',
            name='dbt_sectors',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(),
                blank=True,
                default=list,
                help_text='Select multiple sectors by holding the Ctrl key (Windows) or the Command key (Mac). Currently the parent sector only is used for mapping.',
                size=None,
            ),
        ),
        migrations.AddField(
            model_name='iootradeshowpage',
            name='tradeshow_location',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='iootradeshowpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text='A comma-separated list of tags.',
                through='international_online_offer.EYBTradeShowPageTag',
                to='international_online_offer.EYBArticleTag',
                verbose_name='Trade Show Tags',
            ),
        ),
    ]
