# Generated by Django 4.2.19 on 2025-02-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international_online_offer', '0067_alter_eybarticlepage_dbt_sectors'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='reminder_email_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
