# Generated by Django 4.2.17 on 2025-02-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international_online_offer', '0068_iootradeshowpage_dbt_sectors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagedata',
            name='location',
            field=models.CharField(
                choices=[
                    ('EAST_OF_ENGLAND', 'East of England'),
                    ('EAST_MIDLANDS', 'East Midlands, England'),
                    ('LONDON', 'London'),
                    ('NORTH_EAST', 'North East England'),
                    ('NORTH_WEST', 'North West England'),
                    ('NORTHERN_IRELAND', 'Northern Ireland'),
                    ('SCOTLAND', 'Scotland'),
                    ('SOUTH_EAST', 'South East England'),
                    ('SOUTH_WEST', 'South West England'),
                    ('WALES', 'Wales'),
                    ('WEST_MIDLANDS', 'West Midlands, England'),
                    ('YORKSHIRE_AND_THE_HUMBER', 'Yorkshire and the Humber, England'),
                ],
                max_length=255,
            ),
        ),
    ]
