# Generated by Django 4.2.19 on 2025-04-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international_online_offer', '0069_alter_triagedata_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='reminder_email_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
