# Generated by Django 4.2.17 on 2025-02-20 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('international_online_offer', '0069_alter_triagedata_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iootradeshowpage',
            name='tradeshow_location',
        ),
    ]
