# Generated by Django 4.2.20 on 2025-04-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international_online_offer', '0070_userdata_reminder_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='eybarticlepage',
            name='meta_robots_nofollow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eybarticlepage',
            name='meta_robots_noindex',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eybarticlespage',
            name='meta_robots_nofollow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eybarticlespage',
            name='meta_robots_noindex',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eybguidepage',
            name='meta_robots_nofollow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eybguidepage',
            name='meta_robots_noindex',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eybindexpage',
            name='meta_robots_nofollow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eybindexpage',
            name='meta_robots_noindex',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eybtradeshowspage',
            name='meta_robots_nofollow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eybtradeshowspage',
            name='meta_robots_noindex',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='iootradeshowpage',
            name='meta_robots_nofollow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='iootradeshowpage',
            name='meta_robots_noindex',
            field=models.BooleanField(default=False),
        ),
    ]
