# Generated by Django 4.2.15 on 2024-08-20 13:10

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greatinternationalhomepage',
            name='dep_cards',
            field=wagtail.fields.StreamField(
                [
                    (
                        'cards',
                        wagtail.blocks.StreamBlock(
                            [
                                (
                                    'topic_card',
                                    wagtail.blocks.StructBlock(
                                        [
                                            ('title', wagtail.blocks.CharBlock(label='Title', max_length=255)),
                                            (
                                                'description',
                                                wagtail.blocks.CharBlock(
                                                    label='Description', max_length=255, required=False
                                                ),
                                            ),
                                            ('link_text', wagtail.blocks.CharBlock(label='Link text', required=False)),
                                            ('link_url', wagtail.blocks.CharBlock(label='Link url')),
                                        ]
                                    ),
                                )
                            ],
                            block_counts={'topic_card': {'min_num': 1}},
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
