# Generated by Django 4.2.16 on 2024-11-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0002_alter_greatinternationalhomepage_dep_cards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
