# Generated by Django 4.2.19 on 2025-02-25 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0168_remove_curatedlistpage_struct_org_actions_and_more'),
        ('international', '0003_sector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='greatinternationalhomepage',
            name='struct_org_actions',
        ),
        migrations.RemoveField(
            model_name='greatinternationalhomepage',
            name='struct_org_address_country',
        ),
        migrations.RemoveField(
            model_name='greatinternationalhomepage',
            name='struct_org_address_locality',
        ),
        migrations.RemoveField(
            model_name='greatinternationalhomepage',
            name='struct_org_address_postal',
        ),
        migrations.RemoveField(
            model_name='greatinternationalhomepage',
            name='struct_org_address_region',
        ),
        migrations.RemoveField(
            model_name='greatinternationalhomepage',
            name='struct_org_address_street',
        ),
        migrations.RemoveField(
            model_name='greatinternationalhomepage',
            name='struct_org_extra_json',
        ),
        migrations.RemoveField(
            model_name='greatinternationalhomepage',
            name='struct_org_geo_lat',
        ),
        migrations.RemoveField(
            model_name='greatinternationalhomepage',
            name='struct_org_geo_lng',
        ),
        migrations.RemoveField(
            model_name='greatinternationalhomepage',
            name='struct_org_hours',
        ),
        migrations.RemoveField(
            model_name='greatinternationalhomepage',
            name='struct_org_image',
        ),
        migrations.RemoveField(
            model_name='greatinternationalhomepage',
            name='struct_org_logo',
        ),
        migrations.RemoveField(
            model_name='greatinternationalhomepage',
            name='struct_org_name',
        ),
        migrations.RemoveField(
            model_name='greatinternationalhomepage',
            name='struct_org_phone',
        ),
        migrations.RemoveField(
            model_name='greatinternationalhomepage',
            name='struct_org_type',
        ),
        migrations.AlterField(
            model_name='greatinternationalhomepage',
            name='og_image',
            field=models.ForeignKey(
                blank=True,
                help_text='Shown when linking to this page on social media. If blank, may show an image from the page, or the default from Settings > SEO.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='core.alttextimage',
                verbose_name='Preview image',
            ),
        ),
    ]
