version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: great_nginx
    ports:
      - '8080:80'
    networks:
      - inside-network

  pgsql:
    image: postgres:10
    container_name: great_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./docker_data/initdb.sh:/docker-entrypoint-initdb.d
      - ./docker_data/pgdata:/var/lib/postgresql/data
    ports:
      - '5431:5432'
    networks:
      - inside-network

  redis:
    image: redis
    container_name: great_redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      - inside-network
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    networks:
      - inside-network
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

networks:
  inside-network:
    driver: bridge
  directory-forms-api_outside-network:
    external: true

volumes:
  db-volume:
