import pytest
from django.test import override_settings


@pytest.mark.parametrize(
    'previous_url,migrated_url',
    (
        ('/international/site-help/', '/get-help/'),
        ('/international/site-help/success/', '/get-help/success/'),
        ('/investment-support-directory/', '/international/investment-support-directory/'),
        ('/international/trade/search/', '/international/buy-from-uk/find-a-supplier/'),
        ('/international/trade/', '/international/buy-from-uk/'),
        ('/international/content/trade/how-we-help-you-buy/', '/international/buy-from-uk/'),
        (
            '/international/content/investment/why-invest-in-the-uk/uk-investment-zones/',
            '/international/investment-opportunities/uk-investment-zones/',
        ),
        (
            '/international/content/investment/how-we-can-help/uk-tax-and-incentives/',
            '/international/investment-opportunities/uk-tax-and-incentives/',
        ),
        (
            '/international/content/investment/why-invest-in-the-uk/uk-talent-and-labour/',
            '/international/investment-opportunities/uk-talent-and-labour/',
        ),
        (
            '/international/content/investment/why-invest-in-the-uk/uk-innovation/',
            '/international/investment-opportunities/uk-innovation/',
        ),
        (
            '/international/content/investment/why-invest-in-the-uk/uk-infrastructure/',
            '/international/investment-opportunities/uk-infrastructure/',
        ),
        (
            '/international/content/investment/why-invest-in-the-uk/clean-growth-in-the-uk/',
            '/international/investment-opportunities/clean-growth-in-the-uk/',
        ),
        (
            '/international/content/investment/how-we-can-help/freeports-in-the-uk/',
            '/international/investment-opportunities/freeports-in-the-uk/',
        ),
        ('/international/content/investment/regions/', '/international/investment-opportunities/regions/'),
        ('/international/content/investment/regions/wales/', '/international/investment-opportunities/regions/wales/'),
        (
            '/international/content/investment/regions/south-england/',
            '/international/investment-opportunities/regions/south-england/',
        ),
        (
            '/international/content/investment/regions/northern-ireland/',
            '/international/investment-opportunities/regions/northern-ireland/',
        ),
        (
            '/international/content/investment/regions/north-england/',
            '/international/investment-opportunities/regions/north-england/',
        ),
        (
            '/international/content/investment/regions/midlands/',
            '/international/investment-opportunities/regions/midlands/',
        ),
        (
            '/international/content/investment/regions/scotland/',
            '/international/investment-opportunities/regions/scotland/',
        ),
        ('/international/content/investment/sectors/', '/international/investment-opportunities/sectors/'),
        (
            '/international/content/investment/sectors/aerospace-and-jet-zero/',
            '/international/investment-opportunities/sectors/aerospace-and-jet-zero/',
        ),
        (
            '/international/content/investment/sectors/biopharmaceuticals/',
            '/international/investment-opportunities/sectors/biopharmaceuticals/',
        ),
        (
            '/international/content/investment/sectors/carbon-capture-usage-and-storage/',
            '/international/investment-opportunities/sectors/carbon-capture-usage-and-storage/',
        ),
        (
            '/international/content/investment/sectors/chemicals/',
            '/international/investment-opportunities/sectors/chemicals/',
        ),
        (
            '/international/content/investment/sectors/civil-nuclear/',
            '/international/investment-opportunities/sectors/civil-nuclear/',
        ),
        (
            '/international/content/investment/sectors/agri-tech/',
            '/international/investment-opportunities/sectors/agri-tech/',
        ),
        (
            '/international/content/investment/sectors/creative-industries/',
            '/international/investment-opportunities/sectors/creative-industries/',
        ),
        (
            '/international/content/investment/sectors/cyber-security/',
            '/international/investment-opportunities/sectors/cyber-security/',
        ),
        (
            '/international/content/investment/sectors/edtech/',
            '/international/investment-opportunities/sectors/edtech/',
        ),
        (
            '/international/content/investment/sectors/financial-services/',
            '/international/investment-opportunities/sectors/financial-services/',
        ),
        (
            '/international/content/investment/sectors/fintech/',
            '/international/investment-opportunities/sectors/fintech/',
        ),
        (
            '/international/content/investment/sectors/food-and-drink/',
            '/international/investment-opportunities/sectors/food-and-drink/',
        ),
        (
            '/international/content/investment/sectors/precision-medicine/',
            '/international/investment-opportunities/sectors/precision-medicine/',
        ),
        (
            '/international/content/investment/sectors/green-shipping/',
            '/international/investment-opportunities/sectors/green-shipping/',
        ),
        (
            '/international/content/investment/sectors/green-finance/',
            '/international/investment-opportunities/sectors/green-finance/',
        ),
        (
            '/international/content/investment/sectors/greener-buildings/',
            '/international/investment-opportunities/sectors/greener-buildings/',
        ),
        (
            '/international/content/investment/sectors/healthcare-and-life-sciences/',
            '/international/investment-opportunities/sectors/healthcare-and-life-sciences/',
        ),
        (
            '/international/content/investment/sectors/hydrogen/',
            '/international/investment-opportunities/sectors/hydrogen/',
        ),
        (
            '/international/content/investment/sectors/medtech/',
            '/international/investment-opportunities/sectors/medtech/',
        ),
        (
            '/international/content/investment/sectors/mineral-extraction-and-refining/',
            '/international/investment-opportunities/sectors/mineral-extraction-and-refining/',
        ),
        (
            '/international/content/investment/sectors/offshore-wind/',
            '/international/investment-opportunities/sectors/offshore-wind/',
        ),
        (
            '/international/content/investment/sectors/professional-and-business-services/',
            '/international/investment-opportunities/sectors/professional-and-business-services/',
        ),
        (
            '/international/content/investment/sectors/real-estate/',
            '/international/investment-opportunities/sectors/real-estate/',
        ),
        (
            '/international/content/investment/sectors/retail/',
            '/international/investment-opportunities/sectors/retail/',
        ),
        ('/international/content/investment/sectors/space/', '/international/investment-opportunities/sectors/space/'),
        (
            '/international/content/investment/sectors/sports-economy/',
            '/international/investment-opportunities/sectors/sports-economy/',
        ),
        (
            '/international/content/investment/sectors/sustainable-infrastructure/',
            '/international/investment-opportunities/sectors/sustainable-infrastructure/',
        ),
        (
            '/international/content/investment/sectors/technology/',
            '/international/investment-opportunities/sectors/technology/',
        ),
        (
            '/international/content/investment/sectors/oil-and-gas/',
            '/international/investment-opportunities/sectors/oil-and-gas/',
        ),
        (
            '/international/content/investment/sectors/zero-emission-vehicles/',
            '/international/investment-opportunities/sectors/zero-emission-vehicles/',
        ),
        (
            '/international/content/investment/opportunities/accelerated-electrification-transition-in-the-north-east-of-england/',  # noqa:E501
            '/international/investment-opportunities/accelerated-electrification-transition-in-the-north-east-of-england/',  # noqa:E501
        ),
        (
            '/international/content/investment/opportunities/5g-and-digitisation-in-norfolk-and-suffolk-east-of-england/',  # noqa:E501
            '/international/investment-opportunities/5g-and-digitisation-in-norfolk-and-suffolk-east-of-england/',
        ),
        (
            '/international/content/investment/opportunities/biomanufacturing-in-tees-valley/',
            '/international/investment-opportunities/biomanufacturing-in-tees-valley/',
        ),
        (
            '/international/content/investment/opportunities/cam-modelling-and-simulation-in-oxfordshire/',
            '/international/investment-opportunities/cam-modelling-and-simulation-in-oxfordshire/',
        ),
        (
            '/international/content/investment/opportunities/cell-and-gene-therapy-in-hertfordshire/',
            '/international/investment-opportunities/cell-and-gene-therapy-in-hertfordshire/',
        ),
        (
            '/international/content/investment/opportunities/circular-economy-in-telford/',
            '/international/investment-opportunities/circular-economy-in-telford/',
        ),
        (
            '/international/content/investment/opportunities/compound-semiconductors-and-applications-in-south-wales/',
            '/international/investment-opportunities/compound-semiconductors-and-applications-in-south-wales/',
        ),
        (
            '/international/content/investment/opportunities/connected-and-immersive-technologies-for-future-mobility-in-coventry-and-warwickshire/',  # noqa:E501
            '/international/investment-opportunities/connected-and-immersive-technologies-for-future-mobility-in-coventry-and-warwickshire/',  # noqa:E501
        ),
        (
            '/international/content/investment/opportunities/cyber-security-in-gloucestershire/',
            '/international/investment-opportunities/cyber-security-in-gloucestershire/',
        ),
        (
            '/international/content/investment/opportunities/data-analytics-and-artificial-intelligence-applications-in-leeds-city-region/',  # noqa:E501
            '/international/investment-opportunities/data-analytics-and-artificial-intelligence-applications-in-leeds-city-region/',  # noqa:E501
        ),
        (
            '/international/content/investment/opportunities/food-processing-automation-in-greater-lincolnshire/',
            '/international/investment-opportunities/food-processing-automation-in-greater-lincolnshire/',
        ),
        (
            '/international/content/investment/opportunities/fusion-energy-in-oxfordshire/',
            '/international/investment-opportunities/fusion-energy-in-oxfordshire/',
        ),
        (
            '/international/content/investment/opportunities/future-of-aerospace-northern-ireland/',
            '/international/investment-opportunities/future-of-aerospace-northern-ireland/',
        ),
        (
            '/international/content/investment/opportunities/hydrogen-applications-in-thames-estuary/',
            '/international/investment-opportunities/hydrogen-applications-in-thames-estuary/',
        ),
        (
            '/international/content/investment/opportunities/mining-in-cornwall/',
            '/international/investment-opportunities/mining-in-cornwall/',
        ),
        (
            '/international/content/investment/opportunities/net-zero-transport-in-coventry-and-warwickshire/',
            '/international/investment-opportunities/net-zero-transport-in-coventry-and-warwickshire/',
        ),
        (
            '/international/content/investment/opportunities/nucleic-acid-therapies-in-oxfordshire/',
            '/international/investment-opportunities/nucleic-acid-therapies-in-oxfordshire/',
        ),
        (
            '/international/content/investment/opportunities/offshore-wind-floating-substructures-in-scotland/',
            '/international/investment-opportunities/offshore-wind-floating-substructures-in-scotland/',
        ),
        (
            '/international/content/investment/opportunities/plant-science-for-nutrition-in-norfolk-and-suffolk/',
            '/international/investment-opportunities/plant-science-for-nutrition-in-norfolk-and-suffolk/',
        ),
        (
            '/international/content/investment/opportunities/precision-farming-in-telford/',
            '/international/investment-opportunities/precision-farming-in-telford/',
        ),
        (
            '/international/content/investment/opportunities/rail-in-doncaster/',
            '/international/investment-opportunities/rail-in-doncaster/',
        ),
        (
            '/international/content/investment/opportunities/regtech-in-northern-ireland/',
            '/international/investment-opportunities/regtech-in-northern-ireland/',
        ),
        (
            '/international/content/investment/opportunities/smart-and-sustainable-aviation-in-south-west-england/',
            '/international/investment-opportunities/smart-and-sustainable-aviation-in-south-west-england/',
        ),
        (
            '/international/content/investment/opportunities/vaccine-development-and-manufacture-in-liverpool-city-region/',  # noqa:E501
            '/international/investment-opportunities/vaccine-development-and-manufacture-in-liverpool-city-region/',
        ),
        (
            '/international/content/investment/opportunities/anglesey-freeport/',
            '/international/investment-opportunities/anglesey-freeport/',
        ),
        (
            '/international/content/investment/opportunities/celtic-freeport/',
            '/international/investment-opportunities/celtic-freeport/',
        ),
        (
            '/international/content/investment/opportunities/east-midlands-freeport/',
            '/international/investment-opportunities/east-midlands-freeport/',
        ),
        (
            '/international/content/investment/opportunities/forth-green-freeport/',
            '/international/investment-opportunities/forth-green-freeport/',
        ),
        (
            '/international/content/investment/opportunities/felixstowe-and-harwich-freeport/',
            '/international/investment-opportunities/felixstowe-and-harwich-freeport/',
        ),
        (
            '/international/content/investment/opportunities/humber-freeport/',
            '/international/investment-opportunities/humber-freeport/',
        ),
        (
            '/international/content/investment/opportunities/inverness-and-cromarty-firth-green-freeport/',
            '/international/investment-opportunities/inverness-and-cromarty-firth-green-freeport/',
        ),
        (
            '/international/content/investment/opportunities/liverpool-city-region-freeport/',
            '/international/investment-opportunities/liverpool-city-region-freeport/',
        ),
        (
            '/international/content/investment/opportunities/plymouth-and-south-devon-freeport/',
            '/international/investment-opportunities/plymouth-and-south-devon-freeport/',
        ),
        ('/international/content/investment/opportunities/solent/', '/international/investment-opportunities/solent/'),
        (
            '/international/content/investment/opportunities/teesside-freeport/',
            '/international/investment-opportunities/teesside-freeport/',
        ),
        (
            '/international/content/investment/opportunities/thames-freeport/',
            '/international/investment-opportunities/thames-freeport/',
        ),
        (
            '/international/contact/',
            '/get-help/',
        ),
        (
            '/international/content/investment/how-we-can-help/global-entrepreneur-program/',
            '/campaign-site/gep/',
        ),
        (
            '/international/content/investment/how-we-can-help/the-venture-capital-unit/',
            '/international/expand-business-in-the-uk/',
        ),
        (
            '/international/content/investment/how-we-can-help/',
            '/international/expand-business-in-the-uk/',
        ),
        (
            '/international/content/investment/why-invest-in-the-uk/',
            '/international/',
        ),
        (
            '/international/content/investment/how-we-can-help/research-and-development-rd-support-in-the-uk/',
            '/international/expand-business-in-the-uk/',
        ),
        (
            '/international/trade/contact/',
            '/international/',
        ),
        (
            '/international/invest/contact/',
            '/international/',
        ),
        (
            '/international/content/investment/how-we-can-help/the-office-for-investment/',
            '/international/',
        ),
        (
            '/international/content/investment/how-we-can-help/hire-skilled-workers-for-your-uk-operations/',
            '/international/expand-business-in-the-uk/',
        ),
        (
            '/international/content/investment/how-we-can-help/access-finance-in-the-uk/',
            '/international/expand-business-in-the-uk/',
        ),
        (
            '/international/content/investment/how-we-can-help/establish-a-base-for-business-in-the-uk/',
            '/international/expand-business-in-the-uk/',
        ),
        (
            '/international/content/investment/how-we-can-help/register-a-company-in-the-uk/',
            '/international/expand-business-in-the-uk/',
        ),
        (
            '/international/content/investment/how-we-can-help/uk-visas-and-migration/',
            '/international/expand-business-in-the-uk/',
        ),
        (
            '/international/content/investment/how-we-can-help/open-a-uk-business-bank-account/',
            '/international/expand-business-in-the-uk/',
        ),
        ('/international/content/invest/how-to-setup-in-the-uk/', '/international/expand-business-in-the-uk/'),
        (
            '/international/content/invest/how-to-setup-in-the-uk/random-sub-route/',
            '/international/expand-business-in-the-uk/',
        ),
    ),
)
@pytest.mark.django_db
def test_international_redirects(previous_url, migrated_url, client):
    """
    test redirects implemented as part of the migration from great-international-ui to great-cms and bgs updates

    """
    response = client.get(previous_url)
    assert response.status_code == 301
    assert response.url == migrated_url


@pytest.mark.parametrize(
    'previous_url,migrated_url',
    (
        ('/international/site-help/', '/get-help/'),
        ('/international/site-help/success/', '/get-help/success/'),
        ('/international/trade/search/', '/invest-in-uk/buy-from-uk/find-a-supplier/'),
        ('/international/trade/', '/invest-in-uk/buy-from-uk/'),
        ('/international/content/trade/how-we-help-you-buy/', '/invest-in-uk/buy-from-uk/'),
        (
            '/international/content/investment/why-invest-in-the-uk/uk-investment-zones/',
            '/invest-in-uk/investment-opportunities/uk-investment-zones/',
        ),
        (
            '/international/content/investment/how-we-can-help/uk-tax-and-incentives/',
            '/invest-in-uk/investment-opportunities/uk-tax-and-incentives/',
        ),
        (
            '/international/content/investment/why-invest-in-the-uk/uk-talent-and-labour/',
            '/invest-in-uk/investment-opportunities/uk-talent-and-labour/',
        ),
        (
            '/international/content/investment/why-invest-in-the-uk/uk-innovation/',
            '/invest-in-uk/investment-opportunities/uk-innovation/',
        ),
        (
            '/international/content/investment/why-invest-in-the-uk/uk-infrastructure/',
            '/invest-in-uk/investment-opportunities/uk-infrastructure/',
        ),
        (
            '/international/content/investment/why-invest-in-the-uk/clean-growth-in-the-uk/',
            '/invest-in-uk/investment-opportunities/clean-growth-in-the-uk/',
        ),
        (
            '/international/content/investment/how-we-can-help/freeports-in-the-uk/',
            '/invest-in-uk/investment-opportunities/freeports-in-the-uk/',
        ),
        ('/international/content/investment/regions/', '/invest-in-uk/investment-opportunities/regions/'),
        ('/international/content/investment/regions/wales/', '/invest-in-uk/investment-opportunities/regions/wales/'),
        (
            '/international/content/investment/regions/south-england/',
            '/invest-in-uk/investment-opportunities/regions/south-england/',
        ),
        (
            '/international/content/investment/regions/northern-ireland/',
            '/invest-in-uk/investment-opportunities/regions/northern-ireland/',
        ),
        (
            '/international/content/investment/regions/north-england/',
            '/invest-in-uk/investment-opportunities/regions/north-england/',
        ),
        (
            '/international/content/investment/regions/midlands/',
            '/invest-in-uk/investment-opportunities/regions/midlands/',
        ),
        (
            '/international/content/investment/regions/scotland/',
            '/invest-in-uk/investment-opportunities/regions/scotland/',
        ),
        ('/international/content/investment/sectors/', '/invest-in-uk/investment-opportunities/sectors/'),
        (
            '/international/content/investment/sectors/aerospace-and-jet-zero/',
            '/invest-in-uk/investment-opportunities/sectors/aerospace-and-jet-zero/',
        ),
        (
            '/international/content/investment/sectors/biopharmaceuticals/',
            '/invest-in-uk/investment-opportunities/sectors/biopharmaceuticals/',
        ),
        (
            '/international/content/investment/sectors/carbon-capture-usage-and-storage/',
            '/invest-in-uk/investment-opportunities/sectors/carbon-capture-usage-and-storage/',
        ),
        (
            '/international/content/investment/sectors/chemicals/',
            '/invest-in-uk/investment-opportunities/sectors/chemicals/',
        ),
        (
            '/international/content/investment/sectors/civil-nuclear/',
            '/invest-in-uk/investment-opportunities/sectors/civil-nuclear/',
        ),
        (
            '/international/content/investment/sectors/agri-tech/',
            '/invest-in-uk/investment-opportunities/sectors/agri-tech/',
        ),
        (
            '/international/content/investment/sectors/creative-industries/',
            '/invest-in-uk/investment-opportunities/sectors/creative-industries/',
        ),
        (
            '/international/content/investment/sectors/cyber-security/',
            '/invest-in-uk/investment-opportunities/sectors/cyber-security/',
        ),
        ('/international/content/investment/sectors/edtech/', '/invest-in-uk/investment-opportunities/sectors/edtech/'),
        (
            '/international/content/investment/sectors/financial-services/',
            '/invest-in-uk/investment-opportunities/sectors/financial-services/',
        ),
        (
            '/international/content/investment/sectors/fintech/',
            '/invest-in-uk/investment-opportunities/sectors/fintech/',
        ),
        (
            '/international/content/investment/sectors/food-and-drink/',
            '/invest-in-uk/investment-opportunities/sectors/food-and-drink/',
        ),
        (
            '/international/content/investment/sectors/precision-medicine/',
            '/invest-in-uk/investment-opportunities/sectors/precision-medicine/',
        ),
        (
            '/international/content/investment/sectors/green-shipping/',
            '/invest-in-uk/investment-opportunities/sectors/green-shipping/',
        ),
        (
            '/international/content/investment/sectors/green-finance/',
            '/invest-in-uk/investment-opportunities/sectors/green-finance/',
        ),
        (
            '/international/content/investment/sectors/greener-buildings/',
            '/invest-in-uk/investment-opportunities/sectors/greener-buildings/',
        ),
        (
            '/international/content/investment/sectors/healthcare-and-life-sciences/',
            '/invest-in-uk/investment-opportunities/sectors/healthcare-and-life-sciences/',
        ),
        (
            '/international/content/investment/sectors/hydrogen/',
            '/invest-in-uk/investment-opportunities/sectors/hydrogen/',
        ),
        (
            '/international/content/investment/sectors/medtech/',
            '/invest-in-uk/investment-opportunities/sectors/medtech/',
        ),
        (
            '/international/content/investment/sectors/mineral-extraction-and-refining/',
            '/invest-in-uk/investment-opportunities/sectors/mineral-extraction-and-refining/',
        ),
        (
            '/international/content/investment/sectors/offshore-wind/',
            '/invest-in-uk/investment-opportunities/sectors/offshore-wind/',
        ),
        (
            '/international/content/investment/sectors/professional-and-business-services/',
            '/invest-in-uk/investment-opportunities/sectors/professional-and-business-services/',
        ),
        (
            '/international/content/investment/sectors/real-estate/',
            '/invest-in-uk/investment-opportunities/sectors/real-estate/',
        ),
        ('/international/content/investment/sectors/retail/', '/invest-in-uk/investment-opportunities/sectors/retail/'),
        ('/international/content/investment/sectors/space/', '/invest-in-uk/investment-opportunities/sectors/space/'),
        (
            '/international/content/investment/sectors/sports-economy/',
            '/invest-in-uk/investment-opportunities/sectors/sports-economy/',
        ),
        (
            '/international/content/investment/sectors/sustainable-infrastructure/',
            '/invest-in-uk/investment-opportunities/sectors/sustainable-infrastructure/',
        ),
        (
            '/international/content/investment/sectors/technology/',
            '/invest-in-uk/investment-opportunities/sectors/technology/',
        ),
        (
            '/international/content/investment/sectors/oil-and-gas/',
            '/invest-in-uk/investment-opportunities/sectors/oil-and-gas/',
        ),
        (
            '/international/content/investment/sectors/zero-emission-vehicles/',
            '/invest-in-uk/investment-opportunities/sectors/zero-emission-vehicles/',
        ),
        (
            '/international/content/investment/opportunities/accelerated-electrification-transition-in-the-north-east-of-england/',  # noqa:E501
            '/invest-in-uk/investment-opportunities/accelerated-electrification-transition-in-the-north-east-of-england/',  # noqa:E501
        ),
        (
            '/international/content/investment/opportunities/5g-and-digitisation-in-norfolk-and-suffolk-east-of-england/',  # noqa:E501
            '/invest-in-uk/investment-opportunities/5g-and-digitisation-in-norfolk-and-suffolk-east-of-england/',
        ),
        (
            '/international/content/investment/opportunities/biomanufacturing-in-tees-valley/',
            '/invest-in-uk/investment-opportunities/biomanufacturing-in-tees-valley/',
        ),
        (
            '/international/content/investment/opportunities/cam-modelling-and-simulation-in-oxfordshire/',
            '/invest-in-uk/investment-opportunities/cam-modelling-and-simulation-in-oxfordshire/',
        ),
        (
            '/international/content/investment/opportunities/cell-and-gene-therapy-in-hertfordshire/',
            '/invest-in-uk/investment-opportunities/cell-and-gene-therapy-in-hertfordshire/',
        ),
        (
            '/international/content/investment/opportunities/circular-economy-in-telford/',
            '/invest-in-uk/investment-opportunities/circular-economy-in-telford/',
        ),
        (
            '/international/content/investment/opportunities/compound-semiconductors-and-applications-in-south-wales/',
            '/invest-in-uk/investment-opportunities/compound-semiconductors-and-applications-in-south-wales/',
        ),
        (
            '/international/content/investment/opportunities/connected-and-immersive-technologies-for-future-mobility-in-coventry-and-warwickshire/',  # noqa:E501
            '/invest-in-uk/investment-opportunities/connected-and-immersive-technologies-for-future-mobility-in-coventry-and-warwickshire/',  # noqa:E501
        ),
        (
            '/international/content/investment/opportunities/cyber-security-in-gloucestershire/',
            '/invest-in-uk/investment-opportunities/cyber-security-in-gloucestershire/',
        ),
        (
            '/international/content/investment/opportunities/data-analytics-and-artificial-intelligence-applications-in-leeds-city-region/',  # noqa:E501
            '/invest-in-uk/investment-opportunities/data-analytics-and-artificial-intelligence-applications-in-leeds-city-region/',  # noqa:E501
        ),
        (
            '/international/content/investment/opportunities/food-processing-automation-in-greater-lincolnshire/',
            '/invest-in-uk/investment-opportunities/food-processing-automation-in-greater-lincolnshire/',
        ),
        (
            '/international/content/investment/opportunities/fusion-energy-in-oxfordshire/',
            '/invest-in-uk/investment-opportunities/fusion-energy-in-oxfordshire/',
        ),
        (
            '/international/content/investment/opportunities/future-of-aerospace-northern-ireland/',
            '/invest-in-uk/investment-opportunities/future-of-aerospace-northern-ireland/',
        ),
        (
            '/international/content/investment/opportunities/hydrogen-applications-in-thames-estuary/',
            '/invest-in-uk/investment-opportunities/hydrogen-applications-in-thames-estuary/',
        ),
        (
            '/international/content/investment/opportunities/mining-in-cornwall/',
            '/invest-in-uk/investment-opportunities/mining-in-cornwall/',
        ),
        (
            '/international/content/investment/opportunities/net-zero-transport-in-coventry-and-warwickshire/',
            '/invest-in-uk/investment-opportunities/net-zero-transport-in-coventry-and-warwickshire/',
        ),
        (
            '/international/content/investment/opportunities/nucleic-acid-therapies-in-oxfordshire/',
            '/invest-in-uk/investment-opportunities/nucleic-acid-therapies-in-oxfordshire/',
        ),
        (
            '/international/content/investment/opportunities/offshore-wind-floating-substructures-in-scotland/',
            '/invest-in-uk/investment-opportunities/offshore-wind-floating-substructures-in-scotland/',
        ),
        (
            '/international/content/investment/opportunities/plant-science-for-nutrition-in-norfolk-and-suffolk/',
            '/invest-in-uk/investment-opportunities/plant-science-for-nutrition-in-norfolk-and-suffolk/',
        ),
        (
            '/international/content/investment/opportunities/precision-farming-in-telford/',
            '/invest-in-uk/investment-opportunities/precision-farming-in-telford/',
        ),
        (
            '/international/content/investment/opportunities/rail-in-doncaster/',
            '/invest-in-uk/investment-opportunities/rail-in-doncaster/',
        ),
        (
            '/international/content/investment/opportunities/regtech-in-northern-ireland/',
            '/invest-in-uk/investment-opportunities/regtech-in-northern-ireland/',
        ),
        (
            '/international/content/investment/opportunities/smart-and-sustainable-aviation-in-south-west-england/',
            '/invest-in-uk/investment-opportunities/smart-and-sustainable-aviation-in-south-west-england/',
        ),
        (
            '/international/content/investment/opportunities/vaccine-development-and-manufacture-in-liverpool-city-region/',  # noqa:E501
            '/invest-in-uk/investment-opportunities/vaccine-development-and-manufacture-in-liverpool-city-region/',
        ),
        (
            '/international/content/investment/opportunities/anglesey-freeport/',
            '/invest-in-uk/investment-opportunities/anglesey-freeport/',
        ),
        (
            '/international/content/investment/opportunities/celtic-freeport/',
            '/invest-in-uk/investment-opportunities/celtic-freeport/',
        ),
        (
            '/international/content/investment/opportunities/east-midlands-freeport/',
            '/invest-in-uk/investment-opportunities/east-midlands-freeport/',
        ),
        (
            '/international/content/investment/opportunities/forth-green-freeport/',
            '/invest-in-uk/investment-opportunities/forth-green-freeport/',
        ),
        (
            '/international/content/investment/opportunities/felixstowe-and-harwich-freeport/',
            '/invest-in-uk/investment-opportunities/felixstowe-and-harwich-freeport/',
        ),
        (
            '/international/content/investment/opportunities/humber-freeport/',
            '/invest-in-uk/investment-opportunities/humber-freeport/',
        ),
        (
            '/international/content/investment/opportunities/inverness-and-cromarty-firth-green-freeport/',
            '/invest-in-uk/investment-opportunities/inverness-and-cromarty-firth-green-freeport/',
        ),
        (
            '/international/content/investment/opportunities/liverpool-city-region-freeport/',
            '/invest-in-uk/investment-opportunities/liverpool-city-region-freeport/',
        ),
        (
            '/international/content/investment/opportunities/plymouth-and-south-devon-freeport/',
            '/invest-in-uk/investment-opportunities/plymouth-and-south-devon-freeport/',
        ),
        ('/international/content/investment/opportunities/solent/', '/invest-in-uk/investment-opportunities/solent/'),
        (
            '/international/content/investment/opportunities/teesside-freeport/',
            '/invest-in-uk/investment-opportunities/teesside-freeport/',
        ),
        (
            '/international/content/investment/opportunities/thames-freeport/',
            '/invest-in-uk/investment-opportunities/thames-freeport/',
        ),
        (
            '/international/contact/',
            '/get-help/',
        ),
        (
            '/international/content/investment/how-we-can-help/global-entrepreneur-program/',
            '/campaign-site/gep/',
        ),
        (
            '/international/content/investment/how-we-can-help/the-venture-capital-unit/',
            '/invest-in-uk/expand-business-in-the-uk/',
        ),
        (
            '/international/content/investment/how-we-can-help/',
            '/invest-in-uk/expand-business-in-the-uk/',
        ),
        (
            '/international/content/investment/why-invest-in-the-uk/',
            '/invest-in-uk/',
        ),
        (
            '/international/content/investment/how-we-can-help/research-and-development-rd-support-in-the-uk/',
            '/invest-in-uk/expand-business-in-the-uk/',
        ),
        (
            '/international/trade/contact/',
            '/invest-in-uk/',
        ),
        (
            '/international/invest/contact/',
            '/invest-in-uk/',
        ),
        (
            '/international/content/investment/how-we-can-help/the-office-for-investment/',
            '/invest-in-uk/',
        ),
        (
            '/international/content/investment/how-we-can-help/hire-skilled-workers-for-your-uk-operations/',
            '/invest-in-uk/expand-business-in-the-uk/',
        ),
        (
            '/international/content/investment/how-we-can-help/access-finance-in-the-uk/',
            '/invest-in-uk/expand-business-in-the-uk/',
        ),
        (
            '/international/content/investment/how-we-can-help/establish-a-base-for-business-in-the-uk/',
            '/invest-in-uk/expand-business-in-the-uk/',
        ),
        (
            '/international/content/investment/how-we-can-help/register-a-company-in-the-uk/',
            '/invest-in-uk/expand-business-in-the-uk/',
        ),
        (
            '/international/content/investment/how-we-can-help/uk-visas-and-migration/',
            '/invest-in-uk/expand-business-in-the-uk/',
        ),
        (
            '/international/content/investment/how-we-can-help/open-a-uk-business-bank-account/',
            '/invest-in-uk/expand-business-in-the-uk/',
        ),
        ('/international/content/invest/how-to-setup-in-the-uk/', '/invest-in-uk/expand-business-in-the-uk/'),
        (
            '/international/content/invest/how-to-setup-in-the-uk/random-sub-route/',
            '/invest-in-uk/expand-business-in-the-uk/',
        ),
    ),
)
@pytest.mark.django_db
@override_settings(OVERRIDE_BGS_REDIRECT=True)
def test_invest_in_uk_redirects(previous_url, migrated_url, client):
    """
    test redirects to new bgs url structure

    """
    response = client.get(previous_url)

    # Middleware will alter the url and use redirect()
    assert response.status_code == 302
    redirected_response = client.get(response.url)

    # redirect_urls will carry out the permanent redirects as per the agreed mapping
    assert redirected_response.status_code == 301
    assert redirected_response.url == migrated_url
