# Generated by Django 2.2.24 on 2021-09-16 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('core', '0067_greatmedia_subtitles_en'),
        ('exportplan', '0003_exportplandashboardpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExportPlanDashboardPage',
        ),
    ]
