# Generated by Django 2.2.18 on 2021-02-02 14:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    replaces = [
        ('learn', '0001_initial'),
        ('learn', '0002_delete_lessonpage'),
        ('learn', '0003_lessonpage_matchcountryquerystring_matchproductquerystring'),
        ('learn', '0004_auto_20200319_1734'),
        ('learn', '0005_auto_20200323_1608'),
        ('learn', '0006_auto_20200326_1625'),
        ('learn', '0007_auto_20200330_0848'),
        ('learn', '0008_auto_20200408_0851'),
    ]

    initial = True

    dependencies = [
        ('core', '0006_auto_20200323_1413'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_country_product'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('core', '0008_auto_20200408_0851'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
    ]

    operations = []
