# Generated by Django 2.2.10 on 2020-03-09 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LessonPage',
        ),
    ]
