# Generated by Django 2.2.10 on 2020-03-19 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_lessonpage_matchcountryquerystring_matchproductquerystring'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchproductquerystring',
            name='product',
        ),
        migrations.RemoveField(
            model_name='matchproductquerystring',
            name='segment',
        ),
        migrations.DeleteModel(
            name='MatchCountryQuerystring',
        ),
        migrations.DeleteModel(
            name='MatchProductQuerystring',
        ),
    ]
