# Generated by Django 2.2.10 on 2020-03-23 16:08

import django.db.models.deletion
import django_extensions.db.fields
import wagtail.core.blocks
import wagtail.core.fields
import wagtail_personalisation.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_auto_20200319_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonpage',
            name='generic_content',
            field=wagtail.core.fields.StreamField([('generic_content', wagtail.core.blocks.StructBlock([('segment', wagtail.core.blocks.ChoiceBlock(choices=wagtail_personalisation.blocks.list_segment_choices, help_text='Only show this content block for users in this segment', label='Personalisation segment', required=False)), ('paragraph', wagtail.core.blocks.RichTextBlock())], icon='pilcrow', template='core/personalised_page_struct_paragraph_block.html'))]),
        ),
        migrations.CreateModel(
            name='LessonViewHit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, null=True, verbose_name='modified')),
                ('sso_id', models.TextField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_views', to='learn.LessonPage')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_topic_views', to='learn.TopicPage')),
            ],
            options={
                'ordering': ['lesson__pk'],
                'unique_together': {('lesson', 'sso_id')},
            },
        ),
    ]
