# Generated by Django 2.2.10 on 2020-03-26 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('learn', '0005_auto_20200323_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='lessonviewhit',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_hits', to='learn.LessonPage'),
        ),
        migrations.AlterField(
            model_name='lessonviewhit',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_hits_topic', to='learn.TopicPage'),
        ),
        migrations.AlterUniqueTogether(
            name='lessonviewhit',
            unique_together={('lesson', 'topic', 'sso_id')},
        ),
    ]
