# Generated by Django 2.2.10 on 2020-03-30 08:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('core', '0006_auto_20200323_1413'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtail_personalisation', '0025_auto_20190822_0627'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('learn', '0006_auto_20200326_1625'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LandingPage',
            new_name='LearnPage',
        ),
    ]
