# Generated by Django 2.2.10 on 2020-04-08 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('core', '0008_auto_20200408_0851'),
        ('wagtail_personalisation', '0025_auto_20190822_0627'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('learn', '0007_auto_20200330_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonpage',
            name='page_ptr',
        ),
        migrations.AlterUniqueTogether(
            name='lessonviewhit',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='lessonviewhit',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='lessonviewhit',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='topicpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='LearnPage',
        ),
        migrations.DeleteModel(
            name='LessonPage',
        ),
        migrations.DeleteModel(
            name='LessonViewHit',
        ),
        migrations.DeleteModel(
            name='TopicPage',
        ),
    ]
