# Generated by Django 4.2.14 on 2024-08-05 17:48

import django.contrib.postgres.fields
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learn', '0001_squashed_0008_auto_20200408_0851'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsatUserFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, null=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, null=True, verbose_name='modified'
                    ),
                ),
                ('URL', models.CharField(max_length=255)),
                (
                    'user_journey',
                    models.CharField(
                        choices=[('ARTICLE_PAGE', 'Article Page')], default='ARTICLE_PAGE', max_length=255, null=True
                    ),
                ),
                (
                    'satisfaction_rating',
                    models.CharField(
                        choices=[
                            ('VERY_DISSATISFIED', 'Very dissatisfied'),
                            ('DISSATISFIED', 'Dissatisfied'),
                            ('NEITHER', 'Neither satisfied nor dissatisfied'),
                            ('SATISFIED', 'Satisfied'),
                            ('VERY_SATISFIED', 'Very satisfied'),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    'experienced_issues',
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ('NOT_FIND_LOOKING_FOR', 'I did not find what I was looking for'),
                                ('DIFFICULT_TO_NAVIGATE', 'I found it difficult to navigate the service'),
                                ('SYSTEM_LACKS_FEATURE', 'The service lacks the feature I need'),
                                ('UNABLE_TO_LOAD/REFRESH/ENTER', 'I was unable to load/refresh/enter a page'),
                                ('OTHER', 'Other'),
                                ('NO_ISSUE', 'I did not experience any issues'),
                            ],
                            max_length=255,
                        ),
                        default=list,
                        null=True,
                        size=6,
                    ),
                ),
                ('other_detail', models.CharField(max_length=255, null=True)),
                ('service_improvements_feedback', models.CharField(max_length=3000, null=True)),
                (
                    'likelihood_of_return',
                    models.CharField(
                        choices=[
                            ('EXTREMELY_UNLIKELY', 'Extremely unlikely'),
                            ('UNLIKELY', 'Unlikely'),
                            ('NEITHER_LIKELY_NOR_UNLIKELY', 'Neither likely nor unlikely'),
                            ('LIKELY', 'Likely'),
                            ('EXTREMELY_LIKELY', 'Extremely likely'),
                            ('DONT_KNOW_OR_PREFER_NOT_TO_SAY', "Don't know/prefer not to say"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
