# Generated by Django 4.2.19 on 2025-03-10 13:42

from django.db import migrations, models
import django.db.models.deletion
import domestic_growth.cms_panels
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('core', '0169_merge_20250304_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomesticGrowthHomePage',
            fields=[
                (
                    'page_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='wagtailcore.page',
                    ),
                ),
                (
                    'canonical_url',
                    models.URLField(
                        blank=True,
                        help_text="Leave blank to use the page's URL.",
                        max_length=255,
                        verbose_name='Canonical URL',
                    ),
                ),
                ('hero_title', models.TextField(null=True)),
                (
                    'hero_body',
                    wagtail.fields.StreamField(
                        [('hero_cards', 4)],
                        blank=True,
                        block_lookup={
                            0: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 255}),
                            1: (
                                'wagtail.blocks.CharBlock',
                                (),
                                {'label': 'Description', 'max_length': 255, 'required': False},
                            ),
                            2: ('wagtail.blocks.CharBlock', (), {'label': 'URL', 'max_length': 255, 'required': False}),
                            3: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('url', 2)]], {}),
                            4: (
                                'wagtail.blocks.StreamBlock',
                                [[('hero_card', 3)]],
                                {'block_counts': {'hero_card': {'min_num': 4}}},
                            ),
                        },
                        null=True,
                    ),
                ),
                ('news_title', models.TextField(null=True)),
                (
                    'og_image',
                    models.ForeignKey(
                        blank=True,
                        help_text='Shown when linking to this page on social media. If blank, may show an image from the page, or the default from Settings > SEO.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='core.alttextimage',
                        verbose_name='Preview image',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Domestic Growth Home page',
            },
            bases=(domestic_growth.cms_panels.DomesticGrowthHomePagePanels, 'wagtailcore.page', models.Model),
        ),
    ]
