# Generated by Django 4.2.19 on 2025-03-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_growth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domesticgrowthhomepage',
            name='explore_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
