# Generated by Django 4.2.19 on 2025-02-25 11:31

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_growth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domesticgrowthlandingpage',
            name='hero_body',
            field=wagtail.fields.StreamField(
                [
                    (
                        'hero_cards',
                        wagtail.blocks.StreamBlock(
                            [
                                (
                                    'hero_card',
                                    wagtail.blocks.StructBlock(
                                        [
                                            ('title', wagtail.blocks.CharBlock(label='Title', max_length=255)),
                                            (
                                                'description',
                                                wagtail.blocks.CharBlock(
                                                    label='Description', max_length=255, required=False
                                                ),
                                            ),
                                        ]
                                    ),
                                )
                            ],
                            block_counts={'hero_card': {'min_num': 3}},
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
