# Generated by Django 4.2.19 on 2025-03-12 10:12

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_growth', '0002_alter_domesticgrowthhomepage_explore_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='domesticgrowthhomepage',
            name='guidance_body',
            field=wagtail.fields.StreamField(
                [('guidance_cards', 4)],
                blank=True,
                block_lookup={
                    0: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 255}),
                    1: ('wagtail.blocks.CharBlock', (), {'label': 'Description', 'max_length': 255, 'required': False}),
                    2: ('wagtail.blocks.CharBlock', (), {'label': 'URL', 'max_length': 255, 'required': False}),
                    3: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('url', 2)]], {}),
                    4: (
                        'wagtail.blocks.StreamBlock',
                        [[('guidance_card', 3)]],
                        {'block_counts': {'guidance_card': {'min_num': 4}}},
                    ),
                },
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='domesticgrowthhomepage',
            name='guidance_title',
            field=models.TextField(null=True),
        ),
    ]
