# Generated by Django 4.2.19 on 2025-03-14 10:01

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models

import domestic_growth.cms_panels


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('core', '0169_merge_20250304_1128'),
        ('domestic_growth', '0003_domesticgrowthhomepage_guidance_body_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomesticGrowthGuidePage',
            fields=[
                (
                    'page_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='wagtailcore.page',
                    ),
                ),
                (
                    'canonical_url',
                    models.URLField(
                        blank=True,
                        help_text="Leave blank to use the page's URL.",
                        max_length=255,
                        verbose_name='Canonical URL',
                    ),
                ),
                ('hero_title', models.TextField(null=True)),
                ('hero_intro', models.TextField(null=True)),
                ('body_title', models.TextField(null=True)),
                ('body_intro', models.TextField(null=True)),
                (
                    'og_image',
                    models.ForeignKey(
                        blank=True,
                        help_text='Shown when linking to this page on social media. If blank, may show an image from the page, or the default from Settings > SEO.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='core.alttextimage',
                        verbose_name='Preview image',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Domestic Growth Guide page',
            },
            bases=(domestic_growth.cms_panels.DomesticGrowthGuidePagePanels, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='DomesticGrowthChildGuidePage',
            fields=[
                (
                    'page_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='wagtailcore.page',
                    ),
                ),
                (
                    'canonical_url',
                    models.URLField(
                        blank=True,
                        help_text="Leave blank to use the page's URL.",
                        max_length=255,
                        verbose_name='Canonical URL',
                    ),
                ),
                ('body_title', models.TextField(null=True)),
                ('body_intro', models.TextField(null=True)),
                (
                    'body_sections',
                    wagtail.fields.StreamField(
                        [('section', 1)],
                        blank=True,
                        block_lookup={
                            0: ('wagtail.blocks.CharBlock', (), {}),
                            1: ('wagtail.blocks.StructBlock', [[('title', 0), ('intro', 0)]], {}),
                        },
                        null=True,
                    ),
                ),
                (
                    'og_image',
                    models.ForeignKey(
                        blank=True,
                        help_text='Shown when linking to this page on social media. If blank, may show an image from the page, or the default from Settings > SEO.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='core.alttextimage',
                        verbose_name='Preview image',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Domestic Growth Child Guide page',
            },
            bases=(domestic_growth.cms_panels.DomesticGrowthChildGuidePagePanels, 'wagtailcore.page', models.Model),
        ),
    ]
