# Generated by Django 4.2.19 on 2025-02-25 12:17

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_growth', '0003_alter_domesticgrowthlandingpage_hero_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='domesticgrowthlandingpage',
            name='support_body',
            field=wagtail.fields.StreamField(
                [
                    (
                        'support_cards',
                        wagtail.blocks.StreamBlock(
                            [
                                (
                                    'support_card',
                                    wagtail.blocks.StructBlock(
                                        [
                                            ('title', wagtail.blocks.CharBlock(label='Title', max_length=255)),
                                            (
                                                'description',
                                                wagtail.blocks.CharBlock(
                                                    label='Description', max_length=255, required=False
                                                ),
                                            ),
                                            (
                                                'url',
                                                wagtail.blocks.CharBlock(label='URL', max_length=255, required=False),
                                            ),
                                        ]
                                    ),
                                )
                            ],
                            block_counts={'support_card': {'min_num': 3}},
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AddField(
            model_name='domesticgrowthlandingpage',
            name='support_title',
            field=models.TextField(null=True),
        ),
    ]
