# Generated by Django 4.2.19 on 2025-02-25 13:38

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_growth', '0004_domesticgrowthlandingpage_support_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domesticgrowthlandingpage',
            name='popular_body',
            field=wagtail.fields.StreamField(
                [
                    (
                        'popular_cards',
                        wagtail.blocks.StreamBlock(
                            [
                                (
                                    'popular_card',
                                    wagtail.blocks.StructBlock(
                                        [
                                            ('title', wagtail.blocks.CharBlock(label='Title', max_length=255)),
                                            (
                                                'description',
                                                wagtail.blocks.CharBlock(
                                                    label='Description', max_length=255, required=False
                                                ),
                                            ),
                                            (
                                                'url',
                                                wagtail.blocks.CharBlock(label='URL', max_length=255, required=False),
                                            ),
                                        ]
                                    ),
                                )
                            ],
                            block_counts={'popular_card': {'min_num': 3}},
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AddField(
            model_name='domesticgrowthlandingpage',
            name='popular_title',
            field=models.TextField(null=True),
        ),
    ]
