# Generated by Django 4.2.19 on 2025-02-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_growth', '0005_domesticgrowthlandingpage_popular_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domesticgrowthlandingpage',
            name='news_title',
            field=models.TextField(null=True),
        ),
    ]
