# Generated by Django 4.2.19 on 2025-03-17 13:18

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0169_merge_20250304_1128'),
        ('domestic_growth', '0005_domesticgrowthcontent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domesticgrowthhomepage',
            name='about_description',
        ),
        migrations.RemoveField(
            model_name='domesticgrowthhomepage',
            name='about_intro',
        ),
        migrations.RemoveField(
            model_name='domesticgrowthhomepage',
            name='about_title',
        ),
        migrations.RemoveField(
            model_name='domesticgrowthhomepage',
            name='explore_title',
        ),
        migrations.AddField(
            model_name='domesticgrowthhomepage',
            name='case_study_image',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='core.alttextimage',
            ),
        ),
        migrations.AddField(
            model_name='domesticgrowthhomepage',
            name='case_study_intro',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='domesticgrowthhomepage',
            name='case_study_link_text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='domesticgrowthhomepage',
            name='case_study_link_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='domesticgrowthhomepage',
            name='case_study_title',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='domesticgrowthhomepage',
            name='news_link_text_extra',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='domesticgrowthhomepage',
            name='news_link_url_extra',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='domesticgrowthhomepage',
            name='explore_body',
            field=wagtail.fields.StreamField(
                [('explore_cards', 4), ('explore_benefit_cards', 5)],
                blank=True,
                block_lookup={
                    0: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 255}),
                    1: ('wagtail.blocks.CharBlock', (), {'label': 'Description', 'max_length': 255, 'required': False}),
                    2: ('wagtail.blocks.CharBlock', (), {'label': 'URL', 'max_length': 255, 'required': False}),
                    3: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('url', 2)]], {}),
                    4: (
                        'wagtail.blocks.StreamBlock',
                        [[('explore_card', 3)]],
                        {'block_counts': {'explore_card': {'min_num': 4}}},
                    ),
                    5: (
                        'wagtail.blocks.StreamBlock',
                        [[('benefit_explore_card', 3)]],
                        {'block_counts': {'benefit_explore_card': {'min_num': 3}}},
                    ),
                },
                null=True,
            ),
        ),
    ]
