# Generated by Django 4.2.19 on 2025-03-24 10:55

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_growth', '0006_remove_domesticgrowthhomepage_about_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartingABusinessTriage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, null=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, null=True, verbose_name='modified'
                    ),
                ),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('session_id', models.CharField(max_length=40, unique=True)),
                ('sector_id', models.CharField(blank=True, max_length=10, null=True)),
                ('dont_know_sector', models.BooleanField(blank=True, default=False, null=True)),
                ('postcode', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
