# Generated by Django 4.2.19 on 2025-03-20 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_growth', '0006_domesticgrowthstartingabusinessuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DomesticGrowthStartingABusinessUser',
            new_name='StartingABusinessUser',
        ),
    ]
