# Generated by Django 4.2.19 on 2025-03-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_growth', '0006_remove_domesticgrowthhomepage_about_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domesticgrowthcontent',
            name='is_dynamic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='domesticgrowthcontent',
            name='region',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='domesticgrowthcontent',
            name='sector',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='domesticgrowthcontent',
            name='show_image',
            field=models.BooleanField(default=False),
        ),
    ]
