# Generated by Django 4.2.19 on 2025-03-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_growth', '0007_rename_domesticgrowthstartingabusinessuser_startingabusinessuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startingabusinessuser',
            name='session_key',
        ),
        migrations.AddField(
            model_name='startingabusinessuser',
            name='session_id',
            field=models.CharField(default='temp', max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
