# Generated by Django 4.2.19 on 2025-03-24 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_growth', '0007_domesticgrowthcontent_is_dynamic_and_more'),
        ('domestic_growth', '0007_startingabusinesstriage'),
    ]

    operations = []
