# Generated by Django 4.2.19 on 2025-02-27 14:29

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_growth', '0007_domesticgrowthresultspage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domesticgrowthresultspage',
            name='body',
            field=wagtail.fields.StreamField(
                [
                    (
                        'category',
                        wagtail.blocks.StructBlock(
                            [
                                ('title', wagtail.blocks.CharBlock()),
                                (
                                    'sub_category',
                                    wagtail.blocks.StreamBlock(
                                        [
                                            ('title', wagtail.blocks.CharBlock()),
                                            (
                                                'task',
                                                wagtail.blocks.ListBlock(
                                                    wagtail.snippets.blocks.SnippetChooserBlock('core.Task'),
                                                    label='Choose task',
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
