# Generated by Django 4.2.19 on 2025-03-25 10:56

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_growth', '0008_merge_20250324_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExistingBusinessTriage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, null=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, null=True, verbose_name='modified'
                    ),
                ),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('session_id', models.CharField(max_length=40, unique=True)),
                ('sector_id', models.CharField(blank=True, max_length=10, null=True)),
                ('cant_find_sector', models.BooleanField(blank=True, default=False, null=True)),
                ('postcode', models.CharField(blank=True, max_length=8, null=True)),
                (
                    'when_set_up',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('LESS_THAN_3_YEARS_AGO', 'Less than 3 years ago'),
                            ('MORE_THAN_3_YEARS_AGO', 'More than 3 years ago'),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    'turnover',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('LESS_THAN_90K', 'Less than £90,000'),
                            ('90K_TO_500k', '£90,000 to £500,000'),
                            ('500k_TO_2M', '£500,000 to £2 million'),
                            ('2M_TO_5M', '£2 million to £5 million'),
                            ('5M_TO_10M', '£5 million to £10 million'),
                            ('PREFER_NOT_TO_SAY', 'Prefer not to say'),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    'currently_export',
                    models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=50, null=True),
                ),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
