# Generated by Django 4.2.19 on 2025-03-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_growth', '0009_existingbusinesstriage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='existingbusinesstriage',
            name='turnover',
            field=models.CharField(
                blank=True,
                choices=[
                    ('LESS_THAN_90K', 'Less than £90,000'),
                    ('90K_TO_500k', '£90,000 to £500,000'),
                    ('500k_TO_2M', '£500,000 to £2 million'),
                    ('2M_TO_5M', '£2 million to £5 million'),
                    ('5M_TO_10M', '£5 million to £10 million'),
                    ('10M_PLUS', 'Over £10 million'),
                    ('I_DONT_KNOW', 'I_DONT_KNOW'),
                    ('PREFER_NOT_TO_SAY', 'Prefer not to say'),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
