# Generated by Django 4.2.19 on 2025-03-25 16:11

from django.db import migrations, models
import django.db.models.deletion
import domestic_growth.cms_panels
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0169_merge_20250304_1128'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('domestic_growth', '0009_domesticgrowthguidepage_chamber_of_commerce_intro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomesticGrowthAboutPage',
            fields=[
                (
                    'page_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='wagtailcore.page',
                    ),
                ),
                (
                    'canonical_url',
                    models.URLField(
                        blank=True,
                        help_text="Leave blank to use the page's URL.",
                        max_length=255,
                        verbose_name='Canonical URL',
                    ),
                ),
                (
                    'body',
                    wagtail.fields.StreamField(
                        [('text', 0), ('image', 1)],
                        blank=True,
                        block_lookup={
                            0: (
                                'wagtail.blocks.RichTextBlock',
                                (),
                                {'label': 'Text', 'template': 'includes/about/_text.html'},
                            ),
                            1: (
                                'wagtail.images.blocks.ImageChooserBlock',
                                (),
                                {'label': 'Image', 'required': False, 'template': 'includes/about/_image.html'},
                            ),
                        },
                        null=True,
                    ),
                ),
                (
                    'og_image',
                    models.ForeignKey(
                        blank=True,
                        help_text='Shown when linking to this page on social media. If blank, may show an image from the page, or the default from Settings > SEO.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='core.alttextimage',
                        verbose_name='Preview image',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Domestic Growth About page',
            },
            bases=(domestic_growth.cms_panels.DomesticGrowthAboutPagePanels, 'wagtailcore.page', models.Model),
        ),
    ]
