# Generated by Django 4.2.19 on 2025-02-28 13:31

from django.db import migrations, models
import wagtail.search.index


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_growth', '0009_alter_domesticgrowthresultspage_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomesticGrowthContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.CharField(blank=True)),
                ('title', models.CharField()),
                ('description', models.TextField()),
                ('link_text', models.CharField(blank=True)),
                ('url', models.CharField(blank=True)),
                ('sector', models.CharField(blank=True)),
                ('is_dynamic', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('title',),
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
