# Generated by Django 4.2.19 on 2025-03-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_growth', '0010_domesticgrowthaboutpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='domesticgrowthaboutpage',
            name='heading',
            field=models.TextField(null=True),
        ),
    ]
