# Generated by Django 4.2.19 on 2025-02-28 13:33

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_growth', '0010_domesticgrowthcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domesticgrowthresultspage',
            name='body',
            field=wagtail.fields.StreamField(
                [
                    (
                        'category',
                        wagtail.blocks.StructBlock(
                            [
                                ('title', wagtail.blocks.CharBlock()),
                                (
                                    'section',
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                'sub_category',
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        ('title', wagtail.blocks.CharBlock()),
                                                        (
                                                            'content',
                                                            wagtail.blocks.ListBlock(
                                                                wagtail.snippets.blocks.SnippetChooserBlock(
                                                                    'domestic_growth.DomesticGrowthContent'
                                                                ),
                                                                label='Choose content snippet',
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            )
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
