# Generated by Django 4.2.19 on 2025-03-25 18:30

import django.db.models.deletion
import wagtail.search.index
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0169_merge_20250304_1128'),
        ('domestic_growth', '0011_domesticgrowthaboutpage_heading'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomesticGrowthCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True)),
                ('description', models.CharField(blank=True)),
                ('url', models.CharField(blank=True)),
                ('meta_text', models.CharField(blank=True)),
                (
                    'image',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='core.alttextimage',
                    ),
                ),
            ],
            options={
                'ordering': ('title',),
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
