# Generated by Django 4.2.19 on 2025-03-04 16:14

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_growth', '0012_alter_domesticgrowthresultspage_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domesticgrowthchildresultspage',
            name='body',
            field=wagtail.fields.StreamField(
                [
                    (
                        'section',
                        wagtail.blocks.StructBlock(
                            [
                                ('title', wagtail.blocks.CharBlock()),
                                (
                                    'content',
                                    wagtail.blocks.ListBlock(
                                        wagtail.snippets.blocks.SnippetChooserBlock(
                                            'domestic_growth.DomesticGrowthContent'
                                        ),
                                        label='Choose content snippet',
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
