# Generated by Django 4.2.19 on 2025-03-25 18:44

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_growth', '0012_domesticgrowthcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='domesticgrowthchildguidepage',
            name='related_cta',
            field=wagtail.fields.StreamField(
                [('related_cta', 2)],
                blank=True,
                block_lookup={
                    0: ('wagtail.blocks.CharBlock', (), {}),
                    1: ('wagtail.snippets.blocks.SnippetChooserBlock', ('domestic_growth.DomesticGrowthCard',), {}),
                    2: (
                        'wagtail.blocks.StreamBlock',
                        [[('title', 0), ('card', 1)]],
                        {'block_counts': {'guidance_card': {'max_num': 1}}},
                    ),
                },
                null=True,
            ),
        ),
    ]
