# Generated by Django 4.2.19 on 2025-03-26 10:44

from django.db import migrations, models
import django.db.models.deletion
import domestic_growth.cms_panels
import wagtail.fields
import wagtailcache.cache


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0169_merge_20250304_1128'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('domestic_growth', '0013_domesticgrowthchildguidepage_related_cta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domesticgrowthchildguidepage',
            name='related_cta',
            field=wagtail.fields.StreamField(
                [('related_cta', 2)],
                blank=True,
                block_lookup={
                    0: ('wagtail.blocks.CharBlock', (), {}),
                    1: ('wagtail.snippets.blocks.SnippetChooserBlock', ('domestic_growth.DomesticGrowthCard',), {}),
                    2: ('wagtail.blocks.StreamBlock', [[('title', 0), ('card', 1)]], {}),
                },
                null=True,
            ),
        ),
        migrations.CreateModel(
            name='DomesticGrowthDynamicChildGuidePage',
            fields=[
                (
                    'page_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='wagtailcore.page',
                    ),
                ),
                (
                    'canonical_url',
                    models.URLField(
                        blank=True,
                        help_text="Leave blank to use the page's URL.",
                        max_length=255,
                        verbose_name='Canonical URL',
                    ),
                ),
                (
                    'page_a_type',
                    models.CharField(
                        choices=[
                            ('interested_in_exporting', 'Interested in exporting'),
                            ('not_interested_in_exporting', 'Not interested in exporting'),
                        ]
                    ),
                ),
                ('page_a_body_title', models.TextField(null=True)),
                ('page_a_body_intro', models.TextField(null=True)),
                (
                    'page_a_body_sections',
                    wagtail.fields.StreamField(
                        [('section', 3)],
                        blank=True,
                        block_lookup={
                            0: ('wagtail.blocks.CharBlock', (), {}),
                            1: (
                                'wagtail.snippets.blocks.SnippetChooserBlock',
                                ('domestic_growth.DomesticGrowthContent',),
                                {},
                            ),
                            2: ('wagtail.blocks.ListBlock', (1,), {'label': 'Choose snippet'}),
                            3: ('wagtail.blocks.StructBlock', [[('title', 0), ('intro', 0), ('content', 2)]], {}),
                        },
                        null=True,
                    ),
                ),
                (
                    'page_a_related_cta',
                    wagtail.fields.StreamField(
                        [('related_cta', 2)],
                        blank=True,
                        block_lookup={
                            0: ('wagtail.blocks.CharBlock', (), {}),
                            1: (
                                'wagtail.snippets.blocks.SnippetChooserBlock',
                                ('domestic_growth.DomesticGrowthCard',),
                                {},
                            ),
                            2: ('wagtail.blocks.StreamBlock', [[('title', 0), ('card', 1)]], {}),
                        },
                        null=True,
                    ),
                ),
                (
                    'page_b_type',
                    models.CharField(
                        choices=[
                            ('interested_in_exporting', 'Interested in exporting'),
                            ('not_interested_in_exporting', 'Not interested in exporting'),
                        ]
                    ),
                ),
                ('page_b_body_title', models.TextField(null=True)),
                ('page_b_body_intro', models.TextField(null=True)),
                (
                    'page_b_body_sections',
                    wagtail.fields.StreamField(
                        [('section', 3)],
                        blank=True,
                        block_lookup={
                            0: ('wagtail.blocks.CharBlock', (), {}),
                            1: (
                                'wagtail.snippets.blocks.SnippetChooserBlock',
                                ('domestic_growth.DomesticGrowthContent',),
                                {},
                            ),
                            2: ('wagtail.blocks.ListBlock', (1,), {'label': 'Choose snippet'}),
                            3: ('wagtail.blocks.StructBlock', [[('title', 0), ('intro', 0), ('content', 2)]], {}),
                        },
                        null=True,
                    ),
                ),
                (
                    'page_b_related_cta',
                    wagtail.fields.StreamField(
                        [('related_cta', 2)],
                        blank=True,
                        block_lookup={
                            0: ('wagtail.blocks.CharBlock', (), {}),
                            1: (
                                'wagtail.snippets.blocks.SnippetChooserBlock',
                                ('domestic_growth.DomesticGrowthCard',),
                                {},
                            ),
                            2: ('wagtail.blocks.StreamBlock', [[('title', 0), ('card', 1)]], {}),
                        },
                        null=True,
                    ),
                ),
                (
                    'og_image',
                    models.ForeignKey(
                        blank=True,
                        help_text='Shown when linking to this page on social media. If blank, may show an image from the page, or the default from Settings > SEO.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='core.alttextimage',
                        verbose_name='Preview image',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Domestic Growth Dynamic Child Guide page',
            },
            bases=(
                wagtailcache.cache.WagtailCacheMixin,
                domestic_growth.cms_panels.DomesticGrowthDynamicChildGuidePagePanels,
                'wagtailcore.page',
                models.Model,
            ),
        ),
    ]
