# Generated by Django 4.2.19 on 2025-03-26 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_growth', '0012_alter_existingbusinesstriage_currently_export'),
        ('domestic_growth', '0013_domesticgrowthchildguidepage_related_cta'),
    ]

    operations = []
