# Generated by Django 4.2.19 on 2025-03-06 13:07

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_growth', '0013_alter_domesticgrowthchildresultspage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domesticgrowthresultspage',
            name='body',
            field=wagtail.fields.StreamField(
                [
                    ('growth_hub', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock())])),
                    ('chamber_of_commerce', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock())])),
                    ('trade_associations', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock())])),
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
