# Generated by Django 4.2.19 on 2025-03-26 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_growth', '0014_alter_domesticgrowthchildguidepage_related_cta_and_more'),
        ('domestic_growth', '0014_merge_20250326_1305'),
    ]

    operations = []
