# Generated by Django 4.2.19 on 2025-03-27 11:56

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_growth', '0015_merge_20250326_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domesticgrowthchildguidepage',
            name='body_intro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='domesticgrowthchildguidepage',
            name='body_sections',
            field=wagtail.fields.StreamField(
                [('section', 4)],
                blank=True,
                block_lookup={
                    0: ('wagtail.blocks.CharBlock', (), {}),
                    1: ('wagtail.blocks.CharBlock', (), {'required': False}),
                    2: ('wagtail.snippets.blocks.SnippetChooserBlock', ('domestic_growth.DomesticGrowthContent',), {}),
                    3: ('wagtail.blocks.ListBlock', (2,), {'label': 'Choose snippet'}),
                    4: (
                        'wagtail.blocks.StructBlock',
                        [[('title', 0), ('intro', 1), ('link_text', 1), ('link_url', 1), ('logo', 1), ('content', 3)]],
                        {},
                    ),
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='domesticgrowthdynamicchildguidepage',
            name='page_a_body_intro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='domesticgrowthdynamicchildguidepage',
            name='page_a_body_sections',
            field=wagtail.fields.StreamField(
                [('section', 4)],
                blank=True,
                block_lookup={
                    0: ('wagtail.blocks.CharBlock', (), {}),
                    1: ('wagtail.blocks.CharBlock', (), {'required': False}),
                    2: ('wagtail.snippets.blocks.SnippetChooserBlock', ('domestic_growth.DomesticGrowthContent',), {}),
                    3: ('wagtail.blocks.ListBlock', (2,), {'label': 'Choose snippet'}),
                    4: (
                        'wagtail.blocks.StructBlock',
                        [[('title', 0), ('intro', 1), ('link_text', 1), ('link_url', 1), ('logo', 1), ('content', 3)]],
                        {},
                    ),
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='domesticgrowthdynamicchildguidepage',
            name='page_b_body_intro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='domesticgrowthdynamicchildguidepage',
            name='page_b_body_sections',
            field=wagtail.fields.StreamField(
                [('section', 4)],
                blank=True,
                block_lookup={
                    0: ('wagtail.blocks.CharBlock', (), {}),
                    1: ('wagtail.blocks.CharBlock', (), {'required': False}),
                    2: ('wagtail.snippets.blocks.SnippetChooserBlock', ('domestic_growth.DomesticGrowthContent',), {}),
                    3: ('wagtail.blocks.ListBlock', (2,), {'label': 'Choose snippet'}),
                    4: (
                        'wagtail.blocks.StructBlock',
                        [[('title', 0), ('intro', 1), ('link_text', 1), ('link_url', 1), ('logo', 1), ('content', 3)]],
                        {},
                    ),
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='domesticgrowthguidepage',
            name='body_intro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='domesticgrowthguidepage',
            name='hero_intro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='domesticgrowthhomepage',
            name='hero_intro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='existingbusinesstriage',
            name='turnover',
            field=models.CharField(
                blank=True,
                choices=[
                    ('LESS_THAN_90K', 'Less than £90,000'),
                    ('90K_TO_500K', '£90,000 to £500,000'),
                    ('500k_TO_2M', '£500,000 to £2 million'),
                    ('2M_TO_5M', '£2 million to £5 million'),
                    ('5M_TO_10M', '£5 million to £10 million'),
                    ('10M_PLUS', 'Over £10 million'),
                    ('PREFER_NOT_TO_SAY', 'Prefer not to say'),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
