# Generated by Django 4.2.19 on 2025-04-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_growth', '0016_alter_domesticgrowthchildguidepage_body_intro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domesticgrowthcontent',
            name='sub_sector',
            field=models.CharField(blank=True),
        ),
    ]
