# Generated by Django 4.2.19 on 2025-04-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_growth', '0017_domesticgrowthcontent_sub_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='existingbusinesstriage',
            name='currently_export',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
