# Generated by Django 4.2.19 on 2025-04-17 13:05

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_growth', '0019_remove_existingbusinesstriage_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domesticgrowthdynamicchildguidepage',
            name='page_a_body_sections',
            field=wagtail.fields.StreamField(
                [('section', 4)],
                blank=True,
                block_lookup={
                    0: ('wagtail.blocks.CharBlock', (), {}),
                    1: ('wagtail.blocks.CharBlock', (), {'required': False}),
                    2: ('wagtail.snippets.blocks.SnippetChooserBlock', ('domestic_growth.DomesticGrowthContent',), {}),
                    3: ('wagtail.blocks.ListBlock', (2,), {'label': 'Choose snippet'}),
                    4: (
                        'wagtail.blocks.StructBlock',
                        [
                            [
                                ('title', 0),
                                ('intro', 1),
                                ('link_text', 1),
                                ('link_url', 1),
                                ('logo', 1),
                                ('border_color', 1),
                                ('content', 3),
                            ]
                        ],
                        {},
                    ),
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='domesticgrowthdynamicchildguidepage',
            name='page_b_body_sections',
            field=wagtail.fields.StreamField(
                [('section', 4)],
                blank=True,
                block_lookup={
                    0: ('wagtail.blocks.CharBlock', (), {}),
                    1: ('wagtail.blocks.CharBlock', (), {'required': False}),
                    2: ('wagtail.snippets.blocks.SnippetChooserBlock', ('domestic_growth.DomesticGrowthContent',), {}),
                    3: ('wagtail.blocks.ListBlock', (2,), {'label': 'Choose snippet'}),
                    4: (
                        'wagtail.blocks.StructBlock',
                        [
                            [
                                ('title', 0),
                                ('intro', 1),
                                ('link_text', 1),
                                ('link_url', 1),
                                ('logo', 1),
                                ('border_color', 1),
                                ('content', 3),
                            ]
                        ],
                        {},
                    ),
                },
                null=True,
            ),
        ),
    ]
