# Generated by Django 4.2.20 on 2025-05-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_growth', '0021_alter_domesticgrowthchildguidepage_body_sections'),
    ]

    operations = [
        migrations.RenameField(
            model_name='existingbusinesstriage',
            old_name='session_id',
            new_name='triage_uuid',
        ),
        migrations.RenameField(
            model_name='startingabusinesstriage',
            old_name='session_id',
            new_name='triage_uuid',
        ),
        migrations.AddField(
            model_name='existingbusinessguideemailrecipient',
            name='url_token',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='startingabusinessguideemailrecipient',
            name='url_token',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
