# Generated by Django 4.2.20 on 2025-04-30 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_growth', '0021_alter_domesticgrowthchildguidepage_body_sections'),
    ]

    operations = [
        migrations.RenameField(
            model_name='existingbusinesstriage',
            old_name='session_id',
            new_name='triage_uuid',
        ),
        migrations.RenameField(
            model_name='startingabusinesstriage',
            old_name='session_id',
            new_name='triage_uuid',
        ),
    ]
